In [1]:
import os
from multiprocess import set_start_method
set_start_method("spawn")
import logging
logger = logging.getLogger("ignite.handlers.early_stopping.EarlyStopping")
logger.setLevel(logging.WARNING)

In [2]:
from transformers import Trainer, AutoModelForCausalLM, AutoTokenizer, TrainingArguments, DataCollatorForLanguageModeling
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, TaskType, PeftModel

from coreset_trainer.trainer import CoresetTrainer
import os
import torch

import argparse

In [3]:
from load_experiment_data import (
    train_dataset_name,
    test_dataset_name,
    train_dataset_split,
    test_dataset_split,
    load_data_and_estimators,
    explanation_types,
    optimizers
)
train_dataset, test_dataset, estimators = load_data_and_estimators()

In [6]:
%%writefile validation_engine.py
import torch
import torch.nn.functional as F
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer
import numpy as np
from datasets import load_dataset
from transformers import DataCollatorForLanguageModeling
from torch.cuda.amp import autocast
from tqdm import tqdm
import copy
from transformers import DataCollatorForLanguageModeling
from coreset_trainer.train import tokenize_dataset
from peft import LoraConfig, get_peft_model, PeftModel
from peft import PeftConfig
from finetune import CHAT_TEMPLATE
class ChatTemplateCollator:
    def __init__(self, tokenizer, mlm=False, max_length=1024): # TODO
        self.tokenizer = tokenizer
        
        self.max_length = max_length
        self.base_collator = DataCollatorForLanguageModeling(
            tokenizer=tokenizer, mlm=mlm
        )

    def __call__(self, features):
        texts = [
            self.tokenizer.apply_chat_template(
                f["messages"], tokenize=False, add_generation_prompt=False
            )
            for f in features
        ]
        tokenized = self.tokenizer(
            texts,
            truncation=True,
            return_tensors="pt",
            padding=True,
            max_length=self.max_length
        )
 
        batch = [
            {"input_ids": tokenized["input_ids"][i],
             "attention_mask": tokenized["attention_mask"][i]}
            for i in range(len(tokenized["input_ids"]))
        ]
        return self.base_collator(batch)

class ValidationEngine():
    def __init__(self, adapter_path, device):

        self.device = device
        self.adapter_path = adapter_path
        self.tokenizer = AutoTokenizer.from_pretrained(self.adapter_path, padding_side='left')
        self.tokenizer.pad_token = self.tokenizer.eos_token
        self.tokenizer.padding_side = "left"
    
        peft_config = PeftConfig.from_pretrained(adapter_path)
        self.base_model_path = peft_config.base_model_name_or_path

        
        self.data_collator = ChatTemplateCollator(tokenizer=self.tokenizer, mlm=False)
        if self.tokenizer.chat_template is None:
            self.tokenizer.chat_template = CHAT_TEMPLATE
        
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token # TODO
    def get_log_p(self, model, examples):
        batch = self.data_collator(examples)
        batch = {k: v.to(self.device) for k, v in batch.items()}
        with torch.no_grad(): 
            outputs = model.generate(**batch, max_new_tokens=5, return_dict_in_generate=True, output_scores=True,  num_beams=1)
            transition_scores = model.compute_transition_scores(
                outputs.sequences, outputs.scores, normalize_logits=True
            )
            log_p = transition_scores.sum(axis=1)
            # print("log_p",log_p)
            return log_p

            
        return self.model_
    def score(self, train_dataset, test_dataset):

        base_model_after_ft = AutoModelForCausalLM.from_pretrained(
                self.base_model_path,
                torch_dtype=torch.float32
            )
        model_after_ft = PeftModel.from_pretrained(base_model_after_ft, self.adapter_path).to(self.device)
        model_after_ft.config.pad_token_id = self.tokenizer.eos_token_id
        model_after_ft = self.finetune(model_after_ft, train_dataset)
        
        base_model_before_ft = AutoModelForCausalLM.from_pretrained(
                self.base_model_path,
                torch_dtype=torch.float32
            )
        model_before_ft = PeftModel.from_pretrained(base_model_before_ft, self.adapter_path).to(self.device)
        model_before_ft.config.pad_token_id = self.tokenizer.eos_token_id
        

        log_p_before_ft = self.get_log_p(model_before_ft, test_dataset)       
        log_p_after_ft = self.get_log_p(model_after_ft, test_dataset)
        return log_p_after_ft - log_p_before_ft

    def finetune(self, model, train_dataset):
        
        # Freeze the base model
        for param in model.base_model.parameters():
            param.requires_grad = False

        # Ensure LoRA adapters are trainable
        for name, param in model.named_parameters():
            if 'lora' in name:
                param.requires_grad = True
        
        training_args = TrainingArguments(
            per_device_train_batch_size=1,
            gradient_accumulation_steps=1,
            remove_unused_columns=False,
            num_train_epochs=5,
            learning_rate=2e-5,
            logging_steps=500,
            seed=42,
            report_to=[],
            disable_tqdm=True
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            tokenizer=self.tokenizer,
            data_collator=self.data_collator,
        )

        trainer.train(resume_from_checkpoint=False)
        return model

Overwriting validation_engine.py

In [7]:
%%writefile validation_worker_validation.py
import os
import torch
from tqdm import tqdm
import pandas as pd

def process(partial_results_dir, estimator, explanation, examples_to_train_on, indices_to_train_on, examples_to_test_on, indices_to_test_on, train_dataset, train_dataset_name, train_dataset_split, test_dataset, test_dataset_name, test_dataset_split, device_id, ii):
        results_path = os.path.join(
            partial_results_dir,
            str(ii) + ".parquet",
            )
        os.makedirs(os.path.dirname(results_path), exist_ok=True)
        if os.path.isfile(results_path):
            print(f"Skipping {ii}: parquet file exists", flush=True)
            return
        else:
            try:
                # Restrict this process to a single GPU
                os.environ["CUDA_VISIBLE_DEVICES"] = str(device_id)
                import torch
                from validation_engine import ValidationEngine  # import inside worker

                engine = ValidationEngine(
                                          estimator.model_path, 
                                          device="cuda")
                
                delta = engine.score(examples_to_train_on, examples_to_test_on)
                
                delta_target_document = delta[0].item()
                delta_random_documents = delta[1:].tolist()
                
                
                df = pd.DataFrame([(
                        explanation.description,
                        os.path.basename(estimator.model_path),
                        estimator.get_config_string(),
                        explanation.dataset_idx,
                        train_dataset_name,
                        train_dataset_split,
                        test_dataset_name,
                        test_dataset_split,
                        
                        indices_to_train_on,
                        
                        indices_to_test_on[0],
                        indices_to_test_on[1:],
                        
                        delta_random_documents,
                        delta_target_document
                    )], columns=[
                        "explanation_type", 
                        "model", 
                        "estimator",
                        "dataset_idx", 
                        "train_dataset", 
                        "train_split", 
                        "test_dataset", 
                        "test_split", 
                        
                        "indices_trained_on",
                        "indices_target_document",
                        "indices_random_documents",
                    
                        
                        "delta_random_documents",
                        "delta_target_document"
                        
                ])
                            
                assert df.notnull().all().all(), "DataFrame contains missing values"
                assert not df.isnull().values.any(), "DataFrame contains NaN values"
                df.to_parquet(results_path, index=False)
        
        
        

            except Exception as e:
                import traceback, logging
                logging.error(f"Error in process for GPU {device_id}: {e}")
                logging.error(traceback.format_exc())
                raise
        return []

Overwriting validation_worker_validation.py

In [8]:
import logging
from concurrent.futures import ProcessPoolExecutor, as_completed
import torch
import multiprocessing
from tqdm import tqdm
import itertools
import pandas as pd
import traceback

logging.basicConfig(level=logging.ERROR, format='%(asctime)s [%(levelname)s] %(message)s')
multiprocessing.set_start_method('spawn', force=True)
torch.manual_seed(42)


n_test = 10

test_indices = test_dataset.shuffle(seed=42).select(range(n_test))["indices"]

num_devices = torch.cuda.device_count()

In [9]:
import logging
from concurrent.futures import ProcessPoolExecutor, as_completed
import torch
import multiprocessing
from validation_worker_validation import process

logging.basicConfig(level=logging.ERROR, format='%(asctime)s [%(levelname)s] %(message)s')

multiprocessing.set_start_method('spawn', force=True)

num_gpus = torch.cuda.device_count()
logging.info(f"Detected {num_gpus} GPUs")

[INFO] Detected 2 GPUs

In [10]:

device_ids = itertools.cycle(range(num_devices))
results = []

from peft import LoraConfig, get_peft_model, PeftModel


for estimator in estimators:
    

    explanations = [
        explanation_type(row.name, estimator)
        for explanation_type in explanation_types
        for _, row in estimator.influence_estimate.iloc[test_indices].iterrows()
    ]
            
        
    partial_results_dir =  os.path.join("./cache/validation/partial/",
        estimator.get_config_string(),
        os.path.basename(estimator.model_path),
        train_dataset_name,
        train_dataset_split,
        test_dataset_name,
        test_dataset_split,
        "partial")
    with ProcessPoolExecutor(max_workers=4*num_devices) as executor:
        futures = {}
        for ii, explanation in enumerate(explanations):
            
            # random documents to test log_p for in addition to the document beeing explained
            random_test_indices = test_dataset.shuffle(seed=ii).select(range(5))["indices"]
        
            text_indices = [explanation.dataset_idx] + random_test_indices
            futures[explanation] = executor.submit(
                    process,
                    partial_results_dir,
                    estimator, explanation,
                    train_dataset.select(explanation.documents), explanation.documents, 
                    test_dataset.select(text_indices), text_indices,                 
                    train_dataset, train_dataset_name, train_dataset_split, test_dataset, test_dataset_name, test_dataset_split, 
                    next(device_ids),
                    ii
            )

        with tqdm(total=len(futures), desc="Explanations", position=0) as pbar:
            for future in as_completed(futures.values()):
                try:
                    # You can add future.result() here if you want to catch exceptions
                    future.result()  
                except Exception as e:
                    logging.error(f"A future failed: {e}\n{traceback.format_exc()}")
                    raise
                finally:
                    pbar.update(1)

Explanations:   0%|          | 0/50 [00:00<?, ?it/s]/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:   4%|▍         | 2/50 [00:16<05:25,  6.79s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:   6%|▌         | 3/50 [00:16<03:05,  3.94s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Explanations:   8%|▊         | 4/50 [00:17<01:59,  2.60s/it]A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  12%|█▏        | 6/50 [00:17<00:55,  1.27s/it]/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  20%|██        | 10/50 [00:23<00:50,  1.26s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  22%|██▏       | 11/50 [00:23<00:40,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  24%|██▍       | 12/50 [00:23<00:34,  1.12it/s]/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  26%|██▌       | 13/50 [00:24<00:31,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  30%|███       | 15/50 [00:25<00:19,  1.76it/s]/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

{'train_runtime': 5.1382, 'train_samples_per_second': 9.731, 'train_steps_per_second': 9.731, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.0023, 'train_samples_per_second': 12.493, 'train_steps_per_second': 12.493, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 3.5449, 'train_samples_per_second': 14.105, 'train_steps_per_second': 14.105, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.9207, 'train_samples_per_second': 17.119, 'train_steps_per_second': 17.119, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 2.9283, 'train_samples_per_second': 17.075, 'train_steps_per_second': 17.075, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 3.8327, 'train_samples_per_second': 13.046, 'train_steps_per_second': 13.046, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 4.7649, 'train_samples_per_second': 10.493, 'train_steps_per_second': 10.493, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 3.945, 'train_samples_per_second': 12.674, 'train_steps_per_second': 12.674, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.3022, 'train_samples_per_second': 11.622, 'train_steps_per_second': 11.622, 'train_loss': 4.590455627441406, 'epoch': 5.0}
{'train_runtime': 3.1231, 'train_samples_per_second': 16.01, 'train_steps_per_second': 16.01, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.9529, 'train_samples_per_second': 16.932, 'train_steps_per_second': 16.932, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 3.6896, 'train_samples_per_second': 13.552, 'train_steps_per_second': 13.552, 'train_loss': 5.214383544921875, 'epoch': 5.0}
{'train_runtime': 4.899, 'train_samples_per_second': 10.206, 'train_steps_per_second': 10.206, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.0956, 'train_samples_per_second': 12.208, 'train_steps_per_second': 12.208, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 3.4804, 'train_samples_per_second': 14.366, 'train_steps_per_second': 14.366, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.7648, 'train_samples_per_second': 18.084, 'train_steps_per_second': 18.084, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 2.7949, 'train_samples_per_second': 17.89, 'train_steps_per_second': 17.89, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 4.162, 'train_samples_per_second': 12.014, 'train_steps_per_second': 12.014, 'train_loss': 4.506339111328125, 'epoch': 5.0}
{'train_runtime': 2.102, 'train_samples_per_second': 23.787, 'train_steps_per_second': 23.787, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 5.1972, 'train_samples_per_second': 9.621, 'train_steps_per_second': 9.621, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.1377, 'train_samples_per_second': 12.084, 'train_steps_per_second': 12.084, 'train_loss': 5.214383544921875, 'epoch': 5.0}
{'train_runtime': 3.5284, 'train_samples_per_second': 14.171, 'train_steps_per_second': 14.171, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 3.1698, 'train_samples_per_second': 15.774, 'train_steps_per_second': 15.774, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 3.1146, 'train_samples_per_second': 16.053, 'train_steps_per_second': 16.053, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 3.5867, 'train_samples_per_second': 13.94, 'train_steps_per_second': 13.94, 'train_loss': 4.746460876464844, 'epoch': 5.0}
{'train_runtime': 5.1725, 'train_samples_per_second': 9.666, 'train_steps_per_second': 9.666, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.0649, 'train_samples_per_second': 12.301, 'train_steps_per_second': 12.301, 'train_loss': 4.740416259765625, 'epoch': 5.0}
{'train_runtime': 3.6041, 'train_samples_per_second': 13.873, 'train_steps_per_second': 13.873, 'train_loss': 4.535227966308594, 'epoch': 5.0}
{'train_runtime': 3.139, 'train_samples_per_second': 15.929, 'train_steps_per_second': 15.929, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.9258, 'train_samples_per_second': 17.089, 'train_steps_per_second': 17.089, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 3.8838, 'train_samples_per_second': 12.874, 'train_steps_per_second': 12.874, 'train_loss': 4.737266845703125, 'epoch': 5.0}
{'train_runtime': 5.1443, 'train_samples_per_second': 9.719, 'train_steps_per_second': 9.719, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.3218, 'train_samples_per_second': 11.569, 'train_steps_per_second': 11.569, 'train_loss': 4.724180297851563, 'epoch': 5.0}
{'train_runtime': 3.4212, 'train_samples_per_second': 14.615, 'train_steps_per_second': 14.615, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.9065, 'train_samples_per_second': 17.203, 'train_steps_per_second': 17.203, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 2.9065, 'train_samples_per_second': 17.203, 'train_steps_per_second': 17.203, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 3.4191, 'train_samples_per_second': 14.624, 'train_steps_per_second': 14.624, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 5.1221, 'train_samples_per_second': 9.762, 'train_steps_per_second': 9.762, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.9017, 'train_samples_per_second': 10.2, 'train_steps_per_second': 10.2, 'train_loss': 4.507344055175781, 'epoch': 5.0}
{'train_runtime': 3.2814, 'train_samples_per_second': 15.237, 'train_steps_per_second': 15.237, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 2.9191, 'train_samples_per_second': 17.128, 'train_steps_per_second': 17.128, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.9208, 'train_samples_per_second': 17.118, 'train_steps_per_second': 17.118, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 3.6817, 'train_samples_per_second': 13.581, 'train_steps_per_second': 13.581, 'train_loss': 4.591139221191407, 'epoch': 5.0}
{'train_runtime': 4.7031, 'train_samples_per_second': 10.631, 'train_steps_per_second': 10.631, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 3.6916, 'train_samples_per_second': 13.544, 'train_steps_per_second': 13.544, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 3.3377, 'train_samples_per_second': 14.98, 'train_steps_per_second': 14.98, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.7432, 'train_samples_per_second': 18.227, 'train_steps_per_second': 18.227, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 2.7182, 'train_samples_per_second': 18.394, 'train_steps_per_second': 18.394, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.9224, 'train_samples_per_second': 17.109, 'train_steps_per_second': 17.109, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.4112, 'train_samples_per_second': 20.737, 'train_steps_per_second': 20.737, 'train_loss': 4.534731750488281, 'epoch': 5.0}

Explanations:   0%|          | 0/50 [00:00<?, ?it/s]/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Explanations:   2%|▏         | 1/50 [00:17<14:11, 17.37s/it]A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:   4%|▍         | 2/50 [00:17<05:50,  7.29s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:   6%|▌         | 3/50 [00:17<03:08,  4.02s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:   8%|▊         | 4/50 [00:18<01:58,  2.58s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  12%|█▏        | 6/50 [00:18<00:55,  1.25s/it]/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  18%|█▊        | 9/50 [00:23<01:02,  1.53s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  22%|██▏       | 11/50 [00:23<00:41,  1.06s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  24%|██▍       | 12/50 [00:24<00:37,  1.01it/s]/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  26%|██▌       | 13/50 [00:25<00:35,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  30%|███       | 15/50 [00:25<00:22,  1.54it/s]/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  32%|███▏      | 16/50 [00:25<00:18,  1.89it/s]/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

{'train_runtime': 5.121, 'train_samples_per_second': 9.764, 'train_steps_per_second': 9.764, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 3.5968, 'train_samples_per_second': 13.901, 'train_steps_per_second': 13.901, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 3.9119, 'train_samples_per_second': 12.782, 'train_steps_per_second': 12.782, 'train_loss': 4.557433471679688, 'epoch': 5.0}
{'train_runtime': 3.0528, 'train_samples_per_second': 16.379, 'train_steps_per_second': 16.379, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.555, 'train_samples_per_second': 19.57, 'train_steps_per_second': 19.57, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 3.1058, 'train_samples_per_second': 16.099, 'train_steps_per_second': 16.099, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 5.3534, 'train_samples_per_second': 9.34, 'train_steps_per_second': 9.34, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 3.8805, 'train_samples_per_second': 12.885, 'train_steps_per_second': 12.885, 'train_loss': 5.322017822265625, 'epoch': 5.0}
{'train_runtime': 3.4161, 'train_samples_per_second': 14.637, 'train_steps_per_second': 14.637, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.878, 'train_samples_per_second': 17.373, 'train_steps_per_second': 17.373, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 2.745, 'train_samples_per_second': 18.215, 'train_steps_per_second': 18.215, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 3.0859, 'train_samples_per_second': 16.203, 'train_steps_per_second': 16.203, 'train_loss': 5.322017822265625, 'epoch': 5.0}
{'train_runtime': 5.4133, 'train_samples_per_second': 9.236, 'train_steps_per_second': 9.236, 'train_loss': 4.510911560058593, 'epoch': 5.0}
{'train_runtime': 4.0137, 'train_samples_per_second': 12.457, 'train_steps_per_second': 12.457, 'train_loss': 4.335970458984375, 'epoch': 5.0}
{'train_runtime': 3.2564, 'train_samples_per_second': 15.355, 'train_steps_per_second': 15.355, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 3.073, 'train_samples_per_second': 16.271, 'train_steps_per_second': 16.271, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.8985, 'train_samples_per_second': 17.25, 'train_steps_per_second': 17.25, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 3.3478, 'train_samples_per_second': 14.935, 'train_steps_per_second': 14.935, 'train_loss': 4.3275363159179685, 'epoch': 5.0}
{'train_runtime': 4.9313, 'train_samples_per_second': 10.139, 'train_steps_per_second': 10.139, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 3.5986, 'train_samples_per_second': 13.894, 'train_steps_per_second': 13.894, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 3.1901, 'train_samples_per_second': 15.674, 'train_steps_per_second': 15.674, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.783, 'train_samples_per_second': 17.966, 'train_steps_per_second': 17.966, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 2.681, 'train_samples_per_second': 18.65, 'train_steps_per_second': 18.65, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 3.0472, 'train_samples_per_second': 16.408, 'train_steps_per_second': 16.408, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.4498, 'train_samples_per_second': 20.41, 'train_steps_per_second': 20.41, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 5.2167, 'train_samples_per_second': 9.585, 'train_steps_per_second': 9.585, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 3.7475, 'train_samples_per_second': 13.342, 'train_steps_per_second': 13.342, 'train_loss': 4.530735778808594, 'epoch': 5.0}
{'train_runtime': 3.3319, 'train_samples_per_second': 15.007, 'train_steps_per_second': 15.007, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.6834, 'train_samples_per_second': 18.633, 'train_steps_per_second': 18.633, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 2.6248, 'train_samples_per_second': 19.049, 'train_steps_per_second': 19.049, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 3.4861, 'train_samples_per_second': 14.343, 'train_steps_per_second': 14.343, 'train_loss': 4.475474853515625, 'epoch': 5.0}
{'train_runtime': 2.1864, 'train_samples_per_second': 22.868, 'train_steps_per_second': 22.868, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 5.3855, 'train_samples_per_second': 9.284, 'train_steps_per_second': 9.284, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.085, 'train_samples_per_second': 12.24, 'train_steps_per_second': 12.24, 'train_loss': 4.8184115600585935, 'epoch': 5.0}
{'train_runtime': 3.3155, 'train_samples_per_second': 15.081, 'train_steps_per_second': 15.081, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 2.9866, 'train_samples_per_second': 16.742, 'train_steps_per_second': 16.742, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 3.1074, 'train_samples_per_second': 16.09, 'train_steps_per_second': 16.09, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 3.0673, 'train_samples_per_second': 16.301, 'train_steps_per_second': 16.301, 'train_loss': 4.819707946777344, 'epoch': 5.0}
{'train_runtime': 5.2509, 'train_samples_per_second': 9.522, 'train_steps_per_second': 9.522, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.1831, 'train_samples_per_second': 11.953, 'train_steps_per_second': 11.953, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 3.5857, 'train_samples_per_second': 13.944, 'train_steps_per_second': 13.944, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.9367, 'train_samples_per_second': 17.026, 'train_steps_per_second': 17.026, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.9581, 'train_samples_per_second': 16.903, 'train_steps_per_second': 16.903, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 3.1266, 'train_samples_per_second': 15.992, 'train_steps_per_second': 15.992, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 5.2647, 'train_samples_per_second': 9.497, 'train_steps_per_second': 9.497, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.5953, 'train_samples_per_second': 10.881, 'train_steps_per_second': 10.881, 'train_loss': 4.4748773193359375, 'epoch': 5.0}
{'train_runtime': 3.4591, 'train_samples_per_second': 14.455, 'train_steps_per_second': 14.455, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 2.9262, 'train_samples_per_second': 17.087, 'train_steps_per_second': 17.087, 'train_loss': 4.7251370239257815, 'epoch': 5.0}
{'train_runtime': 2.9096, 'train_samples_per_second': 17.185, 'train_steps_per_second': 17.185, 'train_loss': 4.534731750488281, 'epoch': 5.0}
{'train_runtime': 3.3849, 'train_samples_per_second': 14.772, 'train_steps_per_second': 14.772, 'train_loss': 4.561139221191406, 'epoch': 5.0}

Explanations:   0%|          | 0/50 [00:00<?, ?it/s][INFO] PyTorch version 2.7.0+cu126 available.
[INFO] PyTorch version 2.7.0+cu126 available.
[INFO] PyTorch version 2.7.0+cu126 available.
[INFO] PyTorch version 2.7.0+cu126 available.
[INFO] PyTorch version 2.7.0+cu126 available.
[INFO] PyTorch version 2.7.0+cu126 available.
[INFO] PyTorch version 2.7.0+cu126 available.
[INFO] PyTorch version 2.7.0+cu126 available.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:   2%|▏         | 1/50 [00:15<13:03, 16.00s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:   4%|▍         | 2/50 [00:16<05:43,  7.16s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:   6%|▌         | 3/50 [00:17<03:09,  4.03s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:   8%|▊         | 4/50 [00:17<02:04,  2.70s/it]/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  18%|█▊        | 9/50 [00:21<00:51,  1.26s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Repo card metadata block was not found. Setting CardData to empty.
[WARNING] Repo card metadata block was not found. Setting CardData to empty.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  20%|██        | 10/50 [00:23<00:51,  1.29s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  22%|██▏       | 11/50 [00:23<00:41,  1.06s/it]/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  24%|██▍       | 12/50 [00:25<00:46,  1.22s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Explanations:  30%|███       | 15/50 [00:25<00:21,  1.65it/s]/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/srv/home/users/loriss21cs/cfe/validation_engine.py:124: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

{'train_runtime': 4.8238, 'train_samples_per_second': 10.365, 'train_steps_per_second': 10.365, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 3.5286, 'train_samples_per_second': 14.17, 'train_steps_per_second': 14.17, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 2.8019, 'train_samples_per_second': 17.845, 'train_steps_per_second': 17.845, 'train_loss': 4.488988952636719, 'epoch': 5.0}
{'train_runtime': 4.6719, 'train_samples_per_second': 10.702, 'train_steps_per_second': 10.702, 'train_loss': 4.364281311035156, 'epoch': 5.0}
{'train_runtime': 4.0857, 'train_samples_per_second': 12.238, 'train_steps_per_second': 12.238, 'train_loss': 4.54252197265625, 'epoch': 5.0}
{'train_runtime': 2.7905, 'train_samples_per_second': 17.918, 'train_steps_per_second': 17.918, 'train_loss': 5.007021484375, 'epoch': 5.0}
{'train_runtime': 5.0259, 'train_samples_per_second': 9.949, 'train_steps_per_second': 9.949, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.0338, 'train_samples_per_second': 12.395, 'train_steps_per_second': 12.395, 'train_loss': 4.50362548828125, 'epoch': 5.0}
{'train_runtime': 2.8631, 'train_samples_per_second': 17.464, 'train_steps_per_second': 17.464, 'train_loss': 4.553181762695313, 'epoch': 5.0}
{'train_runtime': 3.5717, 'train_samples_per_second': 13.999, 'train_steps_per_second': 13.999, 'train_loss': 4.882158813476562, 'epoch': 5.0}
{'train_runtime': 4.8813, 'train_samples_per_second': 10.243, 'train_steps_per_second': 10.243, 'train_loss': 4.366488647460938, 'epoch': 5.0}
{'train_runtime': 2.9112, 'train_samples_per_second': 17.175, 'train_steps_per_second': 17.175, 'train_loss': 5.0991357421875, 'epoch': 5.0}
{'train_runtime': 5.0184, 'train_samples_per_second': 9.963, 'train_steps_per_second': 9.963, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.1229, 'train_samples_per_second': 12.127, 'train_steps_per_second': 12.127, 'train_loss': 5.096232604980469, 'epoch': 5.0}
{'train_runtime': 3.0317, 'train_samples_per_second': 16.492, 'train_steps_per_second': 16.492, 'train_loss': 4.745798645019531, 'epoch': 5.0}
{'train_runtime': 4.487, 'train_samples_per_second': 11.143, 'train_steps_per_second': 11.143, 'train_loss': 4.723307800292969, 'epoch': 5.0}
{'train_runtime': 3.9899, 'train_samples_per_second': 12.532, 'train_steps_per_second': 12.532, 'train_loss': 4.882158813476562, 'epoch': 5.0}
{'train_runtime': 3.0036, 'train_samples_per_second': 16.647, 'train_steps_per_second': 16.647, 'train_loss': 4.6987548828125, 'epoch': 5.0}
{'train_runtime': 5.0508, 'train_samples_per_second': 9.899, 'train_steps_per_second': 9.899, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 3.7145, 'train_samples_per_second': 13.461, 'train_steps_per_second': 13.461, 'train_loss': 4.499078979492188, 'epoch': 5.0}
{'train_runtime': 2.7203, 'train_samples_per_second': 18.38, 'train_steps_per_second': 18.38, 'train_loss': 3.6513162231445313, 'epoch': 5.0}
{'train_runtime': 4.5466, 'train_samples_per_second': 10.997, 'train_steps_per_second': 10.997, 'train_loss': 4.557857360839844, 'epoch': 5.0}
{'train_runtime': 3.3017, 'train_samples_per_second': 15.143, 'train_steps_per_second': 15.143, 'train_loss': 5.043630981445313, 'epoch': 5.0}
{'train_runtime': 3.1263, 'train_samples_per_second': 15.993, 'train_steps_per_second': 15.993, 'train_loss': 4.4857308959960935, 'epoch': 5.0}
{'train_runtime': 2.195, 'train_samples_per_second': 22.779, 'train_steps_per_second': 22.779, 'train_loss': 4.553181762695313, 'epoch': 5.0}
{'train_runtime': 5.0911, 'train_samples_per_second': 9.821, 'train_steps_per_second': 9.821, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.0871, 'train_samples_per_second': 12.234, 'train_steps_per_second': 12.234, 'train_loss': 4.6987548828125, 'epoch': 5.0}
{'train_runtime': 3.1316, 'train_samples_per_second': 15.966, 'train_steps_per_second': 15.966, 'train_loss': 5.212678833007812, 'epoch': 5.0}
{'train_runtime': 3.5541, 'train_samples_per_second': 14.068, 'train_steps_per_second': 14.068, 'train_loss': 4.157211608886719, 'epoch': 5.0}
{'train_runtime': 5.1688, 'train_samples_per_second': 9.674, 'train_steps_per_second': 9.674, 'train_loss': 4.556204833984375, 'epoch': 5.0}
{'train_runtime': 3.0308, 'train_samples_per_second': 16.497, 'train_steps_per_second': 16.497, 'train_loss': 4.705931396484375, 'epoch': 5.0}
{'train_runtime': 5.1328, 'train_samples_per_second': 9.741, 'train_steps_per_second': 9.741, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 3.944, 'train_samples_per_second': 12.678, 'train_steps_per_second': 12.678, 'train_loss': 5.007021484375, 'epoch': 5.0}
{'train_runtime': 3.1309, 'train_samples_per_second': 15.97, 'train_steps_per_second': 15.97, 'train_loss': 4.5049285888671875, 'epoch': 5.0}
{'train_runtime': 3.7424, 'train_samples_per_second': 13.361, 'train_steps_per_second': 13.361, 'train_loss': 4.709947204589843, 'epoch': 5.0}
{'train_runtime': 5.0993, 'train_samples_per_second': 9.805, 'train_steps_per_second': 9.805, 'train_loss': 4.691137390136719, 'epoch': 5.0}
{'train_runtime': 2.9498, 'train_samples_per_second': 16.95, 'train_steps_per_second': 16.95, 'train_loss': 4.2192861938476565, 'epoch': 5.0}
{'train_runtime': 4.4122, 'train_samples_per_second': 11.332, 'train_steps_per_second': 11.332, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 2.8131, 'train_samples_per_second': 17.774, 'train_steps_per_second': 17.774, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 2.5142, 'train_samples_per_second': 19.887, 'train_steps_per_second': 19.887, 'train_loss': 4.2192861938476565, 'epoch': 5.0}
{'train_runtime': 3.6664, 'train_samples_per_second': 13.637, 'train_steps_per_second': 13.637, 'train_loss': 4.328012084960937, 'epoch': 5.0}
{'train_runtime': 2.9436, 'train_samples_per_second': 16.986, 'train_steps_per_second': 16.986, 'train_loss': 4.206160583496094, 'epoch': 5.0}
{'train_runtime': 4.3899, 'train_samples_per_second': 11.39, 'train_steps_per_second': 11.39, 'train_loss': 4.496748046875, 'epoch': 5.0}
{'train_runtime': 2.7315, 'train_samples_per_second': 18.305, 'train_steps_per_second': 18.305, 'train_loss': 3.6513162231445313, 'epoch': 5.0}
{'train_runtime': 5.1125, 'train_samples_per_second': 9.78, 'train_steps_per_second': 9.78, 'train_loss': 4.510918273925781, 'epoch': 5.0}
{'train_runtime': 4.0076, 'train_samples_per_second': 12.476, 'train_steps_per_second': 12.476, 'train_loss': 4.705931396484375, 'epoch': 5.0}
{'train_runtime': 3.0983, 'train_samples_per_second': 16.138, 'train_steps_per_second': 16.138, 'train_loss': 4.157211608886719, 'epoch': 5.0}
{'train_runtime': 4.6315, 'train_samples_per_second': 10.796, 'train_steps_per_second': 10.796, 'train_loss': 4.449778747558594, 'epoch': 5.0}
{'train_runtime': 4.9888, 'train_samples_per_second': 10.022, 'train_steps_per_second': 10.022, 'train_loss': 4.449778747558594, 'epoch': 5.0}
{'train_runtime': 3.0646, 'train_samples_per_second': 16.315, 'train_steps_per_second': 16.315, 'train_loss': 4.490630493164063, 'epoch': 5.0}

In [12]:
import pandas as pd

df_validation = pd.read_parquet("./cache/validation/partial/")

In [13]:
df_scoring = pd.read_parquet("./cache/scoring/partial/")

In [44]:
df = df_scoring.merge(
    df_validation,
    on=["explanation_type", "model", "estimator", "dataset_idx", "train_dataset", "train_split", "test_dataset", "test_split"],
    how="left"
)[["explanation_type", "model", "optimizer", "estimator", "dataset_idx", "pred_gain","mse", "delta_target_document"]]
df

,explanation_type,model,optimizer,estimator,dataset_idx,pred_gain,mse,delta_target_document
0,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,OptimizerKLT,DataInfEstimator: fast_implementation=True,59,1.229756,0.332690,-1.409365
1,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,OptimizerKLT,DataInfEstimator: fast_implementation=True,21,1.291397,0.106863,4.995133
2,Top-10 most influential,pythia-31m_tulu-v2-sft-mixture_train,OptimizerKLT,DataInfEstimator: fast_implementation=True,59,2.296454,0.178155,-2.008695
3,Top-10 most influential,pythia-31m_tulu-v2-sft-mixture_train,OptimizerKLT,DataInfEstimator: fast_implementation=True,21,1.305446,0.105713,4.060608
4,Top-10 most influential,pythia-31m_tulu-v2-sft-mixture_train,OptimizerKLT,DataInfEstimator: fast_implementation=True,56,1.550515,0.194724,-0.471478
...,...,...,...,...,...,...,...,...
295,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,OptimizerMSEL1,LESSEstimator: normalize=True,42,1.003162,0.000122,-0.426923
296,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,OptimizerMSEL1,LESSEstimator: normalize=True,50,0.000000,0.000000,0.385370
297,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,OptimizerMSEL1,LESSEstimator: normalize=True,27,1.002931,0.000122,-1.455358
298,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,OptimizerMSEL1,LESSEstimator: normalize=True,92,0.000000,0.000000,-0.475721
299,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,OptimizerMSEL1,LESSEstimator: normalize=True,71,0.000000,0.000000,-0.918682

In [45]:
import statsmodels.api as sm

results = []


for keys, group in df.groupby(["explanation_type", "model", "estimator", "optimizer"]):
    x = pd.to_numeric(group["pred_gain"], errors="coerce")
    y = pd.to_numeric(group["delta_target_document"], errors="coerce")
    
    mask = ~(x.isna() | y.isna())
    x_clean, y_clean = x[mask], y[mask]
    

    X = sm.add_constant(x_clean)
    model = sm.OLS(y_clean, X).fit()
    
    results.append({
        "explanation_type": keys[0],
        "model": keys[1],
        "estimator": keys[2],
        "optimizer": keys[3],
        "coef": model.params.get("pred_gain", None),
        "p_value": model.pvalues.get("pred_gain", None),
        "r_squared": model.rsquared
    })


results_df = pd.DataFrame(results)
results_df

,explanation_type,model,estimator,optimizer,coef,p_value,r_squared
0,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,OptimizerKLT,-0.540479,0.853481,0.004527
1,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,OptimizerMSEL1,169.090723,0.193544,0.201180
2,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=False,OptimizerKLT,0.875100,0.381416,0.096853
3,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=False,OptimizerMSEL1,1.056342,0.390422,0.093425
4,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,OptimizerKLT,0.875298,0.381351,0.096878
5,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,OptimizerMSEL1,1.060227,0.394506,0.091903
6,Bottom-10 least influential,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,OptimizerKLT,-3.780967,0.458693,0.070419
7,Bottom-10 least influential,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,OptimizerMSEL1,112.452413,0.198762,0.197036
8,Bottom-10 least influential,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=False,OptimizerKLT,0.231457,0.861859,0.004020
9,Bottom-10 least influential,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=False,OptimizerMSEL1,0.231457,0.861859,0.004020
10,Bottom-10 least influential,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,OptimizerKLT,0.235764,0.859454,0.004162
11,Bottom-10 least influential,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,OptimizerMSEL1,0.235764,0.859454,0.004162
12,Mean-10 most average scores,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,OptimizerKLT,-1.437588,0.718308,0.017161
13,Mean-10 most average scores,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,OptimizerMSEL1,115.771951,0.219045,0.181885
14,Mean-10 most average scores,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=False,OptimizerKLT,0.055866,0.966512,0.000234
15,Mean-10 most average scores,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=False,OptimizerMSEL1,0.055866,0.966512,0.000234
16,Mean-10 most average scores,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,OptimizerKLT,0.055870,0.966512,0.000234
17,Mean-10 most average scores,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,OptimizerMSEL1,0.055870,0.966512,0.000234
18,Tail-10 most extreme scores,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,OptimizerKLT,-0.688936,0.646766,0.027548
19,Tail-10 most extreme scores,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,OptimizerMSEL1,109.169091,0.298945,0.133613
20,Tail-10 most extreme scores,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=False,OptimizerKLT,0.525424,0.589184,0.038046
21,Tail-10 most extreme scores,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=False,OptimizerMSEL1,0.543118,0.567658,0.042513
22,Tail-10 most extreme scores,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,OptimizerKLT,0.700687,0.565514,0.042975
23,Tail-10 most extreme scores,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,OptimizerMSEL1,0.704649,0.566813,0.042695
24,Top-10 most influential,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,OptimizerKLT,-0.498005,0.731122,0.015586
25,Top-10 most influential,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,OptimizerMSEL1,96.502415,0.342167,0.113047
26,Top-10 most influential,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=False,OptimizerKLT,0.359448,0.699390,0.019640
27,Top-10 most influential,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=False,OptimizerMSEL1,0.375530,0.679721,0.022418
28,Top-10 most influential,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,OptimizerKLT,0.815044,0.544246,0.047733
29,Top-10 most influential,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,OptimizerMSEL1,0.820920,0.544958,0.047568