In [1]:
!rm -rf cache/validation/

In [2]:
import os
from multiprocess import set_start_method
set_start_method("spawn")
import logging
logger = logging.getLogger("ignite.handlers.early_stopping.EarlyStopping")
logger.setLevel(logging.WARNING)

In [3]:
from transformers import Trainer, AutoModelForCausalLM, AutoTokenizer, TrainingArguments, DataCollatorForLanguageModeling
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, TaskType, PeftModel

from coreset_trainer.trainer import CoresetTrainer
import os
import torch

import argparse

In [4]:
from load_experiment_data import (
    train_dataset_name,
    test_dataset_name,
    train_dataset_split,
    test_dataset_split,
    load_data_and_estimators,
    explanation_types
)
train_dataset, test_dataset, estimators, test_indices = load_data_and_estimators()

Repo card metadata block was not found. Setting CardData to empty.
[WARNING] Repo card metadata block was not found. Setting CardData to empty.
Repo card metadata block was not found. Setting CardData to empty.
[WARNING] Repo card metadata block was not found. Setting CardData to empty.

influence_estimate_path: ./results/influence/LESSEstimator/8192-True/pythia-31m_tulu-v2-sft-mixture_train/tulu-v2-sft-mixture_test/tulu-v2-sft-mixture_test/estimate.parquet
dirname: ./results/influence/LESSEstimator/8192-True/pythia-31m_tulu-v2-sft-mixture_train/tulu-v2-sft-mixture_test/tulu-v2-sft-mixture_test
exists: True
influence_estimate_path: ./results/influence/DataInfEstimator/8192-True/pythia-31m_tulu-v2-sft-mixture_train/tulu-v2-sft-mixture_test/tulu-v2-sft-mixture_test/estimate.parquet
dirname: ./results/influence/DataInfEstimator/8192-True/pythia-31m_tulu-v2-sft-mixture_train/tulu-v2-sft-mixture_test/tulu-v2-sft-mixture_test
exists: True

In [5]:
from functools import partial
from explanations import KRandom
k_random_types = [partial(KRandom, seed=s) for s in range(9)]
explanation_types = explanation_types + k_random_types

In [6]:
import logging
from concurrent.futures import ProcessPoolExecutor, as_completed
import torch
import multiprocessing
from tqdm import tqdm
import itertools
import pandas as pd
import traceback

logging.basicConfig(level=logging.ERROR, format='%(asctime)s [%(levelname)s] %(message)s')
multiprocessing.set_start_method('spawn', force=True)
torch.manual_seed(42)




num_devices = torch.cuda.device_count()

In [7]:
import logging
from concurrent.futures import ProcessPoolExecutor, as_completed
import torch
import multiprocessing
from validation_worker_validation import process

logging.basicConfig(level=logging.ERROR, format='%(asctime)s [%(levelname)s] %(message)s')

multiprocessing.set_start_method('spawn', force=True)

num_gpus = torch.cuda.device_count()
logging.info(f"Detected {num_gpus} GPUs")


import warnings
warnings.filterwarnings("ignore")

[INFO] Detected 2 GPUs

In [ ]:

device_ids = itertools.cycle(range(num_devices))
results = []

from peft import LoraConfig, get_peft_model, PeftModel


for estimator in estimators:
    

    explanations = [
        explanation_type(row.name, estimator)
        for explanation_type in explanation_types
        for _, row in estimator.influence_estimate.iloc[test_indices].iterrows()
    ]
            
        
    partial_results_dir =  os.path.join("./cache/validation/partial/",
        estimator.get_config_string(),
        os.path.basename(estimator.model_path),
        train_dataset_name,
        train_dataset_split,
        test_dataset_name,
        test_dataset_split,
        "partial")
    with ProcessPoolExecutor(max_workers=2*num_devices) as executor:
        futures = {}
        for seed in range(1):
            for ii, explanation in enumerate(explanations):
                
                # # random documents to test log_p for in addition to the document beeing explained
                # random_test_indices = test_dataset.shuffle(seed=ii).shuffle(seed=seed).select(range(explanation.k))["indices"]
            
                text_indices = [explanation.document_idx] #+ random_test_indices
                futures[explanation] = executor.submit(
                        process,
                        partial_results_dir,
                        estimator, explanation,
                        train_dataset.select(explanation.documents), explanation.documents, 
                        test_dataset.select(text_indices), text_indices,                 
                        train_dataset, train_dataset_name, train_dataset_split, test_dataset, test_dataset_name, test_dataset_split, 
                        next(device_ids),
                        seed,
                        ii
                )

        with tqdm(total=len(futures), desc="Explanations", position=0) as pbar:
            for future in as_completed(futures.values()):
                try:
                    future.result()  
                except Exception as e:
                    logging.error(f"A future failed: {e}\n{traceback.format_exc()}")
                    raise
                finally:
                    pbar.update(1)

Explanations:   0%|          | 0/1400 [00:00<?, ?it/s]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   0%|          | 1/1400 [00:16<6:23:11, 16.43s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   1%|          | 8/1400 [00:31<1:02:30,  2.69s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   1%|          | 12/1400 [00:46<53:31,  2.31s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   1%|          | 16/1400 [01:01<53:32,  2.32s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   1%|▏         | 20/1400 [01:16<49:55,  2.17s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 24/1400 [01:31<53:26,  2.33s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 27/1400 [01:46<1:08:33,  3.00s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 28/1400 [01:47<50:40,  2.22s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 30/1400 [02:01<1:34:27,  4.14s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 31/1400 [02:01<1:07:46,  2.97s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 33/1400 [02:15<1:46:38,  4.68s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 36/1400 [02:16<48:40,  2.14s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 37/1400 [02:29<1:56:29,  5.13s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 40/1400 [02:31<49:14,  2.17s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 41/1400 [02:43<1:56:28,  5.14s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 43/1400 [02:45<1:09:38,  3.08s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 45/1400 [02:57<1:37:10,  4.30s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 48/1400 [03:00<50:29,  2.24s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▎         | 49/1400 [03:11<1:45:01,  4.66s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▎         | 51/1400 [03:14<1:10:25,  3.13s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▎         | 52/1400 [03:15<50:55,  2.27s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 53/1400 [03:25<1:44:25,  4.65s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 55/1400 [03:29<1:11:06,  3.17s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 56/1400 [03:29<51:57,  2.32s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 57/1400 [03:39<1:40:45,  4.50s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 59/1400 [03:43<1:12:27,  3.24s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 60/1400 [03:43<53:01,  2.37s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 61/1400 [03:53<1:37:25,  4.37s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 62/1400 [03:56<1:34:07,  4.22s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   5%|▍         | 64/1400 [03:58<52:51,  2.37s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   5%|▍         | 65/1400 [04:06<1:33:39,  4.21s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 13.5474, 'train_samples_per_second': 18.454, 'train_steps_per_second': 18.454, 'train_loss': 3.02781494140625, 'epoch': 25.0}
{'train_runtime': 12.9965, 'train_samples_per_second': 19.236, 'train_steps_per_second': 19.236, 'train_loss': 3.02715966796875, 'epoch': 25.0}
{'train_runtime': 13.04, 'train_samples_per_second': 19.172, 'train_steps_per_second': 19.172, 'train_loss': 3.00219873046875, 'epoch': 25.0}
{'train_runtime': 13.0598, 'train_samples_per_second': 19.143, 'train_steps_per_second': 19.143, 'train_loss': 3.00130859375, 'epoch': 25.0}
{'train_runtime': 12.9841, 'train_samples_per_second': 19.254, 'train_steps_per_second': 19.254, 'train_loss': 3.054629150390625, 'epoch': 25.0}
{'train_runtime': 12.7992, 'train_samples_per_second': 19.532, 'train_steps_per_second': 19.532, 'train_loss': 3.04400830078125, 'epoch': 25.0}
{'train_runtime': 12.7774, 'train_samples_per_second': 19.566, 'train_steps_per_second': 19.566, 'train_loss': 3.024914794921875, 'epoch': 25.0}
{'train_runtime': 12.5398, 'train_samples_per_second': 19.937, 'train_steps_per_second': 19.937, 'train_loss': 3.01526611328125, 'epoch': 25.0}
{'train_runtime': 12.4752, 'train_samples_per_second': 20.04, 'train_steps_per_second': 20.04, 'train_loss': 3.017311767578125, 'epoch': 25.0}
{'train_runtime': 12.3663, 'train_samples_per_second': 20.216, 'train_steps_per_second': 20.216, 'train_loss': 3.027128662109375, 'epoch': 25.0}
{'train_runtime': 12.0811, 'train_samples_per_second': 20.694, 'train_steps_per_second': 20.694, 'train_loss': 2.9979521484375, 'epoch': 25.0}
{'train_runtime': 11.7981, 'train_samples_per_second': 21.19, 'train_steps_per_second': 21.19, 'train_loss': 3.010223876953125, 'epoch': 25.0}
{'train_runtime': 11.8392, 'train_samples_per_second': 21.116, 'train_steps_per_second': 21.116, 'train_loss': 3.041669677734375, 'epoch': 25.0}
{'train_runtime': 11.6371, 'train_samples_per_second': 21.483, 'train_steps_per_second': 21.483, 'train_loss': 3.028433837890625, 'epoch': 25.0}
{'train_runtime': 11.6836, 'train_samples_per_second': 21.397, 'train_steps_per_second': 21.397, 'train_loss': 3.010166748046875, 'epoch': 25.0}
{'train_runtime': 11.6909, 'train_samples_per_second': 21.384, 'train_steps_per_second': 21.384, 'train_loss': 3.0388369140625, 'epoch': 25.0}
{'train_runtime': 11.6112, 'train_samples_per_second': 21.531, 'train_steps_per_second': 21.531, 'train_loss': 3.018043212890625, 'epoch': 25.0}
{'train_runtime': 11.6896, 'train_samples_per_second': 21.386, 'train_steps_per_second': 21.386, 'train_loss': 3.020473388671875, 'epoch': 25.0}
{'train_runtime': 11.5905, 'train_samples_per_second': 21.569, 'train_steps_per_second': 21.569, 'train_loss': 3.022986083984375, 'epoch': 25.0}
{'train_runtime': 11.6923, 'train_samples_per_second': 21.382, 'train_steps_per_second': 21.382, 'train_loss': 3.01251123046875, 'epoch': 25.0}
{'train_runtime': 11.4862, 'train_samples_per_second': 21.765, 'train_steps_per_second': 21.765, 'train_loss': 3.016453857421875, 'epoch': 25.0}
{'train_runtime': 11.6276, 'train_samples_per_second': 21.501, 'train_steps_per_second': 21.501, 'train_loss': 3.053210693359375, 'epoch': 25.0}
{'train_runtime': 11.7503, 'train_samples_per_second': 21.276, 'train_steps_per_second': 21.276, 'train_loss': 3.05292578125, 'epoch': 25.0}
{'train_runtime': 11.6599, 'train_samples_per_second': 21.441, 'train_steps_per_second': 21.441, 'train_loss': 3.012577392578125, 'epoch': 25.0}
{'train_runtime': 11.4815, 'train_samples_per_second': 21.774, 'train_steps_per_second': 21.774, 'train_loss': 3.0039189453125, 'epoch': 25.0}
{'train_runtime': 11.3045, 'train_samples_per_second': 22.115, 'train_steps_per_second': 22.115, 'train_loss': 3.163389892578125, 'epoch': 25.0}
{'train_runtime': 10.8505, 'train_samples_per_second': 23.04, 'train_steps_per_second': 23.04, 'train_loss': 2.829462646484375, 'epoch': 25.0}
{'train_runtime': 9.4989, 'train_samples_per_second': 26.319, 'train_steps_per_second': 26.319, 'train_loss': 3.041861083984375, 'epoch': 25.0}
{'train_runtime': 11.3151, 'train_samples_per_second': 22.094, 'train_steps_per_second': 22.094, 'train_loss': 3.24241455078125, 'epoch': 25.0}
{'train_runtime': 11.3909, 'train_samples_per_second': 21.947, 'train_steps_per_second': 21.947, 'train_loss': 3.10711181640625, 'epoch': 25.0}
{'train_runtime': 12.5714, 'train_samples_per_second': 19.886, 'train_steps_per_second': 19.886, 'train_loss': 3.080703369140625, 'epoch': 25.0}
{'train_runtime': 11.2687, 'train_samples_per_second': 22.185, 'train_steps_per_second': 22.185, 'train_loss': 3.07789794921875, 'epoch': 25.0}
{'train_runtime': 10.2129, 'train_samples_per_second': 24.479, 'train_steps_per_second': 24.479, 'train_loss': 2.86589794921875, 'epoch': 25.0}
{'train_runtime': 11.0373, 'train_samples_per_second': 22.65, 'train_steps_per_second': 22.65, 'train_loss': 2.88640087890625, 'epoch': 25.0}
{'train_runtime': 10.7815, 'train_samples_per_second': 23.188, 'train_steps_per_second': 23.188, 'train_loss': 3.0966611328125, 'epoch': 25.0}
{'train_runtime': 10.4582, 'train_samples_per_second': 23.905, 'train_steps_per_second': 23.905, 'train_loss': 2.890841552734375, 'epoch': 25.0}
{'train_runtime': 9.9453, 'train_samples_per_second': 25.137, 'train_steps_per_second': 25.137, 'train_loss': 2.87404150390625, 'epoch': 25.0}
{'train_runtime': 9.9488, 'train_samples_per_second': 25.129, 'train_steps_per_second': 25.129, 'train_loss': 2.923584716796875, 'epoch': 25.0}
{'train_runtime': 9.8299, 'train_samples_per_second': 25.433, 'train_steps_per_second': 25.433, 'train_loss': 3.12866064453125, 'epoch': 25.0}
{'train_runtime': 9.8488, 'train_samples_per_second': 25.384, 'train_steps_per_second': 25.384, 'train_loss': 3.08299853515625, 'epoch': 25.0}
{'train_runtime': 10.0896, 'train_samples_per_second': 24.778, 'train_steps_per_second': 24.778, 'train_loss': 2.8862978515625, 'epoch': 25.0}
{'train_runtime': 9.8855, 'train_samples_per_second': 25.289, 'train_steps_per_second': 25.289, 'train_loss': 3.110947265625, 'epoch': 25.0}
{'train_runtime': 10.6038, 'train_samples_per_second': 23.577, 'train_steps_per_second': 23.577, 'train_loss': 2.95001220703125, 'epoch': 25.0}
{'train_runtime': 10.7502, 'train_samples_per_second': 23.255, 'train_steps_per_second': 23.255, 'train_loss': 3.154256591796875, 'epoch': 25.0}
{'train_runtime': 10.2241, 'train_samples_per_second': 24.452, 'train_steps_per_second': 24.452, 'train_loss': 3.017153564453125, 'epoch': 25.0}
{'train_runtime': 10.6681, 'train_samples_per_second': 23.434, 'train_steps_per_second': 23.434, 'train_loss': 2.9228701171875, 'epoch': 25.0}
{'train_runtime': 10.5366, 'train_samples_per_second': 23.727, 'train_steps_per_second': 23.727, 'train_loss': 2.909772705078125, 'epoch': 25.0}
{'train_runtime': 11.9882, 'train_samples_per_second': 20.854, 'train_steps_per_second': 20.854, 'train_loss': 3.025588623046875, 'epoch': 25.0}
{'train_runtime': 11.4816, 'train_samples_per_second': 21.774, 'train_steps_per_second': 21.774, 'train_loss': 2.755241455078125, 'epoch': 25.0}
{'train_runtime': 11.5142, 'train_samples_per_second': 21.712, 'train_steps_per_second': 21.712, 'train_loss': 2.9523115234375, 'epoch': 25.0}
{'train_runtime': 11.4861, 'train_samples_per_second': 21.766, 'train_steps_per_second': 21.766, 'train_loss': 2.96860107421875, 'epoch': 25.0}
{'train_runtime': 13.5353, 'train_samples_per_second': 18.47, 'train_steps_per_second': 18.47, 'train_loss': 3.389801513671875, 'epoch': 25.0}
{'train_runtime': 12.768, 'train_samples_per_second': 19.58, 'train_steps_per_second': 19.58, 'train_loss': 3.285535400390625, 'epoch': 25.0}
{'train_runtime': 12.6911, 'train_samples_per_second': 19.699, 'train_steps_per_second': 19.699, 'train_loss': 3.408782470703125, 'epoch': 25.0}
{'train_runtime': 11.7661, 'train_samples_per_second': 21.247, 'train_steps_per_second': 21.247, 'train_loss': 3.404921142578125, 'epoch': 25.0}
{'train_runtime': 13.0663, 'train_samples_per_second': 19.133, 'train_steps_per_second': 19.133, 'train_loss': 3.2630283203125, 'epoch': 25.0}

Explanations:  16%|█▌        | 225/1400 [13:00<50:16,  2.57s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  16%|█▌        | 226/1400 [13:11<1:42:39,  5.25s/it]

{'train_runtime': 13.5407, 'train_samples_per_second': 18.463, 'train_steps_per_second': 18.463, 'train_loss': 3.034010498046875, 'epoch': 25.0}
{'train_runtime': 12.9388, 'train_samples_per_second': 19.322, 'train_steps_per_second': 19.322, 'train_loss': 3.032939208984375, 'epoch': 25.0}
{'train_runtime': 12.957, 'train_samples_per_second': 19.295, 'train_steps_per_second': 19.295, 'train_loss': 3.035398681640625, 'epoch': 25.0}
{'train_runtime': 12.9882, 'train_samples_per_second': 19.248, 'train_steps_per_second': 19.248, 'train_loss': 3.035988525390625, 'epoch': 25.0}
{'train_runtime': 12.9336, 'train_samples_per_second': 19.329, 'train_steps_per_second': 19.329, 'train_loss': 3.014712158203125, 'epoch': 25.0}
{'train_runtime': 12.9573, 'train_samples_per_second': 19.294, 'train_steps_per_second': 19.294, 'train_loss': 3.036077392578125, 'epoch': 25.0}
{'train_runtime': 12.8537, 'train_samples_per_second': 19.45, 'train_steps_per_second': 19.45, 'train_loss': 3.01635791015625, 'epoch': 25.0}
{'train_runtime': 13.0316, 'train_samples_per_second': 19.184, 'train_steps_per_second': 19.184, 'train_loss': 3.041692626953125, 'epoch': 25.0}
{'train_runtime': 12.8305, 'train_samples_per_second': 19.485, 'train_steps_per_second': 19.485, 'train_loss': 3.037330322265625, 'epoch': 25.0}
{'train_runtime': 12.6914, 'train_samples_per_second': 19.698, 'train_steps_per_second': 19.698, 'train_loss': 3.04044580078125, 'epoch': 25.0}
{'train_runtime': 12.6169, 'train_samples_per_second': 19.815, 'train_steps_per_second': 19.815, 'train_loss': 3.01131494140625, 'epoch': 25.0}
{'train_runtime': 12.3737, 'train_samples_per_second': 20.204, 'train_steps_per_second': 20.204, 'train_loss': 3.032170166015625, 'epoch': 25.0}
{'train_runtime': 12.4066, 'train_samples_per_second': 20.151, 'train_steps_per_second': 20.151, 'train_loss': 2.994379150390625, 'epoch': 25.0}
{'train_runtime': 12.3822, 'train_samples_per_second': 20.19, 'train_steps_per_second': 20.19, 'train_loss': 3.02396728515625, 'epoch': 25.0}
{'train_runtime': 12.4151, 'train_samples_per_second': 20.137, 'train_steps_per_second': 20.137, 'train_loss': 3.026988037109375, 'epoch': 25.0}
{'train_runtime': 12.3081, 'train_samples_per_second': 20.312, 'train_steps_per_second': 20.312, 'train_loss': 3.00617431640625, 'epoch': 25.0}
{'train_runtime': 12.2374, 'train_samples_per_second': 20.429, 'train_steps_per_second': 20.429, 'train_loss': 3.02283154296875, 'epoch': 25.0}
{'train_runtime': 12.2458, 'train_samples_per_second': 20.415, 'train_steps_per_second': 20.415, 'train_loss': 3.015635009765625, 'epoch': 25.0}
{'train_runtime': 12.1545, 'train_samples_per_second': 20.568, 'train_steps_per_second': 20.568, 'train_loss': 3.038275634765625, 'epoch': 25.0}
{'train_runtime': 12.0565, 'train_samples_per_second': 20.736, 'train_steps_per_second': 20.736, 'train_loss': 3.019334228515625, 'epoch': 25.0}
{'train_runtime': 12.0501, 'train_samples_per_second': 20.747, 'train_steps_per_second': 20.747, 'train_loss': 3.018222900390625, 'epoch': 25.0}
{'train_runtime': 12.0165, 'train_samples_per_second': 20.805, 'train_steps_per_second': 20.805, 'train_loss': 3.023997314453125, 'epoch': 25.0}
{'train_runtime': 12.071, 'train_samples_per_second': 20.711, 'train_steps_per_second': 20.711, 'train_loss': 3.02177685546875, 'epoch': 25.0}
{'train_runtime': 12.3015, 'train_samples_per_second': 20.323, 'train_steps_per_second': 20.323, 'train_loss': 3.02091748046875, 'epoch': 25.0}
{'train_runtime': 11.734, 'train_samples_per_second': 21.306, 'train_steps_per_second': 21.306, 'train_loss': 3.0094609375, 'epoch': 25.0}
{'train_runtime': 12.0738, 'train_samples_per_second': 20.706, 'train_steps_per_second': 20.706, 'train_loss': 3.28834423828125, 'epoch': 25.0}
{'train_runtime': 9.8934, 'train_samples_per_second': 25.269, 'train_steps_per_second': 25.269, 'train_loss': 3.085242431640625, 'epoch': 25.0}
{'train_runtime': 10.4286, 'train_samples_per_second': 23.973, 'train_steps_per_second': 23.973, 'train_loss': 2.933294677734375, 'epoch': 25.0}
{'train_runtime': 10.4563, 'train_samples_per_second': 23.909, 'train_steps_per_second': 23.909, 'train_loss': 3.0998671875, 'epoch': 25.0}
{'train_runtime': 13.311, 'train_samples_per_second': 18.781, 'train_steps_per_second': 18.781, 'train_loss': 2.935566650390625, 'epoch': 25.0}
{'train_runtime': 10.6327, 'train_samples_per_second': 23.512, 'train_steps_per_second': 23.512, 'train_loss': 3.045699462890625, 'epoch': 25.0}
{'train_runtime': 11.2699, 'train_samples_per_second': 22.183, 'train_steps_per_second': 22.183, 'train_loss': 3.0617587890625, 'epoch': 25.0}
{'train_runtime': 11.3939, 'train_samples_per_second': 21.942, 'train_steps_per_second': 21.942, 'train_loss': 3.06474609375, 'epoch': 25.0}
{'train_runtime': 11.2191, 'train_samples_per_second': 22.283, 'train_steps_per_second': 22.283, 'train_loss': 2.897288818359375, 'epoch': 25.0}
{'train_runtime': 11.0822, 'train_samples_per_second': 22.559, 'train_steps_per_second': 22.559, 'train_loss': 2.85591162109375, 'epoch': 25.0}
{'train_runtime': 10.4039, 'train_samples_per_second': 24.029, 'train_steps_per_second': 24.029, 'train_loss': 2.983884521484375, 'epoch': 25.0}
{'train_runtime': 10.3067, 'train_samples_per_second': 24.256, 'train_steps_per_second': 24.256, 'train_loss': 2.950263916015625, 'epoch': 25.0}
{'train_runtime': 9.5482, 'train_samples_per_second': 26.183, 'train_steps_per_second': 26.183, 'train_loss': 2.960171875, 'epoch': 25.0}
{'train_runtime': 9.9746, 'train_samples_per_second': 25.064, 'train_steps_per_second': 25.064, 'train_loss': 2.81979833984375, 'epoch': 25.0}
{'train_runtime': 10.2058, 'train_samples_per_second': 24.496, 'train_steps_per_second': 24.496, 'train_loss': 3.11913720703125, 'epoch': 25.0}
{'train_runtime': 9.9804, 'train_samples_per_second': 25.049, 'train_steps_per_second': 25.049, 'train_loss': 3.0594892578125, 'epoch': 25.0}
{'train_runtime': 11.5539, 'train_samples_per_second': 21.638, 'train_steps_per_second': 21.638, 'train_loss': 3.306980712890625, 'epoch': 25.0}
{'train_runtime': 10.5613, 'train_samples_per_second': 23.671, 'train_steps_per_second': 23.671, 'train_loss': 2.785873046875, 'epoch': 25.0}
{'train_runtime': 10.3816, 'train_samples_per_second': 24.081, 'train_steps_per_second': 24.081, 'train_loss': 2.950428466796875, 'epoch': 25.0}
{'train_runtime': 10.8004, 'train_samples_per_second': 23.147, 'train_steps_per_second': 23.147, 'train_loss': 2.892775390625, 'epoch': 25.0}
{'train_runtime': 10.3659, 'train_samples_per_second': 24.118, 'train_steps_per_second': 24.118, 'train_loss': 3.118068603515625, 'epoch': 25.0}
{'train_runtime': 11.8895, 'train_samples_per_second': 21.027, 'train_steps_per_second': 21.027, 'train_loss': 3.063936279296875, 'epoch': 25.0}
{'train_runtime': 10.3069, 'train_samples_per_second': 24.256, 'train_steps_per_second': 24.256, 'train_loss': 3.14770458984375, 'epoch': 25.0}
{'train_runtime': 11.5905, 'train_samples_per_second': 21.569, 'train_steps_per_second': 21.569, 'train_loss': 2.945234375, 'epoch': 25.0}
{'train_runtime': 11.6423, 'train_samples_per_second': 21.474, 'train_steps_per_second': 21.474, 'train_loss': 3.13006005859375, 'epoch': 25.0}
{'train_runtime': 12.9553, 'train_samples_per_second': 19.297, 'train_steps_per_second': 19.297, 'train_loss': 3.143857421875, 'epoch': 25.0}
{'train_runtime': 12.6696, 'train_samples_per_second': 19.732, 'train_steps_per_second': 19.732, 'train_loss': 3.36199462890625, 'epoch': 25.0}
{'train_runtime': 12.7913, 'train_samples_per_second': 19.545, 'train_steps_per_second': 19.545, 'train_loss': 3.1403701171875, 'epoch': 25.0}
{'train_runtime': 12.2282, 'train_samples_per_second': 20.445, 'train_steps_per_second': 20.445, 'train_loss': 3.232667724609375, 'epoch': 25.0}
{'train_runtime': 13.4401, 'train_samples_per_second': 18.601, 'train_steps_per_second': 18.601, 'train_loss': 3.299658447265625, 'epoch': 25.0}
{'train_runtime': 13.2261, 'train_samples_per_second': 18.902, 'train_steps_per_second': 18.902, 'train_loss': 3.138772705078125, 'epoch': 25.0}

Explanations:  16%|█▌        | 227/1400 [13:12<1:15:14,  3.85s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  16%|█▋        | 228/1400 [13:13<59:51,  3.06s/it]

{'train_runtime': 13.4881, 'train_samples_per_second': 18.535, 'train_steps_per_second': 18.535, 'train_loss': 3.015989501953125, 'epoch': 25.0}
{'train_runtime': 12.9804, 'train_samples_per_second': 19.26, 'train_steps_per_second': 19.26, 'train_loss': 3.0266875, 'epoch': 25.0}
{'train_runtime': 13.0175, 'train_samples_per_second': 19.205, 'train_steps_per_second': 19.205, 'train_loss': 3.032512451171875, 'epoch': 25.0}
{'train_runtime': 13.0576, 'train_samples_per_second': 19.146, 'train_steps_per_second': 19.146, 'train_loss': 3.015510986328125, 'epoch': 25.0}
{'train_runtime': 12.9699, 'train_samples_per_second': 19.275, 'train_steps_per_second': 19.275, 'train_loss': 3.01892333984375, 'epoch': 25.0}
{'train_runtime': 12.9075, 'train_samples_per_second': 19.369, 'train_steps_per_second': 19.369, 'train_loss': 3.015942626953125, 'epoch': 25.0}
{'train_runtime': 12.7647, 'train_samples_per_second': 19.585, 'train_steps_per_second': 19.585, 'train_loss': 3.02765380859375, 'epoch': 25.0}
{'train_runtime': 12.7557, 'train_samples_per_second': 19.599, 'train_steps_per_second': 19.599, 'train_loss': 3.012537353515625, 'epoch': 25.0}
{'train_runtime': 12.7281, 'train_samples_per_second': 19.642, 'train_steps_per_second': 19.642, 'train_loss': 3.03818994140625, 'epoch': 25.0}
{'train_runtime': 12.5813, 'train_samples_per_second': 19.871, 'train_steps_per_second': 19.871, 'train_loss': 3.031569091796875, 'epoch': 25.0}
{'train_runtime': 12.483, 'train_samples_per_second': 20.027, 'train_steps_per_second': 20.027, 'train_loss': 3.0107412109375, 'epoch': 25.0}
{'train_runtime': 12.3969, 'train_samples_per_second': 20.166, 'train_steps_per_second': 20.166, 'train_loss': 3.027863525390625, 'epoch': 25.0}
{'train_runtime': 12.4335, 'train_samples_per_second': 20.107, 'train_steps_per_second': 20.107, 'train_loss': 3.02247216796875, 'epoch': 25.0}
{'train_runtime': 12.4347, 'train_samples_per_second': 20.105, 'train_steps_per_second': 20.105, 'train_loss': 3.01575048828125, 'epoch': 25.0}
{'train_runtime': 12.362, 'train_samples_per_second': 20.223, 'train_steps_per_second': 20.223, 'train_loss': 3.037406982421875, 'epoch': 25.0}
{'train_runtime': 12.272, 'train_samples_per_second': 20.372, 'train_steps_per_second': 20.372, 'train_loss': 3.008060791015625, 'epoch': 25.0}
{'train_runtime': 12.3715, 'train_samples_per_second': 20.208, 'train_steps_per_second': 20.208, 'train_loss': 3.05559716796875, 'epoch': 25.0}
{'train_runtime': 12.2124, 'train_samples_per_second': 20.471, 'train_steps_per_second': 20.471, 'train_loss': 3.037138916015625, 'epoch': 25.0}
{'train_runtime': 12.2088, 'train_samples_per_second': 20.477, 'train_steps_per_second': 20.477, 'train_loss': 3.025940673828125, 'epoch': 25.0}
{'train_runtime': 11.9249, 'train_samples_per_second': 20.964, 'train_steps_per_second': 20.964, 'train_loss': 3.011501220703125, 'epoch': 25.0}
{'train_runtime': 12.0722, 'train_samples_per_second': 20.709, 'train_steps_per_second': 20.709, 'train_loss': 3.015190185546875, 'epoch': 25.0}
{'train_runtime': 11.9982, 'train_samples_per_second': 20.836, 'train_steps_per_second': 20.836, 'train_loss': 3.007614501953125, 'epoch': 25.0}
{'train_runtime': 12.1572, 'train_samples_per_second': 20.564, 'train_steps_per_second': 20.564, 'train_loss': 3.034236328125, 'epoch': 25.0}
{'train_runtime': 12.3844, 'train_samples_per_second': 20.187, 'train_steps_per_second': 20.187, 'train_loss': 3.02029931640625, 'epoch': 25.0}
{'train_runtime': 11.781, 'train_samples_per_second': 21.221, 'train_steps_per_second': 21.221, 'train_loss': 3.007620361328125, 'epoch': 25.0}
{'train_runtime': 12.206, 'train_samples_per_second': 20.482, 'train_steps_per_second': 20.482, 'train_loss': 2.9910009765625, 'epoch': 25.0}
{'train_runtime': 9.6855, 'train_samples_per_second': 25.812, 'train_steps_per_second': 25.812, 'train_loss': 2.963512939453125, 'epoch': 25.0}
{'train_runtime': 11.1397, 'train_samples_per_second': 22.442, 'train_steps_per_second': 22.442, 'train_loss': 3.02832958984375, 'epoch': 25.0}
{'train_runtime': 10.6112, 'train_samples_per_second': 23.56, 'train_steps_per_second': 23.56, 'train_loss': 3.20810302734375, 'epoch': 25.0}
{'train_runtime': 12.2849, 'train_samples_per_second': 20.35, 'train_steps_per_second': 20.35, 'train_loss': 3.19168505859375, 'epoch': 25.0}
{'train_runtime': 10.8404, 'train_samples_per_second': 23.062, 'train_steps_per_second': 23.062, 'train_loss': 3.175331787109375, 'epoch': 25.0}
{'train_runtime': 11.5891, 'train_samples_per_second': 21.572, 'train_steps_per_second': 21.572, 'train_loss': 3.059279541015625, 'epoch': 25.0}
{'train_runtime': 10.6631, 'train_samples_per_second': 23.445, 'train_steps_per_second': 23.445, 'train_loss': 2.881858154296875, 'epoch': 25.0}
{'train_runtime': 11.3851, 'train_samples_per_second': 21.958, 'train_steps_per_second': 21.958, 'train_loss': 3.014780029296875, 'epoch': 25.0}
{'train_runtime': 10.865, 'train_samples_per_second': 23.01, 'train_steps_per_second': 23.01, 'train_loss': 2.87285693359375, 'epoch': 25.0}
{'train_runtime': 10.6718, 'train_samples_per_second': 23.426, 'train_steps_per_second': 23.426, 'train_loss': 2.9570009765625, 'epoch': 25.0}
{'train_runtime': 10.9656, 'train_samples_per_second': 22.799, 'train_steps_per_second': 22.799, 'train_loss': 3.047349365234375, 'epoch': 25.0}
{'train_runtime': 9.6998, 'train_samples_per_second': 25.774, 'train_steps_per_second': 25.774, 'train_loss': 2.691581787109375, 'epoch': 25.0}
{'train_runtime': 9.9284, 'train_samples_per_second': 25.18, 'train_steps_per_second': 25.18, 'train_loss': 3.1543359375, 'epoch': 25.0}
{'train_runtime': 10.4513, 'train_samples_per_second': 23.921, 'train_steps_per_second': 23.921, 'train_loss': 3.04670556640625, 'epoch': 25.0}
{'train_runtime': 9.7582, 'train_samples_per_second': 25.619, 'train_steps_per_second': 25.619, 'train_loss': 3.07256103515625, 'epoch': 25.0}
{'train_runtime': 11.862, 'train_samples_per_second': 21.076, 'train_steps_per_second': 21.076, 'train_loss': 3.27129052734375, 'epoch': 25.0}
{'train_runtime': 10.3433, 'train_samples_per_second': 24.17, 'train_steps_per_second': 24.17, 'train_loss': 3.157740478515625, 'epoch': 25.0}
{'train_runtime': 10.8762, 'train_samples_per_second': 22.986, 'train_steps_per_second': 22.986, 'train_loss': 2.707683837890625, 'epoch': 25.0}
{'train_runtime': 11.4582, 'train_samples_per_second': 21.818, 'train_steps_per_second': 21.818, 'train_loss': 2.864385009765625, 'epoch': 25.0}
{'train_runtime': 10.3145, 'train_samples_per_second': 24.238, 'train_steps_per_second': 24.238, 'train_loss': 2.944499267578125, 'epoch': 25.0}
{'train_runtime': 12.0926, 'train_samples_per_second': 20.674, 'train_steps_per_second': 20.674, 'train_loss': 3.287132080078125, 'epoch': 25.0}
{'train_runtime': 11.3209, 'train_samples_per_second': 22.083, 'train_steps_per_second': 22.083, 'train_loss': 2.87604931640625, 'epoch': 25.0}
{'train_runtime': 12.5596, 'train_samples_per_second': 19.905, 'train_steps_per_second': 19.905, 'train_loss': 3.029584716796875, 'epoch': 25.0}
{'train_runtime': 12.1459, 'train_samples_per_second': 20.583, 'train_steps_per_second': 20.583, 'train_loss': 3.071322265625, 'epoch': 25.0}
{'train_runtime': 13.3565, 'train_samples_per_second': 18.718, 'train_steps_per_second': 18.718, 'train_loss': 3.194617431640625, 'epoch': 25.0}
{'train_runtime': 12.7521, 'train_samples_per_second': 19.605, 'train_steps_per_second': 19.605, 'train_loss': 3.199584716796875, 'epoch': 25.0}
{'train_runtime': 12.5197, 'train_samples_per_second': 19.969, 'train_steps_per_second': 19.969, 'train_loss': 3.05205224609375, 'epoch': 25.0}
{'train_runtime': 11.9406, 'train_samples_per_second': 20.937, 'train_steps_per_second': 20.937, 'train_loss': 3.183694580078125, 'epoch': 25.0}
{'train_runtime': 13.0337, 'train_samples_per_second': 19.181, 'train_steps_per_second': 19.181, 'train_loss': 3.28403369140625, 'epoch': 25.0}
{'train_runtime': 12.8607, 'train_samples_per_second': 19.439, 'train_steps_per_second': 19.439, 'train_loss': 3.123818359375, 'epoch': 25.0}

Explanations:  16%|█▋        | 229/1400 [13:14<48:19,  2.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 13.5633, 'train_samples_per_second': 18.432, 'train_steps_per_second': 18.432, 'train_loss': 3.032781982421875, 'epoch': 25.0}
{'train_runtime': 12.9655, 'train_samples_per_second': 19.282, 'train_steps_per_second': 19.282, 'train_loss': 3.0521943359375, 'epoch': 25.0}
{'train_runtime': 12.959, 'train_samples_per_second': 19.292, 'train_steps_per_second': 19.292, 'train_loss': 3.015984130859375, 'epoch': 25.0}
{'train_runtime': 12.9108, 'train_samples_per_second': 19.364, 'train_steps_per_second': 19.364, 'train_loss': 3.0471396484375, 'epoch': 25.0}
{'train_runtime': 12.8673, 'train_samples_per_second': 19.429, 'train_steps_per_second': 19.429, 'train_loss': 3.029686767578125, 'epoch': 25.0}
{'train_runtime': 12.9346, 'train_samples_per_second': 19.328, 'train_steps_per_second': 19.328, 'train_loss': 2.998935546875, 'epoch': 25.0}
{'train_runtime': 12.9863, 'train_samples_per_second': 19.251, 'train_steps_per_second': 19.251, 'train_loss': 3.017025634765625, 'epoch': 25.0}
{'train_runtime': 12.731, 'train_samples_per_second': 19.637, 'train_steps_per_second': 19.637, 'train_loss': 3.03437890625, 'epoch': 25.0}
{'train_runtime': 12.777, 'train_samples_per_second': 19.566, 'train_steps_per_second': 19.566, 'train_loss': 3.03218994140625, 'epoch': 25.0}
{'train_runtime': 12.6899, 'train_samples_per_second': 19.701, 'train_steps_per_second': 19.701, 'train_loss': 3.02519384765625, 'epoch': 25.0}
{'train_runtime': 12.5264, 'train_samples_per_second': 19.958, 'train_steps_per_second': 19.958, 'train_loss': 3.003965576171875, 'epoch': 25.0}
{'train_runtime': 12.2687, 'train_samples_per_second': 20.377, 'train_steps_per_second': 20.377, 'train_loss': 3.052672607421875, 'epoch': 25.0}
{'train_runtime': 12.2926, 'train_samples_per_second': 20.337, 'train_steps_per_second': 20.337, 'train_loss': 3.01477294921875, 'epoch': 25.0}
{'train_runtime': 12.3049, 'train_samples_per_second': 20.317, 'train_steps_per_second': 20.317, 'train_loss': 3.02119775390625, 'epoch': 25.0}
{'train_runtime': 12.2195, 'train_samples_per_second': 20.459, 'train_steps_per_second': 20.459, 'train_loss': 3.04417919921875, 'epoch': 25.0}
{'train_runtime': 12.1821, 'train_samples_per_second': 20.522, 'train_steps_per_second': 20.522, 'train_loss': 3.033444580078125, 'epoch': 25.0}
{'train_runtime': 11.9986, 'train_samples_per_second': 20.836, 'train_steps_per_second': 20.836, 'train_loss': 3.01564208984375, 'epoch': 25.0}
{'train_runtime': 11.9682, 'train_samples_per_second': 20.889, 'train_steps_per_second': 20.889, 'train_loss': 3.0339462890625, 'epoch': 25.0}
{'train_runtime': 11.8855, 'train_samples_per_second': 21.034, 'train_steps_per_second': 21.034, 'train_loss': 3.03273046875, 'epoch': 25.0}
{'train_runtime': 11.8253, 'train_samples_per_second': 21.141, 'train_steps_per_second': 21.141, 'train_loss': 3.0469150390625, 'epoch': 25.0}
{'train_runtime': 11.6363, 'train_samples_per_second': 21.484, 'train_steps_per_second': 21.484, 'train_loss': 3.0102880859375, 'epoch': 25.0}
{'train_runtime': 11.5404, 'train_samples_per_second': 21.663, 'train_steps_per_second': 21.663, 'train_loss': 3.040158203125, 'epoch': 25.0}
{'train_runtime': 11.7255, 'train_samples_per_second': 21.321, 'train_steps_per_second': 21.321, 'train_loss': 3.035857177734375, 'epoch': 25.0}
{'train_runtime': 11.5005, 'train_samples_per_second': 21.738, 'train_steps_per_second': 21.738, 'train_loss': 3.027035400390625, 'epoch': 25.0}
{'train_runtime': 11.454, 'train_samples_per_second': 21.827, 'train_steps_per_second': 21.827, 'train_loss': 3.02979736328125, 'epoch': 25.0}
{'train_runtime': 11.7275, 'train_samples_per_second': 21.318, 'train_steps_per_second': 21.318, 'train_loss': 2.711096923828125, 'epoch': 25.0}
{'train_runtime': 10.5063, 'train_samples_per_second': 23.795, 'train_steps_per_second': 23.795, 'train_loss': 3.30505859375, 'epoch': 25.0}
{'train_runtime': 10.7933, 'train_samples_per_second': 23.163, 'train_steps_per_second': 23.163, 'train_loss': 2.915039306640625, 'epoch': 25.0}
{'train_runtime': 10.771, 'train_samples_per_second': 23.21, 'train_steps_per_second': 23.21, 'train_loss': 3.003546875, 'epoch': 25.0}
{'train_runtime': 12.7876, 'train_samples_per_second': 19.55, 'train_steps_per_second': 19.55, 'train_loss': 3.2794365234375, 'epoch': 25.0}
{'train_runtime': 11.3935, 'train_samples_per_second': 21.942, 'train_steps_per_second': 21.942, 'train_loss': 2.72694775390625, 'epoch': 25.0}
{'train_runtime': 12.2934, 'train_samples_per_second': 20.336, 'train_steps_per_second': 20.336, 'train_loss': 2.985074462890625, 'epoch': 25.0}
{'train_runtime': 10.9885, 'train_samples_per_second': 22.751, 'train_steps_per_second': 22.751, 'train_loss': 2.92256982421875, 'epoch': 25.0}
{'train_runtime': 12.0534, 'train_samples_per_second': 20.741, 'train_steps_per_second': 20.741, 'train_loss': 3.09199169921875, 'epoch': 25.0}
{'train_runtime': 10.5828, 'train_samples_per_second': 23.623, 'train_steps_per_second': 23.623, 'train_loss': 2.931625244140625, 'epoch': 25.0}
{'train_runtime': 10.9521, 'train_samples_per_second': 22.827, 'train_steps_per_second': 22.827, 'train_loss': 3.15222607421875, 'epoch': 25.0}
{'train_runtime': 11.027, 'train_samples_per_second': 22.672, 'train_steps_per_second': 22.672, 'train_loss': 3.20486279296875, 'epoch': 25.0}
{'train_runtime': 9.5546, 'train_samples_per_second': 26.165, 'train_steps_per_second': 26.165, 'train_loss': 3.004735107421875, 'epoch': 25.0}
{'train_runtime': 9.7762, 'train_samples_per_second': 25.572, 'train_steps_per_second': 25.572, 'train_loss': 2.965912109375, 'epoch': 25.0}
{'train_runtime': 10.2996, 'train_samples_per_second': 24.273, 'train_steps_per_second': 24.273, 'train_loss': 3.099876220703125, 'epoch': 25.0}
{'train_runtime': 10.3365, 'train_samples_per_second': 24.186, 'train_steps_per_second': 24.186, 'train_loss': 3.24120458984375, 'epoch': 25.0}
{'train_runtime': 11.9282, 'train_samples_per_second': 20.959, 'train_steps_per_second': 20.959, 'train_loss': 2.888280029296875, 'epoch': 25.0}
{'train_runtime': 10.5029, 'train_samples_per_second': 23.803, 'train_steps_per_second': 23.803, 'train_loss': 2.810474853515625, 'epoch': 25.0}
{'train_runtime': 10.5606, 'train_samples_per_second': 23.673, 'train_steps_per_second': 23.673, 'train_loss': 3.333574462890625, 'epoch': 25.0}
{'train_runtime': 11.0066, 'train_samples_per_second': 22.714, 'train_steps_per_second': 22.714, 'train_loss': 3.016797607421875, 'epoch': 25.0}
{'train_runtime': 10.3091, 'train_samples_per_second': 24.25, 'train_steps_per_second': 24.25, 'train_loss': 3.227860595703125, 'epoch': 25.0}
{'train_runtime': 11.0806, 'train_samples_per_second': 22.562, 'train_steps_per_second': 22.562, 'train_loss': 3.088171142578125, 'epoch': 25.0}
{'train_runtime': 11.1995, 'train_samples_per_second': 22.323, 'train_steps_per_second': 22.323, 'train_loss': 3.03285498046875, 'epoch': 25.0}
{'train_runtime': 11.7648, 'train_samples_per_second': 21.25, 'train_steps_per_second': 21.25, 'train_loss': 3.01940087890625, 'epoch': 25.0}
{'train_runtime': 11.5101, 'train_samples_per_second': 21.72, 'train_steps_per_second': 21.72, 'train_loss': 2.96892431640625, 'epoch': 25.0}
{'train_runtime': 13.5726, 'train_samples_per_second': 18.419, 'train_steps_per_second': 18.419, 'train_loss': 3.1307412109375, 'epoch': 25.0}
{'train_runtime': 12.7169, 'train_samples_per_second': 19.659, 'train_steps_per_second': 19.659, 'train_loss': 3.278748291015625, 'epoch': 25.0}
{'train_runtime': 12.9285, 'train_samples_per_second': 19.337, 'train_steps_per_second': 19.337, 'train_loss': 3.250558349609375, 'epoch': 25.0}
{'train_runtime': 12.0726, 'train_samples_per_second': 20.708, 'train_steps_per_second': 20.708, 'train_loss': 3.414798583984375, 'epoch': 25.0}
{'train_runtime': 12.9835, 'train_samples_per_second': 19.255, 'train_steps_per_second': 19.255, 'train_loss': 3.29440087890625, 'epoch': 25.0}
{'train_runtime': 13.1361, 'train_samples_per_second': 19.032, 'train_steps_per_second': 19.032, 'train_loss': 3.433554443359375, 'epoch': 25.0}
{'train_runtime': 13.2522, 'train_samples_per_second': 18.865, 'train_steps_per_second': 18.865, 'train_loss': 3.317781494140625, 'epoch': 25.0}

Explanations:  16%|█▋        | 231/1400 [13:27<1:16:03,  3.90s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 233/1400 [13:29<47:03,  2.42s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 235/1400 [13:42<1:16:28,  3.94s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 237/1400 [13:44<44:17,  2.28s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 239/1400 [13:58<1:19:44,  4.12s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 240/1400 [13:59<1:04:58,  3.36s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 242/1400 [14:11<1:28:24,  4.58s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 243/1400 [14:13<1:14:14,  3.85s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 245/1400 [14:15<47:03,  2.44s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 246/1400 [14:26<1:33:54,  4.88s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 247/1400 [14:28<1:18:41,  4.10s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 249/1400 [14:31<49:36,  2.59s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 250/1400 [14:40<1:29:05,  4.65s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 251/1400 [14:43<1:19:15,  4.14s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 253/1400 [14:46<50:02,  2.62s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 254/1400 [14:54<1:21:13,  4.25s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 255/1400 [14:57<1:18:00,  4.09s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 257/1400 [15:01<53:08,  2.79s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 258/1400 [15:08<1:20:15,  4.22s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 259/1400 [15:12<1:15:33,  3.97s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▊        | 261/1400 [15:15<51:38,  2.72s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▊        | 262/1400 [15:21<1:11:59,  3.80s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 263/1400 [15:26<1:16:25,  4.03s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 265/1400 [15:30<54:03,  2.86s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 266/1400 [15:36<1:11:17,  3.77s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 267/1400 [15:41<1:18:49,  4.17s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 268/1400 [15:44<1:11:56,  3.81s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 269/1400 [15:45<56:32,  3.00s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 270/1400 [15:51<1:12:21,  3.84s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 271/1400 [15:55<1:13:36,  3.91s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 273/1400 [15:59<53:39,  2.86s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 274/1400 [16:05<1:09:33,  3.71s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 275/1400 [16:09<1:15:45,  4.04s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 277/1400 [16:13<54:48,  2.93s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 278/1400 [16:19<1:07:23,  3.60s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 279/1400 [16:24<1:17:28,  4.15s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 280/1400 [16:26<1:06:30,  3.56s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 281/1400 [16:28<56:34,  3.03s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 282/1400 [16:33<1:07:18,  3.61s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 283/1400 [16:38<1:15:56,  4.08s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 284/1400 [16:40<1:05:55,  3.54s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 285/1400 [16:42<55:14,  2.97s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 286/1400 [16:48<1:08:48,  3.71s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 287/1400 [16:52<1:15:26,  4.07s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 288/1400 [16:55<1:09:16,  3.74s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 289/1400 [16:57<58:15,  3.15s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 290/1400 [17:02<1:09:20,  3.75s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 291/1400 [17:07<1:13:45,  3.99s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 292/1400 [17:10<1:09:01,  3.74s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 293/1400 [17:12<59:35,  3.23s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 13.311, 'train_samples_per_second': 18.782, 'train_steps_per_second': 18.782, 'train_loss': 3.388469482421875, 'epoch': 25.0}
{'train_runtime': 11.7389, 'train_samples_per_second': 21.297, 'train_steps_per_second': 21.297, 'train_loss': 3.00156103515625, 'epoch': 25.0}
{'train_runtime': 13.5357, 'train_samples_per_second': 18.47, 'train_steps_per_second': 18.47, 'train_loss': 3.010239990234375, 'epoch': 25.0}
{'train_runtime': 12.4087, 'train_samples_per_second': 20.147, 'train_steps_per_second': 20.147, 'train_loss': 3.359627685546875, 'epoch': 25.0}
{'train_runtime': 13.5363, 'train_samples_per_second': 18.469, 'train_steps_per_second': 18.469, 'train_loss': 3.0533896484375, 'epoch': 25.0}
{'train_runtime': 13.4046, 'train_samples_per_second': 18.65, 'train_steps_per_second': 18.65, 'train_loss': 3.206902587890625, 'epoch': 25.0}
{'train_runtime': 13.5376, 'train_samples_per_second': 18.467, 'train_steps_per_second': 18.467, 'train_loss': 3.155923095703125, 'epoch': 25.0}
{'train_runtime': 12.8548, 'train_samples_per_second': 19.448, 'train_steps_per_second': 19.448, 'train_loss': 3.14401416015625, 'epoch': 25.0}
{'train_runtime': 13.1115, 'train_samples_per_second': 19.067, 'train_steps_per_second': 19.067, 'train_loss': 2.997081787109375, 'epoch': 25.0}
{'train_runtime': 12.2921, 'train_samples_per_second': 20.338, 'train_steps_per_second': 20.338, 'train_loss': 3.221596435546875, 'epoch': 25.0}
{'train_runtime': 12.8275, 'train_samples_per_second': 19.489, 'train_steps_per_second': 19.489, 'train_loss': 3.1822783203125, 'epoch': 25.0}
{'train_runtime': 12.9354, 'train_samples_per_second': 19.327, 'train_steps_per_second': 19.327, 'train_loss': 3.064299560546875, 'epoch': 25.0}
{'train_runtime': 11.886, 'train_samples_per_second': 21.033, 'train_steps_per_second': 21.033, 'train_loss': 3.29974462890625, 'epoch': 25.0}
{'train_runtime': 12.3551, 'train_samples_per_second': 20.234, 'train_steps_per_second': 20.234, 'train_loss': 3.2593857421875, 'epoch': 25.0}
{'train_runtime': 12.5665, 'train_samples_per_second': 19.894, 'train_steps_per_second': 19.894, 'train_loss': 3.17640966796875, 'epoch': 25.0}
{'train_runtime': 11.9837, 'train_samples_per_second': 20.862, 'train_steps_per_second': 20.862, 'train_loss': 3.191398193359375, 'epoch': 25.0}
{'train_runtime': 12.8211, 'train_samples_per_second': 19.499, 'train_steps_per_second': 19.499, 'train_loss': 3.1489296875, 'epoch': 25.0}
{'train_runtime': 12.8278, 'train_samples_per_second': 19.489, 'train_steps_per_second': 19.489, 'train_loss': 3.117699951171875, 'epoch': 25.0}
{'train_runtime': 12.3411, 'train_samples_per_second': 20.257, 'train_steps_per_second': 20.257, 'train_loss': 3.352024169921875, 'epoch': 25.0}
{'train_runtime': 11.8126, 'train_samples_per_second': 21.164, 'train_steps_per_second': 21.164, 'train_loss': 3.15256396484375, 'epoch': 25.0}
{'train_runtime': 11.0329, 'train_samples_per_second': 22.66, 'train_steps_per_second': 22.66, 'train_loss': 2.877028564453125, 'epoch': 25.0}
{'train_runtime': 9.379, 'train_samples_per_second': 26.655, 'train_steps_per_second': 26.655, 'train_loss': 3.10178662109375, 'epoch': 25.0}
{'train_runtime': 11.5516, 'train_samples_per_second': 21.642, 'train_steps_per_second': 21.642, 'train_loss': 3.364337890625, 'epoch': 25.0}
{'train_runtime': 11.7287, 'train_samples_per_second': 21.315, 'train_steps_per_second': 21.315, 'train_loss': 3.05343505859375, 'epoch': 25.0}
{'train_runtime': 12.4023, 'train_samples_per_second': 20.158, 'train_steps_per_second': 20.158, 'train_loss': 3.210649169921875, 'epoch': 25.0}
{'train_runtime': 10.7468, 'train_samples_per_second': 23.263, 'train_steps_per_second': 23.263, 'train_loss': 3.0855615234375, 'epoch': 25.0}
{'train_runtime': 10.5871, 'train_samples_per_second': 23.614, 'train_steps_per_second': 23.614, 'train_loss': 2.89165576171875, 'epoch': 25.0}
{'train_runtime': 10.3305, 'train_samples_per_second': 24.2, 'train_steps_per_second': 24.2, 'train_loss': 3.034866455078125, 'epoch': 25.0}
{'train_runtime': 11.2769, 'train_samples_per_second': 22.169, 'train_steps_per_second': 22.169, 'train_loss': 3.230246826171875, 'epoch': 25.0}
{'train_runtime': 10.4168, 'train_samples_per_second': 24.0, 'train_steps_per_second': 24.0, 'train_loss': 3.015144287109375, 'epoch': 25.0}
{'train_runtime': 9.7599, 'train_samples_per_second': 25.615, 'train_steps_per_second': 25.615, 'train_loss': 2.926182861328125, 'epoch': 25.0}
{'train_runtime': 9.7401, 'train_samples_per_second': 25.667, 'train_steps_per_second': 25.667, 'train_loss': 2.91835107421875, 'epoch': 25.0}
{'train_runtime': 9.6986, 'train_samples_per_second': 25.777, 'train_steps_per_second': 25.777, 'train_loss': 3.0833310546875, 'epoch': 25.0}
{'train_runtime': 9.7023, 'train_samples_per_second': 25.767, 'train_steps_per_second': 25.767, 'train_loss': 3.040212646484375, 'epoch': 25.0}
{'train_runtime': 9.2012, 'train_samples_per_second': 27.17, 'train_steps_per_second': 27.17, 'train_loss': 3.137810302734375, 'epoch': 25.0}
{'train_runtime': 9.3712, 'train_samples_per_second': 26.678, 'train_steps_per_second': 26.678, 'train_loss': 3.04197119140625, 'epoch': 25.0}
{'train_runtime': 10.9678, 'train_samples_per_second': 22.794, 'train_steps_per_second': 22.794, 'train_loss': 2.931040283203125, 'epoch': 25.0}
{'train_runtime': 11.0106, 'train_samples_per_second': 22.705, 'train_steps_per_second': 22.705, 'train_loss': 3.18653759765625, 'epoch': 25.0}
{'train_runtime': 9.7228, 'train_samples_per_second': 25.713, 'train_steps_per_second': 25.713, 'train_loss': 3.09507568359375, 'epoch': 25.0}
{'train_runtime': 10.4825, 'train_samples_per_second': 23.849, 'train_steps_per_second': 23.849, 'train_loss': 2.92818798828125, 'epoch': 25.0}
{'train_runtime': 9.9946, 'train_samples_per_second': 25.014, 'train_steps_per_second': 25.014, 'train_loss': 3.13354638671875, 'epoch': 25.0}
{'train_runtime': 11.3159, 'train_samples_per_second': 22.093, 'train_steps_per_second': 22.093, 'train_loss': 2.978269775390625, 'epoch': 25.0}
{'train_runtime': 11.0832, 'train_samples_per_second': 22.557, 'train_steps_per_second': 22.557, 'train_loss': 2.801150146484375, 'epoch': 25.0}
{'train_runtime': 10.5297, 'train_samples_per_second': 23.742, 'train_steps_per_second': 23.742, 'train_loss': 3.1935810546875, 'epoch': 25.0}
{'train_runtime': 10.879, 'train_samples_per_second': 22.98, 'train_steps_per_second': 22.98, 'train_loss': 2.93494921875, 'epoch': 25.0}
{'train_runtime': 12.6946, 'train_samples_per_second': 19.693, 'train_steps_per_second': 19.693, 'train_loss': 3.19905419921875, 'epoch': 25.0}
{'train_runtime': 12.2267, 'train_samples_per_second': 20.447, 'train_steps_per_second': 20.447, 'train_loss': 2.771448974609375, 'epoch': 25.0}
{'train_runtime': 12.4978, 'train_samples_per_second': 20.004, 'train_steps_per_second': 20.004, 'train_loss': 3.26787646484375, 'epoch': 25.0}
{'train_runtime': 13.9573, 'train_samples_per_second': 17.912, 'train_steps_per_second': 17.912, 'train_loss': 3.1749365234375, 'epoch': 25.0}
{'train_runtime': 12.9369, 'train_samples_per_second': 19.325, 'train_steps_per_second': 19.325, 'train_loss': 2.829227783203125, 'epoch': 25.0}
{'train_runtime': 12.3325, 'train_samples_per_second': 20.272, 'train_steps_per_second': 20.272, 'train_loss': 3.05293505859375, 'epoch': 25.0}
{'train_runtime': 13.8233, 'train_samples_per_second': 18.085, 'train_steps_per_second': 18.085, 'train_loss': 3.05403271484375, 'epoch': 25.0}
{'train_runtime': 13.0144, 'train_samples_per_second': 19.209, 'train_steps_per_second': 19.209, 'train_loss': 2.990968994140625, 'epoch': 25.0}
{'train_runtime': 13.8836, 'train_samples_per_second': 18.007, 'train_steps_per_second': 18.007, 'train_loss': 3.000809814453125, 'epoch': 25.0}
{'train_runtime': 13.1057, 'train_samples_per_second': 19.076, 'train_steps_per_second': 19.076, 'train_loss': 2.86609326171875, 'epoch': 25.0}
{'train_runtime': 12.7444, 'train_samples_per_second': 19.616, 'train_steps_per_second': 19.616, 'train_loss': 2.911874755859375, 'epoch': 25.0}
{'train_runtime': 12.201, 'train_samples_per_second': 20.49, 'train_steps_per_second': 20.49, 'train_loss': 2.8670341796875, 'epoch': 25.0}

Explanations:  32%|███▏      | 452/1400 [26:12<58:27,  3.70s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  32%|███▏      | 453/1400 [26:15<57:43,  3.66s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 12.9343, 'train_samples_per_second': 19.328, 'train_steps_per_second': 19.328, 'train_loss': 3.212118896484375, 'epoch': 25.0}
{'train_runtime': 13.0598, 'train_samples_per_second': 19.143, 'train_steps_per_second': 19.143, 'train_loss': 3.4403095703125, 'epoch': 25.0}
{'train_runtime': 13.0809, 'train_samples_per_second': 19.112, 'train_steps_per_second': 19.112, 'train_loss': 3.321168212890625, 'epoch': 25.0}
{'train_runtime': 13.591, 'train_samples_per_second': 18.394, 'train_steps_per_second': 18.394, 'train_loss': 3.38496142578125, 'epoch': 25.0}
{'train_runtime': 13.0702, 'train_samples_per_second': 19.127, 'train_steps_per_second': 19.127, 'train_loss': 3.30201806640625, 'epoch': 25.0}
{'train_runtime': 13.1759, 'train_samples_per_second': 18.974, 'train_steps_per_second': 18.974, 'train_loss': 2.851581787109375, 'epoch': 25.0}
{'train_runtime': 12.7369, 'train_samples_per_second': 19.628, 'train_steps_per_second': 19.628, 'train_loss': 3.20664111328125, 'epoch': 25.0}
{'train_runtime': 12.1999, 'train_samples_per_second': 20.492, 'train_steps_per_second': 20.492, 'train_loss': 2.974552001953125, 'epoch': 25.0}
{'train_runtime': 12.1771, 'train_samples_per_second': 20.53, 'train_steps_per_second': 20.53, 'train_loss': 3.306847900390625, 'epoch': 25.0}
{'train_runtime': 12.1467, 'train_samples_per_second': 20.582, 'train_steps_per_second': 20.582, 'train_loss': 3.35812353515625, 'epoch': 25.0}
{'train_runtime': 12.823, 'train_samples_per_second': 19.496, 'train_steps_per_second': 19.496, 'train_loss': 3.284988037109375, 'epoch': 25.0}
{'train_runtime': 11.8988, 'train_samples_per_second': 21.011, 'train_steps_per_second': 21.011, 'train_loss': 3.2260595703125, 'epoch': 25.0}
{'train_runtime': 12.5471, 'train_samples_per_second': 19.925, 'train_steps_per_second': 19.925, 'train_loss': 3.208402587890625, 'epoch': 25.0}
{'train_runtime': 12.3528, 'train_samples_per_second': 20.238, 'train_steps_per_second': 20.238, 'train_loss': 3.1580283203125, 'epoch': 25.0}
{'train_runtime': 12.0348, 'train_samples_per_second': 20.773, 'train_steps_per_second': 20.773, 'train_loss': 2.799380126953125, 'epoch': 25.0}
{'train_runtime': 12.2175, 'train_samples_per_second': 20.462, 'train_steps_per_second': 20.462, 'train_loss': 3.39122900390625, 'epoch': 25.0}
{'train_runtime': 12.3194, 'train_samples_per_second': 20.293, 'train_steps_per_second': 20.293, 'train_loss': 3.434891845703125, 'epoch': 25.0}
{'train_runtime': 12.6946, 'train_samples_per_second': 19.693, 'train_steps_per_second': 19.693, 'train_loss': 3.265440673828125, 'epoch': 25.0}
{'train_runtime': 11.7626, 'train_samples_per_second': 21.254, 'train_steps_per_second': 21.254, 'train_loss': 2.8988125, 'epoch': 25.0}
{'train_runtime': 12.2922, 'train_samples_per_second': 20.338, 'train_steps_per_second': 20.338, 'train_loss': 3.19590234375, 'epoch': 25.0}
{'train_runtime': 9.584, 'train_samples_per_second': 26.085, 'train_steps_per_second': 26.085, 'train_loss': 3.162443603515625, 'epoch': 25.0}
{'train_runtime': 10.198, 'train_samples_per_second': 24.515, 'train_steps_per_second': 24.515, 'train_loss': 2.916633056640625, 'epoch': 25.0}
{'train_runtime': 9.7102, 'train_samples_per_second': 25.746, 'train_steps_per_second': 25.746, 'train_loss': 3.283578369140625, 'epoch': 25.0}
{'train_runtime': 13.2449, 'train_samples_per_second': 18.875, 'train_steps_per_second': 18.875, 'train_loss': 2.885078125, 'epoch': 25.0}
{'train_runtime': 10.4091, 'train_samples_per_second': 24.018, 'train_steps_per_second': 24.018, 'train_loss': 3.10150537109375, 'epoch': 25.0}
{'train_runtime': 9.744, 'train_samples_per_second': 25.657, 'train_steps_per_second': 25.657, 'train_loss': 3.035760986328125, 'epoch': 25.0}
{'train_runtime': 11.4722, 'train_samples_per_second': 21.792, 'train_steps_per_second': 21.792, 'train_loss': 2.955402587890625, 'epoch': 25.0}
{'train_runtime': 10.6762, 'train_samples_per_second': 23.417, 'train_steps_per_second': 23.417, 'train_loss': 2.9312021484375, 'epoch': 25.0}
{'train_runtime': 10.9798, 'train_samples_per_second': 22.769, 'train_steps_per_second': 22.769, 'train_loss': 2.846658447265625, 'epoch': 25.0}
{'train_runtime': 10.2655, 'train_samples_per_second': 24.353, 'train_steps_per_second': 24.353, 'train_loss': 2.912725830078125, 'epoch': 25.0}
{'train_runtime': 10.4622, 'train_samples_per_second': 23.896, 'train_steps_per_second': 23.896, 'train_loss': 2.7959609375, 'epoch': 25.0}
{'train_runtime': 9.0207, 'train_samples_per_second': 27.714, 'train_steps_per_second': 27.714, 'train_loss': 2.972385986328125, 'epoch': 25.0}
{'train_runtime': 9.4212, 'train_samples_per_second': 26.536, 'train_steps_per_second': 26.536, 'train_loss': 2.848491943359375, 'epoch': 25.0}
{'train_runtime': 10.2852, 'train_samples_per_second': 24.307, 'train_steps_per_second': 24.307, 'train_loss': 3.168556884765625, 'epoch': 25.0}
{'train_runtime': 9.4507, 'train_samples_per_second': 26.453, 'train_steps_per_second': 26.453, 'train_loss': 3.32424853515625, 'epoch': 25.0}
{'train_runtime': 11.2924, 'train_samples_per_second': 22.139, 'train_steps_per_second': 22.139, 'train_loss': 3.301796875, 'epoch': 25.0}
{'train_runtime': 10.1225, 'train_samples_per_second': 24.697, 'train_steps_per_second': 24.697, 'train_loss': 2.807475341796875, 'epoch': 25.0}
{'train_runtime': 10.1042, 'train_samples_per_second': 24.742, 'train_steps_per_second': 24.742, 'train_loss': 3.343112548828125, 'epoch': 25.0}
{'train_runtime': 10.5887, 'train_samples_per_second': 23.61, 'train_steps_per_second': 23.61, 'train_loss': 2.99907763671875, 'epoch': 25.0}
{'train_runtime': 10.3521, 'train_samples_per_second': 24.15, 'train_steps_per_second': 24.15, 'train_loss': 3.20634375, 'epoch': 25.0}
{'train_runtime': 10.5779, 'train_samples_per_second': 23.634, 'train_steps_per_second': 23.634, 'train_loss': 3.20656298828125, 'epoch': 25.0}
{'train_runtime': 10.8727, 'train_samples_per_second': 22.993, 'train_steps_per_second': 22.993, 'train_loss': 2.99922900390625, 'epoch': 25.0}
{'train_runtime': 11.5265, 'train_samples_per_second': 21.689, 'train_steps_per_second': 21.689, 'train_loss': 3.073127197265625, 'epoch': 25.0}
{'train_runtime': 11.1064, 'train_samples_per_second': 22.509, 'train_steps_per_second': 22.509, 'train_loss': 3.18763134765625, 'epoch': 25.0}
{'train_runtime': 12.6153, 'train_samples_per_second': 19.817, 'train_steps_per_second': 19.817, 'train_loss': 2.9872197265625, 'epoch': 25.0}
{'train_runtime': 12.2347, 'train_samples_per_second': 20.434, 'train_steps_per_second': 20.434, 'train_loss': 2.957058349609375, 'epoch': 25.0}
{'train_runtime': 11.2022, 'train_samples_per_second': 22.317, 'train_steps_per_second': 22.317, 'train_loss': 3.538643310546875, 'epoch': 25.0}
{'train_runtime': 13.6047, 'train_samples_per_second': 18.376, 'train_steps_per_second': 18.376, 'train_loss': 3.007006591796875, 'epoch': 25.0}
{'train_runtime': 13.0175, 'train_samples_per_second': 19.205, 'train_steps_per_second': 19.205, 'train_loss': 2.934002685546875, 'epoch': 25.0}
{'train_runtime': 11.7822, 'train_samples_per_second': 21.218, 'train_steps_per_second': 21.218, 'train_loss': 2.85939111328125, 'epoch': 25.0}
{'train_runtime': 13.8089, 'train_samples_per_second': 18.104, 'train_steps_per_second': 18.104, 'train_loss': 3.078480224609375, 'epoch': 25.0}
{'train_runtime': 12.8264, 'train_samples_per_second': 19.491, 'train_steps_per_second': 19.491, 'train_loss': 3.054335693359375, 'epoch': 25.0}
{'train_runtime': 13.4764, 'train_samples_per_second': 18.551, 'train_steps_per_second': 18.551, 'train_loss': 3.22855859375, 'epoch': 25.0}
{'train_runtime': 12.7423, 'train_samples_per_second': 19.62, 'train_steps_per_second': 19.62, 'train_loss': 2.8945771484375, 'epoch': 25.0}
{'train_runtime': 11.6042, 'train_samples_per_second': 21.544, 'train_steps_per_second': 21.544, 'train_loss': 3.101813720703125, 'epoch': 25.0}
{'train_runtime': 13.1362, 'train_samples_per_second': 19.031, 'train_steps_per_second': 19.031, 'train_loss': 2.997818359375, 'epoch': 25.0}
{'train_runtime': 14.8908, 'train_samples_per_second': 16.789, 'train_steps_per_second': 16.789, 'train_loss': 3.055200927734375, 'epoch': 25.0}

Explanations:  32%|███▏      | 454/1400 [26:23<1:17:45,  4.93s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 13.526, 'train_samples_per_second': 18.483, 'train_steps_per_second': 18.483, 'train_loss': 3.418825439453125, 'epoch': 25.0}
{'train_runtime': 12.7715, 'train_samples_per_second': 19.575, 'train_steps_per_second': 19.575, 'train_loss': 3.168702392578125, 'epoch': 25.0}
{'train_runtime': 13.3283, 'train_samples_per_second': 18.757, 'train_steps_per_second': 18.757, 'train_loss': 3.0058935546875, 'epoch': 25.0}
{'train_runtime': 12.3749, 'train_samples_per_second': 20.202, 'train_steps_per_second': 20.202, 'train_loss': 3.414723388671875, 'epoch': 25.0}
{'train_runtime': 12.6451, 'train_samples_per_second': 19.77, 'train_steps_per_second': 19.77, 'train_loss': 3.328878173828125, 'epoch': 25.0}
{'train_runtime': 12.0514, 'train_samples_per_second': 20.744, 'train_steps_per_second': 20.744, 'train_loss': 3.284475830078125, 'epoch': 25.0}
{'train_runtime': 11.4872, 'train_samples_per_second': 21.763, 'train_steps_per_second': 21.763, 'train_loss': 3.23043115234375, 'epoch': 25.0}
{'train_runtime': 12.6353, 'train_samples_per_second': 19.786, 'train_steps_per_second': 19.786, 'train_loss': 3.0062548828125, 'epoch': 25.0}
{'train_runtime': 10.9513, 'train_samples_per_second': 22.828, 'train_steps_per_second': 22.828, 'train_loss': 3.090421142578125, 'epoch': 25.0}
{'train_runtime': 12.4414, 'train_samples_per_second': 20.094, 'train_steps_per_second': 20.094, 'train_loss': 3.22846044921875, 'epoch': 25.0}
{'train_runtime': 12.952, 'train_samples_per_second': 19.302, 'train_steps_per_second': 19.302, 'train_loss': 3.258091552734375, 'epoch': 25.0}
{'train_runtime': 11.7456, 'train_samples_per_second': 21.285, 'train_steps_per_second': 21.285, 'train_loss': 3.32933056640625, 'epoch': 25.0}
{'train_runtime': 11.9734, 'train_samples_per_second': 20.88, 'train_steps_per_second': 20.88, 'train_loss': 2.896039794921875, 'epoch': 25.0}
{'train_runtime': 12.2563, 'train_samples_per_second': 20.398, 'train_steps_per_second': 20.398, 'train_loss': 3.033676513671875, 'epoch': 25.0}
{'train_runtime': 12.4897, 'train_samples_per_second': 20.016, 'train_steps_per_second': 20.016, 'train_loss': 3.00269873046875, 'epoch': 25.0}
{'train_runtime': 12.6852, 'train_samples_per_second': 19.708, 'train_steps_per_second': 19.708, 'train_loss': 3.199505859375, 'epoch': 25.0}
{'train_runtime': 12.1919, 'train_samples_per_second': 20.505, 'train_steps_per_second': 20.505, 'train_loss': 3.03017041015625, 'epoch': 25.0}
{'train_runtime': 12.9617, 'train_samples_per_second': 19.288, 'train_steps_per_second': 19.288, 'train_loss': 3.21200244140625, 'epoch': 25.0}
{'train_runtime': 11.93, 'train_samples_per_second': 20.956, 'train_steps_per_second': 20.956, 'train_loss': 2.709614013671875, 'epoch': 25.0}
{'train_runtime': 11.0193, 'train_samples_per_second': 22.687, 'train_steps_per_second': 22.687, 'train_loss': 3.342675048828125, 'epoch': 25.0}
{'train_runtime': 10.9687, 'train_samples_per_second': 22.792, 'train_steps_per_second': 22.792, 'train_loss': 2.9071005859375, 'epoch': 25.0}
{'train_runtime': 9.9237, 'train_samples_per_second': 25.192, 'train_steps_per_second': 25.192, 'train_loss': 3.126452392578125, 'epoch': 25.0}
{'train_runtime': 12.2668, 'train_samples_per_second': 20.38, 'train_steps_per_second': 20.38, 'train_loss': 3.329968994140625, 'epoch': 25.0}
{'train_runtime': 11.7949, 'train_samples_per_second': 21.196, 'train_steps_per_second': 21.196, 'train_loss': 2.6711552734375, 'epoch': 25.0}
{'train_runtime': 9.9541, 'train_samples_per_second': 25.115, 'train_steps_per_second': 25.115, 'train_loss': 3.00172265625, 'epoch': 25.0}
{'train_runtime': 11.6338, 'train_samples_per_second': 21.489, 'train_steps_per_second': 21.489, 'train_loss': 3.169529052734375, 'epoch': 25.0}
{'train_runtime': 11.8778, 'train_samples_per_second': 21.048, 'train_steps_per_second': 21.048, 'train_loss': 3.10570654296875, 'epoch': 25.0}
{'train_runtime': 10.7313, 'train_samples_per_second': 23.296, 'train_steps_per_second': 23.296, 'train_loss': 2.931036376953125, 'epoch': 25.0}
{'train_runtime': 11.3894, 'train_samples_per_second': 21.95, 'train_steps_per_second': 21.95, 'train_loss': 3.129314208984375, 'epoch': 25.0}
{'train_runtime': 10.4763, 'train_samples_per_second': 23.863, 'train_steps_per_second': 23.863, 'train_loss': 3.217464111328125, 'epoch': 25.0}
{'train_runtime': 9.0995, 'train_samples_per_second': 27.474, 'train_steps_per_second': 27.474, 'train_loss': 3.01499462890625, 'epoch': 25.0}
{'train_runtime': 9.8483, 'train_samples_per_second': 25.385, 'train_steps_per_second': 25.385, 'train_loss': 3.04021826171875, 'epoch': 25.0}
{'train_runtime': 10.1654, 'train_samples_per_second': 24.593, 'train_steps_per_second': 24.593, 'train_loss': 3.068880126953125, 'epoch': 25.0}
{'train_runtime': 10.3288, 'train_samples_per_second': 24.204, 'train_steps_per_second': 24.204, 'train_loss': 3.2946533203125, 'epoch': 25.0}
{'train_runtime': 12.6159, 'train_samples_per_second': 19.816, 'train_steps_per_second': 19.816, 'train_loss': 3.083989013671875, 'epoch': 25.0}
{'train_runtime': 9.9218, 'train_samples_per_second': 25.197, 'train_steps_per_second': 25.197, 'train_loss': 2.934848876953125, 'epoch': 25.0}
{'train_runtime': 9.9509, 'train_samples_per_second': 25.123, 'train_steps_per_second': 25.123, 'train_loss': 2.955454345703125, 'epoch': 25.0}
{'train_runtime': 10.6294, 'train_samples_per_second': 23.52, 'train_steps_per_second': 23.52, 'train_loss': 2.871542724609375, 'epoch': 25.0}
{'train_runtime': 10.1539, 'train_samples_per_second': 24.621, 'train_steps_per_second': 24.621, 'train_loss': 3.142713623046875, 'epoch': 25.0}
{'train_runtime': 11.2169, 'train_samples_per_second': 22.288, 'train_steps_per_second': 22.288, 'train_loss': 2.7742431640625, 'epoch': 25.0}
{'train_runtime': 10.1355, 'train_samples_per_second': 24.666, 'train_steps_per_second': 24.666, 'train_loss': 3.136154052734375, 'epoch': 25.0}
{'train_runtime': 11.408, 'train_samples_per_second': 21.915, 'train_steps_per_second': 21.915, 'train_loss': 3.14847265625, 'epoch': 25.0}
{'train_runtime': 11.4467, 'train_samples_per_second': 21.84, 'train_steps_per_second': 21.84, 'train_loss': 2.99748095703125, 'epoch': 25.0}
{'train_runtime': 12.9757, 'train_samples_per_second': 19.267, 'train_steps_per_second': 19.267, 'train_loss': 3.142851806640625, 'epoch': 25.0}
{'train_runtime': 12.6984, 'train_samples_per_second': 19.687, 'train_steps_per_second': 19.687, 'train_loss': 2.818773193359375, 'epoch': 25.0}
{'train_runtime': 12.3794, 'train_samples_per_second': 20.195, 'train_steps_per_second': 20.195, 'train_loss': 3.11381298828125, 'epoch': 25.0}
{'train_runtime': 14.3896, 'train_samples_per_second': 17.374, 'train_steps_per_second': 17.374, 'train_loss': 3.166384033203125, 'epoch': 25.0}
{'train_runtime': 12.9892, 'train_samples_per_second': 19.247, 'train_steps_per_second': 19.247, 'train_loss': 3.394678466796875, 'epoch': 25.0}
{'train_runtime': 12.7279, 'train_samples_per_second': 19.642, 'train_steps_per_second': 19.642, 'train_loss': 3.158205078125, 'epoch': 25.0}
{'train_runtime': 14.966, 'train_samples_per_second': 16.704, 'train_steps_per_second': 16.704, 'train_loss': 3.653795166015625, 'epoch': 25.0}
{'train_runtime': 11.8499, 'train_samples_per_second': 21.097, 'train_steps_per_second': 21.097, 'train_loss': 2.993378662109375, 'epoch': 25.0}
{'train_runtime': 13.4026, 'train_samples_per_second': 18.653, 'train_steps_per_second': 18.653, 'train_loss': 3.112853515625, 'epoch': 25.0}
{'train_runtime': 12.3402, 'train_samples_per_second': 20.259, 'train_steps_per_second': 20.259, 'train_loss': 3.3096416015625, 'epoch': 25.0}
{'train_runtime': 12.1696, 'train_samples_per_second': 20.543, 'train_steps_per_second': 20.543, 'train_loss': 3.087990478515625, 'epoch': 25.0}
{'train_runtime': 12.5963, 'train_samples_per_second': 19.847, 'train_steps_per_second': 19.847, 'train_loss': 3.00932763671875, 'epoch': 25.0}
{'train_runtime': 14.9135, 'train_samples_per_second': 16.763, 'train_steps_per_second': 16.763, 'train_loss': 3.087804443359375, 'epoch': 25.0}

Explanations:  32%|███▎      | 455/1400 [26:25<1:05:29,  4.16s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 456/1400 [26:27<55:39,  3.54s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 12.4274, 'train_samples_per_second': 20.117, 'train_steps_per_second': 20.117, 'train_loss': 3.1504697265625, 'epoch': 25.0}
{'train_runtime': 12.8167, 'train_samples_per_second': 19.506, 'train_steps_per_second': 19.506, 'train_loss': 3.424916015625, 'epoch': 25.0}
{'train_runtime': 12.4902, 'train_samples_per_second': 20.016, 'train_steps_per_second': 20.016, 'train_loss': 3.00821240234375, 'epoch': 25.0}
{'train_runtime': 13.4992, 'train_samples_per_second': 18.52, 'train_steps_per_second': 18.52, 'train_loss': 3.132798828125, 'epoch': 25.0}
{'train_runtime': 13.4252, 'train_samples_per_second': 18.622, 'train_steps_per_second': 18.622, 'train_loss': 3.410478515625, 'epoch': 25.0}
{'train_runtime': 13.1073, 'train_samples_per_second': 19.073, 'train_steps_per_second': 19.073, 'train_loss': 3.2057998046875, 'epoch': 25.0}
{'train_runtime': 12.7457, 'train_samples_per_second': 19.614, 'train_steps_per_second': 19.614, 'train_loss': 3.16470556640625, 'epoch': 25.0}
{'train_runtime': 13.0242, 'train_samples_per_second': 19.195, 'train_steps_per_second': 19.195, 'train_loss': 3.184921875, 'epoch': 25.0}
{'train_runtime': 12.3763, 'train_samples_per_second': 20.2, 'train_steps_per_second': 20.2, 'train_loss': 3.26136767578125, 'epoch': 25.0}
{'train_runtime': 13.114, 'train_samples_per_second': 19.064, 'train_steps_per_second': 19.064, 'train_loss': 3.1680087890625, 'epoch': 25.0}
{'train_runtime': 12.6797, 'train_samples_per_second': 19.717, 'train_steps_per_second': 19.717, 'train_loss': 3.089036865234375, 'epoch': 25.0}
{'train_runtime': 12.2437, 'train_samples_per_second': 20.419, 'train_steps_per_second': 20.419, 'train_loss': 3.0474990234375, 'epoch': 25.0}
{'train_runtime': 12.5937, 'train_samples_per_second': 19.851, 'train_steps_per_second': 19.851, 'train_loss': 2.941335205078125, 'epoch': 25.0}
{'train_runtime': 11.7013, 'train_samples_per_second': 21.365, 'train_steps_per_second': 21.365, 'train_loss': 2.98128955078125, 'epoch': 25.0}
{'train_runtime': 12.2112, 'train_samples_per_second': 20.473, 'train_steps_per_second': 20.473, 'train_loss': 3.100137451171875, 'epoch': 25.0}
{'train_runtime': 12.896, 'train_samples_per_second': 19.386, 'train_steps_per_second': 19.386, 'train_loss': 3.264813232421875, 'epoch': 25.0}
{'train_runtime': 12.488, 'train_samples_per_second': 20.019, 'train_steps_per_second': 20.019, 'train_loss': 3.44972314453125, 'epoch': 25.0}
{'train_runtime': 12.8012, 'train_samples_per_second': 19.529, 'train_steps_per_second': 19.529, 'train_loss': 3.34430615234375, 'epoch': 25.0}
{'train_runtime': 12.1276, 'train_samples_per_second': 20.614, 'train_steps_per_second': 20.614, 'train_loss': 3.03219482421875, 'epoch': 25.0}
{'train_runtime': 11.9564, 'train_samples_per_second': 20.909, 'train_steps_per_second': 20.909, 'train_loss': 2.952979736328125, 'epoch': 25.0}
{'train_runtime': 9.5468, 'train_samples_per_second': 26.187, 'train_steps_per_second': 26.187, 'train_loss': 3.05829345703125, 'epoch': 25.0}
{'train_runtime': 11.7425, 'train_samples_per_second': 21.29, 'train_steps_per_second': 21.29, 'train_loss': 2.996233642578125, 'epoch': 25.0}
{'train_runtime': 10.8803, 'train_samples_per_second': 22.977, 'train_steps_per_second': 22.977, 'train_loss': 3.18898095703125, 'epoch': 25.0}
{'train_runtime': 12.1765, 'train_samples_per_second': 20.531, 'train_steps_per_second': 20.531, 'train_loss': 3.08541064453125, 'epoch': 25.0}
{'train_runtime': 10.7399, 'train_samples_per_second': 23.278, 'train_steps_per_second': 23.278, 'train_loss': 3.168353515625, 'epoch': 25.0}
{'train_runtime': 10.5871, 'train_samples_per_second': 23.614, 'train_steps_per_second': 23.614, 'train_loss': 3.069327392578125, 'epoch': 25.0}
{'train_runtime': 10.5109, 'train_samples_per_second': 23.785, 'train_steps_per_second': 23.785, 'train_loss': 2.858050048828125, 'epoch': 25.0}
{'train_runtime': 10.9185, 'train_samples_per_second': 22.897, 'train_steps_per_second': 22.897, 'train_loss': 3.026873779296875, 'epoch': 25.0}
{'train_runtime': 10.2669, 'train_samples_per_second': 24.35, 'train_steps_per_second': 24.35, 'train_loss': 2.8908740234375, 'epoch': 25.0}
{'train_runtime': 9.8138, 'train_samples_per_second': 25.474, 'train_steps_per_second': 25.474, 'train_loss': 2.94835693359375, 'epoch': 25.0}
{'train_runtime': 10.6532, 'train_samples_per_second': 23.467, 'train_steps_per_second': 23.467, 'train_loss': 3.14920458984375, 'epoch': 25.0}
{'train_runtime': 10.0362, 'train_samples_per_second': 24.91, 'train_steps_per_second': 24.91, 'train_loss': 2.569791748046875, 'epoch': 25.0}
{'train_runtime': 9.5108, 'train_samples_per_second': 26.286, 'train_steps_per_second': 26.286, 'train_loss': 3.1390859375, 'epoch': 25.0}
{'train_runtime': 10.0167, 'train_samples_per_second': 24.958, 'train_steps_per_second': 24.958, 'train_loss': 2.91256103515625, 'epoch': 25.0}
{'train_runtime': 9.0151, 'train_samples_per_second': 27.731, 'train_steps_per_second': 27.731, 'train_loss': 3.219877197265625, 'epoch': 25.0}
{'train_runtime': 11.9933, 'train_samples_per_second': 20.845, 'train_steps_per_second': 20.845, 'train_loss': 3.394990234375, 'epoch': 25.0}
{'train_runtime': 9.998, 'train_samples_per_second': 25.005, 'train_steps_per_second': 25.005, 'train_loss': 3.121542236328125, 'epoch': 25.0}
{'train_runtime': 10.0874, 'train_samples_per_second': 24.783, 'train_steps_per_second': 24.783, 'train_loss': 2.764128662109375, 'epoch': 25.0}
{'train_runtime': 11.347, 'train_samples_per_second': 22.032, 'train_steps_per_second': 22.032, 'train_loss': 3.154458740234375, 'epoch': 25.0}
{'train_runtime': 9.9315, 'train_samples_per_second': 25.172, 'train_steps_per_second': 25.172, 'train_loss': 2.918078369140625, 'epoch': 25.0}
{'train_runtime': 11.2946, 'train_samples_per_second': 22.134, 'train_steps_per_second': 22.134, 'train_loss': 3.29824658203125, 'epoch': 25.0}
{'train_runtime': 11.0017, 'train_samples_per_second': 22.724, 'train_steps_per_second': 22.724, 'train_loss': 2.858103759765625, 'epoch': 25.0}
{'train_runtime': 11.999, 'train_samples_per_second': 20.835, 'train_steps_per_second': 20.835, 'train_loss': 3.172927490234375, 'epoch': 25.0}
{'train_runtime': 11.8043, 'train_samples_per_second': 21.179, 'train_steps_per_second': 21.179, 'train_loss': 2.8233623046875, 'epoch': 25.0}
{'train_runtime': 12.7094, 'train_samples_per_second': 19.671, 'train_steps_per_second': 19.671, 'train_loss': 3.0968134765625, 'epoch': 25.0}
{'train_runtime': 12.891, 'train_samples_per_second': 19.393, 'train_steps_per_second': 19.393, 'train_loss': 2.83693017578125, 'epoch': 25.0}
{'train_runtime': 11.353, 'train_samples_per_second': 22.021, 'train_steps_per_second': 22.021, 'train_loss': 3.22490625, 'epoch': 25.0}
{'train_runtime': 13.7484, 'train_samples_per_second': 18.184, 'train_steps_per_second': 18.184, 'train_loss': 3.0343330078125, 'epoch': 25.0}
{'train_runtime': 13.6791, 'train_samples_per_second': 18.276, 'train_steps_per_second': 18.276, 'train_loss': 2.8793310546875, 'epoch': 25.0}
{'train_runtime': 12.2205, 'train_samples_per_second': 20.457, 'train_steps_per_second': 20.457, 'train_loss': 2.548557861328125, 'epoch': 25.0}
{'train_runtime': 14.0541, 'train_samples_per_second': 17.788, 'train_steps_per_second': 17.788, 'train_loss': 2.998916015625, 'epoch': 25.0}
{'train_runtime': 13.2735, 'train_samples_per_second': 18.834, 'train_steps_per_second': 18.834, 'train_loss': 3.118984375, 'epoch': 25.0}
{'train_runtime': 13.3022, 'train_samples_per_second': 18.794, 'train_steps_per_second': 18.794, 'train_loss': 2.950474609375, 'epoch': 25.0}
{'train_runtime': 13.519, 'train_samples_per_second': 18.493, 'train_steps_per_second': 18.493, 'train_loss': 3.314846923828125, 'epoch': 25.0}
{'train_runtime': 13.3809, 'train_samples_per_second': 18.683, 'train_steps_per_second': 18.683, 'train_loss': 3.12928515625, 'epoch': 25.0}
{'train_runtime': 13.0452, 'train_samples_per_second': 19.164, 'train_steps_per_second': 19.164, 'train_loss': 3.038503173828125, 'epoch': 25.0}
{'train_runtime': 14.9378, 'train_samples_per_second': 16.736, 'train_steps_per_second': 16.736, 'train_loss': 3.02406005859375, 'epoch': 25.0}

Explanations:  33%|███▎      | 457/1400 [26:31<56:24,  3.59s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 458/1400 [26:39<1:14:44,  4.76s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 459/1400 [26:41<1:03:27,  4.05s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 460/1400 [26:42<49:37,  3.17s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 461/1400 [26:46<54:31,  3.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 462/1400 [26:54<1:12:44,  4.65s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 463/1400 [26:57<1:07:48,  4.34s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 464/1400 [26:58<52:41,  3.38s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 465/1400 [27:03<56:04,  3.60s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 466/1400 [27:08<1:03:05,  4.05s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 467/1400 [27:12<1:04:39,  4.16s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 468/1400 [27:13<50:17,  3.24s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▎      | 469/1400 [27:18<56:44,  3.66s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▎      | 470/1400 [27:24<1:07:10,  4.33s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▎      | 472/1400 [27:29<51:04,  3.30s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 473/1400 [27:33<52:48,  3.42s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 474/1400 [27:39<1:03:27,  4.11s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 476/1400 [27:45<51:13,  3.33s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 477/1400 [27:49<57:00,  3.71s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 478/1400 [27:55<1:05:36,  4.27s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Repo card metadata block was not found. Setting CardData to empty.
[WARNING] Repo card metadata block was not found. Setting CardData to empty.
Explanations:  34%|███▍      | 479/1400 [28:01<1:14:16,  4.84s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 481/1400 [28:05<52:36,  3.43s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 482/1400 [28:11<1:03:58,  4.18s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▍      | 484/1400 [28:18<54:24,  3.56s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▍      | 485/1400 [28:22<55:01,  3.61s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▍      | 486/1400 [28:27<1:01:28,  4.04s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▍      | 488/1400 [28:33<49:16,  3.24s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▍      | 489/1400 [28:36<52:13,  3.44s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▌      | 490/1400 [28:42<59:44,  3.94s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▌      | 492/1400 [28:48<49:41,  3.28s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▌      | 493/1400 [28:52<53:06,  3.51s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▌      | 494/1400 [28:56<55:56,  3.70s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▌      | 496/1400 [29:02<47:48,  3.17s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 497/1400 [29:06<53:36,  3.56s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 498/1400 [29:11<59:18,  3.95s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 500/1400 [29:16<44:50,  2.99s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 501/1400 [29:19<44:08,  2.95s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 502/1400 [29:24<51:56,  3.47s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 504/1400 [29:28<41:02,  2.75s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 505/1400 [29:31<40:15,  2.70s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 506/1400 [29:35<48:45,  3.27s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▋      | 508/1400 [29:40<40:29,  2.72s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▋      | 509/1400 [29:43<38:40,  2.60s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▋      | 510/1400 [29:47<47:47,  3.22s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 512/1400 [29:53<40:24,  2.73s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 513/1400 [29:55<37:50,  2.56s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 514/1400 [29:59<46:34,  3.15s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 516/1400 [30:05<40:04,  2.72s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 517/1400 [30:07<36:28,  2.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 518/1400 [30:11<45:50,  3.12s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 520/1400 [30:16<39:10,  2.67s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 14.2022, 'train_samples_per_second': 17.603, 'train_steps_per_second': 17.603, 'train_loss': 3.111024658203125, 'epoch': 25.0}
{'train_runtime': 13.7334, 'train_samples_per_second': 18.204, 'train_steps_per_second': 18.204, 'train_loss': 2.957802001953125, 'epoch': 25.0}
{'train_runtime': 12.5622, 'train_samples_per_second': 19.901, 'train_steps_per_second': 19.901, 'train_loss': 3.181314453125, 'epoch': 25.0}
{'train_runtime': 14.3581, 'train_samples_per_second': 17.412, 'train_steps_per_second': 17.412, 'train_loss': 2.778761474609375, 'epoch': 25.0}
{'train_runtime': 12.4398, 'train_samples_per_second': 20.097, 'train_steps_per_second': 20.097, 'train_loss': 3.192804931640625, 'epoch': 25.0}
{'train_runtime': 14.0827, 'train_samples_per_second': 17.752, 'train_steps_per_second': 17.752, 'train_loss': 2.74362744140625, 'epoch': 25.0}
{'train_runtime': 13.3574, 'train_samples_per_second': 18.716, 'train_steps_per_second': 18.716, 'train_loss': 2.952418701171875, 'epoch': 25.0}
{'train_runtime': 14.4162, 'train_samples_per_second': 17.342, 'train_steps_per_second': 17.342, 'train_loss': 2.899754638671875, 'epoch': 25.0}
{'train_runtime': 14.5008, 'train_samples_per_second': 17.24, 'train_steps_per_second': 17.24, 'train_loss': 3.18975390625, 'epoch': 25.0}
{'train_runtime': 11.92, 'train_samples_per_second': 20.973, 'train_steps_per_second': 20.973, 'train_loss': 3.393782470703125, 'epoch': 25.0}
{'train_runtime': 13.1488, 'train_samples_per_second': 19.013, 'train_steps_per_second': 19.013, 'train_loss': 2.754069091796875, 'epoch': 25.0}
{'train_runtime': 11.6247, 'train_samples_per_second': 21.506, 'train_steps_per_second': 21.506, 'train_loss': 3.17255029296875, 'epoch': 25.0}
{'train_runtime': 12.3727, 'train_samples_per_second': 20.206, 'train_steps_per_second': 20.206, 'train_loss': 3.175938720703125, 'epoch': 25.0}
{'train_runtime': 10.0289, 'train_samples_per_second': 24.928, 'train_steps_per_second': 24.928, 'train_loss': 2.670439697265625, 'epoch': 25.0}
{'train_runtime': 10.1521, 'train_samples_per_second': 24.625, 'train_steps_per_second': 24.625, 'train_loss': 2.622921875, 'epoch': 25.0}
{'train_runtime': 10.0521, 'train_samples_per_second': 24.87, 'train_steps_per_second': 24.87, 'train_loss': 2.6364677734375, 'epoch': 25.0}
{'train_runtime': 9.9622, 'train_samples_per_second': 25.095, 'train_steps_per_second': 25.095, 'train_loss': 2.662790771484375, 'epoch': 25.0}
{'train_runtime': 10.0823, 'train_samples_per_second': 24.796, 'train_steps_per_second': 24.796, 'train_loss': 2.619404052734375, 'epoch': 25.0}
{'train_runtime': 10.2717, 'train_samples_per_second': 24.339, 'train_steps_per_second': 24.339, 'train_loss': 2.6352470703125, 'epoch': 25.0}
{'train_runtime': 10.0472, 'train_samples_per_second': 24.882, 'train_steps_per_second': 24.882, 'train_loss': 2.61599365234375, 'epoch': 25.0}
{'train_runtime': 10.2918, 'train_samples_per_second': 24.291, 'train_steps_per_second': 24.291, 'train_loss': 2.650156494140625, 'epoch': 25.0}
{'train_runtime': 10.3597, 'train_samples_per_second': 24.132, 'train_steps_per_second': 24.132, 'train_loss': 2.636756103515625, 'epoch': 25.0}
{'train_runtime': 10.2402, 'train_samples_per_second': 24.413, 'train_steps_per_second': 24.413, 'train_loss': 2.6738271484375, 'epoch': 25.0}
{'train_runtime': 10.4603, 'train_samples_per_second': 23.9, 'train_steps_per_second': 23.9, 'train_loss': 2.63932470703125, 'epoch': 25.0}
{'train_runtime': 10.3198, 'train_samples_per_second': 24.225, 'train_steps_per_second': 24.225, 'train_loss': 2.607232666015625, 'epoch': 25.0}
{'train_runtime': 10.3549, 'train_samples_per_second': 24.143, 'train_steps_per_second': 24.143, 'train_loss': 2.670829345703125, 'epoch': 25.0}
{'train_runtime': 10.4017, 'train_samples_per_second': 24.035, 'train_steps_per_second': 24.035, 'train_loss': 2.628083251953125, 'epoch': 25.0}
{'train_runtime': 10.2351, 'train_samples_per_second': 24.426, 'train_steps_per_second': 24.426, 'train_loss': 2.654685302734375, 'epoch': 25.0}
{'train_runtime': 10.0443, 'train_samples_per_second': 24.89, 'train_steps_per_second': 24.89, 'train_loss': 2.629301513671875, 'epoch': 25.0}
{'train_runtime': 10.3544, 'train_samples_per_second': 24.144, 'train_steps_per_second': 24.144, 'train_loss': 2.6440625, 'epoch': 25.0}
{'train_runtime': 10.39, 'train_samples_per_second': 24.062, 'train_steps_per_second': 24.062, 'train_loss': 2.685564697265625, 'epoch': 25.0}
{'train_runtime': 10.2389, 'train_samples_per_second': 24.417, 'train_steps_per_second': 24.417, 'train_loss': 2.6540087890625, 'epoch': 25.0}
{'train_runtime': 10.4636, 'train_samples_per_second': 23.892, 'train_steps_per_second': 23.892, 'train_loss': 2.638132568359375, 'epoch': 25.0}
{'train_runtime': 10.3794, 'train_samples_per_second': 24.086, 'train_steps_per_second': 24.086, 'train_loss': 2.676256591796875, 'epoch': 25.0}
{'train_runtime': 10.3687, 'train_samples_per_second': 24.111, 'train_steps_per_second': 24.111, 'train_loss': 2.632604736328125, 'epoch': 25.0}
{'train_runtime': 10.2867, 'train_samples_per_second': 24.303, 'train_steps_per_second': 24.303, 'train_loss': 2.622408935546875, 'epoch': 25.0}
{'train_runtime': 10.4257, 'train_samples_per_second': 23.979, 'train_steps_per_second': 23.979, 'train_loss': 2.658914306640625, 'epoch': 25.0}
{'train_runtime': 11.138, 'train_samples_per_second': 22.446, 'train_steps_per_second': 22.446, 'train_loss': 3.049387451171875, 'epoch': 25.0}
{'train_runtime': 11.8559, 'train_samples_per_second': 21.087, 'train_steps_per_second': 21.087, 'train_loss': 3.0336669921875, 'epoch': 25.0}
{'train_runtime': 11.746, 'train_samples_per_second': 21.284, 'train_steps_per_second': 21.284, 'train_loss': 3.08255810546875, 'epoch': 25.0}
{'train_runtime': 12.1065, 'train_samples_per_second': 20.65, 'train_steps_per_second': 20.65, 'train_loss': 3.06607470703125, 'epoch': 25.0}
{'train_runtime': 11.9535, 'train_samples_per_second': 20.914, 'train_steps_per_second': 20.914, 'train_loss': 3.04179150390625, 'epoch': 25.0}
{'train_runtime': 11.9776, 'train_samples_per_second': 20.872, 'train_steps_per_second': 20.872, 'train_loss': 3.079828857421875, 'epoch': 25.0}
{'train_runtime': 11.8049, 'train_samples_per_second': 21.178, 'train_steps_per_second': 21.178, 'train_loss': 3.087621826171875, 'epoch': 25.0}
{'train_runtime': 12.025, 'train_samples_per_second': 20.79, 'train_steps_per_second': 20.79, 'train_loss': 3.05255126953125, 'epoch': 25.0}
{'train_runtime': 11.9423, 'train_samples_per_second': 20.934, 'train_steps_per_second': 20.934, 'train_loss': 3.055155029296875, 'epoch': 25.0}
{'train_runtime': 11.8903, 'train_samples_per_second': 21.025, 'train_steps_per_second': 21.025, 'train_loss': 3.031454833984375, 'epoch': 25.0}
{'train_runtime': 11.8645, 'train_samples_per_second': 21.071, 'train_steps_per_second': 21.071, 'train_loss': 3.06454345703125, 'epoch': 25.0}
{'train_runtime': 11.4951, 'train_samples_per_second': 21.748, 'train_steps_per_second': 21.748, 'train_loss': 3.04773974609375, 'epoch': 25.0}
{'train_runtime': 11.6559, 'train_samples_per_second': 21.448, 'train_steps_per_second': 21.448, 'train_loss': 3.073681884765625, 'epoch': 25.0}
{'train_runtime': 11.498, 'train_samples_per_second': 21.743, 'train_steps_per_second': 21.743, 'train_loss': 3.08869189453125, 'epoch': 25.0}
{'train_runtime': 11.5832, 'train_samples_per_second': 21.583, 'train_steps_per_second': 21.583, 'train_loss': 3.023869384765625, 'epoch': 25.0}
{'train_runtime': 11.5351, 'train_samples_per_second': 21.673, 'train_steps_per_second': 21.673, 'train_loss': 3.072044677734375, 'epoch': 25.0}
{'train_runtime': 11.463, 'train_samples_per_second': 21.809, 'train_steps_per_second': 21.809, 'train_loss': 3.044284912109375, 'epoch': 25.0}
{'train_runtime': 11.5478, 'train_samples_per_second': 21.649, 'train_steps_per_second': 21.649, 'train_loss': 3.057377197265625, 'epoch': 25.0}
{'train_runtime': 11.4747, 'train_samples_per_second': 21.787, 'train_steps_per_second': 21.787, 'train_loss': 3.084235107421875, 'epoch': 25.0}

Explanations:  48%|████▊     | 678/1400 [38:47<27:43,  2.30s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▊     | 680/1400 [38:57<39:40,  3.31s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 15.0472, 'train_samples_per_second': 16.614, 'train_steps_per_second': 16.614, 'train_loss': 2.9858505859375, 'epoch': 25.0}
{'train_runtime': 13.5659, 'train_samples_per_second': 18.429, 'train_steps_per_second': 18.429, 'train_loss': 2.8797333984375, 'epoch': 25.0}
{'train_runtime': 13.0804, 'train_samples_per_second': 19.112, 'train_steps_per_second': 19.112, 'train_loss': 3.08277978515625, 'epoch': 25.0}
{'train_runtime': 11.9095, 'train_samples_per_second': 20.992, 'train_steps_per_second': 20.992, 'train_loss': 3.123521484375, 'epoch': 25.0}
{'train_runtime': 13.8729, 'train_samples_per_second': 18.021, 'train_steps_per_second': 18.021, 'train_loss': 3.130584716796875, 'epoch': 25.0}
{'train_runtime': 12.8255, 'train_samples_per_second': 19.492, 'train_steps_per_second': 19.492, 'train_loss': 2.838403564453125, 'epoch': 25.0}
{'train_runtime': 14.3113, 'train_samples_per_second': 17.469, 'train_steps_per_second': 17.469, 'train_loss': 3.171723876953125, 'epoch': 25.0}
{'train_runtime': 14.1158, 'train_samples_per_second': 17.711, 'train_steps_per_second': 17.711, 'train_loss': 3.412311279296875, 'epoch': 25.0}
{'train_runtime': 13.7049, 'train_samples_per_second': 18.242, 'train_steps_per_second': 18.242, 'train_loss': 2.957760498046875, 'epoch': 25.0}
{'train_runtime': 12.6219, 'train_samples_per_second': 19.807, 'train_steps_per_second': 19.807, 'train_loss': 2.82475048828125, 'epoch': 25.0}
{'train_runtime': 12.3269, 'train_samples_per_second': 20.281, 'train_steps_per_second': 20.281, 'train_loss': 2.880544189453125, 'epoch': 25.0}
{'train_runtime': 12.9709, 'train_samples_per_second': 19.274, 'train_steps_per_second': 19.274, 'train_loss': 3.01153466796875, 'epoch': 25.0}
{'train_runtime': 10.181, 'train_samples_per_second': 24.555, 'train_steps_per_second': 24.555, 'train_loss': 2.6719208984375, 'epoch': 25.0}
{'train_runtime': 9.7658, 'train_samples_per_second': 25.6, 'train_steps_per_second': 25.6, 'train_loss': 2.63707080078125, 'epoch': 25.0}
{'train_runtime': 9.9869, 'train_samples_per_second': 25.033, 'train_steps_per_second': 25.033, 'train_loss': 2.639913330078125, 'epoch': 25.0}
{'train_runtime': 9.8461, 'train_samples_per_second': 25.391, 'train_steps_per_second': 25.391, 'train_loss': 2.648310791015625, 'epoch': 25.0}
{'train_runtime': 9.895, 'train_samples_per_second': 25.265, 'train_steps_per_second': 25.265, 'train_loss': 2.66876708984375, 'epoch': 25.0}
{'train_runtime': 10.1516, 'train_samples_per_second': 24.627, 'train_steps_per_second': 24.627, 'train_loss': 2.672041748046875, 'epoch': 25.0}
{'train_runtime': 9.7254, 'train_samples_per_second': 25.706, 'train_steps_per_second': 25.706, 'train_loss': 2.643018310546875, 'epoch': 25.0}
{'train_runtime': 9.9766, 'train_samples_per_second': 25.059, 'train_steps_per_second': 25.059, 'train_loss': 2.628017578125, 'epoch': 25.0}
{'train_runtime': 9.9921, 'train_samples_per_second': 25.02, 'train_steps_per_second': 25.02, 'train_loss': 2.67145751953125, 'epoch': 25.0}
{'train_runtime': 9.9096, 'train_samples_per_second': 25.228, 'train_steps_per_second': 25.228, 'train_loss': 2.65258935546875, 'epoch': 25.0}
{'train_runtime': 9.8974, 'train_samples_per_second': 25.259, 'train_steps_per_second': 25.259, 'train_loss': 2.640423095703125, 'epoch': 25.0}
{'train_runtime': 9.8421, 'train_samples_per_second': 25.401, 'train_steps_per_second': 25.401, 'train_loss': 2.6600927734375, 'epoch': 25.0}
{'train_runtime': 9.8893, 'train_samples_per_second': 25.28, 'train_steps_per_second': 25.28, 'train_loss': 2.644730224609375, 'epoch': 25.0}
{'train_runtime': 10.0268, 'train_samples_per_second': 24.933, 'train_steps_per_second': 24.933, 'train_loss': 2.629495849609375, 'epoch': 25.0}
{'train_runtime': 9.8224, 'train_samples_per_second': 25.452, 'train_steps_per_second': 25.452, 'train_loss': 2.61961328125, 'epoch': 25.0}
{'train_runtime': 10.0352, 'train_samples_per_second': 24.912, 'train_steps_per_second': 24.912, 'train_loss': 2.661279052734375, 'epoch': 25.0}
{'train_runtime': 10.1057, 'train_samples_per_second': 24.738, 'train_steps_per_second': 24.738, 'train_loss': 2.64236279296875, 'epoch': 25.0}
{'train_runtime': 9.7191, 'train_samples_per_second': 25.723, 'train_steps_per_second': 25.723, 'train_loss': 2.657370361328125, 'epoch': 25.0}
{'train_runtime': 9.9256, 'train_samples_per_second': 25.187, 'train_steps_per_second': 25.187, 'train_loss': 2.67412890625, 'epoch': 25.0}
{'train_runtime': 9.9924, 'train_samples_per_second': 25.019, 'train_steps_per_second': 25.019, 'train_loss': 2.677292236328125, 'epoch': 25.0}
{'train_runtime': 10.0266, 'train_samples_per_second': 24.934, 'train_steps_per_second': 24.934, 'train_loss': 2.627772216796875, 'epoch': 25.0}
{'train_runtime': 10.2592, 'train_samples_per_second': 24.368, 'train_steps_per_second': 24.368, 'train_loss': 2.67601220703125, 'epoch': 25.0}
{'train_runtime': 10.3213, 'train_samples_per_second': 24.222, 'train_steps_per_second': 24.222, 'train_loss': 2.62849609375, 'epoch': 25.0}
{'train_runtime': 10.0929, 'train_samples_per_second': 24.77, 'train_steps_per_second': 24.77, 'train_loss': 2.665898681640625, 'epoch': 25.0}
{'train_runtime': 10.1802, 'train_samples_per_second': 24.557, 'train_steps_per_second': 24.557, 'train_loss': 2.662473388671875, 'epoch': 25.0}
{'train_runtime': 11.0832, 'train_samples_per_second': 22.557, 'train_steps_per_second': 22.557, 'train_loss': 3.0918740234375, 'epoch': 25.0}
{'train_runtime': 11.6593, 'train_samples_per_second': 21.442, 'train_steps_per_second': 21.442, 'train_loss': 3.041489013671875, 'epoch': 25.0}
{'train_runtime': 11.7509, 'train_samples_per_second': 21.275, 'train_steps_per_second': 21.275, 'train_loss': 3.063002685546875, 'epoch': 25.0}
{'train_runtime': 11.7575, 'train_samples_per_second': 21.263, 'train_steps_per_second': 21.263, 'train_loss': 3.0680380859375, 'epoch': 25.0}
{'train_runtime': 11.9046, 'train_samples_per_second': 21.0, 'train_steps_per_second': 21.0, 'train_loss': 3.077680419921875, 'epoch': 25.0}
{'train_runtime': 11.7898, 'train_samples_per_second': 21.205, 'train_steps_per_second': 21.205, 'train_loss': 3.07811767578125, 'epoch': 25.0}
{'train_runtime': 11.6956, 'train_samples_per_second': 21.376, 'train_steps_per_second': 21.376, 'train_loss': 3.082600341796875, 'epoch': 25.0}
{'train_runtime': 11.8351, 'train_samples_per_second': 21.124, 'train_steps_per_second': 21.124, 'train_loss': 3.049701171875, 'epoch': 25.0}
{'train_runtime': 11.9142, 'train_samples_per_second': 20.983, 'train_steps_per_second': 20.983, 'train_loss': 3.08547265625, 'epoch': 25.0}
{'train_runtime': 11.8602, 'train_samples_per_second': 21.079, 'train_steps_per_second': 21.079, 'train_loss': 3.04486083984375, 'epoch': 25.0}
{'train_runtime': 11.6986, 'train_samples_per_second': 21.37, 'train_steps_per_second': 21.37, 'train_loss': 3.041577880859375, 'epoch': 25.0}
{'train_runtime': 11.5428, 'train_samples_per_second': 21.659, 'train_steps_per_second': 21.659, 'train_loss': 3.056765380859375, 'epoch': 25.0}
{'train_runtime': 11.8112, 'train_samples_per_second': 21.166, 'train_steps_per_second': 21.166, 'train_loss': 3.07639599609375, 'epoch': 25.0}
{'train_runtime': 11.7427, 'train_samples_per_second': 21.29, 'train_steps_per_second': 21.29, 'train_loss': 3.071984619140625, 'epoch': 25.0}
{'train_runtime': 11.5374, 'train_samples_per_second': 21.669, 'train_steps_per_second': 21.669, 'train_loss': 3.022800048828125, 'epoch': 25.0}
{'train_runtime': 11.3844, 'train_samples_per_second': 21.96, 'train_steps_per_second': 21.96, 'train_loss': 3.085193603515625, 'epoch': 25.0}
{'train_runtime': 11.4763, 'train_samples_per_second': 21.784, 'train_steps_per_second': 21.784, 'train_loss': 3.044675048828125, 'epoch': 25.0}
{'train_runtime': 11.6738, 'train_samples_per_second': 21.416, 'train_steps_per_second': 21.416, 'train_loss': 3.05587451171875, 'epoch': 25.0}
{'train_runtime': 11.4564, 'train_samples_per_second': 21.822, 'train_steps_per_second': 21.822, 'train_loss': 3.066748291015625, 'epoch': 25.0}
{'train_runtime': 11.5089, 'train_samples_per_second': 21.722, 'train_steps_per_second': 21.722, 'train_loss': 3.040463623046875, 'epoch': 25.0}

Explanations:  49%|████▊     | 682/1400 [39:00<27:44,  2.32s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 13.9987, 'train_samples_per_second': 17.859, 'train_steps_per_second': 17.859, 'train_loss': 3.08122119140625, 'epoch': 25.0}
{'train_runtime': 12.9495, 'train_samples_per_second': 19.306, 'train_steps_per_second': 19.306, 'train_loss': 2.91314697265625, 'epoch': 25.0}
{'train_runtime': 14.0777, 'train_samples_per_second': 17.759, 'train_steps_per_second': 17.759, 'train_loss': 2.8733544921875, 'epoch': 25.0}
{'train_runtime': 13.2191, 'train_samples_per_second': 18.912, 'train_steps_per_second': 18.912, 'train_loss': 3.031769775390625, 'epoch': 25.0}
{'train_runtime': 13.0548, 'train_samples_per_second': 19.15, 'train_steps_per_second': 19.15, 'train_loss': 3.24975146484375, 'epoch': 25.0}
{'train_runtime': 14.5088, 'train_samples_per_second': 17.231, 'train_steps_per_second': 17.231, 'train_loss': 2.908015869140625, 'epoch': 25.0}
{'train_runtime': 13.27, 'train_samples_per_second': 18.84, 'train_steps_per_second': 18.84, 'train_loss': 2.973420166015625, 'epoch': 25.0}
{'train_runtime': 15.0165, 'train_samples_per_second': 16.648, 'train_steps_per_second': 16.648, 'train_loss': 2.9342998046875, 'epoch': 25.0}
{'train_runtime': 12.6595, 'train_samples_per_second': 19.748, 'train_steps_per_second': 19.748, 'train_loss': 2.819349853515625, 'epoch': 25.0}
{'train_runtime': 13.3349, 'train_samples_per_second': 18.748, 'train_steps_per_second': 18.748, 'train_loss': 3.5451650390625, 'epoch': 25.0}
{'train_runtime': 12.6391, 'train_samples_per_second': 19.78, 'train_steps_per_second': 19.78, 'train_loss': 2.7955595703125, 'epoch': 25.0}
{'train_runtime': 10.4592, 'train_samples_per_second': 23.902, 'train_steps_per_second': 23.902, 'train_loss': 2.6502138671875, 'epoch': 25.0}
{'train_runtime': 9.9047, 'train_samples_per_second': 25.241, 'train_steps_per_second': 25.241, 'train_loss': 2.649959228515625, 'epoch': 25.0}
{'train_runtime': 9.9074, 'train_samples_per_second': 25.234, 'train_steps_per_second': 25.234, 'train_loss': 2.652688232421875, 'epoch': 25.0}
{'train_runtime': 9.9257, 'train_samples_per_second': 25.187, 'train_steps_per_second': 25.187, 'train_loss': 2.66362060546875, 'epoch': 25.0}
{'train_runtime': 9.845, 'train_samples_per_second': 25.394, 'train_steps_per_second': 25.394, 'train_loss': 2.64689306640625, 'epoch': 25.0}
{'train_runtime': 9.9112, 'train_samples_per_second': 25.224, 'train_steps_per_second': 25.224, 'train_loss': 2.621820556640625, 'epoch': 25.0}
{'train_runtime': 10.1392, 'train_samples_per_second': 24.657, 'train_steps_per_second': 24.657, 'train_loss': 2.678343017578125, 'epoch': 25.0}
{'train_runtime': 9.9154, 'train_samples_per_second': 25.213, 'train_steps_per_second': 25.213, 'train_loss': 2.6100546875, 'epoch': 25.0}
{'train_runtime': 10.1232, 'train_samples_per_second': 24.696, 'train_steps_per_second': 24.696, 'train_loss': 2.69565087890625, 'epoch': 25.0}
{'train_runtime': 10.1279, 'train_samples_per_second': 24.684, 'train_steps_per_second': 24.684, 'train_loss': 2.672468017578125, 'epoch': 25.0}
{'train_runtime': 10.1785, 'train_samples_per_second': 24.561, 'train_steps_per_second': 24.561, 'train_loss': 2.64080322265625, 'epoch': 25.0}
{'train_runtime': 10.2083, 'train_samples_per_second': 24.49, 'train_steps_per_second': 24.49, 'train_loss': 2.6476708984375, 'epoch': 25.0}
{'train_runtime': 10.1156, 'train_samples_per_second': 24.714, 'train_steps_per_second': 24.714, 'train_loss': 2.64360107421875, 'epoch': 25.0}
{'train_runtime': 10.3031, 'train_samples_per_second': 24.265, 'train_steps_per_second': 24.265, 'train_loss': 2.624347900390625, 'epoch': 25.0}
{'train_runtime': 10.1916, 'train_samples_per_second': 24.53, 'train_steps_per_second': 24.53, 'train_loss': 2.605683837890625, 'epoch': 25.0}
{'train_runtime': 10.2143, 'train_samples_per_second': 24.475, 'train_steps_per_second': 24.475, 'train_loss': 2.650130859375, 'epoch': 25.0}
{'train_runtime': 10.1045, 'train_samples_per_second': 24.741, 'train_steps_per_second': 24.741, 'train_loss': 2.677333984375, 'epoch': 25.0}
{'train_runtime': 10.4525, 'train_samples_per_second': 23.918, 'train_steps_per_second': 23.918, 'train_loss': 2.686232177734375, 'epoch': 25.0}
{'train_runtime': 10.3368, 'train_samples_per_second': 24.186, 'train_steps_per_second': 24.186, 'train_loss': 2.654645263671875, 'epoch': 25.0}
{'train_runtime': 10.5259, 'train_samples_per_second': 23.751, 'train_steps_per_second': 23.751, 'train_loss': 2.656597900390625, 'epoch': 25.0}
{'train_runtime': 10.4106, 'train_samples_per_second': 24.014, 'train_steps_per_second': 24.014, 'train_loss': 2.68541015625, 'epoch': 25.0}
{'train_runtime': 10.3076, 'train_samples_per_second': 24.254, 'train_steps_per_second': 24.254, 'train_loss': 2.6663486328125, 'epoch': 25.0}
{'train_runtime': 10.3163, 'train_samples_per_second': 24.233, 'train_steps_per_second': 24.233, 'train_loss': 2.7078037109375, 'epoch': 25.0}
{'train_runtime': 10.3399, 'train_samples_per_second': 24.178, 'train_steps_per_second': 24.178, 'train_loss': 2.67873583984375, 'epoch': 25.0}
{'train_runtime': 10.431, 'train_samples_per_second': 23.967, 'train_steps_per_second': 23.967, 'train_loss': 2.644891845703125, 'epoch': 25.0}
{'train_runtime': 11.1874, 'train_samples_per_second': 22.346, 'train_steps_per_second': 22.346, 'train_loss': 2.658890625, 'epoch': 25.0}
{'train_runtime': 11.8117, 'train_samples_per_second': 21.165, 'train_steps_per_second': 21.165, 'train_loss': 3.04041796875, 'epoch': 25.0}
{'train_runtime': 11.8702, 'train_samples_per_second': 21.061, 'train_steps_per_second': 21.061, 'train_loss': 3.0937412109375, 'epoch': 25.0}
{'train_runtime': 12.212, 'train_samples_per_second': 20.472, 'train_steps_per_second': 20.472, 'train_loss': 3.042121826171875, 'epoch': 25.0}
{'train_runtime': 11.8787, 'train_samples_per_second': 21.046, 'train_steps_per_second': 21.046, 'train_loss': 3.039666015625, 'epoch': 25.0}
{'train_runtime': 11.903, 'train_samples_per_second': 21.003, 'train_steps_per_second': 21.003, 'train_loss': 3.03456689453125, 'epoch': 25.0}
{'train_runtime': 11.9559, 'train_samples_per_second': 20.91, 'train_steps_per_second': 20.91, 'train_loss': 3.0700849609375, 'epoch': 25.0}
{'train_runtime': 12.022, 'train_samples_per_second': 20.795, 'train_steps_per_second': 20.795, 'train_loss': 3.07279541015625, 'epoch': 25.0}
{'train_runtime': 11.8329, 'train_samples_per_second': 21.128, 'train_steps_per_second': 21.128, 'train_loss': 3.041809326171875, 'epoch': 25.0}
{'train_runtime': 11.833, 'train_samples_per_second': 21.127, 'train_steps_per_second': 21.127, 'train_loss': 3.059027587890625, 'epoch': 25.0}
{'train_runtime': 11.6921, 'train_samples_per_second': 21.382, 'train_steps_per_second': 21.382, 'train_loss': 3.043422119140625, 'epoch': 25.0}
{'train_runtime': 11.725, 'train_samples_per_second': 21.322, 'train_steps_per_second': 21.322, 'train_loss': 3.05671142578125, 'epoch': 25.0}
{'train_runtime': 11.7254, 'train_samples_per_second': 21.321, 'train_steps_per_second': 21.321, 'train_loss': 3.075607666015625, 'epoch': 25.0}
{'train_runtime': 11.7021, 'train_samples_per_second': 21.364, 'train_steps_per_second': 21.364, 'train_loss': 3.046329833984375, 'epoch': 25.0}
{'train_runtime': 11.5459, 'train_samples_per_second': 21.653, 'train_steps_per_second': 21.653, 'train_loss': 3.085802490234375, 'epoch': 25.0}
{'train_runtime': 11.4004, 'train_samples_per_second': 21.929, 'train_steps_per_second': 21.929, 'train_loss': 3.068654541015625, 'epoch': 25.0}
{'train_runtime': 11.603, 'train_samples_per_second': 21.546, 'train_steps_per_second': 21.546, 'train_loss': 3.0633564453125, 'epoch': 25.0}
{'train_runtime': 11.5016, 'train_samples_per_second': 21.736, 'train_steps_per_second': 21.736, 'train_loss': 3.072324951171875, 'epoch': 25.0}
{'train_runtime': 11.3418, 'train_samples_per_second': 22.042, 'train_steps_per_second': 22.042, 'train_loss': 3.046116455078125, 'epoch': 25.0}
{'train_runtime': 11.4255, 'train_samples_per_second': 21.881, 'train_steps_per_second': 21.881, 'train_loss': 3.044254150390625, 'epoch': 25.0}
{'train_runtime': 11.5984, 'train_samples_per_second': 21.555, 'train_steps_per_second': 21.555, 'train_loss': 3.0606494140625, 'epoch': 25.0}
{'train_runtime': 13.9702, 'train_samples_per_second': 17.895, 'train_steps_per_second': 17.895, 'train_loss': 2.882628662109375, 'epoch': 25.0}
{'train_runtime': 13.6248, 'train_samples_per_second': 18.349, 'train_steps_per_second': 18.349, 'train_loss': 3.308905517578125, 'epoch': 25.0}
{'train_runtime': 14.3745, 'train_samples_per_second': 17.392, 'train_steps_per_second': 17.392, 'train_loss': 2.8440283203125, 'epoch': 25.0}
{'train_runtime': 12.7849, 'train_samples_per_second': 19.554, 'train_steps_per_second': 19.554, 'train_loss': 3.15168115234375, 'epoch': 25.0}
{'train_runtime': 14.9054, 'train_samples_per_second': 16.772, 'train_steps_per_second': 16.772, 'train_loss': 3.02834765625, 'epoch': 25.0}
{'train_runtime': 13.8309, 'train_samples_per_second': 18.075, 'train_steps_per_second': 18.075, 'train_loss': 2.9997314453125, 'epoch': 25.0}
{'train_runtime': 14.3002, 'train_samples_per_second': 17.482, 'train_steps_per_second': 17.482, 'train_loss': 2.556887939453125, 'epoch': 25.0}
{'train_runtime': 14.6799, 'train_samples_per_second': 17.03, 'train_steps_per_second': 17.03, 'train_loss': 3.036472412109375, 'epoch': 25.0}
{'train_runtime': 12.5065, 'train_samples_per_second': 19.99, 'train_steps_per_second': 19.99, 'train_loss': 2.894087158203125, 'epoch': 25.0}
{'train_runtime': 13.2817, 'train_samples_per_second': 18.823, 'train_steps_per_second': 18.823, 'train_loss': 2.98333154296875, 'epoch': 25.0}
{'train_runtime': 12.2359, 'train_samples_per_second': 20.432, 'train_steps_per_second': 20.432, 'train_loss': 2.848489990234375, 'epoch': 25.0}
{'train_runtime': 12.1269, 'train_samples_per_second': 20.615, 'train_steps_per_second': 20.615, 'train_loss': 3.008373046875, 'epoch': 25.0}
{'train_runtime': 10.1597, 'train_samples_per_second': 24.607, 'train_steps_per_second': 24.607, 'train_loss': 2.656611572265625, 'epoch': 25.0}
{'train_runtime': 10.1701, 'train_samples_per_second': 24.582, 'train_steps_per_second': 24.582, 'train_loss': 2.6501318359375, 'epoch': 25.0}
{'train_runtime': 10.2036, 'train_samples_per_second': 24.501, 'train_steps_per_second': 24.501, 'train_loss': 2.662618408203125, 'epoch': 25.0}
{'train_runtime': 10.1149, 'train_samples_per_second': 24.716, 'train_steps_per_second': 24.716, 'train_loss': 2.641966552734375, 'epoch': 25.0}
{'train_runtime': 9.9614, 'train_samples_per_second': 25.097, 'train_steps_per_second': 25.097, 'train_loss': 2.68467431640625, 'epoch': 25.0}
{'train_runtime': 10.4252, 'train_samples_per_second': 23.98, 'train_steps_per_second': 23.98, 'train_loss': 2.66105078125, 'epoch': 25.0}
{'train_runtime': 10.062, 'train_samples_per_second': 24.846, 'train_steps_per_second': 24.846, 'train_loss': 2.662712158203125, 'epoch': 25.0}
{'train_runtime': 10.3033, 'train_samples_per_second': 24.264, 'train_steps_per_second': 24.264, 'train_loss': 2.67548193359375, 'epoch': 25.0}
{'train_runtime': 10.2609, 'train_samples_per_second': 24.364, 'train_steps_per_second': 24.364, 'train_loss': 2.636783935546875, 'epoch': 25.0}
{'train_runtime': 10.4179, 'train_samples_per_second': 23.997, 'train_steps_per_second': 23.997, 'train_loss': 2.6412119140625, 'epoch': 25.0}
{'train_runtime': 10.2911, 'train_samples_per_second': 24.293, 'train_steps_per_second': 24.293, 'train_loss': 2.63884130859375, 'epoch': 25.0}
{'train_runtime': 10.2428, 'train_samples_per_second': 24.407, 'train_steps_per_second': 24.407, 'train_loss': 2.698486328125, 'epoch': 25.0}
{'train_runtime': 10.3066, 'train_samples_per_second': 24.256, 'train_steps_per_second': 24.256, 'train_loss': 2.64002587890625, 'epoch': 25.0}
{'train_runtime': 10.4593, 'train_samples_per_second': 23.902, 'train_steps_per_second': 23.902, 'train_loss': 2.685254150390625, 'epoch': 25.0}
{'train_runtime': 10.1085, 'train_samples_per_second': 24.732, 'train_steps_per_second': 24.732, 'train_loss': 2.620487548828125, 'epoch': 25.0}
{'train_runtime': 10.4926, 'train_samples_per_second': 23.826, 'train_steps_per_second': 23.826, 'train_loss': 2.6224189453125, 'epoch': 25.0}
{'train_runtime': 10.547, 'train_samples_per_second': 23.703, 'train_steps_per_second': 23.703, 'train_loss': 2.619302734375, 'epoch': 25.0}
{'train_runtime': 10.2796, 'train_samples_per_second': 24.32, 'train_steps_per_second': 24.32, 'train_loss': 2.64433544921875, 'epoch': 25.0}
{'train_runtime': 10.4199, 'train_samples_per_second': 23.993, 'train_steps_per_second': 23.993, 'train_loss': 2.665988037109375, 'epoch': 25.0}
{'train_runtime': 10.2676, 'train_samples_per_second': 24.348, 'train_steps_per_second': 24.348, 'train_loss': 2.65141357421875, 'epoch': 25.0}
{'train_runtime': 10.2959, 'train_samples_per_second': 24.281, 'train_steps_per_second': 24.281, 'train_loss': 2.655481201171875, 'epoch': 25.0}
{'train_runtime': 10.3973, 'train_samples_per_second': 24.045, 'train_steps_per_second': 24.045, 'train_loss': 2.626674072265625, 'epoch': 25.0}
{'train_runtime': 10.5228, 'train_samples_per_second': 23.758, 'train_steps_per_second': 23.758, 'train_loss': 2.66488916015625, 'epoch': 25.0}
{'train_runtime': 10.5694, 'train_samples_per_second': 23.653, 'train_steps_per_second': 23.653, 'train_loss': 2.64584375, 'epoch': 25.0}
{'train_runtime': 11.1069, 'train_samples_per_second': 22.508, 'train_steps_per_second': 22.508, 'train_loss': 2.66087255859375, 'epoch': 25.0}
{'train_runtime': 12.0785, 'train_samples_per_second': 20.698, 'train_steps_per_second': 20.698, 'train_loss': 3.082065673828125, 'epoch': 25.0}
{'train_runtime': 11.9352, 'train_samples_per_second': 20.946, 'train_steps_per_second': 20.946, 'train_loss': 3.053164794921875, 'epoch': 25.0}
{'train_runtime': 12.1423, 'train_samples_per_second': 20.589, 'train_steps_per_second': 20.589, 'train_loss': 3.04439697265625, 'epoch': 25.0}
{'train_runtime': 12.0048, 'train_samples_per_second': 20.825, 'train_steps_per_second': 20.825, 'train_loss': 3.055195556640625, 'epoch': 25.0}
{'train_runtime': 11.8626, 'train_samples_per_second': 21.075, 'train_steps_per_second': 21.075, 'train_loss': 3.094892578125, 'epoch': 25.0}
{'train_runtime': 11.8682, 'train_samples_per_second': 21.065, 'train_steps_per_second': 21.065, 'train_loss': 3.053470458984375, 'epoch': 25.0}
{'train_runtime': 11.8849, 'train_samples_per_second': 21.035, 'train_steps_per_second': 21.035, 'train_loss': 3.0581552734375, 'epoch': 25.0}
{'train_runtime': 11.935, 'train_samples_per_second': 20.947, 'train_steps_per_second': 20.947, 'train_loss': 3.06539208984375, 'epoch': 25.0}
{'train_runtime': 11.7731, 'train_samples_per_second': 21.235, 'train_steps_per_second': 21.235, 'train_loss': 3.063480224609375, 'epoch': 25.0}
{'train_runtime': 11.8321, 'train_samples_per_second': 21.129, 'train_steps_per_second': 21.129, 'train_loss': 3.07631103515625, 'epoch': 25.0}
{'train_runtime': 11.5362, 'train_samples_per_second': 21.671, 'train_steps_per_second': 21.671, 'train_loss': 3.088277587890625, 'epoch': 25.0}
{'train_runtime': 11.7196, 'train_samples_per_second': 21.332, 'train_steps_per_second': 21.332, 'train_loss': 3.0782275390625, 'epoch': 25.0}
{'train_runtime': 11.5058, 'train_samples_per_second': 21.728, 'train_steps_per_second': 21.728, 'train_loss': 3.035507080078125, 'epoch': 25.0}
{'train_runtime': 11.4968, 'train_samples_per_second': 21.745, 'train_steps_per_second': 21.745, 'train_loss': 3.0425458984375, 'epoch': 25.0}
{'train_runtime': 11.3367, 'train_samples_per_second': 22.052, 'train_steps_per_second': 22.052, 'train_loss': 3.04457275390625, 'epoch': 25.0}
{'train_runtime': 11.6545, 'train_samples_per_second': 21.451, 'train_steps_per_second': 21.451, 'train_loss': 3.03720166015625, 'epoch': 25.0}
{'train_runtime': 11.7131, 'train_samples_per_second': 21.344, 'train_steps_per_second': 21.344, 'train_loss': 3.044759033203125, 'epoch': 25.0}
{'train_runtime': 11.3379, 'train_samples_per_second': 22.05, 'train_steps_per_second': 22.05, 'train_loss': 3.071966796875, 'epoch': 25.0}
{'train_runtime': 11.4424, 'train_samples_per_second': 21.848, 'train_steps_per_second': 21.848, 'train_loss': 3.0374482421875, 'epoch': 25.0}
{'train_runtime': 11.6004, 'train_samples_per_second': 21.551, 'train_steps_per_second': 21.551, 'train_loss': 3.059701904296875, 'epoch': 25.0}

Explanations:  49%|████▉     | 684/1400 [39:11<39:57,  3.35s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▉     | 686/1400 [39:14<27:11,  2.29s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▉     | 688/1400 [39:24<40:08,  3.38s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▉     | 690/1400 [39:27<27:00,  2.28s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▉     | 692/1400 [39:38<40:06,  3.40s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|████▉     | 694/1400 [39:41<26:35,  2.26s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|████▉     | 696/1400 [39:52<40:17,  3.43s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|████▉     | 698/1400 [39:54<26:06,  2.23s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|█████     | 700/1400 [40:05<40:17,  3.45s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|█████     | 702/1400 [40:08<27:28,  2.36s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|█████     | 704/1400 [40:20<40:34,  3.50s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|█████     | 706/1400 [40:23<27:35,  2.39s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 708/1400 [40:34<40:31,  3.51s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 710/1400 [40:37<27:36,  2.40s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 712/1400 [40:48<40:39,  3.55s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 714/1400 [40:51<27:28,  2.40s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 716/1400 [41:02<40:56,  3.59s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████▏    | 718/1400 [41:06<28:53,  2.54s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████▏    | 720/1400 [41:16<39:46,  3.51s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 722/1400 [41:20<28:48,  2.55s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 724/1400 [41:30<39:19,  3.49s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 725/1400 [41:33<35:56,  3.19s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 726/1400 [41:34<29:34,  2.63s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 728/1400 [41:44<38:57,  3.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 729/1400 [41:47<35:26,  3.17s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 730/1400 [41:48<29:25,  2.64s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 732/1400 [41:58<39:09,  3.52s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 733/1400 [42:01<34:57,  3.14s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 734/1400 [42:02<28:39,  2.58s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 736/1400 [42:12<39:27,  3.57s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 737/1400 [42:15<34:58,  3.16s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 738/1400 [42:16<28:03,  2.54s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 739/1400 [42:25<51:11,  4.65s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 740/1400 [42:27<42:46,  3.89s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 742/1400 [42:30<27:09,  2.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 743/1400 [42:39<49:04,  4.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 744/1400 [42:42<43:23,  3.97s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 746/1400 [42:44<27:33,  2.53s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 747/1400 [42:52<46:39,  4.29s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 748/1400 [42:56<44:26,  4.09s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  54%|█████▎    | 750/1400 [42:58<27:18,  2.52s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 11.5218, 'train_samples_per_second': 21.698, 'train_steps_per_second': 21.698, 'train_loss': 3.04738427734375, 'epoch': 25.0}
{'train_runtime': 11.5155, 'train_samples_per_second': 21.71, 'train_steps_per_second': 21.71, 'train_loss': 3.075848876953125, 'epoch': 25.0}
{'train_runtime': 11.3621, 'train_samples_per_second': 22.003, 'train_steps_per_second': 22.003, 'train_loss': 3.07580615234375, 'epoch': 25.0}
{'train_runtime': 11.482, 'train_samples_per_second': 21.773, 'train_steps_per_second': 21.773, 'train_loss': 3.050119873046875, 'epoch': 25.0}
{'train_runtime': 11.4715, 'train_samples_per_second': 21.793, 'train_steps_per_second': 21.793, 'train_loss': 3.095212646484375, 'epoch': 25.0}
{'train_runtime': 11.3842, 'train_samples_per_second': 21.96, 'train_steps_per_second': 21.96, 'train_loss': 3.065911865234375, 'epoch': 25.0}
{'train_runtime': 12.0879, 'train_samples_per_second': 20.682, 'train_steps_per_second': 20.682, 'train_loss': 3.2123056640625, 'epoch': 25.0}
{'train_runtime': 12.1584, 'train_samples_per_second': 20.562, 'train_steps_per_second': 20.562, 'train_loss': 3.207226318359375, 'epoch': 25.0}
{'train_runtime': 12.0979, 'train_samples_per_second': 20.665, 'train_steps_per_second': 20.665, 'train_loss': 3.233603515625, 'epoch': 25.0}
{'train_runtime': 12.1287, 'train_samples_per_second': 20.612, 'train_steps_per_second': 20.612, 'train_loss': 3.2156767578125, 'epoch': 25.0}
{'train_runtime': 12.6824, 'train_samples_per_second': 19.712, 'train_steps_per_second': 19.712, 'train_loss': 3.225980712890625, 'epoch': 25.0}
{'train_runtime': 12.1201, 'train_samples_per_second': 20.627, 'train_steps_per_second': 20.627, 'train_loss': 3.207026123046875, 'epoch': 25.0}
{'train_runtime': 11.961, 'train_samples_per_second': 20.901, 'train_steps_per_second': 20.901, 'train_loss': 3.21777392578125, 'epoch': 25.0}
{'train_runtime': 11.9891, 'train_samples_per_second': 20.852, 'train_steps_per_second': 20.852, 'train_loss': 3.18563623046875, 'epoch': 25.0}
{'train_runtime': 11.8065, 'train_samples_per_second': 21.175, 'train_steps_per_second': 21.175, 'train_loss': 3.2095654296875, 'epoch': 25.0}
{'train_runtime': 11.8621, 'train_samples_per_second': 21.075, 'train_steps_per_second': 21.075, 'train_loss': 3.208120361328125, 'epoch': 25.0}
{'train_runtime': 11.7689, 'train_samples_per_second': 21.242, 'train_steps_per_second': 21.242, 'train_loss': 3.208700439453125, 'epoch': 25.0}
{'train_runtime': 12.1707, 'train_samples_per_second': 20.541, 'train_steps_per_second': 20.541, 'train_loss': 3.236219482421875, 'epoch': 25.0}
{'train_runtime': 12.1236, 'train_samples_per_second': 20.621, 'train_steps_per_second': 20.621, 'train_loss': 3.204198486328125, 'epoch': 25.0}
{'train_runtime': 12.0887, 'train_samples_per_second': 20.68, 'train_steps_per_second': 20.68, 'train_loss': 3.218313720703125, 'epoch': 25.0}
{'train_runtime': 12.1777, 'train_samples_per_second': 20.529, 'train_steps_per_second': 20.529, 'train_loss': 3.18921630859375, 'epoch': 25.0}
{'train_runtime': 11.9586, 'train_samples_per_second': 20.905, 'train_steps_per_second': 20.905, 'train_loss': 3.22330078125, 'epoch': 25.0}
{'train_runtime': 11.8779, 'train_samples_per_second': 21.047, 'train_steps_per_second': 21.047, 'train_loss': 3.235342529296875, 'epoch': 25.0}
{'train_runtime': 11.958, 'train_samples_per_second': 20.906, 'train_steps_per_second': 20.906, 'train_loss': 3.221808837890625, 'epoch': 25.0}
{'train_runtime': 11.9167, 'train_samples_per_second': 20.979, 'train_steps_per_second': 20.979, 'train_loss': 3.226090087890625, 'epoch': 25.0}
{'train_runtime': 12.0225, 'train_samples_per_second': 20.794, 'train_steps_per_second': 20.794, 'train_loss': 3.23064208984375, 'epoch': 25.0}
{'train_runtime': 11.9761, 'train_samples_per_second': 20.875, 'train_steps_per_second': 20.875, 'train_loss': 3.255900634765625, 'epoch': 25.0}
{'train_runtime': 12.1542, 'train_samples_per_second': 20.569, 'train_steps_per_second': 20.569, 'train_loss': 3.230690673828125, 'epoch': 25.0}
{'train_runtime': 11.7586, 'train_samples_per_second': 21.261, 'train_steps_per_second': 21.261, 'train_loss': 3.2154423828125, 'epoch': 25.0}
{'train_runtime': 11.7535, 'train_samples_per_second': 21.27, 'train_steps_per_second': 21.27, 'train_loss': 3.196497802734375, 'epoch': 25.0}
{'train_runtime': 11.7768, 'train_samples_per_second': 21.228, 'train_steps_per_second': 21.228, 'train_loss': 3.217047607421875, 'epoch': 25.0}
{'train_runtime': 10.0977, 'train_samples_per_second': 24.758, 'train_steps_per_second': 24.758, 'train_loss': 2.970144775390625, 'epoch': 25.0}
{'train_runtime': 9.9536, 'train_samples_per_second': 25.117, 'train_steps_per_second': 25.117, 'train_loss': 2.88819140625, 'epoch': 25.0}
{'train_runtime': 9.7707, 'train_samples_per_second': 25.587, 'train_steps_per_second': 25.587, 'train_loss': 2.93044287109375, 'epoch': 25.0}
{'train_runtime': 9.7633, 'train_samples_per_second': 25.606, 'train_steps_per_second': 25.606, 'train_loss': 2.917362060546875, 'epoch': 25.0}
{'train_runtime': 9.9841, 'train_samples_per_second': 25.04, 'train_steps_per_second': 25.04, 'train_loss': 2.9138564453125, 'epoch': 25.0}
{'train_runtime': 9.7617, 'train_samples_per_second': 25.61, 'train_steps_per_second': 25.61, 'train_loss': 2.88103271484375, 'epoch': 25.0}
{'train_runtime': 9.8647, 'train_samples_per_second': 25.343, 'train_steps_per_second': 25.343, 'train_loss': 2.914327392578125, 'epoch': 25.0}
{'train_runtime': 9.8209, 'train_samples_per_second': 25.456, 'train_steps_per_second': 25.456, 'train_loss': 2.946004150390625, 'epoch': 25.0}
{'train_runtime': 9.7575, 'train_samples_per_second': 25.621, 'train_steps_per_second': 25.621, 'train_loss': 2.95187841796875, 'epoch': 25.0}
{'train_runtime': 9.7881, 'train_samples_per_second': 25.541, 'train_steps_per_second': 25.541, 'train_loss': 2.8996240234375, 'epoch': 25.0}
{'train_runtime': 10.0167, 'train_samples_per_second': 24.958, 'train_steps_per_second': 24.958, 'train_loss': 2.934905517578125, 'epoch': 25.0}
{'train_runtime': 9.891, 'train_samples_per_second': 25.276, 'train_steps_per_second': 25.276, 'train_loss': 2.947686279296875, 'epoch': 25.0}
{'train_runtime': 9.7813, 'train_samples_per_second': 25.559, 'train_steps_per_second': 25.559, 'train_loss': 2.90969921875, 'epoch': 25.0}
{'train_runtime': 9.862, 'train_samples_per_second': 25.35, 'train_steps_per_second': 25.35, 'train_loss': 2.920123291015625, 'epoch': 25.0}
{'train_runtime': 9.8487, 'train_samples_per_second': 25.384, 'train_steps_per_second': 25.384, 'train_loss': 2.914232421875, 'epoch': 25.0}
{'train_runtime': 9.8325, 'train_samples_per_second': 25.426, 'train_steps_per_second': 25.426, 'train_loss': 2.88895947265625, 'epoch': 25.0}
{'train_runtime': 9.9101, 'train_samples_per_second': 25.227, 'train_steps_per_second': 25.227, 'train_loss': 2.921782958984375, 'epoch': 25.0}
{'train_runtime': 9.9838, 'train_samples_per_second': 25.041, 'train_steps_per_second': 25.041, 'train_loss': 2.901605224609375, 'epoch': 25.0}
{'train_runtime': 9.8669, 'train_samples_per_second': 25.337, 'train_steps_per_second': 25.337, 'train_loss': 2.920961181640625, 'epoch': 25.0}
{'train_runtime': 9.8952, 'train_samples_per_second': 25.265, 'train_steps_per_second': 25.265, 'train_loss': 2.924073974609375, 'epoch': 25.0}
{'train_runtime': 10.0292, 'train_samples_per_second': 24.927, 'train_steps_per_second': 24.927, 'train_loss': 2.966249267578125, 'epoch': 25.0}
{'train_runtime': 9.9853, 'train_samples_per_second': 25.037, 'train_steps_per_second': 25.037, 'train_loss': 2.919676513671875, 'epoch': 25.0}
{'train_runtime': 9.8933, 'train_samples_per_second': 25.27, 'train_steps_per_second': 25.27, 'train_loss': 2.90576318359375, 'epoch': 25.0}
{'train_runtime': 9.9108, 'train_samples_per_second': 25.225, 'train_steps_per_second': 25.225, 'train_loss': 2.91701171875, 'epoch': 25.0}
{'train_runtime': 10.0308, 'train_samples_per_second': 24.923, 'train_steps_per_second': 24.923, 'train_loss': 2.915376953125, 'epoch': 25.0}
{'train_runtime': 15.1834, 'train_samples_per_second': 16.465, 'train_steps_per_second': 16.465, 'train_loss': 2.709385986328125, 'epoch': 25.0}

Explanations:  65%|██████▍   | 906/1400 [51:21<43:54,  5.33s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  65%|██████▍   | 907/1400 [51:22<34:25,  4.19s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  65%|██████▍   | 908/1400 [51:24<27:31,  3.36s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 11.3487, 'train_samples_per_second': 22.029, 'train_steps_per_second': 22.029, 'train_loss': 3.07425537109375, 'epoch': 25.0}
{'train_runtime': 11.2983, 'train_samples_per_second': 22.127, 'train_steps_per_second': 22.127, 'train_loss': 3.0620224609375, 'epoch': 25.0}
{'train_runtime': 11.5145, 'train_samples_per_second': 21.712, 'train_steps_per_second': 21.712, 'train_loss': 3.039755126953125, 'epoch': 25.0}
{'train_runtime': 11.6085, 'train_samples_per_second': 21.536, 'train_steps_per_second': 21.536, 'train_loss': 3.07591357421875, 'epoch': 25.0}
{'train_runtime': 11.4889, 'train_samples_per_second': 21.76, 'train_steps_per_second': 21.76, 'train_loss': 3.092337646484375, 'epoch': 25.0}
{'train_runtime': 12.1648, 'train_samples_per_second': 20.551, 'train_steps_per_second': 20.551, 'train_loss': 3.217378173828125, 'epoch': 25.0}
{'train_runtime': 12.1474, 'train_samples_per_second': 20.581, 'train_steps_per_second': 20.581, 'train_loss': 3.2131201171875, 'epoch': 25.0}
{'train_runtime': 12.0462, 'train_samples_per_second': 20.753, 'train_steps_per_second': 20.753, 'train_loss': 3.212411865234375, 'epoch': 25.0}
{'train_runtime': 12.0908, 'train_samples_per_second': 20.677, 'train_steps_per_second': 20.677, 'train_loss': 3.22190966796875, 'epoch': 25.0}
{'train_runtime': 12.4241, 'train_samples_per_second': 20.122, 'train_steps_per_second': 20.122, 'train_loss': 3.201212890625, 'epoch': 25.0}
{'train_runtime': 11.8137, 'train_samples_per_second': 21.162, 'train_steps_per_second': 21.162, 'train_loss': 3.219495361328125, 'epoch': 25.0}
{'train_runtime': 11.9544, 'train_samples_per_second': 20.913, 'train_steps_per_second': 20.913, 'train_loss': 3.248207275390625, 'epoch': 25.0}
{'train_runtime': 11.8348, 'train_samples_per_second': 21.124, 'train_steps_per_second': 21.124, 'train_loss': 3.22917431640625, 'epoch': 25.0}
{'train_runtime': 11.9532, 'train_samples_per_second': 20.915, 'train_steps_per_second': 20.915, 'train_loss': 3.2301220703125, 'epoch': 25.0}
{'train_runtime': 11.911, 'train_samples_per_second': 20.989, 'train_steps_per_second': 20.989, 'train_loss': 3.212131103515625, 'epoch': 25.0}
{'train_runtime': 11.9229, 'train_samples_per_second': 20.968, 'train_steps_per_second': 20.968, 'train_loss': 3.21501806640625, 'epoch': 25.0}
{'train_runtime': 12.156, 'train_samples_per_second': 20.566, 'train_steps_per_second': 20.566, 'train_loss': 3.20910546875, 'epoch': 25.0}
{'train_runtime': 12.2031, 'train_samples_per_second': 20.487, 'train_steps_per_second': 20.487, 'train_loss': 3.221327880859375, 'epoch': 25.0}
{'train_runtime': 12.2506, 'train_samples_per_second': 20.407, 'train_steps_per_second': 20.407, 'train_loss': 3.212365234375, 'epoch': 25.0}
{'train_runtime': 12.163, 'train_samples_per_second': 20.554, 'train_steps_per_second': 20.554, 'train_loss': 3.213763671875, 'epoch': 25.0}
{'train_runtime': 12.0889, 'train_samples_per_second': 20.68, 'train_steps_per_second': 20.68, 'train_loss': 3.206093994140625, 'epoch': 25.0}
{'train_runtime': 11.96, 'train_samples_per_second': 20.903, 'train_steps_per_second': 20.903, 'train_loss': 3.21966650390625, 'epoch': 25.0}
{'train_runtime': 12.1727, 'train_samples_per_second': 20.538, 'train_steps_per_second': 20.538, 'train_loss': 3.209600830078125, 'epoch': 25.0}
{'train_runtime': 11.8366, 'train_samples_per_second': 21.121, 'train_steps_per_second': 21.121, 'train_loss': 3.20884521484375, 'epoch': 25.0}
{'train_runtime': 11.9648, 'train_samples_per_second': 20.895, 'train_steps_per_second': 20.895, 'train_loss': 3.239041259765625, 'epoch': 25.0}
{'train_runtime': 11.9456, 'train_samples_per_second': 20.928, 'train_steps_per_second': 20.928, 'train_loss': 3.18934765625, 'epoch': 25.0}
{'train_runtime': 11.8669, 'train_samples_per_second': 21.067, 'train_steps_per_second': 21.067, 'train_loss': 3.2386201171875, 'epoch': 25.0}
{'train_runtime': 11.7267, 'train_samples_per_second': 21.319, 'train_steps_per_second': 21.319, 'train_loss': 3.218927490234375, 'epoch': 25.0}
{'train_runtime': 11.7894, 'train_samples_per_second': 21.206, 'train_steps_per_second': 21.206, 'train_loss': 3.230065673828125, 'epoch': 25.0}
{'train_runtime': 11.7673, 'train_samples_per_second': 21.245, 'train_steps_per_second': 21.245, 'train_loss': 3.222199951171875, 'epoch': 25.0}
{'train_runtime': 10.1528, 'train_samples_per_second': 24.624, 'train_steps_per_second': 24.624, 'train_loss': 2.932552734375, 'epoch': 25.0}
{'train_runtime': 9.8461, 'train_samples_per_second': 25.391, 'train_steps_per_second': 25.391, 'train_loss': 2.899831298828125, 'epoch': 25.0}
{'train_runtime': 9.7231, 'train_samples_per_second': 25.712, 'train_steps_per_second': 25.712, 'train_loss': 2.874141845703125, 'epoch': 25.0}
{'train_runtime': 9.6812, 'train_samples_per_second': 25.823, 'train_steps_per_second': 25.823, 'train_loss': 2.941276611328125, 'epoch': 25.0}
{'train_runtime': 9.7502, 'train_samples_per_second': 25.64, 'train_steps_per_second': 25.64, 'train_loss': 2.9047978515625, 'epoch': 25.0}
{'train_runtime': 9.7055, 'train_samples_per_second': 25.759, 'train_steps_per_second': 25.759, 'train_loss': 2.9441611328125, 'epoch': 25.0}
{'train_runtime': 9.7621, 'train_samples_per_second': 25.609, 'train_steps_per_second': 25.609, 'train_loss': 2.904179443359375, 'epoch': 25.0}
{'train_runtime': 9.8857, 'train_samples_per_second': 25.289, 'train_steps_per_second': 25.289, 'train_loss': 2.966566162109375, 'epoch': 25.0}
{'train_runtime': 9.5772, 'train_samples_per_second': 26.104, 'train_steps_per_second': 26.104, 'train_loss': 2.91075830078125, 'epoch': 25.0}
{'train_runtime': 9.7619, 'train_samples_per_second': 25.61, 'train_steps_per_second': 25.61, 'train_loss': 2.9213876953125, 'epoch': 25.0}
{'train_runtime': 9.7531, 'train_samples_per_second': 25.633, 'train_steps_per_second': 25.633, 'train_loss': 2.878171875, 'epoch': 25.0}
{'train_runtime': 9.7384, 'train_samples_per_second': 25.672, 'train_steps_per_second': 25.672, 'train_loss': 2.911682373046875, 'epoch': 25.0}
{'train_runtime': 9.6016, 'train_samples_per_second': 26.037, 'train_steps_per_second': 26.037, 'train_loss': 2.9135732421875, 'epoch': 25.0}
{'train_runtime': 9.7307, 'train_samples_per_second': 25.692, 'train_steps_per_second': 25.692, 'train_loss': 2.914789306640625, 'epoch': 25.0}
{'train_runtime': 9.7271, 'train_samples_per_second': 25.701, 'train_steps_per_second': 25.701, 'train_loss': 2.94225439453125, 'epoch': 25.0}
{'train_runtime': 9.6354, 'train_samples_per_second': 25.946, 'train_steps_per_second': 25.946, 'train_loss': 2.926712158203125, 'epoch': 25.0}
{'train_runtime': 9.7795, 'train_samples_per_second': 25.564, 'train_steps_per_second': 25.564, 'train_loss': 2.958007568359375, 'epoch': 25.0}
{'train_runtime': 9.769, 'train_samples_per_second': 25.591, 'train_steps_per_second': 25.591, 'train_loss': 2.93252490234375, 'epoch': 25.0}
{'train_runtime': 9.6831, 'train_samples_per_second': 25.818, 'train_steps_per_second': 25.818, 'train_loss': 2.92126806640625, 'epoch': 25.0}
{'train_runtime': 9.673, 'train_samples_per_second': 25.845, 'train_steps_per_second': 25.845, 'train_loss': 2.900537353515625, 'epoch': 25.0}
{'train_runtime': 9.7273, 'train_samples_per_second': 25.701, 'train_steps_per_second': 25.701, 'train_loss': 2.91248486328125, 'epoch': 25.0}
{'train_runtime': 9.69, 'train_samples_per_second': 25.8, 'train_steps_per_second': 25.8, 'train_loss': 2.89920068359375, 'epoch': 25.0}
{'train_runtime': 9.6483, 'train_samples_per_second': 25.911, 'train_steps_per_second': 25.911, 'train_loss': 2.90837353515625, 'epoch': 25.0}
{'train_runtime': 9.8163, 'train_samples_per_second': 25.468, 'train_steps_per_second': 25.468, 'train_loss': 2.89400341796875, 'epoch': 25.0}
{'train_runtime': 9.7825, 'train_samples_per_second': 25.556, 'train_steps_per_second': 25.556, 'train_loss': 2.912220947265625, 'epoch': 25.0}
{'train_runtime': 13.071, 'train_samples_per_second': 19.126, 'train_steps_per_second': 19.126, 'train_loss': 2.714699462890625, 'epoch': 25.0}
{'train_runtime': 14.9844, 'train_samples_per_second': 16.684, 'train_steps_per_second': 16.684, 'train_loss': 2.709972412109375, 'epoch': 25.0}

Explanations:  65%|██████▍   | 909/1400 [51:29<33:22,  4.08s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  65%|██████▌   | 910/1400 [51:38<44:32,  5.45s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 11.7081, 'train_samples_per_second': 21.353, 'train_steps_per_second': 21.353, 'train_loss': 3.09720654296875, 'epoch': 25.0}
{'train_runtime': 11.7358, 'train_samples_per_second': 21.302, 'train_steps_per_second': 21.302, 'train_loss': 3.04507861328125, 'epoch': 25.0}
{'train_runtime': 11.6412, 'train_samples_per_second': 21.475, 'train_steps_per_second': 21.475, 'train_loss': 3.066880615234375, 'epoch': 25.0}
{'train_runtime': 11.6341, 'train_samples_per_second': 21.489, 'train_steps_per_second': 21.489, 'train_loss': 3.06765234375, 'epoch': 25.0}
{'train_runtime': 11.7014, 'train_samples_per_second': 21.365, 'train_steps_per_second': 21.365, 'train_loss': 3.083788330078125, 'epoch': 25.0}
{'train_runtime': 12.1561, 'train_samples_per_second': 20.566, 'train_steps_per_second': 20.566, 'train_loss': 3.2061708984375, 'epoch': 25.0}
{'train_runtime': 12.0192, 'train_samples_per_second': 20.8, 'train_steps_per_second': 20.8, 'train_loss': 3.193408203125, 'epoch': 25.0}
{'train_runtime': 12.1658, 'train_samples_per_second': 20.549, 'train_steps_per_second': 20.549, 'train_loss': 3.221457763671875, 'epoch': 25.0}
{'train_runtime': 12.2354, 'train_samples_per_second': 20.433, 'train_steps_per_second': 20.433, 'train_loss': 3.21898876953125, 'epoch': 25.0}
{'train_runtime': 12.0927, 'train_samples_per_second': 20.674, 'train_steps_per_second': 20.674, 'train_loss': 3.1963154296875, 'epoch': 25.0}
{'train_runtime': 12.0907, 'train_samples_per_second': 20.677, 'train_steps_per_second': 20.677, 'train_loss': 3.218404541015625, 'epoch': 25.0}
{'train_runtime': 12.2318, 'train_samples_per_second': 20.439, 'train_steps_per_second': 20.439, 'train_loss': 3.20988720703125, 'epoch': 25.0}
{'train_runtime': 11.9907, 'train_samples_per_second': 20.849, 'train_steps_per_second': 20.849, 'train_loss': 3.242845703125, 'epoch': 25.0}
{'train_runtime': 12.0291, 'train_samples_per_second': 20.783, 'train_steps_per_second': 20.783, 'train_loss': 3.22166845703125, 'epoch': 25.0}
{'train_runtime': 11.8114, 'train_samples_per_second': 21.166, 'train_steps_per_second': 21.166, 'train_loss': 3.1900263671875, 'epoch': 25.0}
{'train_runtime': 11.602, 'train_samples_per_second': 21.548, 'train_steps_per_second': 21.548, 'train_loss': 3.230615966796875, 'epoch': 25.0}
{'train_runtime': 11.5397, 'train_samples_per_second': 21.664, 'train_steps_per_second': 21.664, 'train_loss': 3.24259765625, 'epoch': 25.0}
{'train_runtime': 11.8066, 'train_samples_per_second': 21.175, 'train_steps_per_second': 21.175, 'train_loss': 3.22123974609375, 'epoch': 25.0}
{'train_runtime': 11.8608, 'train_samples_per_second': 21.078, 'train_steps_per_second': 21.078, 'train_loss': 3.211516357421875, 'epoch': 25.0}
{'train_runtime': 11.4351, 'train_samples_per_second': 21.862, 'train_steps_per_second': 21.862, 'train_loss': 3.21867724609375, 'epoch': 25.0}
{'train_runtime': 11.6265, 'train_samples_per_second': 21.503, 'train_steps_per_second': 21.503, 'train_loss': 3.2150166015625, 'epoch': 25.0}
{'train_runtime': 11.6969, 'train_samples_per_second': 21.373, 'train_steps_per_second': 21.373, 'train_loss': 3.2012177734375, 'epoch': 25.0}
{'train_runtime': 11.7983, 'train_samples_per_second': 21.189, 'train_steps_per_second': 21.189, 'train_loss': 3.222271728515625, 'epoch': 25.0}
{'train_runtime': 11.7393, 'train_samples_per_second': 21.296, 'train_steps_per_second': 21.296, 'train_loss': 3.253407470703125, 'epoch': 25.0}
{'train_runtime': 11.6959, 'train_samples_per_second': 21.375, 'train_steps_per_second': 21.375, 'train_loss': 3.205100341796875, 'epoch': 25.0}
{'train_runtime': 11.8066, 'train_samples_per_second': 21.175, 'train_steps_per_second': 21.175, 'train_loss': 3.200709228515625, 'epoch': 25.0}
{'train_runtime': 11.5822, 'train_samples_per_second': 21.585, 'train_steps_per_second': 21.585, 'train_loss': 3.20599609375, 'epoch': 25.0}
{'train_runtime': 11.7962, 'train_samples_per_second': 21.193, 'train_steps_per_second': 21.193, 'train_loss': 3.221939208984375, 'epoch': 25.0}
{'train_runtime': 11.7134, 'train_samples_per_second': 21.343, 'train_steps_per_second': 21.343, 'train_loss': 3.222471923828125, 'epoch': 25.0}
{'train_runtime': 11.4852, 'train_samples_per_second': 21.767, 'train_steps_per_second': 21.767, 'train_loss': 3.208121826171875, 'epoch': 25.0}
{'train_runtime': 9.7321, 'train_samples_per_second': 25.688, 'train_steps_per_second': 25.688, 'train_loss': 2.932212890625, 'epoch': 25.0}
{'train_runtime': 9.6981, 'train_samples_per_second': 25.778, 'train_steps_per_second': 25.778, 'train_loss': 2.932715087890625, 'epoch': 25.0}
{'train_runtime': 9.6128, 'train_samples_per_second': 26.007, 'train_steps_per_second': 26.007, 'train_loss': 2.934189453125, 'epoch': 25.0}
{'train_runtime': 9.6819, 'train_samples_per_second': 25.821, 'train_steps_per_second': 25.821, 'train_loss': 2.9207529296875, 'epoch': 25.0}
{'train_runtime': 9.7827, 'train_samples_per_second': 25.555, 'train_steps_per_second': 25.555, 'train_loss': 2.89373291015625, 'epoch': 25.0}
{'train_runtime': 9.6538, 'train_samples_per_second': 25.897, 'train_steps_per_second': 25.897, 'train_loss': 2.938745849609375, 'epoch': 25.0}
{'train_runtime': 9.9739, 'train_samples_per_second': 25.065, 'train_steps_per_second': 25.065, 'train_loss': 2.927225341796875, 'epoch': 25.0}
{'train_runtime': 9.8144, 'train_samples_per_second': 25.473, 'train_steps_per_second': 25.473, 'train_loss': 2.90721923828125, 'epoch': 25.0}
{'train_runtime': 9.7456, 'train_samples_per_second': 25.653, 'train_steps_per_second': 25.653, 'train_loss': 2.895723876953125, 'epoch': 25.0}
{'train_runtime': 9.7956, 'train_samples_per_second': 25.522, 'train_steps_per_second': 25.522, 'train_loss': 2.935501220703125, 'epoch': 25.0}
{'train_runtime': 9.9495, 'train_samples_per_second': 25.127, 'train_steps_per_second': 25.127, 'train_loss': 2.905042236328125, 'epoch': 25.0}
{'train_runtime': 9.9561, 'train_samples_per_second': 25.11, 'train_steps_per_second': 25.11, 'train_loss': 2.918314208984375, 'epoch': 25.0}
{'train_runtime': 9.7771, 'train_samples_per_second': 25.57, 'train_steps_per_second': 25.57, 'train_loss': 2.912385986328125, 'epoch': 25.0}
{'train_runtime': 9.8369, 'train_samples_per_second': 25.414, 'train_steps_per_second': 25.414, 'train_loss': 2.943123779296875, 'epoch': 25.0}
{'train_runtime': 9.8906, 'train_samples_per_second': 25.276, 'train_steps_per_second': 25.276, 'train_loss': 2.928843017578125, 'epoch': 25.0}
{'train_runtime': 9.8708, 'train_samples_per_second': 25.327, 'train_steps_per_second': 25.327, 'train_loss': 2.949260009765625, 'epoch': 25.0}
{'train_runtime': 9.8868, 'train_samples_per_second': 25.286, 'train_steps_per_second': 25.286, 'train_loss': 2.938625244140625, 'epoch': 25.0}
{'train_runtime': 9.9985, 'train_samples_per_second': 25.004, 'train_steps_per_second': 25.004, 'train_loss': 2.91766845703125, 'epoch': 25.0}
{'train_runtime': 9.9338, 'train_samples_per_second': 25.167, 'train_steps_per_second': 25.167, 'train_loss': 2.890701904296875, 'epoch': 25.0}
{'train_runtime': 10.0359, 'train_samples_per_second': 24.911, 'train_steps_per_second': 24.911, 'train_loss': 2.890383056640625, 'epoch': 25.0}
{'train_runtime': 9.9458, 'train_samples_per_second': 25.136, 'train_steps_per_second': 25.136, 'train_loss': 2.945228271484375, 'epoch': 25.0}
{'train_runtime': 10.2073, 'train_samples_per_second': 24.492, 'train_steps_per_second': 24.492, 'train_loss': 2.91837158203125, 'epoch': 25.0}
{'train_runtime': 10.0473, 'train_samples_per_second': 24.882, 'train_steps_per_second': 24.882, 'train_loss': 2.960850830078125, 'epoch': 25.0}
{'train_runtime': 9.9021, 'train_samples_per_second': 25.247, 'train_steps_per_second': 25.247, 'train_loss': 2.93371142578125, 'epoch': 25.0}
{'train_runtime': 10.2714, 'train_samples_per_second': 24.339, 'train_steps_per_second': 24.339, 'train_loss': 2.89006884765625, 'epoch': 25.0}
{'train_runtime': 15.5315, 'train_samples_per_second': 16.096, 'train_steps_per_second': 16.096, 'train_loss': 2.7008798828125, 'epoch': 25.0}
{'train_runtime': 15.5597, 'train_samples_per_second': 16.067, 'train_steps_per_second': 16.067, 'train_loss': 2.72970068359375, 'epoch': 25.0}

Explanations:  65%|██████▌   | 911/1400 [51:40<35:40,  4.38s/it]

{'train_runtime': 11.6467, 'train_samples_per_second': 21.465, 'train_steps_per_second': 21.465, 'train_loss': 3.06654638671875, 'epoch': 25.0}
{'train_runtime': 11.4947, 'train_samples_per_second': 21.749, 'train_steps_per_second': 21.749, 'train_loss': 3.072952392578125, 'epoch': 25.0}
{'train_runtime': 11.6633, 'train_samples_per_second': 21.435, 'train_steps_per_second': 21.435, 'train_loss': 3.062618896484375, 'epoch': 25.0}
{'train_runtime': 11.6987, 'train_samples_per_second': 21.37, 'train_steps_per_second': 21.37, 'train_loss': 3.057624755859375, 'epoch': 25.0}
{'train_runtime': 11.7064, 'train_samples_per_second': 21.356, 'train_steps_per_second': 21.356, 'train_loss': 3.07493017578125, 'epoch': 25.0}
{'train_runtime': 12.0505, 'train_samples_per_second': 20.746, 'train_steps_per_second': 20.746, 'train_loss': 3.227962890625, 'epoch': 25.0}
{'train_runtime': 12.1231, 'train_samples_per_second': 20.622, 'train_steps_per_second': 20.622, 'train_loss': 3.194049560546875, 'epoch': 25.0}
{'train_runtime': 12.1244, 'train_samples_per_second': 20.62, 'train_steps_per_second': 20.62, 'train_loss': 3.20493017578125, 'epoch': 25.0}
{'train_runtime': 12.2993, 'train_samples_per_second': 20.326, 'train_steps_per_second': 20.326, 'train_loss': 3.228697265625, 'epoch': 25.0}
{'train_runtime': 11.9469, 'train_samples_per_second': 20.926, 'train_steps_per_second': 20.926, 'train_loss': 3.232230224609375, 'epoch': 25.0}
{'train_runtime': 12.0123, 'train_samples_per_second': 20.812, 'train_steps_per_second': 20.812, 'train_loss': 3.221500732421875, 'epoch': 25.0}
{'train_runtime': 12.1309, 'train_samples_per_second': 20.609, 'train_steps_per_second': 20.609, 'train_loss': 3.2167705078125, 'epoch': 25.0}
{'train_runtime': 12.1607, 'train_samples_per_second': 20.558, 'train_steps_per_second': 20.558, 'train_loss': 3.222973876953125, 'epoch': 25.0}
{'train_runtime': 12.1161, 'train_samples_per_second': 20.634, 'train_steps_per_second': 20.634, 'train_loss': 3.2281337890625, 'epoch': 25.0}
{'train_runtime': 12.9877, 'train_samples_per_second': 19.249, 'train_steps_per_second': 19.249, 'train_loss': 3.216356201171875, 'epoch': 25.0}
{'train_runtime': 12.1538, 'train_samples_per_second': 20.57, 'train_steps_per_second': 20.57, 'train_loss': 3.24770947265625, 'epoch': 25.0}
{'train_runtime': 12.1683, 'train_samples_per_second': 20.545, 'train_steps_per_second': 20.545, 'train_loss': 3.210565673828125, 'epoch': 25.0}
{'train_runtime': 12.0989, 'train_samples_per_second': 20.663, 'train_steps_per_second': 20.663, 'train_loss': 3.2429482421875, 'epoch': 25.0}
{'train_runtime': 11.9109, 'train_samples_per_second': 20.989, 'train_steps_per_second': 20.989, 'train_loss': 3.2094443359375, 'epoch': 25.0}
{'train_runtime': 11.9184, 'train_samples_per_second': 20.976, 'train_steps_per_second': 20.976, 'train_loss': 3.212224609375, 'epoch': 25.0}
{'train_runtime': 11.8224, 'train_samples_per_second': 21.146, 'train_steps_per_second': 21.146, 'train_loss': 3.186646484375, 'epoch': 25.0}
{'train_runtime': 11.7578, 'train_samples_per_second': 21.262, 'train_steps_per_second': 21.262, 'train_loss': 3.19505810546875, 'epoch': 25.0}
{'train_runtime': 11.7791, 'train_samples_per_second': 21.224, 'train_steps_per_second': 21.224, 'train_loss': 3.219537841796875, 'epoch': 25.0}
{'train_runtime': 11.6042, 'train_samples_per_second': 21.544, 'train_steps_per_second': 21.544, 'train_loss': 3.222947509765625, 'epoch': 25.0}
{'train_runtime': 11.5883, 'train_samples_per_second': 21.573, 'train_steps_per_second': 21.573, 'train_loss': 3.2038447265625, 'epoch': 25.0}
{'train_runtime': 11.6119, 'train_samples_per_second': 21.53, 'train_steps_per_second': 21.53, 'train_loss': 3.194806884765625, 'epoch': 25.0}
{'train_runtime': 11.6368, 'train_samples_per_second': 21.484, 'train_steps_per_second': 21.484, 'train_loss': 3.207092529296875, 'epoch': 25.0}
{'train_runtime': 11.731, 'train_samples_per_second': 21.311, 'train_steps_per_second': 21.311, 'train_loss': 3.224723388671875, 'epoch': 25.0}
{'train_runtime': 11.5979, 'train_samples_per_second': 21.556, 'train_steps_per_second': 21.556, 'train_loss': 3.2488701171875, 'epoch': 25.0}
{'train_runtime': 10.9711, 'train_samples_per_second': 22.787, 'train_steps_per_second': 22.787, 'train_loss': 3.223373291015625, 'epoch': 25.0}
{'train_runtime': 9.6356, 'train_samples_per_second': 25.945, 'train_steps_per_second': 25.945, 'train_loss': 2.91686962890625, 'epoch': 25.0}
{'train_runtime': 9.7419, 'train_samples_per_second': 25.662, 'train_steps_per_second': 25.662, 'train_loss': 2.922279052734375, 'epoch': 25.0}
{'train_runtime': 9.7027, 'train_samples_per_second': 25.766, 'train_steps_per_second': 25.766, 'train_loss': 2.897057373046875, 'epoch': 25.0}
{'train_runtime': 9.7895, 'train_samples_per_second': 25.537, 'train_steps_per_second': 25.537, 'train_loss': 2.9576943359375, 'epoch': 25.0}
{'train_runtime': 9.705, 'train_samples_per_second': 25.76, 'train_steps_per_second': 25.76, 'train_loss': 2.921153076171875, 'epoch': 25.0}
{'train_runtime': 9.6712, 'train_samples_per_second': 25.85, 'train_steps_per_second': 25.85, 'train_loss': 2.914103271484375, 'epoch': 25.0}
{'train_runtime': 9.8159, 'train_samples_per_second': 25.469, 'train_steps_per_second': 25.469, 'train_loss': 2.9275166015625, 'epoch': 25.0}
{'train_runtime': 9.6934, 'train_samples_per_second': 25.791, 'train_steps_per_second': 25.791, 'train_loss': 2.90354443359375, 'epoch': 25.0}
{'train_runtime': 9.7272, 'train_samples_per_second': 25.701, 'train_steps_per_second': 25.701, 'train_loss': 2.90565478515625, 'epoch': 25.0}
{'train_runtime': 9.719, 'train_samples_per_second': 25.723, 'train_steps_per_second': 25.723, 'train_loss': 2.971996826171875, 'epoch': 25.0}
{'train_runtime': 9.5935, 'train_samples_per_second': 26.059, 'train_steps_per_second': 26.059, 'train_loss': 2.922531982421875, 'epoch': 25.0}
{'train_runtime': 9.8782, 'train_samples_per_second': 25.308, 'train_steps_per_second': 25.308, 'train_loss': 2.894423583984375, 'epoch': 25.0}
{'train_runtime': 9.6824, 'train_samples_per_second': 25.82, 'train_steps_per_second': 25.82, 'train_loss': 2.886712646484375, 'epoch': 25.0}
{'train_runtime': 9.6451, 'train_samples_per_second': 25.92, 'train_steps_per_second': 25.92, 'train_loss': 2.929974609375, 'epoch': 25.0}
{'train_runtime': 9.7831, 'train_samples_per_second': 25.554, 'train_steps_per_second': 25.554, 'train_loss': 2.9243955078125, 'epoch': 25.0}
{'train_runtime': 9.948, 'train_samples_per_second': 25.131, 'train_steps_per_second': 25.131, 'train_loss': 2.906937744140625, 'epoch': 25.0}
{'train_runtime': 9.607, 'train_samples_per_second': 26.023, 'train_steps_per_second': 26.023, 'train_loss': 2.896575927734375, 'epoch': 25.0}
{'train_runtime': 9.7466, 'train_samples_per_second': 25.65, 'train_steps_per_second': 25.65, 'train_loss': 2.92377490234375, 'epoch': 25.0}
{'train_runtime': 9.808, 'train_samples_per_second': 25.489, 'train_steps_per_second': 25.489, 'train_loss': 2.9220556640625, 'epoch': 25.0}
{'train_runtime': 9.7447, 'train_samples_per_second': 25.655, 'train_steps_per_second': 25.655, 'train_loss': 2.962552490234375, 'epoch': 25.0}
{'train_runtime': 9.8268, 'train_samples_per_second': 25.441, 'train_steps_per_second': 25.441, 'train_loss': 2.930462158203125, 'epoch': 25.0}
{'train_runtime': 9.8018, 'train_samples_per_second': 25.506, 'train_steps_per_second': 25.506, 'train_loss': 2.91733447265625, 'epoch': 25.0}
{'train_runtime': 9.9732, 'train_samples_per_second': 25.067, 'train_steps_per_second': 25.067, 'train_loss': 2.922479736328125, 'epoch': 25.0}
{'train_runtime': 9.7917, 'train_samples_per_second': 25.532, 'train_steps_per_second': 25.532, 'train_loss': 2.931277099609375, 'epoch': 25.0}
{'train_runtime': 10.5915, 'train_samples_per_second': 23.604, 'train_steps_per_second': 23.604, 'train_loss': 2.89726123046875, 'epoch': 25.0}
{'train_runtime': 15.0937, 'train_samples_per_second': 16.563, 'train_steps_per_second': 16.563, 'train_loss': 2.696770263671875, 'epoch': 25.0}
{'train_runtime': 15.1576, 'train_samples_per_second': 16.493, 'train_steps_per_second': 16.493, 'train_loss': 2.6886826171875, 'epoch': 25.0}

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  65%|██████▌   | 912/1400 [51:41<27:54,  3.43s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  65%|██████▌   | 913/1400 [51:47<32:40,  4.03s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  65%|██████▌   | 914/1400 [51:55<44:22,  5.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  65%|██████▌   | 915/1400 [51:57<35:52,  4.44s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  65%|██████▌   | 916/1400 [51:58<27:40,  3.43s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  66%|██████▌   | 917/1400 [52:04<31:58,  3.97s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  66%|██████▌   | 918/1400 [52:13<44:22,  5.52s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  66%|██████▌   | 920/1400 [52:16<26:58,  3.37s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  66%|██████▌   | 921/1400 [52:21<30:43,  3.85s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  66%|██████▌   | 922/1400 [52:30<43:38,  5.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  66%|██████▌   | 924/1400 [52:33<27:02,  3.41s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  66%|██████▌   | 925/1400 [52:38<30:15,  3.82s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  66%|██████▌   | 926/1400 [52:47<42:20,  5.36s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  66%|██████▋   | 928/1400 [52:51<26:57,  3.43s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  66%|██████▋   | 929/1400 [52:55<29:25,  3.75s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  66%|██████▋   | 930/1400 [53:04<41:57,  5.36s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  67%|██████▋   | 932/1400 [53:08<27:23,  3.51s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  67%|██████▋   | 933/1400 [53:12<28:04,  3.61s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  67%|██████▋   | 934/1400 [53:21<41:25,  5.33s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  67%|██████▋   | 936/1400 [53:26<27:51,  3.60s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  67%|██████▋   | 937/1400 [53:29<26:49,  3.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  67%|██████▋   | 938/1400 [53:38<40:39,  5.28s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  67%|██████▋   | 940/1400 [53:43<28:05,  3.66s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  67%|██████▋   | 941/1400 [53:46<25:27,  3.33s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  67%|██████▋   | 942/1400 [53:56<40:31,  5.31s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  67%|██████▋   | 944/1400 [54:01<28:45,  3.78s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  68%|██████▊   | 945/1400 [54:03<23:51,  3.15s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  68%|██████▊   | 946/1400 [54:13<39:41,  5.25s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  68%|██████▊   | 948/1400 [54:19<29:07,  3.87s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  68%|██████▊   | 949/1400 [54:20<23:24,  3.11s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  68%|██████▊   | 950/1400 [54:30<38:39,  5.15s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  68%|██████▊   | 952/1400 [54:37<29:42,  3.98s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  68%|██████▊   | 953/1400 [54:38<23:24,  3.14s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  68%|██████▊   | 954/1400 [54:48<37:39,  5.07s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  68%|██████▊   | 955/1400 [54:53<39:24,  5.31s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  68%|██████▊   | 957/1400 [54:55<23:00,  3.12s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  68%|██████▊   | 958/1400 [55:05<36:12,  4.92s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  68%|██████▊   | 959/1400 [55:11<39:20,  5.35s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  69%|██████▊   | 961/1400 [55:13<22:45,  3.11s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  69%|██████▊   | 962/1400 [55:22<34:56,  4.79s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  69%|██████▉   | 963/1400 [55:28<39:09,  5.38s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  69%|██████▉   | 965/1400 [55:31<22:48,  3.15s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  69%|██████▉   | 966/1400 [55:39<33:34,  4.64s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  69%|██████▉   | 967/1400 [55:46<38:30,  5.34s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  69%|██████▉   | 969/1400 [55:48<23:11,  3.23s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  69%|██████▉   | 970/1400 [55:56<32:59,  4.60s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  69%|██████▉   | 971/1400 [56:03<37:07,  5.19s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  70%|██████▉   | 973/1400 [56:06<23:21,  3.28s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  70%|██████▉   | 974/1400 [56:13<31:31,  4.44s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  70%|██████▉   | 975/1400 [56:20<35:23,  5.00s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 14.8237, 'train_samples_per_second': 16.865, 'train_steps_per_second': 16.865, 'train_loss': 2.71568798828125, 'epoch': 25.0}
{'train_runtime': 15.0987, 'train_samples_per_second': 16.558, 'train_steps_per_second': 16.558, 'train_loss': 2.68516357421875, 'epoch': 25.0}
{'train_runtime': 14.9745, 'train_samples_per_second': 16.695, 'train_steps_per_second': 16.695, 'train_loss': 2.71068994140625, 'epoch': 25.0}
{'train_runtime': 14.8819, 'train_samples_per_second': 16.799, 'train_steps_per_second': 16.799, 'train_loss': 2.710223876953125, 'epoch': 25.0}
{'train_runtime': 15.0471, 'train_samples_per_second': 16.615, 'train_steps_per_second': 16.615, 'train_loss': 2.709482666015625, 'epoch': 25.0}
{'train_runtime': 14.7142, 'train_samples_per_second': 16.99, 'train_steps_per_second': 16.99, 'train_loss': 2.72569091796875, 'epoch': 25.0}
{'train_runtime': 14.8093, 'train_samples_per_second': 16.881, 'train_steps_per_second': 16.881, 'train_loss': 2.694169189453125, 'epoch': 25.0}
{'train_runtime': 14.9597, 'train_samples_per_second': 16.712, 'train_steps_per_second': 16.712, 'train_loss': 2.691377197265625, 'epoch': 25.0}
{'train_runtime': 14.9431, 'train_samples_per_second': 16.73, 'train_steps_per_second': 16.73, 'train_loss': 2.718110107421875, 'epoch': 25.0}
{'train_runtime': 14.8786, 'train_samples_per_second': 16.803, 'train_steps_per_second': 16.803, 'train_loss': 2.718658447265625, 'epoch': 25.0}
{'train_runtime': 15.3811, 'train_samples_per_second': 16.254, 'train_steps_per_second': 16.254, 'train_loss': 2.70116552734375, 'epoch': 25.0}
{'train_runtime': 15.4164, 'train_samples_per_second': 16.217, 'train_steps_per_second': 16.217, 'train_loss': 2.71046484375, 'epoch': 25.0}
{'train_runtime': 15.4192, 'train_samples_per_second': 16.214, 'train_steps_per_second': 16.214, 'train_loss': 2.71220458984375, 'epoch': 25.0}
{'train_runtime': 15.3965, 'train_samples_per_second': 16.237, 'train_steps_per_second': 16.237, 'train_loss': 2.703287353515625, 'epoch': 25.0}
{'train_runtime': 15.6403, 'train_samples_per_second': 15.984, 'train_steps_per_second': 15.984, 'train_loss': 2.714882080078125, 'epoch': 25.0}
{'train_runtime': 15.6299, 'train_samples_per_second': 15.995, 'train_steps_per_second': 15.995, 'train_loss': 2.71138818359375, 'epoch': 25.0}
{'train_runtime': 15.6527, 'train_samples_per_second': 15.972, 'train_steps_per_second': 15.972, 'train_loss': 2.6961279296875, 'epoch': 25.0}
{'train_runtime': 15.5811, 'train_samples_per_second': 16.045, 'train_steps_per_second': 16.045, 'train_loss': 2.67462744140625, 'epoch': 25.0}
{'train_runtime': 15.7138, 'train_samples_per_second': 15.91, 'train_steps_per_second': 15.91, 'train_loss': 2.707534423828125, 'epoch': 25.0}
{'train_runtime': 15.5564, 'train_samples_per_second': 16.071, 'train_steps_per_second': 16.071, 'train_loss': 2.70205224609375, 'epoch': 25.0}
{'train_runtime': 15.5817, 'train_samples_per_second': 16.045, 'train_steps_per_second': 16.045, 'train_loss': 2.709642822265625, 'epoch': 25.0}
{'train_runtime': 15.4368, 'train_samples_per_second': 16.195, 'train_steps_per_second': 16.195, 'train_loss': 2.72803515625, 'epoch': 25.0}
{'train_runtime': 15.5664, 'train_samples_per_second': 16.06, 'train_steps_per_second': 16.06, 'train_loss': 2.7111044921875, 'epoch': 25.0}
{'train_runtime': 11.88, 'train_samples_per_second': 21.044, 'train_steps_per_second': 21.044, 'train_loss': 2.832963623046875, 'epoch': 25.0}
{'train_runtime': 10.4405, 'train_samples_per_second': 23.945, 'train_steps_per_second': 23.945, 'train_loss': 2.830497802734375, 'epoch': 25.0}
{'train_runtime': 10.5066, 'train_samples_per_second': 23.794, 'train_steps_per_second': 23.794, 'train_loss': 2.81084521484375, 'epoch': 25.0}
{'train_runtime': 10.5408, 'train_samples_per_second': 23.717, 'train_steps_per_second': 23.717, 'train_loss': 2.831812744140625, 'epoch': 25.0}
{'train_runtime': 10.7566, 'train_samples_per_second': 23.242, 'train_steps_per_second': 23.242, 'train_loss': 2.830628662109375, 'epoch': 25.0}
{'train_runtime': 10.5428, 'train_samples_per_second': 23.713, 'train_steps_per_second': 23.713, 'train_loss': 2.8619658203125, 'epoch': 25.0}
{'train_runtime': 10.4454, 'train_samples_per_second': 23.934, 'train_steps_per_second': 23.934, 'train_loss': 2.812275634765625, 'epoch': 25.0}
{'train_runtime': 10.4598, 'train_samples_per_second': 23.901, 'train_steps_per_second': 23.901, 'train_loss': 2.8355771484375, 'epoch': 25.0}
{'train_runtime': 10.5277, 'train_samples_per_second': 23.747, 'train_steps_per_second': 23.747, 'train_loss': 2.839536865234375, 'epoch': 25.0}
{'train_runtime': 10.4335, 'train_samples_per_second': 23.961, 'train_steps_per_second': 23.961, 'train_loss': 2.860928466796875, 'epoch': 25.0}
{'train_runtime': 10.5791, 'train_samples_per_second': 23.632, 'train_steps_per_second': 23.632, 'train_loss': 2.831510498046875, 'epoch': 25.0}
{'train_runtime': 10.6046, 'train_samples_per_second': 23.575, 'train_steps_per_second': 23.575, 'train_loss': 2.80210302734375, 'epoch': 25.0}
{'train_runtime': 10.5339, 'train_samples_per_second': 23.733, 'train_steps_per_second': 23.733, 'train_loss': 2.82821435546875, 'epoch': 25.0}
{'train_runtime': 10.5575, 'train_samples_per_second': 23.68, 'train_steps_per_second': 23.68, 'train_loss': 2.811410888671875, 'epoch': 25.0}
{'train_runtime': 10.2116, 'train_samples_per_second': 24.482, 'train_steps_per_second': 24.482, 'train_loss': 2.79745458984375, 'epoch': 25.0}
{'train_runtime': 10.7324, 'train_samples_per_second': 23.294, 'train_steps_per_second': 23.294, 'train_loss': 2.840351806640625, 'epoch': 25.0}
{'train_runtime': 10.5747, 'train_samples_per_second': 23.641, 'train_steps_per_second': 23.641, 'train_loss': 2.79932373046875, 'epoch': 25.0}
{'train_runtime': 10.6849, 'train_samples_per_second': 23.398, 'train_steps_per_second': 23.398, 'train_loss': 2.798757568359375, 'epoch': 25.0}
{'train_runtime': 10.5716, 'train_samples_per_second': 23.648, 'train_steps_per_second': 23.648, 'train_loss': 2.851959228515625, 'epoch': 25.0}
{'train_runtime': 10.4767, 'train_samples_per_second': 23.863, 'train_steps_per_second': 23.863, 'train_loss': 2.800933349609375, 'epoch': 25.0}
{'train_runtime': 10.4742, 'train_samples_per_second': 23.868, 'train_steps_per_second': 23.868, 'train_loss': 2.8434501953125, 'epoch': 25.0}
{'train_runtime': 10.4852, 'train_samples_per_second': 23.843, 'train_steps_per_second': 23.843, 'train_loss': 2.833386474609375, 'epoch': 25.0}
{'train_runtime': 10.3898, 'train_samples_per_second': 24.062, 'train_steps_per_second': 24.062, 'train_loss': 2.818635498046875, 'epoch': 25.0}
{'train_runtime': 10.3703, 'train_samples_per_second': 24.107, 'train_steps_per_second': 24.107, 'train_loss': 2.86254931640625, 'epoch': 25.0}
{'train_runtime': 10.4017, 'train_samples_per_second': 24.035, 'train_steps_per_second': 24.035, 'train_loss': 2.842771484375, 'epoch': 25.0}
{'train_runtime': 11.5018, 'train_samples_per_second': 21.736, 'train_steps_per_second': 21.736, 'train_loss': 2.832574951171875, 'epoch': 25.0}
{'train_runtime': 12.4217, 'train_samples_per_second': 20.126, 'train_steps_per_second': 20.126, 'train_loss': 3.034527587890625, 'epoch': 25.0}
{'train_runtime': 12.3863, 'train_samples_per_second': 20.184, 'train_steps_per_second': 20.184, 'train_loss': 3.03757763671875, 'epoch': 25.0}
{'train_runtime': 12.2621, 'train_samples_per_second': 20.388, 'train_steps_per_second': 20.388, 'train_loss': 3.05187890625, 'epoch': 25.0}
{'train_runtime': 12.3964, 'train_samples_per_second': 20.167, 'train_steps_per_second': 20.167, 'train_loss': 3.034375244140625, 'epoch': 25.0}
{'train_runtime': 12.2502, 'train_samples_per_second': 20.408, 'train_steps_per_second': 20.408, 'train_loss': 3.024197998046875, 'epoch': 25.0}
{'train_runtime': 12.3209, 'train_samples_per_second': 20.291, 'train_steps_per_second': 20.291, 'train_loss': 3.0460830078125, 'epoch': 25.0}
{'train_runtime': 12.2652, 'train_samples_per_second': 20.383, 'train_steps_per_second': 20.383, 'train_loss': 3.035318603515625, 'epoch': 25.0}

Explanations:  81%|████████  | 1132/1400 [1:05:17<18:38,  4.17s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  81%|████████  | 1133/1400 [1:05:19<16:31,  3.71s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 15.3968, 'train_samples_per_second': 16.237, 'train_steps_per_second': 16.237, 'train_loss': 2.7120849609375, 'epoch': 25.0}
{'train_runtime': 15.273, 'train_samples_per_second': 16.369, 'train_steps_per_second': 16.369, 'train_loss': 2.69615869140625, 'epoch': 25.0}
{'train_runtime': 15.2467, 'train_samples_per_second': 16.397, 'train_steps_per_second': 16.397, 'train_loss': 2.718602783203125, 'epoch': 25.0}
{'train_runtime': 15.3789, 'train_samples_per_second': 16.256, 'train_steps_per_second': 16.256, 'train_loss': 2.71717578125, 'epoch': 25.0}
{'train_runtime': 15.0671, 'train_samples_per_second': 16.592, 'train_steps_per_second': 16.592, 'train_loss': 2.696059326171875, 'epoch': 25.0}
{'train_runtime': 14.8291, 'train_samples_per_second': 16.859, 'train_steps_per_second': 16.859, 'train_loss': 2.721521484375, 'epoch': 25.0}
{'train_runtime': 14.7876, 'train_samples_per_second': 16.906, 'train_steps_per_second': 16.906, 'train_loss': 2.7013837890625, 'epoch': 25.0}
{'train_runtime': 14.91, 'train_samples_per_second': 16.767, 'train_steps_per_second': 16.767, 'train_loss': 2.7058515625, 'epoch': 25.0}
{'train_runtime': 15.0971, 'train_samples_per_second': 16.56, 'train_steps_per_second': 16.56, 'train_loss': 2.707417236328125, 'epoch': 25.0}
{'train_runtime': 15.3223, 'train_samples_per_second': 16.316, 'train_steps_per_second': 16.316, 'train_loss': 2.704156982421875, 'epoch': 25.0}
{'train_runtime': 14.958, 'train_samples_per_second': 16.713, 'train_steps_per_second': 16.713, 'train_loss': 2.705787353515625, 'epoch': 25.0}
{'train_runtime': 14.9657, 'train_samples_per_second': 16.705, 'train_steps_per_second': 16.705, 'train_loss': 2.692755126953125, 'epoch': 25.0}
{'train_runtime': 14.9645, 'train_samples_per_second': 16.706, 'train_steps_per_second': 16.706, 'train_loss': 2.700084716796875, 'epoch': 25.0}
{'train_runtime': 14.9554, 'train_samples_per_second': 16.716, 'train_steps_per_second': 16.716, 'train_loss': 2.68422412109375, 'epoch': 25.0}
{'train_runtime': 14.8026, 'train_samples_per_second': 16.889, 'train_steps_per_second': 16.889, 'train_loss': 2.704195068359375, 'epoch': 25.0}
{'train_runtime': 14.9628, 'train_samples_per_second': 16.708, 'train_steps_per_second': 16.708, 'train_loss': 2.70614794921875, 'epoch': 25.0}
{'train_runtime': 15.2852, 'train_samples_per_second': 16.356, 'train_steps_per_second': 16.356, 'train_loss': 2.70350634765625, 'epoch': 25.0}
{'train_runtime': 14.8216, 'train_samples_per_second': 16.867, 'train_steps_per_second': 16.867, 'train_loss': 2.702953369140625, 'epoch': 25.0}
{'train_runtime': 14.9012, 'train_samples_per_second': 16.777, 'train_steps_per_second': 16.777, 'train_loss': 2.703435302734375, 'epoch': 25.0}
{'train_runtime': 15.1018, 'train_samples_per_second': 16.554, 'train_steps_per_second': 16.554, 'train_loss': 2.695731201171875, 'epoch': 25.0}
{'train_runtime': 14.9771, 'train_samples_per_second': 16.692, 'train_steps_per_second': 16.692, 'train_loss': 2.7001669921875, 'epoch': 25.0}
{'train_runtime': 14.8106, 'train_samples_per_second': 16.88, 'train_steps_per_second': 16.88, 'train_loss': 2.7197080078125, 'epoch': 25.0}
{'train_runtime': 14.9716, 'train_samples_per_second': 16.698, 'train_steps_per_second': 16.698, 'train_loss': 2.694869140625, 'epoch': 25.0}
{'train_runtime': 14.5618, 'train_samples_per_second': 17.168, 'train_steps_per_second': 17.168, 'train_loss': 2.7081689453125, 'epoch': 25.0}
{'train_runtime': 11.1552, 'train_samples_per_second': 22.411, 'train_steps_per_second': 22.411, 'train_loss': 2.79627294921875, 'epoch': 25.0}
{'train_runtime': 10.2596, 'train_samples_per_second': 24.367, 'train_steps_per_second': 24.367, 'train_loss': 2.832194580078125, 'epoch': 25.0}
{'train_runtime': 10.3173, 'train_samples_per_second': 24.231, 'train_steps_per_second': 24.231, 'train_loss': 2.841543212890625, 'epoch': 25.0}
{'train_runtime': 10.3091, 'train_samples_per_second': 24.25, 'train_steps_per_second': 24.25, 'train_loss': 2.836180419921875, 'epoch': 25.0}
{'train_runtime': 10.4327, 'train_samples_per_second': 23.963, 'train_steps_per_second': 23.963, 'train_loss': 2.8002421875, 'epoch': 25.0}
{'train_runtime': 10.3677, 'train_samples_per_second': 24.113, 'train_steps_per_second': 24.113, 'train_loss': 2.835536865234375, 'epoch': 25.0}
{'train_runtime': 10.3998, 'train_samples_per_second': 24.039, 'train_steps_per_second': 24.039, 'train_loss': 2.810369384765625, 'epoch': 25.0}
{'train_runtime': 10.4663, 'train_samples_per_second': 23.886, 'train_steps_per_second': 23.886, 'train_loss': 2.8633310546875, 'epoch': 25.0}
{'train_runtime': 10.3728, 'train_samples_per_second': 24.102, 'train_steps_per_second': 24.102, 'train_loss': 2.8014345703125, 'epoch': 25.0}
{'train_runtime': 10.2627, 'train_samples_per_second': 24.36, 'train_steps_per_second': 24.36, 'train_loss': 2.84668798828125, 'epoch': 25.0}
{'train_runtime': 10.4337, 'train_samples_per_second': 23.961, 'train_steps_per_second': 23.961, 'train_loss': 2.808722412109375, 'epoch': 25.0}
{'train_runtime': 10.5085, 'train_samples_per_second': 23.79, 'train_steps_per_second': 23.79, 'train_loss': 2.80163671875, 'epoch': 25.0}
{'train_runtime': 10.5484, 'train_samples_per_second': 23.7, 'train_steps_per_second': 23.7, 'train_loss': 2.830449951171875, 'epoch': 25.0}
{'train_runtime': 10.6568, 'train_samples_per_second': 23.459, 'train_steps_per_second': 23.459, 'train_loss': 2.810464111328125, 'epoch': 25.0}
{'train_runtime': 10.3609, 'train_samples_per_second': 24.129, 'train_steps_per_second': 24.129, 'train_loss': 2.8460556640625, 'epoch': 25.0}
{'train_runtime': 10.3757, 'train_samples_per_second': 24.095, 'train_steps_per_second': 24.095, 'train_loss': 2.8338310546875, 'epoch': 25.0}
{'train_runtime': 10.6138, 'train_samples_per_second': 23.554, 'train_steps_per_second': 23.554, 'train_loss': 2.806689697265625, 'epoch': 25.0}
{'train_runtime': 10.6326, 'train_samples_per_second': 23.513, 'train_steps_per_second': 23.513, 'train_loss': 2.802820556640625, 'epoch': 25.0}
{'train_runtime': 10.623, 'train_samples_per_second': 23.534, 'train_steps_per_second': 23.534, 'train_loss': 2.815202392578125, 'epoch': 25.0}
{'train_runtime': 10.8913, 'train_samples_per_second': 22.954, 'train_steps_per_second': 22.954, 'train_loss': 2.80645166015625, 'epoch': 25.0}
{'train_runtime': 10.8897, 'train_samples_per_second': 22.958, 'train_steps_per_second': 22.958, 'train_loss': 2.838134033203125, 'epoch': 25.0}
{'train_runtime': 10.6305, 'train_samples_per_second': 23.517, 'train_steps_per_second': 23.517, 'train_loss': 2.82555029296875, 'epoch': 25.0}
{'train_runtime': 10.6444, 'train_samples_per_second': 23.487, 'train_steps_per_second': 23.487, 'train_loss': 2.84400439453125, 'epoch': 25.0}
{'train_runtime': 10.6103, 'train_samples_per_second': 23.562, 'train_steps_per_second': 23.562, 'train_loss': 2.831892578125, 'epoch': 25.0}
{'train_runtime': 10.6112, 'train_samples_per_second': 23.56, 'train_steps_per_second': 23.56, 'train_loss': 2.86327392578125, 'epoch': 25.0}
{'train_runtime': 12.316, 'train_samples_per_second': 20.299, 'train_steps_per_second': 20.299, 'train_loss': 3.0108564453125, 'epoch': 25.0}
{'train_runtime': 12.8144, 'train_samples_per_second': 19.509, 'train_steps_per_second': 19.509, 'train_loss': 3.057359130859375, 'epoch': 25.0}
{'train_runtime': 12.638, 'train_samples_per_second': 19.782, 'train_steps_per_second': 19.782, 'train_loss': 3.0202294921875, 'epoch': 25.0}
{'train_runtime': 12.571, 'train_samples_per_second': 19.887, 'train_steps_per_second': 19.887, 'train_loss': 3.0305390625, 'epoch': 25.0}
{'train_runtime': 12.4834, 'train_samples_per_second': 20.027, 'train_steps_per_second': 20.027, 'train_loss': 3.042637939453125, 'epoch': 25.0}
{'train_runtime': 12.5896, 'train_samples_per_second': 19.858, 'train_steps_per_second': 19.858, 'train_loss': 3.0565322265625, 'epoch': 25.0}
{'train_runtime': 12.6315, 'train_samples_per_second': 19.792, 'train_steps_per_second': 19.792, 'train_loss': 3.010743896484375, 'epoch': 25.0}
{'train_runtime': 12.7148, 'train_samples_per_second': 19.662, 'train_steps_per_second': 19.662, 'train_loss': 2.999833984375, 'epoch': 25.0}
{'train_runtime': 15.6885, 'train_samples_per_second': 15.935, 'train_steps_per_second': 15.935, 'train_loss': 2.712915283203125, 'epoch': 25.0}
{'train_runtime': 15.4375, 'train_samples_per_second': 16.194, 'train_steps_per_second': 16.194, 'train_loss': 2.703746826171875, 'epoch': 25.0}
{'train_runtime': 15.7154, 'train_samples_per_second': 15.908, 'train_steps_per_second': 15.908, 'train_loss': 2.708489990234375, 'epoch': 25.0}
{'train_runtime': 15.4272, 'train_samples_per_second': 16.205, 'train_steps_per_second': 16.205, 'train_loss': 2.69728271484375, 'epoch': 25.0}
{'train_runtime': 15.2918, 'train_samples_per_second': 16.349, 'train_steps_per_second': 16.349, 'train_loss': 2.698515869140625, 'epoch': 25.0}
{'train_runtime': 15.2891, 'train_samples_per_second': 16.352, 'train_steps_per_second': 16.352, 'train_loss': 2.68926611328125, 'epoch': 25.0}
{'train_runtime': 15.9241, 'train_samples_per_second': 15.699, 'train_steps_per_second': 15.699, 'train_loss': 2.6977841796875, 'epoch': 25.0}
{'train_runtime': 15.5474, 'train_samples_per_second': 16.08, 'train_steps_per_second': 16.08, 'train_loss': 2.723839599609375, 'epoch': 25.0}
{'train_runtime': 15.8467, 'train_samples_per_second': 15.776, 'train_steps_per_second': 15.776, 'train_loss': 2.713841064453125, 'epoch': 25.0}
{'train_runtime': 15.6724, 'train_samples_per_second': 15.952, 'train_steps_per_second': 15.952, 'train_loss': 2.71694775390625, 'epoch': 25.0}
{'train_runtime': 15.6324, 'train_samples_per_second': 15.992, 'train_steps_per_second': 15.992, 'train_loss': 2.689674072265625, 'epoch': 25.0}
{'train_runtime': 15.5002, 'train_samples_per_second': 16.129, 'train_steps_per_second': 16.129, 'train_loss': 2.69510302734375, 'epoch': 25.0}
{'train_runtime': 15.3004, 'train_samples_per_second': 16.339, 'train_steps_per_second': 16.339, 'train_loss': 2.690023193359375, 'epoch': 25.0}
{'train_runtime': 15.4155, 'train_samples_per_second': 16.217, 'train_steps_per_second': 16.217, 'train_loss': 2.705314453125, 'epoch': 25.0}
{'train_runtime': 15.2909, 'train_samples_per_second': 16.35, 'train_steps_per_second': 16.35, 'train_loss': 2.714041259765625, 'epoch': 25.0}
{'train_runtime': 14.9934, 'train_samples_per_second': 16.674, 'train_steps_per_second': 16.674, 'train_loss': 2.681991943359375, 'epoch': 25.0}
{'train_runtime': 14.7643, 'train_samples_per_second': 16.933, 'train_steps_per_second': 16.933, 'train_loss': 2.712811279296875, 'epoch': 25.0}
{'train_runtime': 14.9123, 'train_samples_per_second': 16.765, 'train_steps_per_second': 16.765, 'train_loss': 2.696291748046875, 'epoch': 25.0}
{'train_runtime': 14.9075, 'train_samples_per_second': 16.77, 'train_steps_per_second': 16.77, 'train_loss': 2.716544677734375, 'epoch': 25.0}
{'train_runtime': 15.0236, 'train_samples_per_second': 16.641, 'train_steps_per_second': 16.641, 'train_loss': 2.710355712890625, 'epoch': 25.0}
{'train_runtime': 14.7823, 'train_samples_per_second': 16.912, 'train_steps_per_second': 16.912, 'train_loss': 2.712451904296875, 'epoch': 25.0}
{'train_runtime': 14.9938, 'train_samples_per_second': 16.674, 'train_steps_per_second': 16.674, 'train_loss': 2.717893798828125, 'epoch': 25.0}
{'train_runtime': 14.0845, 'train_samples_per_second': 17.75, 'train_steps_per_second': 17.75, 'train_loss': 2.70270751953125, 'epoch': 25.0}
{'train_runtime': 10.4915, 'train_samples_per_second': 23.829, 'train_steps_per_second': 23.829, 'train_loss': 2.784996337890625, 'epoch': 25.0}
{'train_runtime': 10.3391, 'train_samples_per_second': 24.18, 'train_steps_per_second': 24.18, 'train_loss': 2.788886474609375, 'epoch': 25.0}
{'train_runtime': 10.1985, 'train_samples_per_second': 24.513, 'train_steps_per_second': 24.513, 'train_loss': 2.79897265625, 'epoch': 25.0}
{'train_runtime': 10.3009, 'train_samples_per_second': 24.27, 'train_steps_per_second': 24.27, 'train_loss': 2.824328857421875, 'epoch': 25.0}
{'train_runtime': 10.2166, 'train_samples_per_second': 24.47, 'train_steps_per_second': 24.47, 'train_loss': 2.835645263671875, 'epoch': 25.0}
{'train_runtime': 10.3097, 'train_samples_per_second': 24.249, 'train_steps_per_second': 24.249, 'train_loss': 2.844205078125, 'epoch': 25.0}
{'train_runtime': 10.3725, 'train_samples_per_second': 24.102, 'train_steps_per_second': 24.102, 'train_loss': 2.84284228515625, 'epoch': 25.0}
{'train_runtime': 10.282, 'train_samples_per_second': 24.314, 'train_steps_per_second': 24.314, 'train_loss': 2.816711181640625, 'epoch': 25.0}
{'train_runtime': 10.5871, 'train_samples_per_second': 23.614, 'train_steps_per_second': 23.614, 'train_loss': 2.79740869140625, 'epoch': 25.0}
{'train_runtime': 10.1549, 'train_samples_per_second': 24.619, 'train_steps_per_second': 24.619, 'train_loss': 2.834190673828125, 'epoch': 25.0}
{'train_runtime': 10.3708, 'train_samples_per_second': 24.106, 'train_steps_per_second': 24.106, 'train_loss': 2.828911865234375, 'epoch': 25.0}
{'train_runtime': 10.4511, 'train_samples_per_second': 23.921, 'train_steps_per_second': 23.921, 'train_loss': 2.84469921875, 'epoch': 25.0}
{'train_runtime': 10.4164, 'train_samples_per_second': 24.001, 'train_steps_per_second': 24.001, 'train_loss': 2.821858642578125, 'epoch': 25.0}
{'train_runtime': 11.4121, 'train_samples_per_second': 21.907, 'train_steps_per_second': 21.907, 'train_loss': 2.8222255859375, 'epoch': 25.0}
{'train_runtime': 10.4152, 'train_samples_per_second': 24.003, 'train_steps_per_second': 24.003, 'train_loss': 2.822822265625, 'epoch': 25.0}
{'train_runtime': 10.671, 'train_samples_per_second': 23.428, 'train_steps_per_second': 23.428, 'train_loss': 2.847054443359375, 'epoch': 25.0}
{'train_runtime': 10.5035, 'train_samples_per_second': 23.802, 'train_steps_per_second': 23.802, 'train_loss': 2.8231396484375, 'epoch': 25.0}
{'train_runtime': 10.4591, 'train_samples_per_second': 23.903, 'train_steps_per_second': 23.903, 'train_loss': 2.809081298828125, 'epoch': 25.0}
{'train_runtime': 10.4437, 'train_samples_per_second': 23.938, 'train_steps_per_second': 23.938, 'train_loss': 2.801638427734375, 'epoch': 25.0}
{'train_runtime': 10.4941, 'train_samples_per_second': 23.823, 'train_steps_per_second': 23.823, 'train_loss': 2.856927001953125, 'epoch': 25.0}
{'train_runtime': 10.5577, 'train_samples_per_second': 23.679, 'train_steps_per_second': 23.679, 'train_loss': 2.788783203125, 'epoch': 25.0}
{'train_runtime': 10.5243, 'train_samples_per_second': 23.754, 'train_steps_per_second': 23.754, 'train_loss': 2.80385205078125, 'epoch': 25.0}
{'train_runtime': 10.6358, 'train_samples_per_second': 23.505, 'train_steps_per_second': 23.505, 'train_loss': 2.7994296875, 'epoch': 25.0}
{'train_runtime': 10.5648, 'train_samples_per_second': 23.663, 'train_steps_per_second': 23.663, 'train_loss': 2.83451904296875, 'epoch': 25.0}
{'train_runtime': 10.7283, 'train_samples_per_second': 23.303, 'train_steps_per_second': 23.303, 'train_loss': 2.82893798828125, 'epoch': 25.0}
{'train_runtime': 12.4408, 'train_samples_per_second': 20.095, 'train_steps_per_second': 20.095, 'train_loss': 3.026234130859375, 'epoch': 25.0}
{'train_runtime': 12.5843, 'train_samples_per_second': 19.866, 'train_steps_per_second': 19.866, 'train_loss': 3.03278759765625, 'epoch': 25.0}
{'train_runtime': 12.6467, 'train_samples_per_second': 19.768, 'train_steps_per_second': 19.768, 'train_loss': 3.027780029296875, 'epoch': 25.0}
{'train_runtime': 12.6223, 'train_samples_per_second': 19.806, 'train_steps_per_second': 19.806, 'train_loss': 3.063987548828125, 'epoch': 25.0}
{'train_runtime': 12.6527, 'train_samples_per_second': 19.759, 'train_steps_per_second': 19.759, 'train_loss': 3.025951416015625, 'epoch': 25.0}
{'train_runtime': 12.4893, 'train_samples_per_second': 20.017, 'train_steps_per_second': 20.017, 'train_loss': 3.034839111328125, 'epoch': 25.0}
{'train_runtime': 12.5567, 'train_samples_per_second': 19.91, 'train_steps_per_second': 19.91, 'train_loss': 3.00186474609375, 'epoch': 25.0}
{'train_runtime': 12.5562, 'train_samples_per_second': 19.91, 'train_steps_per_second': 19.91, 'train_loss': 3.031327392578125, 'epoch': 25.0}

Explanations:  81%|████████  | 1135/1400 [1:05:24<12:43,  2.88s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  81%|████████  | 1136/1400 [1:05:31<17:43,  4.03s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  81%|████████  | 1137/1400 [1:05:34<16:01,  3.65s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  81%|████████▏ | 1139/1400 [1:05:39<13:02,  3.00s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  81%|████████▏ | 1140/1400 [1:05:45<17:05,  3.94s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 15.5145, 'train_samples_per_second': 16.114, 'train_steps_per_second': 16.114, 'train_loss': 2.698919921875, 'epoch': 25.0}
{'train_runtime': 15.2562, 'train_samples_per_second': 16.387, 'train_steps_per_second': 16.387, 'train_loss': 2.691774169921875, 'epoch': 25.0}
{'train_runtime': 15.2364, 'train_samples_per_second': 16.408, 'train_steps_per_second': 16.408, 'train_loss': 2.6967431640625, 'epoch': 25.0}
{'train_runtime': 15.4476, 'train_samples_per_second': 16.184, 'train_steps_per_second': 16.184, 'train_loss': 2.70696728515625, 'epoch': 25.0}
{'train_runtime': 15.322, 'train_samples_per_second': 16.316, 'train_steps_per_second': 16.316, 'train_loss': 2.684875244140625, 'epoch': 25.0}
{'train_runtime': 15.3068, 'train_samples_per_second': 16.333, 'train_steps_per_second': 16.333, 'train_loss': 2.703224609375, 'epoch': 25.0}
{'train_runtime': 15.7683, 'train_samples_per_second': 15.855, 'train_steps_per_second': 15.855, 'train_loss': 2.68773583984375, 'epoch': 25.0}
{'train_runtime': 15.499, 'train_samples_per_second': 16.13, 'train_steps_per_second': 16.13, 'train_loss': 2.70411962890625, 'epoch': 25.0}
{'train_runtime': 15.8764, 'train_samples_per_second': 15.747, 'train_steps_per_second': 15.747, 'train_loss': 2.70358154296875, 'epoch': 25.0}
{'train_runtime': 15.7791, 'train_samples_per_second': 15.844, 'train_steps_per_second': 15.844, 'train_loss': 2.70673193359375, 'epoch': 25.0}
{'train_runtime': 15.7344, 'train_samples_per_second': 15.889, 'train_steps_per_second': 15.889, 'train_loss': 2.704505859375, 'epoch': 25.0}
{'train_runtime': 15.781, 'train_samples_per_second': 15.842, 'train_steps_per_second': 15.842, 'train_loss': 2.68313623046875, 'epoch': 25.0}
{'train_runtime': 15.7071, 'train_samples_per_second': 15.916, 'train_steps_per_second': 15.916, 'train_loss': 2.69312548828125, 'epoch': 25.0}
{'train_runtime': 15.8724, 'train_samples_per_second': 15.751, 'train_steps_per_second': 15.751, 'train_loss': 2.713619384765625, 'epoch': 25.0}
{'train_runtime': 15.7835, 'train_samples_per_second': 15.839, 'train_steps_per_second': 15.839, 'train_loss': 2.707510009765625, 'epoch': 25.0}
{'train_runtime': 15.6329, 'train_samples_per_second': 15.992, 'train_steps_per_second': 15.992, 'train_loss': 2.701791259765625, 'epoch': 25.0}
{'train_runtime': 15.4782, 'train_samples_per_second': 16.152, 'train_steps_per_second': 16.152, 'train_loss': 2.707904541015625, 'epoch': 25.0}
{'train_runtime': 15.5175, 'train_samples_per_second': 16.111, 'train_steps_per_second': 16.111, 'train_loss': 2.686635009765625, 'epoch': 25.0}
{'train_runtime': 15.5693, 'train_samples_per_second': 16.057, 'train_steps_per_second': 16.057, 'train_loss': 2.717464599609375, 'epoch': 25.0}
{'train_runtime': 15.5388, 'train_samples_per_second': 16.089, 'train_steps_per_second': 16.089, 'train_loss': 2.674488037109375, 'epoch': 25.0}
{'train_runtime': 15.4936, 'train_samples_per_second': 16.136, 'train_steps_per_second': 16.136, 'train_loss': 2.739321044921875, 'epoch': 25.0}
{'train_runtime': 15.6799, 'train_samples_per_second': 15.944, 'train_steps_per_second': 15.944, 'train_loss': 2.7039208984375, 'epoch': 25.0}
{'train_runtime': 12.8755, 'train_samples_per_second': 19.417, 'train_steps_per_second': 19.417, 'train_loss': 2.692654541015625, 'epoch': 25.0}
{'train_runtime': 10.4922, 'train_samples_per_second': 23.827, 'train_steps_per_second': 23.827, 'train_loss': 2.8428994140625, 'epoch': 25.0}
{'train_runtime': 10.7765, 'train_samples_per_second': 23.199, 'train_steps_per_second': 23.199, 'train_loss': 2.778253662109375, 'epoch': 25.0}
{'train_runtime': 10.5266, 'train_samples_per_second': 23.749, 'train_steps_per_second': 23.749, 'train_loss': 2.8348955078125, 'epoch': 25.0}
{'train_runtime': 10.5656, 'train_samples_per_second': 23.662, 'train_steps_per_second': 23.662, 'train_loss': 2.83192626953125, 'epoch': 25.0}
{'train_runtime': 10.5002, 'train_samples_per_second': 23.809, 'train_steps_per_second': 23.809, 'train_loss': 2.8441005859375, 'epoch': 25.0}
{'train_runtime': 10.7089, 'train_samples_per_second': 23.345, 'train_steps_per_second': 23.345, 'train_loss': 2.83459375, 'epoch': 25.0}
{'train_runtime': 10.7339, 'train_samples_per_second': 23.291, 'train_steps_per_second': 23.291, 'train_loss': 2.821564697265625, 'epoch': 25.0}
{'train_runtime': 10.6417, 'train_samples_per_second': 23.493, 'train_steps_per_second': 23.493, 'train_loss': 2.85858984375, 'epoch': 25.0}
{'train_runtime': 10.5271, 'train_samples_per_second': 23.748, 'train_steps_per_second': 23.748, 'train_loss': 2.80157275390625, 'epoch': 25.0}
{'train_runtime': 10.6563, 'train_samples_per_second': 23.46, 'train_steps_per_second': 23.46, 'train_loss': 2.781560791015625, 'epoch': 25.0}
{'train_runtime': 10.7395, 'train_samples_per_second': 23.279, 'train_steps_per_second': 23.279, 'train_loss': 2.828739013671875, 'epoch': 25.0}
{'train_runtime': 10.6799, 'train_samples_per_second': 23.408, 'train_steps_per_second': 23.408, 'train_loss': 2.784994873046875, 'epoch': 25.0}
{'train_runtime': 10.6372, 'train_samples_per_second': 23.502, 'train_steps_per_second': 23.502, 'train_loss': 2.81604248046875, 'epoch': 25.0}
{'train_runtime': 10.5032, 'train_samples_per_second': 23.802, 'train_steps_per_second': 23.802, 'train_loss': 2.852720703125, 'epoch': 25.0}
{'train_runtime': 10.6608, 'train_samples_per_second': 23.45, 'train_steps_per_second': 23.45, 'train_loss': 2.796919921875, 'epoch': 25.0}
{'train_runtime': 10.7797, 'train_samples_per_second': 23.192, 'train_steps_per_second': 23.192, 'train_loss': 2.823712646484375, 'epoch': 25.0}
{'train_runtime': 10.837, 'train_samples_per_second': 23.069, 'train_steps_per_second': 23.069, 'train_loss': 2.84373193359375, 'epoch': 25.0}
{'train_runtime': 10.7717, 'train_samples_per_second': 23.209, 'train_steps_per_second': 23.209, 'train_loss': 2.80471044921875, 'epoch': 25.0}
{'train_runtime': 10.692, 'train_samples_per_second': 23.382, 'train_steps_per_second': 23.382, 'train_loss': 2.845512939453125, 'epoch': 25.0}
{'train_runtime': 10.7543, 'train_samples_per_second': 23.246, 'train_steps_per_second': 23.246, 'train_loss': 2.82869482421875, 'epoch': 25.0}
{'train_runtime': 10.6208, 'train_samples_per_second': 23.539, 'train_steps_per_second': 23.539, 'train_loss': 2.826835693359375, 'epoch': 25.0}
{'train_runtime': 10.5606, 'train_samples_per_second': 23.673, 'train_steps_per_second': 23.673, 'train_loss': 2.848885498046875, 'epoch': 25.0}
{'train_runtime': 10.615, 'train_samples_per_second': 23.552, 'train_steps_per_second': 23.552, 'train_loss': 2.84115283203125, 'epoch': 25.0}
{'train_runtime': 10.5193, 'train_samples_per_second': 23.766, 'train_steps_per_second': 23.766, 'train_loss': 2.803318603515625, 'epoch': 25.0}
{'train_runtime': 11.9687, 'train_samples_per_second': 20.888, 'train_steps_per_second': 20.888, 'train_loss': 3.001985595703125, 'epoch': 25.0}
{'train_runtime': 12.4642, 'train_samples_per_second': 20.057, 'train_steps_per_second': 20.057, 'train_loss': 3.046628173828125, 'epoch': 25.0}
{'train_runtime': 12.3486, 'train_samples_per_second': 20.245, 'train_steps_per_second': 20.245, 'train_loss': 3.03436962890625, 'epoch': 25.0}
{'train_runtime': 12.3152, 'train_samples_per_second': 20.3, 'train_steps_per_second': 20.3, 'train_loss': 3.01328369140625, 'epoch': 25.0}
{'train_runtime': 12.4595, 'train_samples_per_second': 20.065, 'train_steps_per_second': 20.065, 'train_loss': 3.0042890625, 'epoch': 25.0}
{'train_runtime': 12.387, 'train_samples_per_second': 20.182, 'train_steps_per_second': 20.182, 'train_loss': 3.00678662109375, 'epoch': 25.0}
{'train_runtime': 12.391, 'train_samples_per_second': 20.176, 'train_steps_per_second': 20.176, 'train_loss': 3.043317138671875, 'epoch': 25.0}
{'train_runtime': 12.4083, 'train_samples_per_second': 20.148, 'train_steps_per_second': 20.148, 'train_loss': 3.02163720703125, 'epoch': 25.0}
{'train_runtime': 12.3687, 'train_samples_per_second': 20.212, 'train_steps_per_second': 20.212, 'train_loss': 3.03856103515625, 'epoch': 25.0}
{'train_runtime': 12.3398, 'train_samples_per_second': 20.26, 'train_steps_per_second': 20.26, 'train_loss': 3.03026708984375, 'epoch': 25.0}

Explanations:  82%|████████▏ | 1141/1400 [1:05:48<15:38,  3.62s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  82%|████████▏ | 1143/1400 [1:05:54<13:01,  3.04s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  82%|████████▏ | 1144/1400 [1:05:59<16:19,  3.82s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  82%|████████▏ | 1145/1400 [1:06:03<15:37,  3.68s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  82%|████████▏ | 1147/1400 [1:06:08<12:44,  3.02s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  82%|████████▏ | 1148/1400 [1:06:14<15:40,  3.73s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  82%|████████▏ | 1149/1400 [1:06:17<15:15,  3.65s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  82%|████████▏ | 1151/1400 [1:06:23<12:47,  3.08s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  82%|████████▏ | 1152/1400 [1:06:28<15:04,  3.65s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  82%|████████▏ | 1153/1400 [1:06:32<14:40,  3.56s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  82%|████████▎ | 1155/1400 [1:06:38<12:58,  3.18s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  83%|████████▎ | 1156/1400 [1:06:42<14:06,  3.47s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  83%|████████▎ | 1157/1400 [1:06:46<14:05,  3.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  83%|████████▎ | 1159/1400 [1:06:53<13:11,  3.28s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  83%|████████▎ | 1160/1400 [1:06:57<13:27,  3.37s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  83%|████████▎ | 1161/1400 [1:07:00<13:43,  3.45s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  83%|████████▎ | 1163/1400 [1:07:08<13:01,  3.30s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  83%|████████▎ | 1164/1400 [1:07:11<12:57,  3.30s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  83%|████████▎ | 1165/1400 [1:07:15<13:12,  3.37s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  83%|████████▎ | 1167/1400 [1:07:23<13:16,  3.42s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  83%|████████▎ | 1168/1400 [1:07:26<12:23,  3.20s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  84%|████████▎ | 1169/1400 [1:07:29<12:41,  3.30s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  84%|████████▎ | 1171/1400 [1:07:38<13:13,  3.47s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  84%|████████▎ | 1172/1400 [1:07:40<11:53,  3.13s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  84%|████████▍ | 1173/1400 [1:07:44<12:21,  3.27s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  84%|████████▍ | 1175/1400 [1:07:52<12:55,  3.44s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  84%|████████▍ | 1176/1400 [1:07:55<11:29,  3.08s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  84%|████████▍ | 1177/1400 [1:07:58<12:03,  3.24s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  84%|████████▍ | 1179/1400 [1:08:07<12:52,  3.50s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  84%|████████▍ | 1180/1400 [1:08:09<11:04,  3.02s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  84%|████████▍ | 1181/1400 [1:08:13<11:32,  3.16s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  84%|████████▍ | 1183/1400 [1:08:22<13:02,  3.61s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  85%|████████▍ | 1184/1400 [1:08:24<10:39,  2.96s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  85%|████████▍ | 1185/1400 [1:08:27<10:53,  3.04s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  85%|████████▍ | 1187/1400 [1:08:37<12:58,  3.65s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  85%|████████▍ | 1188/1400 [1:08:38<10:15,  2.90s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  85%|████████▍ | 1189/1400 [1:08:41<10:17,  2.93s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  85%|████████▌ | 1192/1400 [1:08:53<09:59,  2.88s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  85%|████████▌ | 1193/1400 [1:08:56<09:23,  2.72s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  85%|████████▌ | 1196/1400 [1:09:08<09:57,  2.93s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  86%|████████▌ | 1197/1400 [1:09:10<08:38,  2.55s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  86%|████████▌ | 1200/1400 [1:09:24<09:55,  2.98s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  86%|████████▌ | 1201/1400 [1:09:25<08:04,  2.44s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  86%|████████▌ | 1204/1400 [1:09:39<09:50,  3.01s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  86%|████████▌ | 1205/1400 [1:09:40<07:43,  2.38s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 12.3085, 'train_samples_per_second': 20.311, 'train_steps_per_second': 20.311, 'train_loss': 3.046106201171875, 'epoch': 25.0}
{'train_runtime': 12.269, 'train_samples_per_second': 20.377, 'train_steps_per_second': 20.377, 'train_loss': 3.027843505859375, 'epoch': 25.0}
{'train_runtime': 12.4346, 'train_samples_per_second': 20.105, 'train_steps_per_second': 20.105, 'train_loss': 3.01745458984375, 'epoch': 25.0}
{'train_runtime': 12.2337, 'train_samples_per_second': 20.435, 'train_steps_per_second': 20.435, 'train_loss': 3.040017578125, 'epoch': 25.0}
{'train_runtime': 12.3346, 'train_samples_per_second': 20.268, 'train_steps_per_second': 20.268, 'train_loss': 3.028017822265625, 'epoch': 25.0}
{'train_runtime': 12.3962, 'train_samples_per_second': 20.168, 'train_steps_per_second': 20.168, 'train_loss': 3.0545068359375, 'epoch': 25.0}
{'train_runtime': 12.1278, 'train_samples_per_second': 20.614, 'train_steps_per_second': 20.614, 'train_loss': 3.022848388671875, 'epoch': 25.0}
{'train_runtime': 12.3257, 'train_samples_per_second': 20.283, 'train_steps_per_second': 20.283, 'train_loss': 3.01185107421875, 'epoch': 25.0}
{'train_runtime': 12.3421, 'train_samples_per_second': 20.256, 'train_steps_per_second': 20.256, 'train_loss': 3.02421044921875, 'epoch': 25.0}
{'train_runtime': 12.3853, 'train_samples_per_second': 20.185, 'train_steps_per_second': 20.185, 'train_loss': 3.03181494140625, 'epoch': 25.0}
{'train_runtime': 12.4105, 'train_samples_per_second': 20.144, 'train_steps_per_second': 20.144, 'train_loss': 3.070135986328125, 'epoch': 25.0}
{'train_runtime': 12.4137, 'train_samples_per_second': 20.139, 'train_steps_per_second': 20.139, 'train_loss': 3.05372705078125, 'epoch': 25.0}
{'train_runtime': 12.5948, 'train_samples_per_second': 19.85, 'train_steps_per_second': 19.85, 'train_loss': 3.040440673828125, 'epoch': 25.0}
{'train_runtime': 12.6172, 'train_samples_per_second': 19.814, 'train_steps_per_second': 19.814, 'train_loss': 3.026248779296875, 'epoch': 25.0}
{'train_runtime': 12.7058, 'train_samples_per_second': 19.676, 'train_steps_per_second': 19.676, 'train_loss': 3.0610478515625, 'epoch': 25.0}
{'train_runtime': 12.9558, 'train_samples_per_second': 19.296, 'train_steps_per_second': 19.296, 'train_loss': 3.026095947265625, 'epoch': 25.0}
{'train_runtime': 13.1762, 'train_samples_per_second': 18.974, 'train_steps_per_second': 18.974, 'train_loss': 3.01500341796875, 'epoch': 25.0}
{'train_runtime': 13.1674, 'train_samples_per_second': 18.986, 'train_steps_per_second': 18.986, 'train_loss': 3.028676025390625, 'epoch': 25.0}
{'train_runtime': 13.2858, 'train_samples_per_second': 18.817, 'train_steps_per_second': 18.817, 'train_loss': 2.844533447265625, 'epoch': 25.0}
{'train_runtime': 13.3587, 'train_samples_per_second': 18.714, 'train_steps_per_second': 18.714, 'train_loss': 2.879060302734375, 'epoch': 25.0}
{'train_runtime': 13.2, 'train_samples_per_second': 18.939, 'train_steps_per_second': 18.939, 'train_loss': 2.872554443359375, 'epoch': 25.0}
{'train_runtime': 13.3731, 'train_samples_per_second': 18.694, 'train_steps_per_second': 18.694, 'train_loss': 2.883048828125, 'epoch': 25.0}
{'train_runtime': 13.1945, 'train_samples_per_second': 18.947, 'train_steps_per_second': 18.947, 'train_loss': 2.851735595703125, 'epoch': 25.0}
{'train_runtime': 13.3919, 'train_samples_per_second': 18.668, 'train_steps_per_second': 18.668, 'train_loss': 2.852708251953125, 'epoch': 25.0}
{'train_runtime': 13.0443, 'train_samples_per_second': 19.165, 'train_steps_per_second': 19.165, 'train_loss': 2.86308349609375, 'epoch': 25.0}
{'train_runtime': 13.0707, 'train_samples_per_second': 19.127, 'train_steps_per_second': 19.127, 'train_loss': 2.883731689453125, 'epoch': 25.0}
{'train_runtime': 13.1428, 'train_samples_per_second': 19.022, 'train_steps_per_second': 19.022, 'train_loss': 2.850807861328125, 'epoch': 25.0}
{'train_runtime': 13.1495, 'train_samples_per_second': 19.012, 'train_steps_per_second': 19.012, 'train_loss': 2.83951708984375, 'epoch': 25.0}
{'train_runtime': 12.8169, 'train_samples_per_second': 19.505, 'train_steps_per_second': 19.505, 'train_loss': 2.83909033203125, 'epoch': 25.0}
{'train_runtime': 13.686, 'train_samples_per_second': 18.267, 'train_steps_per_second': 18.267, 'train_loss': 2.8631240234375, 'epoch': 25.0}
{'train_runtime': 13.0175, 'train_samples_per_second': 19.205, 'train_steps_per_second': 19.205, 'train_loss': 2.87306689453125, 'epoch': 25.0}
{'train_runtime': 12.7596, 'train_samples_per_second': 19.593, 'train_steps_per_second': 19.593, 'train_loss': 2.8807529296875, 'epoch': 25.0}
{'train_runtime': 13.2822, 'train_samples_per_second': 18.822, 'train_steps_per_second': 18.822, 'train_loss': 2.855556884765625, 'epoch': 25.0}
{'train_runtime': 13.382, 'train_samples_per_second': 18.682, 'train_steps_per_second': 18.682, 'train_loss': 2.872127197265625, 'epoch': 25.0}
{'train_runtime': 13.2386, 'train_samples_per_second': 18.884, 'train_steps_per_second': 18.884, 'train_loss': 2.859172119140625, 'epoch': 25.0}
{'train_runtime': 13.207, 'train_samples_per_second': 18.929, 'train_steps_per_second': 18.929, 'train_loss': 2.8530078125, 'epoch': 25.0}
{'train_runtime': 13.0527, 'train_samples_per_second': 19.153, 'train_steps_per_second': 19.153, 'train_loss': 2.8532255859375, 'epoch': 25.0}
{'train_runtime': 13.1008, 'train_samples_per_second': 19.083, 'train_steps_per_second': 19.083, 'train_loss': 2.843677001953125, 'epoch': 25.0}
{'train_runtime': 13.1013, 'train_samples_per_second': 19.082, 'train_steps_per_second': 19.082, 'train_loss': 2.846163330078125, 'epoch': 25.0}
{'train_runtime': 13.1256, 'train_samples_per_second': 19.047, 'train_steps_per_second': 19.047, 'train_loss': 2.855853515625, 'epoch': 25.0}
{'train_runtime': 13.333, 'train_samples_per_second': 18.75, 'train_steps_per_second': 18.75, 'train_loss': 2.865192138671875, 'epoch': 25.0}
{'train_runtime': 13.2734, 'train_samples_per_second': 18.835, 'train_steps_per_second': 18.835, 'train_loss': 2.83091357421875, 'epoch': 25.0}
{'train_runtime': 12.0563, 'train_samples_per_second': 20.736, 'train_steps_per_second': 20.736, 'train_loss': 2.829634521484375, 'epoch': 25.0}
{'train_runtime': 10.7155, 'train_samples_per_second': 23.331, 'train_steps_per_second': 23.331, 'train_loss': 2.9044677734375, 'epoch': 25.0}
{'train_runtime': 10.6379, 'train_samples_per_second': 23.501, 'train_steps_per_second': 23.501, 'train_loss': 2.912904296875, 'epoch': 25.0}
{'train_runtime': 10.706, 'train_samples_per_second': 23.351, 'train_steps_per_second': 23.351, 'train_loss': 2.938403076171875, 'epoch': 25.0}
{'train_runtime': 10.9762, 'train_samples_per_second': 22.777, 'train_steps_per_second': 22.777, 'train_loss': 2.89746875, 'epoch': 25.0}
{'train_runtime': 10.6381, 'train_samples_per_second': 23.5, 'train_steps_per_second': 23.5, 'train_loss': 2.907348388671875, 'epoch': 25.0}
{'train_runtime': 10.9152, 'train_samples_per_second': 22.904, 'train_steps_per_second': 22.904, 'train_loss': 2.876128173828125, 'epoch': 25.0}
{'train_runtime': 10.5994, 'train_samples_per_second': 23.586, 'train_steps_per_second': 23.586, 'train_loss': 2.872625244140625, 'epoch': 25.0}
{'train_runtime': 10.8418, 'train_samples_per_second': 23.059, 'train_steps_per_second': 23.059, 'train_loss': 2.89598291015625, 'epoch': 25.0}
{'train_runtime': 10.8756, 'train_samples_per_second': 22.987, 'train_steps_per_second': 22.987, 'train_loss': 2.893817138671875, 'epoch': 25.0}
{'train_runtime': 11.0506, 'train_samples_per_second': 22.623, 'train_steps_per_second': 22.623, 'train_loss': 2.9059208984375, 'epoch': 25.0}
{'train_runtime': 10.4653, 'train_samples_per_second': 23.888, 'train_steps_per_second': 23.888, 'train_loss': 2.927818359375, 'epoch': 25.0}
{'train_runtime': 10.7097, 'train_samples_per_second': 23.343, 'train_steps_per_second': 23.343, 'train_loss': 2.909608642578125, 'epoch': 25.0}
{'train_runtime': 10.5962, 'train_samples_per_second': 23.593, 'train_steps_per_second': 23.593, 'train_loss': 2.904958740234375, 'epoch': 25.0}
{'train_runtime': 10.6089, 'train_samples_per_second': 23.565, 'train_steps_per_second': 23.565, 'train_loss': 2.8830087890625, 'epoch': 25.0}

Explanations:  97%|█████████▋| 1356/1400 [1:18:43<02:33,  3.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  97%|█████████▋| 1358/1400 [1:18:44<01:17,  1.86s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  97%|█████████▋| 1359/1400 [1:18:55<03:10,  4.65s/it]

{'train_runtime': 12.8403, 'train_samples_per_second': 19.47, 'train_steps_per_second': 19.47, 'train_loss': 3.019488037109375, 'epoch': 25.0}
{'train_runtime': 12.779, 'train_samples_per_second': 19.563, 'train_steps_per_second': 19.563, 'train_loss': 3.02610107421875, 'epoch': 25.0}
{'train_runtime': 12.6953, 'train_samples_per_second': 19.692, 'train_steps_per_second': 19.692, 'train_loss': 2.996286376953125, 'epoch': 25.0}
{'train_runtime': 12.7271, 'train_samples_per_second': 19.643, 'train_steps_per_second': 19.643, 'train_loss': 3.03223291015625, 'epoch': 25.0}
{'train_runtime': 13.1119, 'train_samples_per_second': 19.067, 'train_steps_per_second': 19.067, 'train_loss': 3.0074912109375, 'epoch': 25.0}
{'train_runtime': 12.8654, 'train_samples_per_second': 19.432, 'train_steps_per_second': 19.432, 'train_loss': 3.035612060546875, 'epoch': 25.0}
{'train_runtime': 12.7453, 'train_samples_per_second': 19.615, 'train_steps_per_second': 19.615, 'train_loss': 3.013546142578125, 'epoch': 25.0}
{'train_runtime': 12.7879, 'train_samples_per_second': 19.55, 'train_steps_per_second': 19.55, 'train_loss': 3.01403369140625, 'epoch': 25.0}
{'train_runtime': 12.6627, 'train_samples_per_second': 19.743, 'train_steps_per_second': 19.743, 'train_loss': 3.047819091796875, 'epoch': 25.0}
{'train_runtime': 12.7456, 'train_samples_per_second': 19.615, 'train_steps_per_second': 19.615, 'train_loss': 3.040748779296875, 'epoch': 25.0}
{'train_runtime': 12.9224, 'train_samples_per_second': 19.346, 'train_steps_per_second': 19.346, 'train_loss': 3.0398359375, 'epoch': 25.0}
{'train_runtime': 12.9365, 'train_samples_per_second': 19.325, 'train_steps_per_second': 19.325, 'train_loss': 3.024293212890625, 'epoch': 25.0}
{'train_runtime': 13.0355, 'train_samples_per_second': 19.178, 'train_steps_per_second': 19.178, 'train_loss': 3.022507080078125, 'epoch': 25.0}
{'train_runtime': 12.8619, 'train_samples_per_second': 19.437, 'train_steps_per_second': 19.437, 'train_loss': 3.040990234375, 'epoch': 25.0}
{'train_runtime': 13.266, 'train_samples_per_second': 18.845, 'train_steps_per_second': 18.845, 'train_loss': 3.035322998046875, 'epoch': 25.0}
{'train_runtime': 13.1103, 'train_samples_per_second': 19.069, 'train_steps_per_second': 19.069, 'train_loss': 3.05174951171875, 'epoch': 25.0}
{'train_runtime': 13.195, 'train_samples_per_second': 18.947, 'train_steps_per_second': 18.947, 'train_loss': 3.043825439453125, 'epoch': 25.0}
{'train_runtime': 13.2143, 'train_samples_per_second': 18.919, 'train_steps_per_second': 18.919, 'train_loss': 2.856134033203125, 'epoch': 25.0}
{'train_runtime': 13.3877, 'train_samples_per_second': 18.674, 'train_steps_per_second': 18.674, 'train_loss': 2.880113525390625, 'epoch': 25.0}
{'train_runtime': 13.2278, 'train_samples_per_second': 18.9, 'train_steps_per_second': 18.9, 'train_loss': 2.864800537109375, 'epoch': 25.0}
{'train_runtime': 13.2607, 'train_samples_per_second': 18.853, 'train_steps_per_second': 18.853, 'train_loss': 2.84882373046875, 'epoch': 25.0}
{'train_runtime': 13.1816, 'train_samples_per_second': 18.966, 'train_steps_per_second': 18.966, 'train_loss': 2.8543056640625, 'epoch': 25.0}
{'train_runtime': 13.3172, 'train_samples_per_second': 18.773, 'train_steps_per_second': 18.773, 'train_loss': 2.8256005859375, 'epoch': 25.0}
{'train_runtime': 13.0703, 'train_samples_per_second': 19.127, 'train_steps_per_second': 19.127, 'train_loss': 2.858579345703125, 'epoch': 25.0}
{'train_runtime': 13.0681, 'train_samples_per_second': 19.131, 'train_steps_per_second': 19.131, 'train_loss': 2.8491376953125, 'epoch': 25.0}
{'train_runtime': 13.2058, 'train_samples_per_second': 18.931, 'train_steps_per_second': 18.931, 'train_loss': 2.8491142578125, 'epoch': 25.0}
{'train_runtime': 13.0874, 'train_samples_per_second': 19.102, 'train_steps_per_second': 19.102, 'train_loss': 2.85265478515625, 'epoch': 25.0}
{'train_runtime': 13.3839, 'train_samples_per_second': 18.679, 'train_steps_per_second': 18.679, 'train_loss': 2.868570068359375, 'epoch': 25.0}
{'train_runtime': 13.3265, 'train_samples_per_second': 18.76, 'train_steps_per_second': 18.76, 'train_loss': 2.87095068359375, 'epoch': 25.0}
{'train_runtime': 12.7969, 'train_samples_per_second': 19.536, 'train_steps_per_second': 19.536, 'train_loss': 2.872243896484375, 'epoch': 25.0}
{'train_runtime': 12.5763, 'train_samples_per_second': 19.879, 'train_steps_per_second': 19.879, 'train_loss': 2.870202880859375, 'epoch': 25.0}
{'train_runtime': 13.9494, 'train_samples_per_second': 17.922, 'train_steps_per_second': 17.922, 'train_loss': 2.843627685546875, 'epoch': 25.0}
{'train_runtime': 13.3845, 'train_samples_per_second': 18.678, 'train_steps_per_second': 18.678, 'train_loss': 2.846864013671875, 'epoch': 25.0}
{'train_runtime': 13.4493, 'train_samples_per_second': 18.588, 'train_steps_per_second': 18.588, 'train_loss': 2.857342529296875, 'epoch': 25.0}
{'train_runtime': 13.6708, 'train_samples_per_second': 18.287, 'train_steps_per_second': 18.287, 'train_loss': 2.853239013671875, 'epoch': 25.0}
{'train_runtime': 13.1074, 'train_samples_per_second': 19.073, 'train_steps_per_second': 19.073, 'train_loss': 2.864401611328125, 'epoch': 25.0}
{'train_runtime': 13.1184, 'train_samples_per_second': 19.057, 'train_steps_per_second': 19.057, 'train_loss': 2.844005859375, 'epoch': 25.0}
{'train_runtime': 13.2029, 'train_samples_per_second': 18.935, 'train_steps_per_second': 18.935, 'train_loss': 2.8684921875, 'epoch': 25.0}
{'train_runtime': 13.0718, 'train_samples_per_second': 19.125, 'train_steps_per_second': 19.125, 'train_loss': 2.851880615234375, 'epoch': 25.0}
{'train_runtime': 13.2297, 'train_samples_per_second': 18.897, 'train_steps_per_second': 18.897, 'train_loss': 2.842692138671875, 'epoch': 25.0}
{'train_runtime': 13.3236, 'train_samples_per_second': 18.764, 'train_steps_per_second': 18.764, 'train_loss': 2.849790771484375, 'epoch': 25.0}
{'train_runtime': 11.9503, 'train_samples_per_second': 20.92, 'train_steps_per_second': 20.92, 'train_loss': 2.92988037109375, 'epoch': 25.0}
{'train_runtime': 10.5889, 'train_samples_per_second': 23.61, 'train_steps_per_second': 23.61, 'train_loss': 2.912656005859375, 'epoch': 25.0}
{'train_runtime': 10.5867, 'train_samples_per_second': 23.615, 'train_steps_per_second': 23.615, 'train_loss': 2.8904033203125, 'epoch': 25.0}
{'train_runtime': 10.663, 'train_samples_per_second': 23.446, 'train_steps_per_second': 23.446, 'train_loss': 2.86989794921875, 'epoch': 25.0}
{'train_runtime': 10.7983, 'train_samples_per_second': 23.152, 'train_steps_per_second': 23.152, 'train_loss': 2.91098779296875, 'epoch': 25.0}
{'train_runtime': 10.7217, 'train_samples_per_second': 23.317, 'train_steps_per_second': 23.317, 'train_loss': 2.897803466796875, 'epoch': 25.0}
{'train_runtime': 10.9635, 'train_samples_per_second': 22.803, 'train_steps_per_second': 22.803, 'train_loss': 2.895560302734375, 'epoch': 25.0}
{'train_runtime': 10.7494, 'train_samples_per_second': 23.257, 'train_steps_per_second': 23.257, 'train_loss': 2.918529052734375, 'epoch': 25.0}
{'train_runtime': 10.8885, 'train_samples_per_second': 22.96, 'train_steps_per_second': 22.96, 'train_loss': 2.914974853515625, 'epoch': 25.0}
{'train_runtime': 10.8383, 'train_samples_per_second': 23.066, 'train_steps_per_second': 23.066, 'train_loss': 2.890284912109375, 'epoch': 25.0}
{'train_runtime': 10.729, 'train_samples_per_second': 23.301, 'train_steps_per_second': 23.301, 'train_loss': 2.91095361328125, 'epoch': 25.0}
{'train_runtime': 10.4704, 'train_samples_per_second': 23.877, 'train_steps_per_second': 23.877, 'train_loss': 2.888455322265625, 'epoch': 25.0}
{'train_runtime': 10.6333, 'train_samples_per_second': 23.511, 'train_steps_per_second': 23.511, 'train_loss': 2.8660546875, 'epoch': 25.0}
{'train_runtime': 10.6907, 'train_samples_per_second': 23.385, 'train_steps_per_second': 23.385, 'train_loss': 2.934536865234375, 'epoch': 25.0}
{'train_runtime': 10.6831, 'train_samples_per_second': 23.402, 'train_steps_per_second': 23.402, 'train_loss': 2.89257470703125, 'epoch': 25.0}

Explanations:  97%|█████████▋| 1360/1400 [1:18:56<02:20,  3.51s/it]

{'train_runtime': 12.87, 'train_samples_per_second': 19.425, 'train_steps_per_second': 19.425, 'train_loss': 3.037733154296875, 'epoch': 25.0}
{'train_runtime': 12.7057, 'train_samples_per_second': 19.676, 'train_steps_per_second': 19.676, 'train_loss': 3.02370361328125, 'epoch': 25.0}
{'train_runtime': 12.7579, 'train_samples_per_second': 19.596, 'train_steps_per_second': 19.596, 'train_loss': 3.025871337890625, 'epoch': 25.0}
{'train_runtime': 12.6166, 'train_samples_per_second': 19.815, 'train_steps_per_second': 19.815, 'train_loss': 3.02807421875, 'epoch': 25.0}
{'train_runtime': 12.9292, 'train_samples_per_second': 19.336, 'train_steps_per_second': 19.336, 'train_loss': 3.00407177734375, 'epoch': 25.0}
{'train_runtime': 12.8758, 'train_samples_per_second': 19.416, 'train_steps_per_second': 19.416, 'train_loss': 3.02615185546875, 'epoch': 25.0}
{'train_runtime': 12.8532, 'train_samples_per_second': 19.45, 'train_steps_per_second': 19.45, 'train_loss': 3.020323974609375, 'epoch': 25.0}
{'train_runtime': 12.6641, 'train_samples_per_second': 19.741, 'train_steps_per_second': 19.741, 'train_loss': 2.99626953125, 'epoch': 25.0}
{'train_runtime': 12.7951, 'train_samples_per_second': 19.539, 'train_steps_per_second': 19.539, 'train_loss': 3.009502685546875, 'epoch': 25.0}
{'train_runtime': 12.7792, 'train_samples_per_second': 19.563, 'train_steps_per_second': 19.563, 'train_loss': 3.016640869140625, 'epoch': 25.0}
{'train_runtime': 12.6664, 'train_samples_per_second': 19.737, 'train_steps_per_second': 19.737, 'train_loss': 3.0298720703125, 'epoch': 25.0}
{'train_runtime': 12.9497, 'train_samples_per_second': 19.305, 'train_steps_per_second': 19.305, 'train_loss': 3.050332275390625, 'epoch': 25.0}
{'train_runtime': 13.0705, 'train_samples_per_second': 19.127, 'train_steps_per_second': 19.127, 'train_loss': 3.02459716796875, 'epoch': 25.0}
{'train_runtime': 12.9294, 'train_samples_per_second': 19.336, 'train_steps_per_second': 19.336, 'train_loss': 3.035798583984375, 'epoch': 25.0}
{'train_runtime': 13.2502, 'train_samples_per_second': 18.868, 'train_steps_per_second': 18.868, 'train_loss': 2.99309765625, 'epoch': 25.0}
{'train_runtime': 13.163, 'train_samples_per_second': 18.993, 'train_steps_per_second': 18.993, 'train_loss': 3.0089208984375, 'epoch': 25.0}
{'train_runtime': 13.124, 'train_samples_per_second': 19.049, 'train_steps_per_second': 19.049, 'train_loss': 3.0306396484375, 'epoch': 25.0}
{'train_runtime': 13.3695, 'train_samples_per_second': 18.699, 'train_steps_per_second': 18.699, 'train_loss': 2.85092138671875, 'epoch': 25.0}
{'train_runtime': 13.3821, 'train_samples_per_second': 18.682, 'train_steps_per_second': 18.682, 'train_loss': 2.853646240234375, 'epoch': 25.0}
{'train_runtime': 13.1658, 'train_samples_per_second': 18.989, 'train_steps_per_second': 18.989, 'train_loss': 2.857322509765625, 'epoch': 25.0}
{'train_runtime': 13.2725, 'train_samples_per_second': 18.836, 'train_steps_per_second': 18.836, 'train_loss': 2.86774462890625, 'epoch': 25.0}
{'train_runtime': 13.3659, 'train_samples_per_second': 18.704, 'train_steps_per_second': 18.704, 'train_loss': 2.8597119140625, 'epoch': 25.0}
{'train_runtime': 13.1817, 'train_samples_per_second': 18.966, 'train_steps_per_second': 18.966, 'train_loss': 2.8746435546875, 'epoch': 25.0}
{'train_runtime': 13.006, 'train_samples_per_second': 19.222, 'train_steps_per_second': 19.222, 'train_loss': 2.8635029296875, 'epoch': 25.0}
{'train_runtime': 12.7669, 'train_samples_per_second': 19.582, 'train_steps_per_second': 19.582, 'train_loss': 2.862339599609375, 'epoch': 25.0}
{'train_runtime': 12.9508, 'train_samples_per_second': 19.304, 'train_steps_per_second': 19.304, 'train_loss': 2.858158935546875, 'epoch': 25.0}
{'train_runtime': 12.7775, 'train_samples_per_second': 19.566, 'train_steps_per_second': 19.566, 'train_loss': 2.852138916015625, 'epoch': 25.0}
{'train_runtime': 12.6321, 'train_samples_per_second': 19.791, 'train_steps_per_second': 19.791, 'train_loss': 2.861284423828125, 'epoch': 25.0}
{'train_runtime': 12.7281, 'train_samples_per_second': 19.642, 'train_steps_per_second': 19.642, 'train_loss': 2.854296142578125, 'epoch': 25.0}
{'train_runtime': 11.8333, 'train_samples_per_second': 21.127, 'train_steps_per_second': 21.127, 'train_loss': 2.848267333984375, 'epoch': 25.0}
{'train_runtime': 12.8437, 'train_samples_per_second': 19.465, 'train_steps_per_second': 19.465, 'train_loss': 2.861091796875, 'epoch': 25.0}
{'train_runtime': 13.6739, 'train_samples_per_second': 18.283, 'train_steps_per_second': 18.283, 'train_loss': 2.87897119140625, 'epoch': 25.0}
{'train_runtime': 12.1512, 'train_samples_per_second': 20.574, 'train_steps_per_second': 20.574, 'train_loss': 2.8378388671875, 'epoch': 25.0}
{'train_runtime': 12.4459, 'train_samples_per_second': 20.087, 'train_steps_per_second': 20.087, 'train_loss': 2.863862060546875, 'epoch': 25.0}
{'train_runtime': 11.9181, 'train_samples_per_second': 20.977, 'train_steps_per_second': 20.977, 'train_loss': 2.85697705078125, 'epoch': 25.0}
{'train_runtime': 12.0799, 'train_samples_per_second': 20.696, 'train_steps_per_second': 20.696, 'train_loss': 2.871141357421875, 'epoch': 25.0}
{'train_runtime': 12.1203, 'train_samples_per_second': 20.627, 'train_steps_per_second': 20.627, 'train_loss': 2.862833251953125, 'epoch': 25.0}
{'train_runtime': 12.2009, 'train_samples_per_second': 20.49, 'train_steps_per_second': 20.49, 'train_loss': 2.864693359375, 'epoch': 25.0}
{'train_runtime': 12.4535, 'train_samples_per_second': 20.075, 'train_steps_per_second': 20.075, 'train_loss': 2.854702880859375, 'epoch': 25.0}
{'train_runtime': 12.321, 'train_samples_per_second': 20.291, 'train_steps_per_second': 20.291, 'train_loss': 2.850939208984375, 'epoch': 25.0}
{'train_runtime': 12.2817, 'train_samples_per_second': 20.355, 'train_steps_per_second': 20.355, 'train_loss': 2.85384716796875, 'epoch': 25.0}
{'train_runtime': 12.2602, 'train_samples_per_second': 20.391, 'train_steps_per_second': 20.391, 'train_loss': 2.851703369140625, 'epoch': 25.0}
{'train_runtime': 11.4463, 'train_samples_per_second': 21.841, 'train_steps_per_second': 21.841, 'train_loss': 2.910501953125, 'epoch': 25.0}
{'train_runtime': 10.4184, 'train_samples_per_second': 23.996, 'train_steps_per_second': 23.996, 'train_loss': 2.883151123046875, 'epoch': 25.0}
{'train_runtime': 10.4775, 'train_samples_per_second': 23.861, 'train_steps_per_second': 23.861, 'train_loss': 2.874904296875, 'epoch': 25.0}
{'train_runtime': 10.5603, 'train_samples_per_second': 23.674, 'train_steps_per_second': 23.674, 'train_loss': 2.91777001953125, 'epoch': 25.0}
{'train_runtime': 10.6079, 'train_samples_per_second': 23.567, 'train_steps_per_second': 23.567, 'train_loss': 2.930187744140625, 'epoch': 25.0}
{'train_runtime': 10.811, 'train_samples_per_second': 23.125, 'train_steps_per_second': 23.125, 'train_loss': 2.89883544921875, 'epoch': 25.0}
{'train_runtime': 10.879, 'train_samples_per_second': 22.98, 'train_steps_per_second': 22.98, 'train_loss': 2.9418388671875, 'epoch': 25.0}
{'train_runtime': 10.5259, 'train_samples_per_second': 23.751, 'train_steps_per_second': 23.751, 'train_loss': 2.87619970703125, 'epoch': 25.0}
{'train_runtime': 10.6083, 'train_samples_per_second': 23.566, 'train_steps_per_second': 23.566, 'train_loss': 2.918427001953125, 'epoch': 25.0}
{'train_runtime': 10.8114, 'train_samples_per_second': 23.124, 'train_steps_per_second': 23.124, 'train_loss': 2.9290087890625, 'epoch': 25.0}
{'train_runtime': 10.8968, 'train_samples_per_second': 22.942, 'train_steps_per_second': 22.942, 'train_loss': 2.908483642578125, 'epoch': 25.0}
{'train_runtime': 10.5484, 'train_samples_per_second': 23.7, 'train_steps_per_second': 23.7, 'train_loss': 2.912230224609375, 'epoch': 25.0}
{'train_runtime': 10.631, 'train_samples_per_second': 23.516, 'train_steps_per_second': 23.516, 'train_loss': 2.90797900390625, 'epoch': 25.0}
{'train_runtime': 10.5917, 'train_samples_per_second': 23.603, 'train_steps_per_second': 23.603, 'train_loss': 2.898402587890625, 'epoch': 25.0}
{'train_runtime': 10.6708, 'train_samples_per_second': 23.428, 'train_steps_per_second': 23.428, 'train_loss': 2.930923583984375, 'epoch': 25.0}

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  97%|█████████▋| 1362/1400 [1:18:56<01:12,  1.91s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 12.4051, 'train_samples_per_second': 20.153, 'train_steps_per_second': 20.153, 'train_loss': 3.0230498046875, 'epoch': 25.0}
{'train_runtime': 12.4929, 'train_samples_per_second': 20.011, 'train_steps_per_second': 20.011, 'train_loss': 3.03390771484375, 'epoch': 25.0}
{'train_runtime': 12.4833, 'train_samples_per_second': 20.027, 'train_steps_per_second': 20.027, 'train_loss': 3.023334228515625, 'epoch': 25.0}
{'train_runtime': 12.4229, 'train_samples_per_second': 20.124, 'train_steps_per_second': 20.124, 'train_loss': 3.033822021484375, 'epoch': 25.0}
{'train_runtime': 12.3396, 'train_samples_per_second': 20.26, 'train_steps_per_second': 20.26, 'train_loss': 3.017541015625, 'epoch': 25.0}
{'train_runtime': 12.3986, 'train_samples_per_second': 20.163, 'train_steps_per_second': 20.163, 'train_loss': 3.039700439453125, 'epoch': 25.0}
{'train_runtime': 12.2884, 'train_samples_per_second': 20.344, 'train_steps_per_second': 20.344, 'train_loss': 3.0427607421875, 'epoch': 25.0}
{'train_runtime': 12.3049, 'train_samples_per_second': 20.317, 'train_steps_per_second': 20.317, 'train_loss': 3.03059521484375, 'epoch': 25.0}
{'train_runtime': 12.4647, 'train_samples_per_second': 20.057, 'train_steps_per_second': 20.057, 'train_loss': 3.029901123046875, 'epoch': 25.0}
{'train_runtime': 12.4763, 'train_samples_per_second': 20.038, 'train_steps_per_second': 20.038, 'train_loss': 3.041075927734375, 'epoch': 25.0}
{'train_runtime': 12.3872, 'train_samples_per_second': 20.182, 'train_steps_per_second': 20.182, 'train_loss': 3.05076171875, 'epoch': 25.0}
{'train_runtime': 12.3793, 'train_samples_per_second': 20.195, 'train_steps_per_second': 20.195, 'train_loss': 3.02380419921875, 'epoch': 25.0}
{'train_runtime': 12.3659, 'train_samples_per_second': 20.217, 'train_steps_per_second': 20.217, 'train_loss': 3.06043359375, 'epoch': 25.0}
{'train_runtime': 12.306, 'train_samples_per_second': 20.315, 'train_steps_per_second': 20.315, 'train_loss': 3.008908203125, 'epoch': 25.0}
{'train_runtime': 12.5199, 'train_samples_per_second': 19.968, 'train_steps_per_second': 19.968, 'train_loss': 3.0501875, 'epoch': 25.0}
{'train_runtime': 12.7234, 'train_samples_per_second': 19.649, 'train_steps_per_second': 19.649, 'train_loss': 2.842422607421875, 'epoch': 25.0}
{'train_runtime': 12.9651, 'train_samples_per_second': 19.283, 'train_steps_per_second': 19.283, 'train_loss': 2.868582275390625, 'epoch': 25.0}
{'train_runtime': 13.2206, 'train_samples_per_second': 18.91, 'train_steps_per_second': 18.91, 'train_loss': 2.85526123046875, 'epoch': 25.0}
{'train_runtime': 13.0128, 'train_samples_per_second': 19.212, 'train_steps_per_second': 19.212, 'train_loss': 2.873212646484375, 'epoch': 25.0}
{'train_runtime': 13.2685, 'train_samples_per_second': 18.842, 'train_steps_per_second': 18.842, 'train_loss': 2.85449365234375, 'epoch': 25.0}
{'train_runtime': 13.1884, 'train_samples_per_second': 18.956, 'train_steps_per_second': 18.956, 'train_loss': 2.85662939453125, 'epoch': 25.0}
{'train_runtime': 13.3592, 'train_samples_per_second': 18.714, 'train_steps_per_second': 18.714, 'train_loss': 2.831178466796875, 'epoch': 25.0}
{'train_runtime': 13.1455, 'train_samples_per_second': 19.018, 'train_steps_per_second': 19.018, 'train_loss': 2.8595908203125, 'epoch': 25.0}
{'train_runtime': 13.0244, 'train_samples_per_second': 19.195, 'train_steps_per_second': 19.195, 'train_loss': 2.870112060546875, 'epoch': 25.0}
{'train_runtime': 13.1713, 'train_samples_per_second': 18.981, 'train_steps_per_second': 18.981, 'train_loss': 2.8415927734375, 'epoch': 25.0}
{'train_runtime': 13.1278, 'train_samples_per_second': 19.044, 'train_steps_per_second': 19.044, 'train_loss': 2.849382080078125, 'epoch': 25.0}
{'train_runtime': 12.8452, 'train_samples_per_second': 19.462, 'train_steps_per_second': 19.462, 'train_loss': 2.85044580078125, 'epoch': 25.0}
{'train_runtime': 13.6005, 'train_samples_per_second': 18.382, 'train_steps_per_second': 18.382, 'train_loss': 2.859537353515625, 'epoch': 25.0}
{'train_runtime': 13.01, 'train_samples_per_second': 19.216, 'train_steps_per_second': 19.216, 'train_loss': 2.86252197265625, 'epoch': 25.0}
{'train_runtime': 12.9092, 'train_samples_per_second': 19.366, 'train_steps_per_second': 19.366, 'train_loss': 2.872384033203125, 'epoch': 25.0}
{'train_runtime': 12.9444, 'train_samples_per_second': 19.313, 'train_steps_per_second': 19.313, 'train_loss': 2.854878662109375, 'epoch': 25.0}
{'train_runtime': 13.2786, 'train_samples_per_second': 18.827, 'train_steps_per_second': 18.827, 'train_loss': 2.848161865234375, 'epoch': 25.0}
{'train_runtime': 13.7535, 'train_samples_per_second': 18.177, 'train_steps_per_second': 18.177, 'train_loss': 2.86050244140625, 'epoch': 25.0}
{'train_runtime': 13.4216, 'train_samples_per_second': 18.627, 'train_steps_per_second': 18.627, 'train_loss': 2.84347021484375, 'epoch': 25.0}
{'train_runtime': 12.9775, 'train_samples_per_second': 19.264, 'train_steps_per_second': 19.264, 'train_loss': 2.845587646484375, 'epoch': 25.0}
{'train_runtime': 13.1571, 'train_samples_per_second': 19.001, 'train_steps_per_second': 19.001, 'train_loss': 2.866931884765625, 'epoch': 25.0}
{'train_runtime': 13.2489, 'train_samples_per_second': 18.87, 'train_steps_per_second': 18.87, 'train_loss': 2.850189208984375, 'epoch': 25.0}
{'train_runtime': 13.1, 'train_samples_per_second': 19.084, 'train_steps_per_second': 19.084, 'train_loss': 2.883968505859375, 'epoch': 25.0}
{'train_runtime': 13.4063, 'train_samples_per_second': 18.648, 'train_steps_per_second': 18.648, 'train_loss': 2.868805908203125, 'epoch': 25.0}
{'train_runtime': 13.3535, 'train_samples_per_second': 18.722, 'train_steps_per_second': 18.722, 'train_loss': 2.85001123046875, 'epoch': 25.0}
{'train_runtime': 12.0741, 'train_samples_per_second': 20.706, 'train_steps_per_second': 20.706, 'train_loss': 2.864337646484375, 'epoch': 25.0}
{'train_runtime': 10.6331, 'train_samples_per_second': 23.511, 'train_steps_per_second': 23.511, 'train_loss': 2.9099169921875, 'epoch': 25.0}
{'train_runtime': 10.5816, 'train_samples_per_second': 23.626, 'train_steps_per_second': 23.626, 'train_loss': 2.885240234375, 'epoch': 25.0}
{'train_runtime': 10.7388, 'train_samples_per_second': 23.28, 'train_steps_per_second': 23.28, 'train_loss': 2.902967529296875, 'epoch': 25.0}
{'train_runtime': 10.7634, 'train_samples_per_second': 23.227, 'train_steps_per_second': 23.227, 'train_loss': 2.877326904296875, 'epoch': 25.0}
{'train_runtime': 10.5924, 'train_samples_per_second': 23.602, 'train_steps_per_second': 23.602, 'train_loss': 2.950254150390625, 'epoch': 25.0}
{'train_runtime': 11.0565, 'train_samples_per_second': 22.611, 'train_steps_per_second': 22.611, 'train_loss': 2.927467041015625, 'epoch': 25.0}
{'train_runtime': 10.8795, 'train_samples_per_second': 22.979, 'train_steps_per_second': 22.979, 'train_loss': 2.9073681640625, 'epoch': 25.0}
{'train_runtime': 10.708, 'train_samples_per_second': 23.347, 'train_steps_per_second': 23.347, 'train_loss': 2.89552294921875, 'epoch': 25.0}
{'train_runtime': 10.7864, 'train_samples_per_second': 23.177, 'train_steps_per_second': 23.177, 'train_loss': 2.902495849609375, 'epoch': 25.0}
{'train_runtime': 10.7599, 'train_samples_per_second': 23.234, 'train_steps_per_second': 23.234, 'train_loss': 2.8923759765625, 'epoch': 25.0}
{'train_runtime': 10.4563, 'train_samples_per_second': 23.909, 'train_steps_per_second': 23.909, 'train_loss': 2.908241455078125, 'epoch': 25.0}
{'train_runtime': 10.7106, 'train_samples_per_second': 23.341, 'train_steps_per_second': 23.341, 'train_loss': 2.927172119140625, 'epoch': 25.0}
{'train_runtime': 10.7782, 'train_samples_per_second': 23.195, 'train_steps_per_second': 23.195, 'train_loss': 2.924296630859375, 'epoch': 25.0}
{'train_runtime': 10.5239, 'train_samples_per_second': 23.755, 'train_steps_per_second': 23.755, 'train_loss': 2.95183544921875, 'epoch': 25.0}
{'train_runtime': 10.616, 'train_samples_per_second': 23.549, 'train_steps_per_second': 23.549, 'train_loss': 2.894507568359375, 'epoch': 25.0}

Explanations:  97%|█████████▋| 1364/1400 [1:19:08<02:04,  3.46s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  98%|█████████▊| 1366/1400 [1:19:09<01:04,  1.89s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  98%|█████████▊| 1367/1400 [1:19:20<02:29,  4.54s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  98%|█████████▊| 1370/1400 [1:19:22<00:57,  1.91s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  98%|█████████▊| 1371/1400 [1:19:32<02:10,  4.49s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  98%|█████████▊| 1374/1400 [1:19:34<00:49,  1.91s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  98%|█████████▊| 1375/1400 [1:19:45<01:51,  4.44s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  98%|█████████▊| 1377/1400 [1:19:47<01:01,  2.67s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  98%|█████████▊| 1379/1400 [1:19:57<01:17,  3.71s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  99%|█████████▊| 1381/1400 [1:19:59<00:49,  2.60s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  99%|█████████▉| 1383/1400 [1:20:09<00:59,  3.47s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  99%|█████████▉| 1385/1400 [1:20:12<00:38,  2.59s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  99%|█████████▉| 1387/1400 [1:20:21<00:43,  3.36s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  99%|█████████▉| 1390/1400 [1:20:25<00:19,  2.00s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  99%|█████████▉| 1391/1400 [1:20:33<00:33,  3.69s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations: 100%|█████████▉| 1394/1400 [1:20:38<00:13,  2.20s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations: 100%|█████████▉| 1395/1400 [1:20:46<00:17,  3.58s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations: 100%|█████████▉| 1398/1400 [1:20:50<00:04,  2.22s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations: 100%|██████████| 1400/1400 [1:20:59<00:00,  3.47s/it]

{'train_runtime': 10.7851, 'train_samples_per_second': 23.18, 'train_steps_per_second': 23.18, 'train_loss': 2.895861328125, 'epoch': 25.0}
{'train_runtime': 10.5238, 'train_samples_per_second': 23.756, 'train_steps_per_second': 23.756, 'train_loss': 2.90620166015625, 'epoch': 25.0}
{'train_runtime': 10.6068, 'train_samples_per_second': 23.57, 'train_steps_per_second': 23.57, 'train_loss': 2.913507080078125, 'epoch': 25.0}
{'train_runtime': 10.7631, 'train_samples_per_second': 23.227, 'train_steps_per_second': 23.227, 'train_loss': 2.901261474609375, 'epoch': 25.0}
{'train_runtime': 10.7335, 'train_samples_per_second': 23.292, 'train_steps_per_second': 23.292, 'train_loss': 2.894990234375, 'epoch': 25.0}
{'train_runtime': 10.5238, 'train_samples_per_second': 23.756, 'train_steps_per_second': 23.756, 'train_loss': 2.93260546875, 'epoch': 25.0}
{'train_runtime': 10.5664, 'train_samples_per_second': 23.66, 'train_steps_per_second': 23.66, 'train_loss': 2.8764775390625, 'epoch': 25.0}
{'train_runtime': 10.6905, 'train_samples_per_second': 23.385, 'train_steps_per_second': 23.385, 'train_loss': 2.900634521484375, 'epoch': 25.0}
{'train_runtime': 10.5904, 'train_samples_per_second': 23.606, 'train_steps_per_second': 23.606, 'train_loss': 2.889440673828125, 'epoch': 25.0}
{'train_runtime': 10.4878, 'train_samples_per_second': 23.837, 'train_steps_per_second': 23.837, 'train_loss': 2.93038330078125, 'epoch': 25.0}
{'train_runtime': 7.4495, 'train_samples_per_second': 33.559, 'train_steps_per_second': 33.559, 'train_loss': 2.901654541015625, 'epoch': 25.0}
{'train_runtime': 10.8074, 'train_samples_per_second': 23.132, 'train_steps_per_second': 23.132, 'train_loss': 2.905463623046875, 'epoch': 25.0}
{'train_runtime': 10.4962, 'train_samples_per_second': 23.818, 'train_steps_per_second': 23.818, 'train_loss': 2.911648681640625, 'epoch': 25.0}
{'train_runtime': 10.681, 'train_samples_per_second': 23.406, 'train_steps_per_second': 23.406, 'train_loss': 2.9174169921875, 'epoch': 25.0}
{'train_runtime': 10.6698, 'train_samples_per_second': 23.431, 'train_steps_per_second': 23.431, 'train_loss': 2.949204833984375, 'epoch': 25.0}
{'train_runtime': 10.673, 'train_samples_per_second': 23.424, 'train_steps_per_second': 23.424, 'train_loss': 2.91939453125, 'epoch': 25.0}
{'train_runtime': 10.5894, 'train_samples_per_second': 23.609, 'train_steps_per_second': 23.609, 'train_loss': 2.93447216796875, 'epoch': 25.0}
{'train_runtime': 10.5722, 'train_samples_per_second': 23.647, 'train_steps_per_second': 23.647, 'train_loss': 2.878014892578125, 'epoch': 25.0}
{'train_runtime': 10.6835, 'train_samples_per_second': 23.401, 'train_steps_per_second': 23.401, 'train_loss': 2.887260498046875, 'epoch': 25.0}
{'train_runtime': 10.7084, 'train_samples_per_second': 23.346, 'train_steps_per_second': 23.346, 'train_loss': 2.91813623046875, 'epoch': 25.0}
{'train_runtime': 10.4627, 'train_samples_per_second': 23.894, 'train_steps_per_second': 23.894, 'train_loss': 2.901066162109375, 'epoch': 25.0}

{'train_runtime': 10.7548, 'train_samples_per_second': 23.245, 'train_steps_per_second': 23.245, 'train_loss': 2.903241455078125, 'epoch': 25.0}
{'train_runtime': 10.5084, 'train_samples_per_second': 23.79, 'train_steps_per_second': 23.79, 'train_loss': 2.9031953125, 'epoch': 25.0}
{'train_runtime': 10.6172, 'train_samples_per_second': 23.547, 'train_steps_per_second': 23.547, 'train_loss': 2.921139892578125, 'epoch': 25.0}
{'train_runtime': 10.7087, 'train_samples_per_second': 23.346, 'train_steps_per_second': 23.346, 'train_loss': 2.909558349609375, 'epoch': 25.0}
{'train_runtime': 10.7352, 'train_samples_per_second': 23.288, 'train_steps_per_second': 23.288, 'train_loss': 2.896293701171875, 'epoch': 25.0}
{'train_runtime': 10.5942, 'train_samples_per_second': 23.598, 'train_steps_per_second': 23.598, 'train_loss': 2.91816796875, 'epoch': 25.0}
{'train_runtime': 10.5574, 'train_samples_per_second': 23.68, 'train_steps_per_second': 23.68, 'train_loss': 2.8889453125, 'epoch': 25.0}
{'train_runtime': 10.5349, 'train_samples_per_second': 23.731, 'train_steps_per_second': 23.731, 'train_loss': 2.95298779296875, 'epoch': 25.0}
{'train_runtime': 10.5928, 'train_samples_per_second': 23.601, 'train_steps_per_second': 23.601, 'train_loss': 2.922119140625, 'epoch': 25.0}
{'train_runtime': 10.4697, 'train_samples_per_second': 23.878, 'train_steps_per_second': 23.878, 'train_loss': 2.901862548828125, 'epoch': 25.0}
{'train_runtime': 10.5289, 'train_samples_per_second': 23.744, 'train_steps_per_second': 23.744, 'train_loss': 2.903522705078125, 'epoch': 25.0}
{'train_runtime': 10.5005, 'train_samples_per_second': 23.808, 'train_steps_per_second': 23.808, 'train_loss': 2.9254833984375, 'epoch': 25.0}
{'train_runtime': 10.4877, 'train_samples_per_second': 23.837, 'train_steps_per_second': 23.837, 'train_loss': 2.894380126953125, 'epoch': 25.0}
{'train_runtime': 10.4049, 'train_samples_per_second': 24.027, 'train_steps_per_second': 24.027, 'train_loss': 2.902352294921875, 'epoch': 25.0}
{'train_runtime': 10.2049, 'train_samples_per_second': 24.498, 'train_steps_per_second': 24.498, 'train_loss': 2.875192138671875, 'epoch': 25.0}
{'train_runtime': 10.1086, 'train_samples_per_second': 24.731, 'train_steps_per_second': 24.731, 'train_loss': 2.8951474609375, 'epoch': 25.0}
{'train_runtime': 10.1535, 'train_samples_per_second': 24.622, 'train_steps_per_second': 24.622, 'train_loss': 2.92983642578125, 'epoch': 25.0}
{'train_runtime': 10.0782, 'train_samples_per_second': 24.806, 'train_steps_per_second': 24.806, 'train_loss': 2.91432861328125, 'epoch': 25.0}
{'train_runtime': 10.3872, 'train_samples_per_second': 24.068, 'train_steps_per_second': 24.068, 'train_loss': 2.89958984375, 'epoch': 25.0}
{'train_runtime': 8.359, 'train_samples_per_second': 29.908, 'train_steps_per_second': 29.908, 'train_loss': 2.915244873046875, 'epoch': 25.0}

[INFO] PyTorch version 2.7.0+cu126 available.
[INFO] PyTorch version 2.7.0+cu126 available.
[INFO] PyTorch version 2.7.0+cu126 available.
[INFO] PyTorch version 2.7.0+cu126 available.
Explanations:   0%|          | 0/1400 [00:00<?, ?it/s]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   0%|          | 2/1400 [00:16<2:43:08,  7.00s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   0%|          | 7/1400 [00:31<1:12:45,  3.13s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   1%|          | 8/1400 [00:32<55:02,  2.37s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   1%|          | 10/1400 [00:46<1:35:54,  4.14s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   1%|          | 12/1400 [00:47<52:29,  2.27s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   1%|          | 14/1400 [01:01<1:33:23,  4.04s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   1%|          | 16/1400 [01:02<50:23,  2.18s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   1%|▏         | 18/1400 [01:15<1:31:48,  3.99s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   1%|▏         | 19/1400 [01:16<1:10:12,  3.05s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   1%|▏         | 20/1400 [01:16<51:00,  2.22s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 22/1400 [01:30<1:31:05,  3.97s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 24/1400 [01:31<50:39,  2.21s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 25/1400 [01:43<2:01:46,  5.31s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 28/1400 [01:45<50:52,  2.23s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 29/1400 [01:57<1:57:43,  5.15s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 32/1400 [02:00<50:06,  2.20s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▏         | 33/1400 [02:12<1:55:29,  5.07s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   2%|▎         | 35/1400 [02:14<1:10:02,  3.08s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 36/1400 [02:14<50:43,  2.23s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 37/1400 [02:26<1:55:14,  5.07s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 40/1400 [02:29<50:43,  2.24s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 41/1400 [02:40<1:52:05,  4.95s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 44/1400 [02:43<50:52,  2.25s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 45/1400 [02:54<1:50:57,  4.91s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   3%|▎         | 48/1400 [02:58<50:26,  2.24s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▎         | 49/1400 [03:08<1:47:58,  4.80s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▎         | 51/1400 [03:12<1:10:32,  3.14s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▎         | 52/1400 [03:12<51:49,  2.31s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 53/1400 [03:22<1:42:19,  4.56s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 55/1400 [03:26<1:11:51,  3.21s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 56/1400 [03:26<52:02,  2.32s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 57/1400 [03:36<1:37:48,  4.37s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 58/1400 [03:39<1:34:22,  4.22s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 60/1400 [03:41<52:25,  2.35s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 61/1400 [03:50<1:35:28,  4.28s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   4%|▍         | 62/1400 [03:53<1:32:02,  4.13s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:   5%|▍         | 64/1400 [03:55<55:30,  2.49s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 13.4971, 'train_samples_per_second': 18.523, 'train_steps_per_second': 18.523, 'train_loss': 3.020321533203125, 'epoch': 25.0}
{'train_runtime': 12.8957, 'train_samples_per_second': 19.386, 'train_steps_per_second': 19.386, 'train_loss': 3.02488330078125, 'epoch': 25.0}
{'train_runtime': 12.9016, 'train_samples_per_second': 19.377, 'train_steps_per_second': 19.377, 'train_loss': 3.03454638671875, 'epoch': 25.0}
{'train_runtime': 12.5831, 'train_samples_per_second': 19.868, 'train_steps_per_second': 19.868, 'train_loss': 3.013309814453125, 'epoch': 25.0}
{'train_runtime': 12.4984, 'train_samples_per_second': 20.003, 'train_steps_per_second': 20.003, 'train_loss': 3.04581005859375, 'epoch': 25.0}
{'train_runtime': 12.5207, 'train_samples_per_second': 19.967, 'train_steps_per_second': 19.967, 'train_loss': 3.037209716796875, 'epoch': 25.0}
{'train_runtime': 12.6975, 'train_samples_per_second': 19.689, 'train_steps_per_second': 19.689, 'train_loss': 3.012394775390625, 'epoch': 25.0}
{'train_runtime': 12.4667, 'train_samples_per_second': 20.053, 'train_steps_per_second': 20.053, 'train_loss': 3.035552490234375, 'epoch': 25.0}
{'train_runtime': 12.536, 'train_samples_per_second': 19.943, 'train_steps_per_second': 19.943, 'train_loss': 3.0412421875, 'epoch': 25.0}
{'train_runtime': 12.3488, 'train_samples_per_second': 20.245, 'train_steps_per_second': 20.245, 'train_loss': 3.016673583984375, 'epoch': 25.0}
{'train_runtime': 12.3774, 'train_samples_per_second': 20.198, 'train_steps_per_second': 20.198, 'train_loss': 3.01317919921875, 'epoch': 25.0}
{'train_runtime': 12.3065, 'train_samples_per_second': 20.314, 'train_steps_per_second': 20.314, 'train_loss': 3.05183251953125, 'epoch': 25.0}
{'train_runtime': 12.3742, 'train_samples_per_second': 20.203, 'train_steps_per_second': 20.203, 'train_loss': 3.022738037109375, 'epoch': 25.0}
{'train_runtime': 12.2506, 'train_samples_per_second': 20.407, 'train_steps_per_second': 20.407, 'train_loss': 3.054850341796875, 'epoch': 25.0}
{'train_runtime': 12.1712, 'train_samples_per_second': 20.54, 'train_steps_per_second': 20.54, 'train_loss': 3.043573486328125, 'epoch': 25.0}
{'train_runtime': 11.8566, 'train_samples_per_second': 21.085, 'train_steps_per_second': 21.085, 'train_loss': 3.041264892578125, 'epoch': 25.0}
{'train_runtime': 11.8974, 'train_samples_per_second': 21.013, 'train_steps_per_second': 21.013, 'train_loss': 3.014261474609375, 'epoch': 25.0}
{'train_runtime': 11.7436, 'train_samples_per_second': 21.288, 'train_steps_per_second': 21.288, 'train_loss': 3.001099609375, 'epoch': 25.0}
{'train_runtime': 11.6227, 'train_samples_per_second': 21.51, 'train_steps_per_second': 21.51, 'train_loss': 3.029388671875, 'epoch': 25.0}
{'train_runtime': 11.6383, 'train_samples_per_second': 21.481, 'train_steps_per_second': 21.481, 'train_loss': 3.042154052734375, 'epoch': 25.0}
{'train_runtime': 11.823, 'train_samples_per_second': 21.145, 'train_steps_per_second': 21.145, 'train_loss': 3.02864208984375, 'epoch': 25.0}
{'train_runtime': 11.6122, 'train_samples_per_second': 21.529, 'train_steps_per_second': 21.529, 'train_loss': 3.04756689453125, 'epoch': 25.0}
{'train_runtime': 11.702, 'train_samples_per_second': 21.364, 'train_steps_per_second': 21.364, 'train_loss': 3.025815673828125, 'epoch': 25.0}
{'train_runtime': 11.5602, 'train_samples_per_second': 21.626, 'train_steps_per_second': 21.626, 'train_loss': 3.014894287109375, 'epoch': 25.0}
{'train_runtime': 11.5356, 'train_samples_per_second': 21.672, 'train_steps_per_second': 21.672, 'train_loss': 3.023600830078125, 'epoch': 25.0}
{'train_runtime': 11.6383, 'train_samples_per_second': 21.481, 'train_steps_per_second': 21.481, 'train_loss': 2.845160888671875, 'epoch': 25.0}
{'train_runtime': 11.359, 'train_samples_per_second': 22.009, 'train_steps_per_second': 22.009, 'train_loss': 2.858740966796875, 'epoch': 25.0}
{'train_runtime': 11.4809, 'train_samples_per_second': 21.775, 'train_steps_per_second': 21.775, 'train_loss': 2.8501650390625, 'epoch': 25.0}
{'train_runtime': 11.4059, 'train_samples_per_second': 21.919, 'train_steps_per_second': 21.919, 'train_loss': 2.82864208984375, 'epoch': 25.0}
{'train_runtime': 11.3154, 'train_samples_per_second': 22.094, 'train_steps_per_second': 22.094, 'train_loss': 2.86043896484375, 'epoch': 25.0}
{'train_runtime': 11.4628, 'train_samples_per_second': 21.81, 'train_steps_per_second': 21.81, 'train_loss': 2.856185302734375, 'epoch': 25.0}
{'train_runtime': 11.3436, 'train_samples_per_second': 22.039, 'train_steps_per_second': 22.039, 'train_loss': 2.8636064453125, 'epoch': 25.0}
{'train_runtime': 11.4494, 'train_samples_per_second': 21.835, 'train_steps_per_second': 21.835, 'train_loss': 2.83784814453125, 'epoch': 25.0}
{'train_runtime': 11.3725, 'train_samples_per_second': 21.983, 'train_steps_per_second': 21.983, 'train_loss': 2.83747802734375, 'epoch': 25.0}
{'train_runtime': 11.4067, 'train_samples_per_second': 21.917, 'train_steps_per_second': 21.917, 'train_loss': 2.8404228515625, 'epoch': 25.0}
{'train_runtime': 11.4864, 'train_samples_per_second': 21.765, 'train_steps_per_second': 21.765, 'train_loss': 2.883263671875, 'epoch': 25.0}
{'train_runtime': 11.2965, 'train_samples_per_second': 22.131, 'train_steps_per_second': 22.131, 'train_loss': 2.886956298828125, 'epoch': 25.0}
{'train_runtime': 11.3239, 'train_samples_per_second': 22.077, 'train_steps_per_second': 22.077, 'train_loss': 2.85762939453125, 'epoch': 25.0}
{'train_runtime': 11.2994, 'train_samples_per_second': 22.125, 'train_steps_per_second': 22.125, 'train_loss': 2.8526669921875, 'epoch': 25.0}
{'train_runtime': 11.1925, 'train_samples_per_second': 22.336, 'train_steps_per_second': 22.336, 'train_loss': 2.839646484375, 'epoch': 25.0}
{'train_runtime': 11.4115, 'train_samples_per_second': 21.908, 'train_steps_per_second': 21.908, 'train_loss': 2.856880859375, 'epoch': 25.0}
{'train_runtime': 11.3896, 'train_samples_per_second': 21.95, 'train_steps_per_second': 21.95, 'train_loss': 2.8659833984375, 'epoch': 25.0}
{'train_runtime': 11.428, 'train_samples_per_second': 21.876, 'train_steps_per_second': 21.876, 'train_loss': 2.8305654296875, 'epoch': 25.0}
{'train_runtime': 11.5069, 'train_samples_per_second': 21.726, 'train_steps_per_second': 21.726, 'train_loss': 2.855632080078125, 'epoch': 25.0}
{'train_runtime': 11.895, 'train_samples_per_second': 21.017, 'train_steps_per_second': 21.017, 'train_loss': 2.850436767578125, 'epoch': 25.0}
{'train_runtime': 12.1345, 'train_samples_per_second': 20.602, 'train_steps_per_second': 20.602, 'train_loss': 2.854595947265625, 'epoch': 25.0}
{'train_runtime': 11.918, 'train_samples_per_second': 20.977, 'train_steps_per_second': 20.977, 'train_loss': 2.8577294921875, 'epoch': 25.0}
{'train_runtime': 11.9093, 'train_samples_per_second': 20.992, 'train_steps_per_second': 20.992, 'train_loss': 2.858503173828125, 'epoch': 25.0}
{'train_runtime': 11.9109, 'train_samples_per_second': 20.989, 'train_steps_per_second': 20.989, 'train_loss': 2.853292724609375, 'epoch': 25.0}
{'train_runtime': 11.9438, 'train_samples_per_second': 20.931, 'train_steps_per_second': 20.931, 'train_loss': 2.840258544921875, 'epoch': 25.0}
{'train_runtime': 11.8216, 'train_samples_per_second': 21.148, 'train_steps_per_second': 21.148, 'train_loss': 2.869647216796875, 'epoch': 25.0}
{'train_runtime': 11.6849, 'train_samples_per_second': 21.395, 'train_steps_per_second': 21.395, 'train_loss': 2.8551962890625, 'epoch': 25.0}
{'train_runtime': 11.7955, 'train_samples_per_second': 21.194, 'train_steps_per_second': 21.194, 'train_loss': 2.852135009765625, 'epoch': 25.0}
{'train_runtime': 11.9363, 'train_samples_per_second': 20.945, 'train_steps_per_second': 20.945, 'train_loss': 2.881144287109375, 'epoch': 25.0}
{'train_runtime': 11.6932, 'train_samples_per_second': 21.38, 'train_steps_per_second': 21.38, 'train_loss': 2.843149169921875, 'epoch': 25.0}
{'train_runtime': 11.796, 'train_samples_per_second': 21.194, 'train_steps_per_second': 21.194, 'train_loss': 2.846792236328125, 'epoch': 25.0}

Explanations:  16%|█▌        | 226/1400 [13:16<52:36,  2.69s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  16%|█▌        | 227/1400 [13:22<1:10:28,  3.60s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  16%|█▋        | 228/1400 [13:25<1:07:15,  3.44s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 13.3688, 'train_samples_per_second': 18.7, 'train_steps_per_second': 18.7, 'train_loss': 3.027768310546875, 'epoch': 25.0}
{'train_runtime': 12.8195, 'train_samples_per_second': 19.502, 'train_steps_per_second': 19.502, 'train_loss': 3.029510498046875, 'epoch': 25.0}
{'train_runtime': 12.7476, 'train_samples_per_second': 19.612, 'train_steps_per_second': 19.612, 'train_loss': 3.009510498046875, 'epoch': 25.0}
{'train_runtime': 12.4964, 'train_samples_per_second': 20.006, 'train_steps_per_second': 20.006, 'train_loss': 3.0235361328125, 'epoch': 25.0}
{'train_runtime': 12.4685, 'train_samples_per_second': 20.051, 'train_steps_per_second': 20.051, 'train_loss': 3.03220458984375, 'epoch': 25.0}
{'train_runtime': 12.3934, 'train_samples_per_second': 20.172, 'train_steps_per_second': 20.172, 'train_loss': 3.037391845703125, 'epoch': 25.0}
{'train_runtime': 12.502, 'train_samples_per_second': 19.997, 'train_steps_per_second': 19.997, 'train_loss': 3.04010107421875, 'epoch': 25.0}
{'train_runtime': 12.0434, 'train_samples_per_second': 20.758, 'train_steps_per_second': 20.758, 'train_loss': 3.0151591796875, 'epoch': 25.0}
{'train_runtime': 12.1188, 'train_samples_per_second': 20.629, 'train_steps_per_second': 20.629, 'train_loss': 3.024504638671875, 'epoch': 25.0}
{'train_runtime': 12.1817, 'train_samples_per_second': 20.523, 'train_steps_per_second': 20.523, 'train_loss': 3.03116455078125, 'epoch': 25.0}
{'train_runtime': 11.9144, 'train_samples_per_second': 20.983, 'train_steps_per_second': 20.983, 'train_loss': 2.999746337890625, 'epoch': 25.0}
{'train_runtime': 12.2361, 'train_samples_per_second': 20.431, 'train_steps_per_second': 20.431, 'train_loss': 3.0106025390625, 'epoch': 25.0}
{'train_runtime': 11.8659, 'train_samples_per_second': 21.069, 'train_steps_per_second': 21.069, 'train_loss': 3.058836181640625, 'epoch': 25.0}
{'train_runtime': 11.5404, 'train_samples_per_second': 21.663, 'train_steps_per_second': 21.663, 'train_loss': 3.0376025390625, 'epoch': 25.0}
{'train_runtime': 11.5753, 'train_samples_per_second': 21.598, 'train_steps_per_second': 21.598, 'train_loss': 3.01535400390625, 'epoch': 25.0}
{'train_runtime': 11.8195, 'train_samples_per_second': 21.152, 'train_steps_per_second': 21.152, 'train_loss': 3.062294921875, 'epoch': 25.0}
{'train_runtime': 11.6077, 'train_samples_per_second': 21.537, 'train_steps_per_second': 21.537, 'train_loss': 3.02437744140625, 'epoch': 25.0}
{'train_runtime': 11.6767, 'train_samples_per_second': 21.41, 'train_steps_per_second': 21.41, 'train_loss': 3.04384326171875, 'epoch': 25.0}
{'train_runtime': 11.6046, 'train_samples_per_second': 21.543, 'train_steps_per_second': 21.543, 'train_loss': 3.007146728515625, 'epoch': 25.0}
{'train_runtime': 12.0079, 'train_samples_per_second': 20.82, 'train_steps_per_second': 20.82, 'train_loss': 3.007271728515625, 'epoch': 25.0}
{'train_runtime': 11.7122, 'train_samples_per_second': 21.345, 'train_steps_per_second': 21.345, 'train_loss': 3.01384033203125, 'epoch': 25.0}
{'train_runtime': 11.5566, 'train_samples_per_second': 21.633, 'train_steps_per_second': 21.633, 'train_loss': 3.044678466796875, 'epoch': 25.0}
{'train_runtime': 11.3034, 'train_samples_per_second': 22.117, 'train_steps_per_second': 22.117, 'train_loss': 3.0373408203125, 'epoch': 25.0}
{'train_runtime': 11.4513, 'train_samples_per_second': 21.832, 'train_steps_per_second': 21.832, 'train_loss': 3.01353125, 'epoch': 25.0}
{'train_runtime': 11.8107, 'train_samples_per_second': 21.167, 'train_steps_per_second': 21.167, 'train_loss': 3.0184326171875, 'epoch': 25.0}
{'train_runtime': 11.6369, 'train_samples_per_second': 21.483, 'train_steps_per_second': 21.483, 'train_loss': 2.86529736328125, 'epoch': 25.0}
{'train_runtime': 11.4999, 'train_samples_per_second': 21.739, 'train_steps_per_second': 21.739, 'train_loss': 2.87025244140625, 'epoch': 25.0}
{'train_runtime': 11.7403, 'train_samples_per_second': 21.294, 'train_steps_per_second': 21.294, 'train_loss': 2.8606142578125, 'epoch': 25.0}
{'train_runtime': 11.435, 'train_samples_per_second': 21.863, 'train_steps_per_second': 21.863, 'train_loss': 2.834609619140625, 'epoch': 25.0}
{'train_runtime': 11.4398, 'train_samples_per_second': 21.853, 'train_steps_per_second': 21.853, 'train_loss': 2.86306298828125, 'epoch': 25.0}
{'train_runtime': 11.2871, 'train_samples_per_second': 22.149, 'train_steps_per_second': 22.149, 'train_loss': 2.85704931640625, 'epoch': 25.0}
{'train_runtime': 11.1873, 'train_samples_per_second': 22.347, 'train_steps_per_second': 22.347, 'train_loss': 2.869532470703125, 'epoch': 25.0}
{'train_runtime': 11.3698, 'train_samples_per_second': 21.988, 'train_steps_per_second': 21.988, 'train_loss': 2.847135498046875, 'epoch': 25.0}
{'train_runtime': 11.3287, 'train_samples_per_second': 22.068, 'train_steps_per_second': 22.068, 'train_loss': 2.838907470703125, 'epoch': 25.0}
{'train_runtime': 11.4397, 'train_samples_per_second': 21.854, 'train_steps_per_second': 21.854, 'train_loss': 2.837955078125, 'epoch': 25.0}
{'train_runtime': 11.555, 'train_samples_per_second': 21.636, 'train_steps_per_second': 21.636, 'train_loss': 2.83177197265625, 'epoch': 25.0}
{'train_runtime': 11.4926, 'train_samples_per_second': 21.753, 'train_steps_per_second': 21.753, 'train_loss': 2.85025146484375, 'epoch': 25.0}
{'train_runtime': 11.5316, 'train_samples_per_second': 21.68, 'train_steps_per_second': 21.68, 'train_loss': 2.863265869140625, 'epoch': 25.0}
{'train_runtime': 11.5416, 'train_samples_per_second': 21.661, 'train_steps_per_second': 21.661, 'train_loss': 2.85632275390625, 'epoch': 25.0}
{'train_runtime': 11.6015, 'train_samples_per_second': 21.549, 'train_steps_per_second': 21.549, 'train_loss': 2.86636181640625, 'epoch': 25.0}
{'train_runtime': 11.7661, 'train_samples_per_second': 21.247, 'train_steps_per_second': 21.247, 'train_loss': 2.85909912109375, 'epoch': 25.0}
{'train_runtime': 11.8292, 'train_samples_per_second': 21.134, 'train_steps_per_second': 21.134, 'train_loss': 2.838047607421875, 'epoch': 25.0}
{'train_runtime': 11.9622, 'train_samples_per_second': 20.899, 'train_steps_per_second': 20.899, 'train_loss': 2.866010009765625, 'epoch': 25.0}
{'train_runtime': 11.9331, 'train_samples_per_second': 20.95, 'train_steps_per_second': 20.95, 'train_loss': 2.8799912109375, 'epoch': 25.0}
{'train_runtime': 12.1308, 'train_samples_per_second': 20.609, 'train_steps_per_second': 20.609, 'train_loss': 2.86115576171875, 'epoch': 25.0}
{'train_runtime': 12.2386, 'train_samples_per_second': 20.427, 'train_steps_per_second': 20.427, 'train_loss': 2.871707275390625, 'epoch': 25.0}
{'train_runtime': 12.4523, 'train_samples_per_second': 20.077, 'train_steps_per_second': 20.077, 'train_loss': 2.876568603515625, 'epoch': 25.0}
{'train_runtime': 12.127, 'train_samples_per_second': 20.615, 'train_steps_per_second': 20.615, 'train_loss': 2.873837158203125, 'epoch': 25.0}
{'train_runtime': 11.9884, 'train_samples_per_second': 20.854, 'train_steps_per_second': 20.854, 'train_loss': 2.844281005859375, 'epoch': 25.0}
{'train_runtime': 12.0545, 'train_samples_per_second': 20.739, 'train_steps_per_second': 20.739, 'train_loss': 2.873786376953125, 'epoch': 25.0}
{'train_runtime': 11.8536, 'train_samples_per_second': 21.091, 'train_steps_per_second': 21.091, 'train_loss': 2.864634765625, 'epoch': 25.0}
{'train_runtime': 11.8742, 'train_samples_per_second': 21.054, 'train_steps_per_second': 21.054, 'train_loss': 2.83624658203125, 'epoch': 25.0}
{'train_runtime': 11.8629, 'train_samples_per_second': 21.074, 'train_steps_per_second': 21.074, 'train_loss': 2.85782177734375, 'epoch': 25.0}
{'train_runtime': 12.054, 'train_samples_per_second': 20.74, 'train_steps_per_second': 20.74, 'train_loss': 2.84082568359375, 'epoch': 25.0}
{'train_runtime': 11.743, 'train_samples_per_second': 21.289, 'train_steps_per_second': 21.289, 'train_loss': 2.84501416015625, 'epoch': 25.0}
{'train_runtime': 11.9792, 'train_samples_per_second': 20.87, 'train_steps_per_second': 20.87, 'train_loss': 2.84473388671875, 'epoch': 25.0}
{'train_runtime': 11.7736, 'train_samples_per_second': 21.234, 'train_steps_per_second': 21.234, 'train_loss': 2.8390205078125, 'epoch': 25.0}

Explanations:  16%|█▋        | 230/1400 [13:29<53:36,  2.75s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 13.5598, 'train_samples_per_second': 18.437, 'train_steps_per_second': 18.437, 'train_loss': 3.01609326171875, 'epoch': 25.0}
{'train_runtime': 12.7884, 'train_samples_per_second': 19.549, 'train_steps_per_second': 19.549, 'train_loss': 3.04186181640625, 'epoch': 25.0}
{'train_runtime': 13.0824, 'train_samples_per_second': 19.11, 'train_steps_per_second': 19.11, 'train_loss': 3.031115966796875, 'epoch': 25.0}
{'train_runtime': 12.6428, 'train_samples_per_second': 19.774, 'train_steps_per_second': 19.774, 'train_loss': 3.02761767578125, 'epoch': 25.0}
{'train_runtime': 12.5423, 'train_samples_per_second': 19.933, 'train_steps_per_second': 19.933, 'train_loss': 3.029185546875, 'epoch': 25.0}
{'train_runtime': 12.539, 'train_samples_per_second': 19.938, 'train_steps_per_second': 19.938, 'train_loss': 3.03578759765625, 'epoch': 25.0}
{'train_runtime': 12.6431, 'train_samples_per_second': 19.774, 'train_steps_per_second': 19.774, 'train_loss': 3.02782568359375, 'epoch': 25.0}
{'train_runtime': 12.6641, 'train_samples_per_second': 19.741, 'train_steps_per_second': 19.741, 'train_loss': 3.035539794921875, 'epoch': 25.0}
{'train_runtime': 12.4173, 'train_samples_per_second': 20.133, 'train_steps_per_second': 20.133, 'train_loss': 3.0233095703125, 'epoch': 25.0}
{'train_runtime': 12.44, 'train_samples_per_second': 20.096, 'train_steps_per_second': 20.096, 'train_loss': 3.043351806640625, 'epoch': 25.0}
{'train_runtime': 12.3796, 'train_samples_per_second': 20.195, 'train_steps_per_second': 20.195, 'train_loss': 3.028218994140625, 'epoch': 25.0}
{'train_runtime': 12.3248, 'train_samples_per_second': 20.284, 'train_steps_per_second': 20.284, 'train_loss': 3.048242431640625, 'epoch': 25.0}
{'train_runtime': 12.3943, 'train_samples_per_second': 20.17, 'train_steps_per_second': 20.17, 'train_loss': 3.02871044921875, 'epoch': 25.0}
{'train_runtime': 12.4052, 'train_samples_per_second': 20.153, 'train_steps_per_second': 20.153, 'train_loss': 3.040508056640625, 'epoch': 25.0}
{'train_runtime': 12.3695, 'train_samples_per_second': 20.211, 'train_steps_per_second': 20.211, 'train_loss': 3.05612646484375, 'epoch': 25.0}
{'train_runtime': 12.1615, 'train_samples_per_second': 20.557, 'train_steps_per_second': 20.557, 'train_loss': 3.011375, 'epoch': 25.0}
{'train_runtime': 12.2683, 'train_samples_per_second': 20.378, 'train_steps_per_second': 20.378, 'train_loss': 3.02298779296875, 'epoch': 25.0}
{'train_runtime': 11.968, 'train_samples_per_second': 20.889, 'train_steps_per_second': 20.889, 'train_loss': 3.011387451171875, 'epoch': 25.0}
{'train_runtime': 11.9564, 'train_samples_per_second': 20.909, 'train_steps_per_second': 20.909, 'train_loss': 3.05053955078125, 'epoch': 25.0}
{'train_runtime': 11.8522, 'train_samples_per_second': 21.093, 'train_steps_per_second': 21.093, 'train_loss': 3.024573974609375, 'epoch': 25.0}
{'train_runtime': 11.9375, 'train_samples_per_second': 20.942, 'train_steps_per_second': 20.942, 'train_loss': 3.013318603515625, 'epoch': 25.0}
{'train_runtime': 12.4249, 'train_samples_per_second': 20.121, 'train_steps_per_second': 20.121, 'train_loss': 3.02758251953125, 'epoch': 25.0}
{'train_runtime': 11.9834, 'train_samples_per_second': 20.862, 'train_steps_per_second': 20.862, 'train_loss': 3.025893798828125, 'epoch': 25.0}
{'train_runtime': 12.0917, 'train_samples_per_second': 20.675, 'train_steps_per_second': 20.675, 'train_loss': 3.026427001953125, 'epoch': 25.0}
{'train_runtime': 11.8761, 'train_samples_per_second': 21.051, 'train_steps_per_second': 21.051, 'train_loss': 3.01276513671875, 'epoch': 25.0}
{'train_runtime': 11.9306, 'train_samples_per_second': 20.955, 'train_steps_per_second': 20.955, 'train_loss': 2.8573515625, 'epoch': 25.0}
{'train_runtime': 11.6411, 'train_samples_per_second': 21.476, 'train_steps_per_second': 21.476, 'train_loss': 2.8840576171875, 'epoch': 25.0}
{'train_runtime': 11.8608, 'train_samples_per_second': 21.078, 'train_steps_per_second': 21.078, 'train_loss': 2.85008837890625, 'epoch': 25.0}
{'train_runtime': 11.6755, 'train_samples_per_second': 21.412, 'train_steps_per_second': 21.412, 'train_loss': 2.848263671875, 'epoch': 25.0}
{'train_runtime': 11.7237, 'train_samples_per_second': 21.324, 'train_steps_per_second': 21.324, 'train_loss': 2.87786865234375, 'epoch': 25.0}
{'train_runtime': 11.6865, 'train_samples_per_second': 21.392, 'train_steps_per_second': 21.392, 'train_loss': 2.8367919921875, 'epoch': 25.0}
{'train_runtime': 11.6115, 'train_samples_per_second': 21.53, 'train_steps_per_second': 21.53, 'train_loss': 2.887548828125, 'epoch': 25.0}
{'train_runtime': 11.538, 'train_samples_per_second': 21.667, 'train_steps_per_second': 21.667, 'train_loss': 2.85215478515625, 'epoch': 25.0}
{'train_runtime': 11.8335, 'train_samples_per_second': 21.126, 'train_steps_per_second': 21.126, 'train_loss': 2.851222900390625, 'epoch': 25.0}
{'train_runtime': 11.8309, 'train_samples_per_second': 21.131, 'train_steps_per_second': 21.131, 'train_loss': 2.839088134765625, 'epoch': 25.0}
{'train_runtime': 11.6781, 'train_samples_per_second': 21.408, 'train_steps_per_second': 21.408, 'train_loss': 2.86099609375, 'epoch': 25.0}
{'train_runtime': 11.8913, 'train_samples_per_second': 21.024, 'train_steps_per_second': 21.024, 'train_loss': 2.846253662109375, 'epoch': 25.0}
{'train_runtime': 11.7141, 'train_samples_per_second': 21.342, 'train_steps_per_second': 21.342, 'train_loss': 2.86234814453125, 'epoch': 25.0}
{'train_runtime': 11.7675, 'train_samples_per_second': 21.245, 'train_steps_per_second': 21.245, 'train_loss': 2.88703662109375, 'epoch': 25.0}
{'train_runtime': 11.7761, 'train_samples_per_second': 21.229, 'train_steps_per_second': 21.229, 'train_loss': 2.83875927734375, 'epoch': 25.0}
{'train_runtime': 11.8433, 'train_samples_per_second': 21.109, 'train_steps_per_second': 21.109, 'train_loss': 2.853200439453125, 'epoch': 25.0}
{'train_runtime': 11.8109, 'train_samples_per_second': 21.167, 'train_steps_per_second': 21.167, 'train_loss': 2.876903564453125, 'epoch': 25.0}
{'train_runtime': 11.8904, 'train_samples_per_second': 21.025, 'train_steps_per_second': 21.025, 'train_loss': 2.871199951171875, 'epoch': 25.0}
{'train_runtime': 11.8003, 'train_samples_per_second': 21.186, 'train_steps_per_second': 21.186, 'train_loss': 2.87262109375, 'epoch': 25.0}
{'train_runtime': 12.1659, 'train_samples_per_second': 20.549, 'train_steps_per_second': 20.549, 'train_loss': 2.84932373046875, 'epoch': 25.0}
{'train_runtime': 11.9772, 'train_samples_per_second': 20.873, 'train_steps_per_second': 20.873, 'train_loss': 2.85073193359375, 'epoch': 25.0}
{'train_runtime': 12.0056, 'train_samples_per_second': 20.824, 'train_steps_per_second': 20.824, 'train_loss': 2.8486806640625, 'epoch': 25.0}
{'train_runtime': 11.8642, 'train_samples_per_second': 21.072, 'train_steps_per_second': 21.072, 'train_loss': 2.870302001953125, 'epoch': 25.0}
{'train_runtime': 11.4919, 'train_samples_per_second': 21.755, 'train_steps_per_second': 21.755, 'train_loss': 2.826427734375, 'epoch': 25.0}
{'train_runtime': 11.4815, 'train_samples_per_second': 21.774, 'train_steps_per_second': 21.774, 'train_loss': 2.829899169921875, 'epoch': 25.0}
{'train_runtime': 11.5498, 'train_samples_per_second': 21.645, 'train_steps_per_second': 21.645, 'train_loss': 2.882913818359375, 'epoch': 25.0}
{'train_runtime': 11.451, 'train_samples_per_second': 21.832, 'train_steps_per_second': 21.832, 'train_loss': 2.8677109375, 'epoch': 25.0}
{'train_runtime': 11.3631, 'train_samples_per_second': 22.001, 'train_steps_per_second': 22.001, 'train_loss': 2.8660556640625, 'epoch': 25.0}
{'train_runtime': 11.3723, 'train_samples_per_second': 21.983, 'train_steps_per_second': 21.983, 'train_loss': 2.83323046875, 'epoch': 25.0}
{'train_runtime': 11.3597, 'train_samples_per_second': 22.008, 'train_steps_per_second': 22.008, 'train_loss': 2.835278564453125, 'epoch': 25.0}
{'train_runtime': 11.3039, 'train_samples_per_second': 22.116, 'train_steps_per_second': 22.116, 'train_loss': 2.840078125, 'epoch': 25.0}
{'train_runtime': 11.3049, 'train_samples_per_second': 22.114, 'train_steps_per_second': 22.114, 'train_loss': 2.83578271484375, 'epoch': 25.0}

Explanations:  16%|█▋        | 231/1400 [13:35<1:09:37,  3.57s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 13.4883, 'train_samples_per_second': 18.535, 'train_steps_per_second': 18.535, 'train_loss': 3.044324951171875, 'epoch': 25.0}
{'train_runtime': 12.7724, 'train_samples_per_second': 19.573, 'train_steps_per_second': 19.573, 'train_loss': 3.0563056640625, 'epoch': 25.0}
{'train_runtime': 12.9469, 'train_samples_per_second': 19.31, 'train_steps_per_second': 19.31, 'train_loss': 3.0162900390625, 'epoch': 25.0}
{'train_runtime': 12.5403, 'train_samples_per_second': 19.936, 'train_steps_per_second': 19.936, 'train_loss': 3.047907470703125, 'epoch': 25.0}
{'train_runtime': 12.4527, 'train_samples_per_second': 20.076, 'train_steps_per_second': 20.076, 'train_loss': 3.02282373046875, 'epoch': 25.0}
{'train_runtime': 12.4902, 'train_samples_per_second': 20.016, 'train_steps_per_second': 20.016, 'train_loss': 3.02980810546875, 'epoch': 25.0}
{'train_runtime': 12.5838, 'train_samples_per_second': 19.867, 'train_steps_per_second': 19.867, 'train_loss': 3.00844970703125, 'epoch': 25.0}
{'train_runtime': 12.4235, 'train_samples_per_second': 20.123, 'train_steps_per_second': 20.123, 'train_loss': 3.034999267578125, 'epoch': 25.0}
{'train_runtime': 12.2301, 'train_samples_per_second': 20.441, 'train_steps_per_second': 20.441, 'train_loss': 3.027823974609375, 'epoch': 25.0}
{'train_runtime': 12.3513, 'train_samples_per_second': 20.241, 'train_steps_per_second': 20.241, 'train_loss': 3.0236650390625, 'epoch': 25.0}
{'train_runtime': 12.3225, 'train_samples_per_second': 20.288, 'train_steps_per_second': 20.288, 'train_loss': 3.02095166015625, 'epoch': 25.0}
{'train_runtime': 12.253, 'train_samples_per_second': 20.403, 'train_steps_per_second': 20.403, 'train_loss': 3.03233837890625, 'epoch': 25.0}
{'train_runtime': 12.6066, 'train_samples_per_second': 19.831, 'train_steps_per_second': 19.831, 'train_loss': 3.0187978515625, 'epoch': 25.0}
{'train_runtime': 12.2743, 'train_samples_per_second': 20.368, 'train_steps_per_second': 20.368, 'train_loss': 3.02043017578125, 'epoch': 25.0}
{'train_runtime': 12.2885, 'train_samples_per_second': 20.344, 'train_steps_per_second': 20.344, 'train_loss': 3.04201953125, 'epoch': 25.0}
{'train_runtime': 12.0614, 'train_samples_per_second': 20.727, 'train_steps_per_second': 20.727, 'train_loss': 3.0393642578125, 'epoch': 25.0}
{'train_runtime': 12.1529, 'train_samples_per_second': 20.571, 'train_steps_per_second': 20.571, 'train_loss': 3.04661279296875, 'epoch': 25.0}
{'train_runtime': 12.0443, 'train_samples_per_second': 20.757, 'train_steps_per_second': 20.757, 'train_loss': 3.02928662109375, 'epoch': 25.0}
{'train_runtime': 11.9726, 'train_samples_per_second': 20.881, 'train_steps_per_second': 20.881, 'train_loss': 3.020804931640625, 'epoch': 25.0}
{'train_runtime': 11.8252, 'train_samples_per_second': 21.141, 'train_steps_per_second': 21.141, 'train_loss': 3.0170048828125, 'epoch': 25.0}
{'train_runtime': 11.9482, 'train_samples_per_second': 20.924, 'train_steps_per_second': 20.924, 'train_loss': 2.9986552734375, 'epoch': 25.0}
{'train_runtime': 12.186, 'train_samples_per_second': 20.515, 'train_steps_per_second': 20.515, 'train_loss': 3.024293212890625, 'epoch': 25.0}
{'train_runtime': 12.0632, 'train_samples_per_second': 20.724, 'train_steps_per_second': 20.724, 'train_loss': 3.018480224609375, 'epoch': 25.0}
{'train_runtime': 11.9562, 'train_samples_per_second': 20.91, 'train_steps_per_second': 20.91, 'train_loss': 3.026151611328125, 'epoch': 25.0}
{'train_runtime': 11.9112, 'train_samples_per_second': 20.989, 'train_steps_per_second': 20.989, 'train_loss': 3.03764306640625, 'epoch': 25.0}
{'train_runtime': 11.7924, 'train_samples_per_second': 21.2, 'train_steps_per_second': 21.2, 'train_loss': 2.840084228515625, 'epoch': 25.0}
{'train_runtime': 11.7294, 'train_samples_per_second': 21.314, 'train_steps_per_second': 21.314, 'train_loss': 2.85012255859375, 'epoch': 25.0}
{'train_runtime': 11.8839, 'train_samples_per_second': 21.037, 'train_steps_per_second': 21.037, 'train_loss': 2.85066357421875, 'epoch': 25.0}
{'train_runtime': 11.9091, 'train_samples_per_second': 20.992, 'train_steps_per_second': 20.992, 'train_loss': 2.83013818359375, 'epoch': 25.0}
{'train_runtime': 11.6646, 'train_samples_per_second': 21.432, 'train_steps_per_second': 21.432, 'train_loss': 2.847635986328125, 'epoch': 25.0}
{'train_runtime': 11.8704, 'train_samples_per_second': 21.061, 'train_steps_per_second': 21.061, 'train_loss': 2.84232763671875, 'epoch': 25.0}
{'train_runtime': 11.696, 'train_samples_per_second': 21.375, 'train_steps_per_second': 21.375, 'train_loss': 2.863122314453125, 'epoch': 25.0}
{'train_runtime': 11.6487, 'train_samples_per_second': 21.462, 'train_steps_per_second': 21.462, 'train_loss': 2.844244873046875, 'epoch': 25.0}
{'train_runtime': 11.6999, 'train_samples_per_second': 21.368, 'train_steps_per_second': 21.368, 'train_loss': 2.8791142578125, 'epoch': 25.0}
{'train_runtime': 11.6836, 'train_samples_per_second': 21.398, 'train_steps_per_second': 21.398, 'train_loss': 2.852986328125, 'epoch': 25.0}
{'train_runtime': 11.673, 'train_samples_per_second': 21.417, 'train_steps_per_second': 21.417, 'train_loss': 2.908208740234375, 'epoch': 25.0}
{'train_runtime': 11.7083, 'train_samples_per_second': 21.352, 'train_steps_per_second': 21.352, 'train_loss': 2.8638779296875, 'epoch': 25.0}
{'train_runtime': 11.7926, 'train_samples_per_second': 21.2, 'train_steps_per_second': 21.2, 'train_loss': 2.870555908203125, 'epoch': 25.0}
{'train_runtime': 11.8504, 'train_samples_per_second': 21.096, 'train_steps_per_second': 21.096, 'train_loss': 2.8592119140625, 'epoch': 25.0}
{'train_runtime': 11.8833, 'train_samples_per_second': 21.038, 'train_steps_per_second': 21.038, 'train_loss': 2.86157958984375, 'epoch': 25.0}
{'train_runtime': 11.9537, 'train_samples_per_second': 20.914, 'train_steps_per_second': 20.914, 'train_loss': 2.8433212890625, 'epoch': 25.0}
{'train_runtime': 11.9448, 'train_samples_per_second': 20.93, 'train_steps_per_second': 20.93, 'train_loss': 2.8278681640625, 'epoch': 25.0}
{'train_runtime': 11.9863, 'train_samples_per_second': 20.857, 'train_steps_per_second': 20.857, 'train_loss': 2.861969970703125, 'epoch': 25.0}
{'train_runtime': 12.0001, 'train_samples_per_second': 20.833, 'train_steps_per_second': 20.833, 'train_loss': 2.819208740234375, 'epoch': 25.0}
{'train_runtime': 12.3477, 'train_samples_per_second': 20.247, 'train_steps_per_second': 20.247, 'train_loss': 2.860849853515625, 'epoch': 25.0}
{'train_runtime': 12.1849, 'train_samples_per_second': 20.517, 'train_steps_per_second': 20.517, 'train_loss': 2.842830810546875, 'epoch': 25.0}
{'train_runtime': 12.0204, 'train_samples_per_second': 20.798, 'train_steps_per_second': 20.798, 'train_loss': 2.87150341796875, 'epoch': 25.0}
{'train_runtime': 12.1957, 'train_samples_per_second': 20.499, 'train_steps_per_second': 20.499, 'train_loss': 2.8616552734375, 'epoch': 25.0}
{'train_runtime': 11.7616, 'train_samples_per_second': 21.256, 'train_steps_per_second': 21.256, 'train_loss': 2.835552490234375, 'epoch': 25.0}
{'train_runtime': 11.7253, 'train_samples_per_second': 21.321, 'train_steps_per_second': 21.321, 'train_loss': 2.881004150390625, 'epoch': 25.0}
{'train_runtime': 11.655, 'train_samples_per_second': 21.45, 'train_steps_per_second': 21.45, 'train_loss': 2.86614013671875, 'epoch': 25.0}
{'train_runtime': 11.5676, 'train_samples_per_second': 21.612, 'train_steps_per_second': 21.612, 'train_loss': 2.87869384765625, 'epoch': 25.0}
{'train_runtime': 11.6283, 'train_samples_per_second': 21.499, 'train_steps_per_second': 21.499, 'train_loss': 2.873952392578125, 'epoch': 25.0}
{'train_runtime': 11.554, 'train_samples_per_second': 21.638, 'train_steps_per_second': 21.638, 'train_loss': 2.841216064453125, 'epoch': 25.0}
{'train_runtime': 11.4119, 'train_samples_per_second': 21.907, 'train_steps_per_second': 21.907, 'train_loss': 2.8305166015625, 'epoch': 25.0}
{'train_runtime': 11.1941, 'train_samples_per_second': 22.333, 'train_steps_per_second': 22.333, 'train_loss': 2.838194580078125, 'epoch': 25.0}
{'train_runtime': 11.1582, 'train_samples_per_second': 22.405, 'train_steps_per_second': 22.405, 'train_loss': 2.852189208984375, 'epoch': 25.0}

Explanations:  17%|█▋        | 232/1400 [13:38<1:06:14,  3.40s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 233/1400 [13:43<1:17:25,  3.98s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 235/1400 [13:48<1:04:03,  3.30s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 236/1400 [13:52<1:04:00,  3.30s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 238/1400 [13:57<56:18,  2.91s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 239/1400 [14:02<1:04:41,  3.34s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 240/1400 [14:05<1:02:55,  3.25s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 242/1400 [14:11<57:12,  2.96s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 243/1400 [14:15<1:02:19,  3.23s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  17%|█▋        | 244/1400 [14:18<1:00:44,  3.15s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 246/1400 [14:25<58:43,  3.05s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 247/1400 [14:29<1:01:39,  3.21s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 248/1400 [14:32<59:39,  3.11s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 250/1400 [14:39<58:51,  3.07s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 251/1400 [14:42<1:02:08,  3.24s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 252/1400 [14:45<58:25,  3.05s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 254/1400 [14:53<59:43,  3.13s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 255/1400 [14:56<1:01:52,  3.24s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 256/1400 [14:59<57:51,  3.03s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 258/1400 [15:06<59:50,  3.14s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  18%|█▊        | 259/1400 [15:10<1:01:41,  3.24s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▊        | 260/1400 [15:12<56:23,  2.97s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▊        | 262/1400 [15:20<1:01:03,  3.22s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 263/1400 [15:23<1:00:53,  3.21s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 264/1400 [15:26<55:03,  2.91s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 266/1400 [15:34<1:01:19,  3.25s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 267/1400 [15:37<1:01:18,  3.25s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 268/1400 [15:39<55:27,  2.94s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 270/1400 [15:48<1:01:30,  3.27s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 271/1400 [15:51<1:00:18,  3.21s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  19%|█▉        | 272/1400 [15:53<53:07,  2.83s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 273/1400 [16:00<1:20:50,  4.30s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 274/1400 [16:02<1:03:57,  3.41s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 275/1400 [16:04<59:31,  3.17s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 276/1400 [16:06<51:56,  2.77s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 277/1400 [16:14<1:19:34,  4.25s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 278/1400 [16:15<1:04:03,  3.43s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|█▉        | 279/1400 [16:18<58:31,  3.13s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 280/1400 [16:20<52:54,  2.83s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 281/1400 [16:27<1:17:57,  4.18s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 282/1400 [16:29<1:03:17,  3.40s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 283/1400 [16:31<58:33,  3.15s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 284/1400 [16:33<52:08,  2.80s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 285/1400 [16:41<1:18:48,  4.24s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 286/1400 [16:43<1:04:13,  3.46s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  20%|██        | 287/1400 [16:45<58:23,  3.15s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 288/1400 [16:47<50:53,  2.75s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 289/1400 [16:55<1:18:01,  4.21s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 290/1400 [16:56<1:04:23,  3.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 291/1400 [16:59<58:01,  3.14s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 292/1400 [17:00<49:13,  2.67s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 293/1400 [17:08<1:17:05,  4.18s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  21%|██        | 294/1400 [17:10<1:04:13,  3.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 11.9514, 'train_samples_per_second': 20.918, 'train_steps_per_second': 20.918, 'train_loss': 2.831396240234375, 'epoch': 25.0}
{'train_runtime': 11.7147, 'train_samples_per_second': 21.341, 'train_steps_per_second': 21.341, 'train_loss': 2.883346923828125, 'epoch': 25.0}
{'train_runtime': 11.8871, 'train_samples_per_second': 21.031, 'train_steps_per_second': 21.031, 'train_loss': 2.853868896484375, 'epoch': 25.0}
{'train_runtime': 11.7378, 'train_samples_per_second': 21.299, 'train_steps_per_second': 21.299, 'train_loss': 2.862109130859375, 'epoch': 25.0}
{'train_runtime': 11.9826, 'train_samples_per_second': 20.864, 'train_steps_per_second': 20.864, 'train_loss': 2.84180224609375, 'epoch': 25.0}
{'train_runtime': 11.5329, 'train_samples_per_second': 21.677, 'train_steps_per_second': 21.677, 'train_loss': 2.879605224609375, 'epoch': 25.0}
{'train_runtime': 11.5467, 'train_samples_per_second': 21.651, 'train_steps_per_second': 21.651, 'train_loss': 2.844638427734375, 'epoch': 25.0}
{'train_runtime': 11.6622, 'train_samples_per_second': 21.437, 'train_steps_per_second': 21.437, 'train_loss': 2.87184326171875, 'epoch': 25.0}
{'train_runtime': 11.6455, 'train_samples_per_second': 21.468, 'train_steps_per_second': 21.468, 'train_loss': 2.829484130859375, 'epoch': 25.0}
{'train_runtime': 11.7806, 'train_samples_per_second': 21.221, 'train_steps_per_second': 21.221, 'train_loss': 2.882219970703125, 'epoch': 25.0}
{'train_runtime': 11.6624, 'train_samples_per_second': 21.436, 'train_steps_per_second': 21.436, 'train_loss': 2.8432548828125, 'epoch': 25.0}
{'train_runtime': 11.7765, 'train_samples_per_second': 21.229, 'train_steps_per_second': 21.229, 'train_loss': 2.8794794921875, 'epoch': 25.0}
{'train_runtime': 11.6044, 'train_samples_per_second': 21.544, 'train_steps_per_second': 21.544, 'train_loss': 2.861850830078125, 'epoch': 25.0}
{'train_runtime': 11.4441, 'train_samples_per_second': 21.845, 'train_steps_per_second': 21.845, 'train_loss': 2.85437255859375, 'epoch': 25.0}
{'train_runtime': 11.4195, 'train_samples_per_second': 21.892, 'train_steps_per_second': 21.892, 'train_loss': 2.8381767578125, 'epoch': 25.0}
{'train_runtime': 11.6531, 'train_samples_per_second': 21.453, 'train_steps_per_second': 21.453, 'train_loss': 2.861210205078125, 'epoch': 25.0}
{'train_runtime': 11.3763, 'train_samples_per_second': 21.976, 'train_steps_per_second': 21.976, 'train_loss': 2.872013671875, 'epoch': 25.0}
{'train_runtime': 11.3425, 'train_samples_per_second': 22.041, 'train_steps_per_second': 22.041, 'train_loss': 2.902353271484375, 'epoch': 25.0}
{'train_runtime': 11.5199, 'train_samples_per_second': 21.702, 'train_steps_per_second': 21.702, 'train_loss': 2.84727294921875, 'epoch': 25.0}
{'train_runtime': 11.4997, 'train_samples_per_second': 21.74, 'train_steps_per_second': 21.74, 'train_loss': 2.850727783203125, 'epoch': 25.0}
{'train_runtime': 11.4739, 'train_samples_per_second': 21.789, 'train_steps_per_second': 21.789, 'train_loss': 2.8295380859375, 'epoch': 25.0}
{'train_runtime': 11.4248, 'train_samples_per_second': 21.882, 'train_steps_per_second': 21.882, 'train_loss': 2.9006904296875, 'epoch': 25.0}
{'train_runtime': 11.5276, 'train_samples_per_second': 21.687, 'train_steps_per_second': 21.687, 'train_loss': 2.846222900390625, 'epoch': 25.0}
{'train_runtime': 11.4351, 'train_samples_per_second': 21.863, 'train_steps_per_second': 21.863, 'train_loss': 2.8254609375, 'epoch': 25.0}
{'train_runtime': 11.5748, 'train_samples_per_second': 21.599, 'train_steps_per_second': 21.599, 'train_loss': 2.84725537109375, 'epoch': 25.0}
{'train_runtime': 11.3794, 'train_samples_per_second': 21.969, 'train_steps_per_second': 21.969, 'train_loss': 2.877322021484375, 'epoch': 25.0}
{'train_runtime': 11.2908, 'train_samples_per_second': 22.142, 'train_steps_per_second': 22.142, 'train_loss': 2.877040283203125, 'epoch': 25.0}
{'train_runtime': 11.3037, 'train_samples_per_second': 22.117, 'train_steps_per_second': 22.117, 'train_loss': 2.862683349609375, 'epoch': 25.0}
{'train_runtime': 11.4174, 'train_samples_per_second': 21.896, 'train_steps_per_second': 21.896, 'train_loss': 2.867654296875, 'epoch': 25.0}
{'train_runtime': 11.3907, 'train_samples_per_second': 21.948, 'train_steps_per_second': 21.948, 'train_loss': 2.863784423828125, 'epoch': 25.0}
{'train_runtime': 11.4237, 'train_samples_per_second': 21.884, 'train_steps_per_second': 21.884, 'train_loss': 2.84824658203125, 'epoch': 25.0}
{'train_runtime': 11.2972, 'train_samples_per_second': 22.129, 'train_steps_per_second': 22.129, 'train_loss': 2.8681435546875, 'epoch': 25.0}
{'train_runtime': 11.2797, 'train_samples_per_second': 22.164, 'train_steps_per_second': 22.164, 'train_loss': 2.84108837890625, 'epoch': 25.0}
{'train_runtime': 11.3806, 'train_samples_per_second': 21.967, 'train_steps_per_second': 21.967, 'train_loss': 2.871801513671875, 'epoch': 25.0}
{'train_runtime': 11.4365, 'train_samples_per_second': 21.86, 'train_steps_per_second': 21.86, 'train_loss': 2.84740283203125, 'epoch': 25.0}
{'train_runtime': 11.2126, 'train_samples_per_second': 22.296, 'train_steps_per_second': 22.296, 'train_loss': 2.89266845703125, 'epoch': 25.0}
{'train_runtime': 11.4148, 'train_samples_per_second': 21.901, 'train_steps_per_second': 21.901, 'train_loss': 2.8396123046875, 'epoch': 25.0}
{'train_runtime': 11.2651, 'train_samples_per_second': 22.192, 'train_steps_per_second': 22.192, 'train_loss': 2.8347109375, 'epoch': 25.0}
{'train_runtime': 11.477, 'train_samples_per_second': 21.783, 'train_steps_per_second': 21.783, 'train_loss': 2.83681787109375, 'epoch': 25.0}
{'train_runtime': 11.338, 'train_samples_per_second': 22.05, 'train_steps_per_second': 22.05, 'train_loss': 2.902895263671875, 'epoch': 25.0}
{'train_runtime': 11.251, 'train_samples_per_second': 22.22, 'train_steps_per_second': 22.22, 'train_loss': 2.846106201171875, 'epoch': 25.0}
{'train_runtime': 11.5036, 'train_samples_per_second': 21.732, 'train_steps_per_second': 21.732, 'train_loss': 2.82495849609375, 'epoch': 25.0}
{'train_runtime': 11.6767, 'train_samples_per_second': 21.41, 'train_steps_per_second': 21.41, 'train_loss': 2.867248779296875, 'epoch': 25.0}
{'train_runtime': 11.368, 'train_samples_per_second': 21.992, 'train_steps_per_second': 21.992, 'train_loss': 2.847260986328125, 'epoch': 25.0}
{'train_runtime': 11.2631, 'train_samples_per_second': 22.196, 'train_steps_per_second': 22.196, 'train_loss': 2.838933837890625, 'epoch': 25.0}
{'train_runtime': 11.3121, 'train_samples_per_second': 22.1, 'train_steps_per_second': 22.1, 'train_loss': 2.85476953125, 'epoch': 25.0}
{'train_runtime': 11.6268, 'train_samples_per_second': 21.502, 'train_steps_per_second': 21.502, 'train_loss': 2.875011962890625, 'epoch': 25.0}
{'train_runtime': 11.6121, 'train_samples_per_second': 21.529, 'train_steps_per_second': 21.529, 'train_loss': 2.83610107421875, 'epoch': 25.0}
{'train_runtime': 11.4322, 'train_samples_per_second': 21.868, 'train_steps_per_second': 21.868, 'train_loss': 2.87714111328125, 'epoch': 25.0}
{'train_runtime': 11.6171, 'train_samples_per_second': 21.52, 'train_steps_per_second': 21.52, 'train_loss': 2.861951416015625, 'epoch': 25.0}
{'train_runtime': 11.4461, 'train_samples_per_second': 21.842, 'train_steps_per_second': 21.842, 'train_loss': 2.8371240234375, 'epoch': 25.0}
{'train_runtime': 11.685, 'train_samples_per_second': 21.395, 'train_steps_per_second': 21.395, 'train_loss': 2.87414404296875, 'epoch': 25.0}
{'train_runtime': 11.7102, 'train_samples_per_second': 21.349, 'train_steps_per_second': 21.349, 'train_loss': 2.883757080078125, 'epoch': 25.0}
{'train_runtime': 11.8121, 'train_samples_per_second': 21.165, 'train_steps_per_second': 21.165, 'train_loss': 2.8418916015625, 'epoch': 25.0}
{'train_runtime': 11.9054, 'train_samples_per_second': 20.999, 'train_steps_per_second': 20.999, 'train_loss': 2.842922119140625, 'epoch': 25.0}
{'train_runtime': 11.7637, 'train_samples_per_second': 21.252, 'train_steps_per_second': 21.252, 'train_loss': 2.842747314453125, 'epoch': 25.0}
{'train_runtime': 11.6614, 'train_samples_per_second': 21.438, 'train_steps_per_second': 21.438, 'train_loss': 2.890747802734375, 'epoch': 25.0}

Explanations:  32%|███▏      | 449/1400 [25:55<47:38,  3.01s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  32%|███▏      | 450/1400 [25:56<38:53,  2.46s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  32%|███▏      | 451/1400 [26:05<1:06:49,  4.22s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  32%|███▏      | 452/1400 [26:08<1:02:15,  3.94s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  32%|███▏      | 453/1400 [26:09<48:54,  3.10s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  32%|███▏      | 454/1400 [26:10<39:44,  2.52s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  32%|███▎      | 455/1400 [26:18<1:05:22,  4.15s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 456/1400 [26:22<1:01:29,  3.91s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 457/1400 [26:23<49:41,  3.16s/it]

{'train_runtime': 11.7612, 'train_samples_per_second': 21.256, 'train_steps_per_second': 21.256, 'train_loss': 2.87066748046875, 'epoch': 25.0}
{'train_runtime': 12.0209, 'train_samples_per_second': 20.797, 'train_steps_per_second': 20.797, 'train_loss': 2.8495185546875, 'epoch': 25.0}
{'train_runtime': 11.8613, 'train_samples_per_second': 21.077, 'train_steps_per_second': 21.077, 'train_loss': 2.8660859375, 'epoch': 25.0}
{'train_runtime': 11.9285, 'train_samples_per_second': 20.958, 'train_steps_per_second': 20.958, 'train_loss': 2.84355517578125, 'epoch': 25.0}
{'train_runtime': 11.7526, 'train_samples_per_second': 21.272, 'train_steps_per_second': 21.272, 'train_loss': 2.84319677734375, 'epoch': 25.0}
{'train_runtime': 11.5407, 'train_samples_per_second': 21.662, 'train_steps_per_second': 21.662, 'train_loss': 2.844412109375, 'epoch': 25.0}
{'train_runtime': 11.5932, 'train_samples_per_second': 21.564, 'train_steps_per_second': 21.564, 'train_loss': 2.83382177734375, 'epoch': 25.0}
{'train_runtime': 11.6659, 'train_samples_per_second': 21.43, 'train_steps_per_second': 21.43, 'train_loss': 2.869688232421875, 'epoch': 25.0}
{'train_runtime': 11.8086, 'train_samples_per_second': 21.171, 'train_steps_per_second': 21.171, 'train_loss': 2.83878564453125, 'epoch': 25.0}
{'train_runtime': 11.7236, 'train_samples_per_second': 21.324, 'train_steps_per_second': 21.324, 'train_loss': 2.888887451171875, 'epoch': 25.0}
{'train_runtime': 11.8791, 'train_samples_per_second': 21.045, 'train_steps_per_second': 21.045, 'train_loss': 2.840737548828125, 'epoch': 25.0}
{'train_runtime': 11.6275, 'train_samples_per_second': 21.501, 'train_steps_per_second': 21.501, 'train_loss': 2.807581298828125, 'epoch': 25.0}
{'train_runtime': 11.612, 'train_samples_per_second': 21.529, 'train_steps_per_second': 21.529, 'train_loss': 2.8282421875, 'epoch': 25.0}
{'train_runtime': 11.4554, 'train_samples_per_second': 21.824, 'train_steps_per_second': 21.824, 'train_loss': 2.852671142578125, 'epoch': 25.0}
{'train_runtime': 11.76, 'train_samples_per_second': 21.259, 'train_steps_per_second': 21.259, 'train_loss': 2.853296630859375, 'epoch': 25.0}
{'train_runtime': 11.582, 'train_samples_per_second': 21.585, 'train_steps_per_second': 21.585, 'train_loss': 2.85226806640625, 'epoch': 25.0}
{'train_runtime': 11.4848, 'train_samples_per_second': 21.768, 'train_steps_per_second': 21.768, 'train_loss': 2.867376953125, 'epoch': 25.0}
{'train_runtime': 11.346, 'train_samples_per_second': 22.034, 'train_steps_per_second': 22.034, 'train_loss': 2.855056884765625, 'epoch': 25.0}
{'train_runtime': 11.478, 'train_samples_per_second': 21.781, 'train_steps_per_second': 21.781, 'train_loss': 2.854803466796875, 'epoch': 25.0}
{'train_runtime': 11.4931, 'train_samples_per_second': 21.752, 'train_steps_per_second': 21.752, 'train_loss': 2.82775244140625, 'epoch': 25.0}
{'train_runtime': 11.4174, 'train_samples_per_second': 21.896, 'train_steps_per_second': 21.896, 'train_loss': 2.83274609375, 'epoch': 25.0}
{'train_runtime': 11.6476, 'train_samples_per_second': 21.464, 'train_steps_per_second': 21.464, 'train_loss': 2.853596923828125, 'epoch': 25.0}
{'train_runtime': 11.6846, 'train_samples_per_second': 21.396, 'train_steps_per_second': 21.396, 'train_loss': 2.875093994140625, 'epoch': 25.0}
{'train_runtime': 11.5582, 'train_samples_per_second': 21.63, 'train_steps_per_second': 21.63, 'train_loss': 2.812866943359375, 'epoch': 25.0}
{'train_runtime': 11.6285, 'train_samples_per_second': 21.499, 'train_steps_per_second': 21.499, 'train_loss': 2.873140380859375, 'epoch': 25.0}
{'train_runtime': 11.2894, 'train_samples_per_second': 22.145, 'train_steps_per_second': 22.145, 'train_loss': 2.856554931640625, 'epoch': 25.0}
{'train_runtime': 11.3718, 'train_samples_per_second': 21.984, 'train_steps_per_second': 21.984, 'train_loss': 2.881602783203125, 'epoch': 25.0}
{'train_runtime': 11.3378, 'train_samples_per_second': 22.05, 'train_steps_per_second': 22.05, 'train_loss': 2.896329345703125, 'epoch': 25.0}
{'train_runtime': 11.2794, 'train_samples_per_second': 22.164, 'train_steps_per_second': 22.164, 'train_loss': 2.834022705078125, 'epoch': 25.0}
{'train_runtime': 11.4425, 'train_samples_per_second': 21.848, 'train_steps_per_second': 21.848, 'train_loss': 2.829689453125, 'epoch': 25.0}
{'train_runtime': 11.3849, 'train_samples_per_second': 21.959, 'train_steps_per_second': 21.959, 'train_loss': 2.83968603515625, 'epoch': 25.0}
{'train_runtime': 11.3929, 'train_samples_per_second': 21.944, 'train_steps_per_second': 21.944, 'train_loss': 2.833600341796875, 'epoch': 25.0}
{'train_runtime': 11.4694, 'train_samples_per_second': 21.797, 'train_steps_per_second': 21.797, 'train_loss': 2.867344970703125, 'epoch': 25.0}
{'train_runtime': 11.4749, 'train_samples_per_second': 21.787, 'train_steps_per_second': 21.787, 'train_loss': 2.8421611328125, 'epoch': 25.0}
{'train_runtime': 11.2563, 'train_samples_per_second': 22.21, 'train_steps_per_second': 22.21, 'train_loss': 2.8508408203125, 'epoch': 25.0}
{'train_runtime': 11.3739, 'train_samples_per_second': 21.98, 'train_steps_per_second': 21.98, 'train_loss': 2.85778759765625, 'epoch': 25.0}
{'train_runtime': 11.2938, 'train_samples_per_second': 22.136, 'train_steps_per_second': 22.136, 'train_loss': 2.8530791015625, 'epoch': 25.0}
{'train_runtime': 11.3926, 'train_samples_per_second': 21.944, 'train_steps_per_second': 21.944, 'train_loss': 2.8341142578125, 'epoch': 25.0}
{'train_runtime': 11.3046, 'train_samples_per_second': 22.115, 'train_steps_per_second': 22.115, 'train_loss': 2.839532958984375, 'epoch': 25.0}
{'train_runtime': 11.4165, 'train_samples_per_second': 21.898, 'train_steps_per_second': 21.898, 'train_loss': 2.89145068359375, 'epoch': 25.0}
{'train_runtime': 11.4298, 'train_samples_per_second': 21.873, 'train_steps_per_second': 21.873, 'train_loss': 2.8272744140625, 'epoch': 25.0}
{'train_runtime': 11.2784, 'train_samples_per_second': 22.166, 'train_steps_per_second': 22.166, 'train_loss': 2.83410546875, 'epoch': 25.0}
{'train_runtime': 11.3092, 'train_samples_per_second': 22.106, 'train_steps_per_second': 22.106, 'train_loss': 2.84127490234375, 'epoch': 25.0}
{'train_runtime': 11.447, 'train_samples_per_second': 21.84, 'train_steps_per_second': 21.84, 'train_loss': 2.82737890625, 'epoch': 25.0}
{'train_runtime': 11.4092, 'train_samples_per_second': 21.912, 'train_steps_per_second': 21.912, 'train_loss': 2.840451171875, 'epoch': 25.0}
{'train_runtime': 11.4389, 'train_samples_per_second': 21.855, 'train_steps_per_second': 21.855, 'train_loss': 2.846679931640625, 'epoch': 25.0}
{'train_runtime': 11.4763, 'train_samples_per_second': 21.784, 'train_steps_per_second': 21.784, 'train_loss': 2.862172119140625, 'epoch': 25.0}
{'train_runtime': 11.3635, 'train_samples_per_second': 22.0, 'train_steps_per_second': 22.0, 'train_loss': 2.836246337890625, 'epoch': 25.0}
{'train_runtime': 11.5452, 'train_samples_per_second': 21.654, 'train_steps_per_second': 21.654, 'train_loss': 2.829681640625, 'epoch': 25.0}
{'train_runtime': 11.2847, 'train_samples_per_second': 22.154, 'train_steps_per_second': 22.154, 'train_loss': 2.861297607421875, 'epoch': 25.0}
{'train_runtime': 11.3773, 'train_samples_per_second': 21.973, 'train_steps_per_second': 21.973, 'train_loss': 2.83473193359375, 'epoch': 25.0}
{'train_runtime': 11.5773, 'train_samples_per_second': 21.594, 'train_steps_per_second': 21.594, 'train_loss': 2.84836767578125, 'epoch': 25.0}
{'train_runtime': 11.5337, 'train_samples_per_second': 21.676, 'train_steps_per_second': 21.676, 'train_loss': 2.85930029296875, 'epoch': 25.0}
{'train_runtime': 11.5455, 'train_samples_per_second': 21.653, 'train_steps_per_second': 21.653, 'train_loss': 2.848780029296875, 'epoch': 25.0}
{'train_runtime': 11.5992, 'train_samples_per_second': 21.553, 'train_steps_per_second': 21.553, 'train_loss': 2.882446533203125, 'epoch': 25.0}
{'train_runtime': 11.51, 'train_samples_per_second': 21.72, 'train_steps_per_second': 21.72, 'train_loss': 2.8490322265625, 'epoch': 25.0}
{'train_runtime': 11.889, 'train_samples_per_second': 21.028, 'train_steps_per_second': 21.028, 'train_loss': 2.873507568359375, 'epoch': 25.0}

Explanations:  33%|███▎      | 458/1400 [26:24<39:09,  2.49s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 11.4165, 'train_samples_per_second': 21.898, 'train_steps_per_second': 21.898, 'train_loss': 2.88203173828125, 'epoch': 25.0}
{'train_runtime': 11.2598, 'train_samples_per_second': 22.203, 'train_steps_per_second': 22.203, 'train_loss': 2.866489990234375, 'epoch': 25.0}
{'train_runtime': 11.4848, 'train_samples_per_second': 21.768, 'train_steps_per_second': 21.768, 'train_loss': 2.855593994140625, 'epoch': 25.0}
{'train_runtime': 11.2134, 'train_samples_per_second': 22.295, 'train_steps_per_second': 22.295, 'train_loss': 2.86647119140625, 'epoch': 25.0}
{'train_runtime': 11.308, 'train_samples_per_second': 22.108, 'train_steps_per_second': 22.108, 'train_loss': 2.84528369140625, 'epoch': 25.0}
{'train_runtime': 11.6342, 'train_samples_per_second': 21.488, 'train_steps_per_second': 21.488, 'train_loss': 2.85268701171875, 'epoch': 25.0}
{'train_runtime': 11.5123, 'train_samples_per_second': 21.716, 'train_steps_per_second': 21.716, 'train_loss': 2.854191162109375, 'epoch': 25.0}
{'train_runtime': 11.5929, 'train_samples_per_second': 21.565, 'train_steps_per_second': 21.565, 'train_loss': 2.862421142578125, 'epoch': 25.0}
{'train_runtime': 11.5091, 'train_samples_per_second': 21.722, 'train_steps_per_second': 21.722, 'train_loss': 2.841438232421875, 'epoch': 25.0}
{'train_runtime': 11.6538, 'train_samples_per_second': 21.452, 'train_steps_per_second': 21.452, 'train_loss': 2.846948486328125, 'epoch': 25.0}
{'train_runtime': 11.6218, 'train_samples_per_second': 21.511, 'train_steps_per_second': 21.511, 'train_loss': 2.85239208984375, 'epoch': 25.0}
{'train_runtime': 11.5994, 'train_samples_per_second': 21.553, 'train_steps_per_second': 21.553, 'train_loss': 2.83974072265625, 'epoch': 25.0}
{'train_runtime': 11.4514, 'train_samples_per_second': 21.831, 'train_steps_per_second': 21.831, 'train_loss': 2.85513671875, 'epoch': 25.0}
{'train_runtime': 11.5453, 'train_samples_per_second': 21.654, 'train_steps_per_second': 21.654, 'train_loss': 2.8772548828125, 'epoch': 25.0}
{'train_runtime': 11.6459, 'train_samples_per_second': 21.467, 'train_steps_per_second': 21.467, 'train_loss': 2.882993408203125, 'epoch': 25.0}
{'train_runtime': 11.467, 'train_samples_per_second': 21.802, 'train_steps_per_second': 21.802, 'train_loss': 2.85314013671875, 'epoch': 25.0}
{'train_runtime': 11.3795, 'train_samples_per_second': 21.969, 'train_steps_per_second': 21.969, 'train_loss': 2.850279541015625, 'epoch': 25.0}
{'train_runtime': 11.5932, 'train_samples_per_second': 21.564, 'train_steps_per_second': 21.564, 'train_loss': 2.83850830078125, 'epoch': 25.0}
{'train_runtime': 11.5102, 'train_samples_per_second': 21.72, 'train_steps_per_second': 21.72, 'train_loss': 2.85059228515625, 'epoch': 25.0}
{'train_runtime': 11.5358, 'train_samples_per_second': 21.672, 'train_steps_per_second': 21.672, 'train_loss': 2.88030224609375, 'epoch': 25.0}
{'train_runtime': 11.5111, 'train_samples_per_second': 21.718, 'train_steps_per_second': 21.718, 'train_loss': 2.8640205078125, 'epoch': 25.0}
{'train_runtime': 11.6379, 'train_samples_per_second': 21.481, 'train_steps_per_second': 21.481, 'train_loss': 2.862644775390625, 'epoch': 25.0}
{'train_runtime': 11.5209, 'train_samples_per_second': 21.7, 'train_steps_per_second': 21.7, 'train_loss': 2.837896728515625, 'epoch': 25.0}
{'train_runtime': 11.7325, 'train_samples_per_second': 21.308, 'train_steps_per_second': 21.308, 'train_loss': 2.8430009765625, 'epoch': 25.0}
{'train_runtime': 11.6653, 'train_samples_per_second': 21.431, 'train_steps_per_second': 21.431, 'train_loss': 2.857143798828125, 'epoch': 25.0}
{'train_runtime': 11.6856, 'train_samples_per_second': 21.394, 'train_steps_per_second': 21.394, 'train_loss': 2.824915771484375, 'epoch': 25.0}
{'train_runtime': 11.7262, 'train_samples_per_second': 21.32, 'train_steps_per_second': 21.32, 'train_loss': 2.874491455078125, 'epoch': 25.0}
{'train_runtime': 11.4929, 'train_samples_per_second': 21.753, 'train_steps_per_second': 21.753, 'train_loss': 2.858827392578125, 'epoch': 25.0}
{'train_runtime': 11.6672, 'train_samples_per_second': 21.428, 'train_steps_per_second': 21.428, 'train_loss': 2.812039794921875, 'epoch': 25.0}
{'train_runtime': 11.5323, 'train_samples_per_second': 21.678, 'train_steps_per_second': 21.678, 'train_loss': 2.8366328125, 'epoch': 25.0}
{'train_runtime': 11.5358, 'train_samples_per_second': 21.672, 'train_steps_per_second': 21.672, 'train_loss': 2.82936376953125, 'epoch': 25.0}
{'train_runtime': 11.679, 'train_samples_per_second': 21.406, 'train_steps_per_second': 21.406, 'train_loss': 2.872171630859375, 'epoch': 25.0}
{'train_runtime': 11.7431, 'train_samples_per_second': 21.289, 'train_steps_per_second': 21.289, 'train_loss': 2.85069580078125, 'epoch': 25.0}
{'train_runtime': 12.0456, 'train_samples_per_second': 20.754, 'train_steps_per_second': 20.754, 'train_loss': 2.8316669921875, 'epoch': 25.0}
{'train_runtime': 11.6716, 'train_samples_per_second': 21.42, 'train_steps_per_second': 21.42, 'train_loss': 2.8389140625, 'epoch': 25.0}
{'train_runtime': 11.6498, 'train_samples_per_second': 21.46, 'train_steps_per_second': 21.46, 'train_loss': 2.8653388671875, 'epoch': 25.0}
{'train_runtime': 11.6366, 'train_samples_per_second': 21.484, 'train_steps_per_second': 21.484, 'train_loss': 2.839503173828125, 'epoch': 25.0}
{'train_runtime': 11.6487, 'train_samples_per_second': 21.462, 'train_steps_per_second': 21.462, 'train_loss': 2.84044091796875, 'epoch': 25.0}
{'train_runtime': 11.5665, 'train_samples_per_second': 21.614, 'train_steps_per_second': 21.614, 'train_loss': 2.84354296875, 'epoch': 25.0}
{'train_runtime': 11.7365, 'train_samples_per_second': 21.301, 'train_steps_per_second': 21.301, 'train_loss': 2.852717041015625, 'epoch': 25.0}
{'train_runtime': 11.6709, 'train_samples_per_second': 21.421, 'train_steps_per_second': 21.421, 'train_loss': 2.865500244140625, 'epoch': 25.0}
{'train_runtime': 11.5921, 'train_samples_per_second': 21.566, 'train_steps_per_second': 21.566, 'train_loss': 2.8380048828125, 'epoch': 25.0}
{'train_runtime': 11.5836, 'train_samples_per_second': 21.582, 'train_steps_per_second': 21.582, 'train_loss': 2.87179248046875, 'epoch': 25.0}
{'train_runtime': 11.5894, 'train_samples_per_second': 21.571, 'train_steps_per_second': 21.571, 'train_loss': 2.872302978515625, 'epoch': 25.0}
{'train_runtime': 11.5717, 'train_samples_per_second': 21.604, 'train_steps_per_second': 21.604, 'train_loss': 2.875503662109375, 'epoch': 25.0}
{'train_runtime': 11.614, 'train_samples_per_second': 21.526, 'train_steps_per_second': 21.526, 'train_loss': 2.841643310546875, 'epoch': 25.0}
{'train_runtime': 11.4473, 'train_samples_per_second': 21.839, 'train_steps_per_second': 21.839, 'train_loss': 2.831946044921875, 'epoch': 25.0}
{'train_runtime': 11.8026, 'train_samples_per_second': 21.182, 'train_steps_per_second': 21.182, 'train_loss': 2.86866748046875, 'epoch': 25.0}
{'train_runtime': 11.6366, 'train_samples_per_second': 21.484, 'train_steps_per_second': 21.484, 'train_loss': 2.87546484375, 'epoch': 25.0}
{'train_runtime': 11.6001, 'train_samples_per_second': 21.552, 'train_steps_per_second': 21.552, 'train_loss': 2.84481201171875, 'epoch': 25.0}
{'train_runtime': 11.4448, 'train_samples_per_second': 21.844, 'train_steps_per_second': 21.844, 'train_loss': 2.841635498046875, 'epoch': 25.0}
{'train_runtime': 11.5511, 'train_samples_per_second': 21.643, 'train_steps_per_second': 21.643, 'train_loss': 2.843489990234375, 'epoch': 25.0}
{'train_runtime': 11.3707, 'train_samples_per_second': 21.986, 'train_steps_per_second': 21.986, 'train_loss': 2.865649169921875, 'epoch': 25.0}
{'train_runtime': 11.3276, 'train_samples_per_second': 22.07, 'train_steps_per_second': 22.07, 'train_loss': 2.872248046875, 'epoch': 25.0}
{'train_runtime': 11.49, 'train_samples_per_second': 21.758, 'train_steps_per_second': 21.758, 'train_loss': 2.839796875, 'epoch': 25.0}
{'train_runtime': 11.3517, 'train_samples_per_second': 22.023, 'train_steps_per_second': 22.023, 'train_loss': 2.8509638671875, 'epoch': 25.0}
{'train_runtime': 11.4444, 'train_samples_per_second': 21.845, 'train_steps_per_second': 21.845, 'train_loss': 2.84705322265625, 'epoch': 25.0}

Explanations:  33%|███▎      | 459/1400 [26:32<1:03:07,  4.02s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 11.3485, 'train_samples_per_second': 22.029, 'train_steps_per_second': 22.029, 'train_loss': 2.879451904296875, 'epoch': 25.0}
{'train_runtime': 11.5122, 'train_samples_per_second': 21.716, 'train_steps_per_second': 21.716, 'train_loss': 2.88292236328125, 'epoch': 25.0}
{'train_runtime': 11.247, 'train_samples_per_second': 22.228, 'train_steps_per_second': 22.228, 'train_loss': 2.85170458984375, 'epoch': 25.0}
{'train_runtime': 11.1902, 'train_samples_per_second': 22.341, 'train_steps_per_second': 22.341, 'train_loss': 2.876319091796875, 'epoch': 25.0}
{'train_runtime': 11.306, 'train_samples_per_second': 22.112, 'train_steps_per_second': 22.112, 'train_loss': 2.853181640625, 'epoch': 25.0}
{'train_runtime': 11.3244, 'train_samples_per_second': 22.076, 'train_steps_per_second': 22.076, 'train_loss': 2.838421630859375, 'epoch': 25.0}
{'train_runtime': 11.5204, 'train_samples_per_second': 21.701, 'train_steps_per_second': 21.701, 'train_loss': 2.831406005859375, 'epoch': 25.0}
{'train_runtime': 11.3023, 'train_samples_per_second': 22.119, 'train_steps_per_second': 22.119, 'train_loss': 2.8571748046875, 'epoch': 25.0}
{'train_runtime': 11.4637, 'train_samples_per_second': 21.808, 'train_steps_per_second': 21.808, 'train_loss': 2.88028173828125, 'epoch': 25.0}
{'train_runtime': 11.6808, 'train_samples_per_second': 21.403, 'train_steps_per_second': 21.403, 'train_loss': 2.840831298828125, 'epoch': 25.0}
{'train_runtime': 11.3535, 'train_samples_per_second': 22.02, 'train_steps_per_second': 22.02, 'train_loss': 2.852833984375, 'epoch': 25.0}
{'train_runtime': 11.4735, 'train_samples_per_second': 21.789, 'train_steps_per_second': 21.789, 'train_loss': 2.852929443359375, 'epoch': 25.0}
{'train_runtime': 11.4661, 'train_samples_per_second': 21.803, 'train_steps_per_second': 21.803, 'train_loss': 2.827714599609375, 'epoch': 25.0}
{'train_runtime': 11.4033, 'train_samples_per_second': 21.923, 'train_steps_per_second': 21.923, 'train_loss': 2.882629638671875, 'epoch': 25.0}
{'train_runtime': 11.4215, 'train_samples_per_second': 21.889, 'train_steps_per_second': 21.889, 'train_loss': 2.8606787109375, 'epoch': 25.0}
{'train_runtime': 11.366, 'train_samples_per_second': 21.995, 'train_steps_per_second': 21.995, 'train_loss': 2.86186767578125, 'epoch': 25.0}
{'train_runtime': 11.4948, 'train_samples_per_second': 21.749, 'train_steps_per_second': 21.749, 'train_loss': 2.8745478515625, 'epoch': 25.0}
{'train_runtime': 11.4957, 'train_samples_per_second': 21.747, 'train_steps_per_second': 21.747, 'train_loss': 2.83126611328125, 'epoch': 25.0}
{'train_runtime': 11.4858, 'train_samples_per_second': 21.766, 'train_steps_per_second': 21.766, 'train_loss': 2.840236572265625, 'epoch': 25.0}
{'train_runtime': 11.491, 'train_samples_per_second': 21.756, 'train_steps_per_second': 21.756, 'train_loss': 2.8359345703125, 'epoch': 25.0}
{'train_runtime': 11.5466, 'train_samples_per_second': 21.651, 'train_steps_per_second': 21.651, 'train_loss': 2.8558955078125, 'epoch': 25.0}
{'train_runtime': 11.4472, 'train_samples_per_second': 21.839, 'train_steps_per_second': 21.839, 'train_loss': 2.83340185546875, 'epoch': 25.0}
{'train_runtime': 11.5392, 'train_samples_per_second': 21.665, 'train_steps_per_second': 21.665, 'train_loss': 2.8676494140625, 'epoch': 25.0}
{'train_runtime': 11.5977, 'train_samples_per_second': 21.556, 'train_steps_per_second': 21.556, 'train_loss': 2.873732421875, 'epoch': 25.0}
{'train_runtime': 11.459, 'train_samples_per_second': 21.817, 'train_steps_per_second': 21.817, 'train_loss': 2.845459716796875, 'epoch': 25.0}
{'train_runtime': 11.5183, 'train_samples_per_second': 21.705, 'train_steps_per_second': 21.705, 'train_loss': 2.86486865234375, 'epoch': 25.0}
{'train_runtime': 11.5407, 'train_samples_per_second': 21.662, 'train_steps_per_second': 21.662, 'train_loss': 2.854179443359375, 'epoch': 25.0}
{'train_runtime': 11.5314, 'train_samples_per_second': 21.68, 'train_steps_per_second': 21.68, 'train_loss': 2.857797607421875, 'epoch': 25.0}
{'train_runtime': 11.8423, 'train_samples_per_second': 21.111, 'train_steps_per_second': 21.111, 'train_loss': 2.85412060546875, 'epoch': 25.0}
{'train_runtime': 11.4929, 'train_samples_per_second': 21.753, 'train_steps_per_second': 21.753, 'train_loss': 2.8465927734375, 'epoch': 25.0}
{'train_runtime': 11.6568, 'train_samples_per_second': 21.447, 'train_steps_per_second': 21.447, 'train_loss': 2.838758544921875, 'epoch': 25.0}
{'train_runtime': 11.6034, 'train_samples_per_second': 21.545, 'train_steps_per_second': 21.545, 'train_loss': 2.877526611328125, 'epoch': 25.0}
{'train_runtime': 11.5205, 'train_samples_per_second': 21.7, 'train_steps_per_second': 21.7, 'train_loss': 2.839509521484375, 'epoch': 25.0}
{'train_runtime': 11.7218, 'train_samples_per_second': 21.328, 'train_steps_per_second': 21.328, 'train_loss': 2.85971484375, 'epoch': 25.0}
{'train_runtime': 11.5955, 'train_samples_per_second': 21.56, 'train_steps_per_second': 21.56, 'train_loss': 2.87468115234375, 'epoch': 25.0}
{'train_runtime': 11.6786, 'train_samples_per_second': 21.407, 'train_steps_per_second': 21.407, 'train_loss': 2.839407958984375, 'epoch': 25.0}
{'train_runtime': 11.5783, 'train_samples_per_second': 21.592, 'train_steps_per_second': 21.592, 'train_loss': 2.85545263671875, 'epoch': 25.0}
{'train_runtime': 11.6607, 'train_samples_per_second': 21.44, 'train_steps_per_second': 21.44, 'train_loss': 2.8772353515625, 'epoch': 25.0}
{'train_runtime': 11.5089, 'train_samples_per_second': 21.722, 'train_steps_per_second': 21.722, 'train_loss': 2.837247314453125, 'epoch': 25.0}
{'train_runtime': 11.6167, 'train_samples_per_second': 21.521, 'train_steps_per_second': 21.521, 'train_loss': 2.855785400390625, 'epoch': 25.0}
{'train_runtime': 11.6793, 'train_samples_per_second': 21.405, 'train_steps_per_second': 21.405, 'train_loss': 2.84753076171875, 'epoch': 25.0}
{'train_runtime': 11.6586, 'train_samples_per_second': 21.443, 'train_steps_per_second': 21.443, 'train_loss': 2.852879150390625, 'epoch': 25.0}
{'train_runtime': 11.4835, 'train_samples_per_second': 21.77, 'train_steps_per_second': 21.77, 'train_loss': 2.830707275390625, 'epoch': 25.0}
{'train_runtime': 11.7287, 'train_samples_per_second': 21.315, 'train_steps_per_second': 21.315, 'train_loss': 2.8814365234375, 'epoch': 25.0}
{'train_runtime': 11.7059, 'train_samples_per_second': 21.357, 'train_steps_per_second': 21.357, 'train_loss': 2.872582275390625, 'epoch': 25.0}
{'train_runtime': 11.7312, 'train_samples_per_second': 21.311, 'train_steps_per_second': 21.311, 'train_loss': 2.84594921875, 'epoch': 25.0}
{'train_runtime': 11.7196, 'train_samples_per_second': 21.332, 'train_steps_per_second': 21.332, 'train_loss': 2.843315185546875, 'epoch': 25.0}
{'train_runtime': 11.7695, 'train_samples_per_second': 21.241, 'train_steps_per_second': 21.241, 'train_loss': 2.864961181640625, 'epoch': 25.0}
{'train_runtime': 11.7632, 'train_samples_per_second': 21.253, 'train_steps_per_second': 21.253, 'train_loss': 2.8386455078125, 'epoch': 25.0}
{'train_runtime': 11.7561, 'train_samples_per_second': 21.265, 'train_steps_per_second': 21.265, 'train_loss': 2.86394873046875, 'epoch': 25.0}
{'train_runtime': 11.8335, 'train_samples_per_second': 21.127, 'train_steps_per_second': 21.127, 'train_loss': 2.8599130859375, 'epoch': 25.0}
{'train_runtime': 11.6822, 'train_samples_per_second': 21.4, 'train_steps_per_second': 21.4, 'train_loss': 2.842317626953125, 'epoch': 25.0}
{'train_runtime': 11.8201, 'train_samples_per_second': 21.15, 'train_steps_per_second': 21.15, 'train_loss': 2.860334716796875, 'epoch': 25.0}
{'train_runtime': 11.667, 'train_samples_per_second': 21.428, 'train_steps_per_second': 21.428, 'train_loss': 2.84027734375, 'epoch': 25.0}
{'train_runtime': 11.765, 'train_samples_per_second': 21.249, 'train_steps_per_second': 21.249, 'train_loss': 2.854822998046875, 'epoch': 25.0}
{'train_runtime': 11.6339, 'train_samples_per_second': 21.489, 'train_steps_per_second': 21.489, 'train_loss': 2.87797412109375, 'epoch': 25.0}
{'train_runtime': 11.5486, 'train_samples_per_second': 21.648, 'train_steps_per_second': 21.648, 'train_loss': 2.834364501953125, 'epoch': 25.0}

Explanations:  33%|███▎      | 460/1400 [26:35<1:01:58,  3.96s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 462/1400 [26:38<39:40,  2.54s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 463/1400 [26:45<1:01:35,  3.94s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 464/1400 [26:49<1:02:23,  4.00s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 466/1400 [26:51<39:45,  2.55s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 467/1400 [26:58<59:55,  3.85s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  33%|███▎      | 468/1400 [27:03<1:02:05,  4.00s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▎      | 470/1400 [27:05<39:18,  2.54s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▎      | 471/1400 [27:12<58:11,  3.76s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▎      | 472/1400 [27:16<1:01:36,  3.98s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 474/1400 [27:19<39:34,  2.56s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 475/1400 [27:25<56:57,  3.69s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 476/1400 [27:30<1:01:12,  3.97s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 478/1400 [27:32<39:48,  2.59s/it]  No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 479/1400 [27:39<55:49,  3.64s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 480/1400 [27:43<59:19,  3.87s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 482/1400 [27:46<41:05,  2.69s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  34%|███▍      | 483/1400 [27:52<54:15,  3.55s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▍      | 484/1400 [27:56<58:25,  3.83s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▍      | 485/1400 [27:59<52:49,  3.46s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▍      | 486/1400 [28:00<43:02,  2.83s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▍      | 487/1400 [28:06<53:54,  3.54s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▍      | 488/1400 [28:10<56:00,  3.69s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▍      | 489/1400 [28:12<52:24,  3.45s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▌      | 490/1400 [28:14<43:13,  2.85s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▌      | 491/1400 [28:20<55:57,  3.69s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▌      | 492/1400 [28:23<55:06,  3.64s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▌      | 493/1400 [28:26<52:26,  3.47s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▌      | 494/1400 [28:27<42:28,  2.81s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▌      | 495/1400 [28:33<56:00,  3.71s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  35%|███▌      | 496/1400 [28:37<55:05,  3.66s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 497/1400 [28:40<51:38,  3.43s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 498/1400 [28:41<41:49,  2.78s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 499/1400 [28:47<54:17,  3.62s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 500/1400 [28:50<51:47,  3.45s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 501/1400 [28:52<47:16,  3.16s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 502/1400 [28:54<40:00,  2.67s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 503/1400 [28:59<50:05,  3.35s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 504/1400 [29:02<49:11,  3.29s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 505/1400 [29:04<44:04,  2.95s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 506/1400 [29:06<38:54,  2.61s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▌      | 507/1400 [29:10<48:23,  3.25s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▋      | 508/1400 [29:14<48:55,  3.29s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▋      | 509/1400 [29:16<43:42,  2.94s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▋      | 510/1400 [29:18<38:25,  2.59s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  36%|███▋      | 511/1400 [29:22<47:23,  3.20s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 512/1400 [29:26<48:23,  3.27s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 513/1400 [29:28<44:07,  2.99s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 514/1400 [29:30<38:31,  2.61s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 515/1400 [29:34<46:00,  3.12s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 516/1400 [29:38<47:26,  3.22s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 517/1400 [29:40<44:23,  3.02s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 518/1400 [29:42<38:54,  2.65s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 519/1400 [29:46<47:19,  3.22s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 520/1400 [29:49<46:08,  3.15s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 521/1400 [29:52<43:06,  2.94s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  37%|███▋      | 522/1400 [29:54<38:51,  2.66s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 11.8189, 'train_samples_per_second': 21.153, 'train_steps_per_second': 21.153, 'train_loss': 2.871040771484375, 'epoch': 25.0}
{'train_runtime': 11.9032, 'train_samples_per_second': 21.003, 'train_steps_per_second': 21.003, 'train_loss': 2.85820166015625, 'epoch': 25.0}
{'train_runtime': 11.7405, 'train_samples_per_second': 21.294, 'train_steps_per_second': 21.294, 'train_loss': 2.841603759765625, 'epoch': 25.0}
{'train_runtime': 11.6912, 'train_samples_per_second': 21.384, 'train_steps_per_second': 21.384, 'train_loss': 2.84550341796875, 'epoch': 25.0}
{'train_runtime': 11.7075, 'train_samples_per_second': 21.354, 'train_steps_per_second': 21.354, 'train_loss': 2.887130126953125, 'epoch': 25.0}
{'train_runtime': 11.653, 'train_samples_per_second': 21.454, 'train_steps_per_second': 21.454, 'train_loss': 2.914072021484375, 'epoch': 25.0}
{'train_runtime': 11.821, 'train_samples_per_second': 21.149, 'train_steps_per_second': 21.149, 'train_loss': 2.8337880859375, 'epoch': 25.0}
{'train_runtime': 11.7143, 'train_samples_per_second': 21.342, 'train_steps_per_second': 21.342, 'train_loss': 2.84378466796875, 'epoch': 25.0}
{'train_runtime': 11.5091, 'train_samples_per_second': 21.722, 'train_steps_per_second': 21.722, 'train_loss': 2.885571533203125, 'epoch': 25.0}
{'train_runtime': 11.3631, 'train_samples_per_second': 22.001, 'train_steps_per_second': 22.001, 'train_loss': 2.90935205078125, 'epoch': 25.0}
{'train_runtime': 11.7221, 'train_samples_per_second': 21.327, 'train_steps_per_second': 21.327, 'train_loss': 2.85394580078125, 'epoch': 25.0}
{'train_runtime': 11.4495, 'train_samples_per_second': 21.835, 'train_steps_per_second': 21.835, 'train_loss': 2.83993115234375, 'epoch': 25.0}
{'train_runtime': 10.4207, 'train_samples_per_second': 23.991, 'train_steps_per_second': 23.991, 'train_loss': 2.6502138671875, 'epoch': 25.0}
{'train_runtime': 9.8703, 'train_samples_per_second': 25.328, 'train_steps_per_second': 25.328, 'train_loss': 2.649959228515625, 'epoch': 25.0}
{'train_runtime': 10.0582, 'train_samples_per_second': 24.855, 'train_steps_per_second': 24.855, 'train_loss': 2.652688232421875, 'epoch': 25.0}
{'train_runtime': 9.9587, 'train_samples_per_second': 25.104, 'train_steps_per_second': 25.104, 'train_loss': 2.66362060546875, 'epoch': 25.0}
{'train_runtime': 9.8749, 'train_samples_per_second': 25.317, 'train_steps_per_second': 25.317, 'train_loss': 2.64689306640625, 'epoch': 25.0}
{'train_runtime': 9.8349, 'train_samples_per_second': 25.42, 'train_steps_per_second': 25.42, 'train_loss': 2.619064208984375, 'epoch': 25.0}
{'train_runtime': 9.9027, 'train_samples_per_second': 25.246, 'train_steps_per_second': 25.246, 'train_loss': 2.678343017578125, 'epoch': 25.0}
{'train_runtime': 9.8099, 'train_samples_per_second': 25.484, 'train_steps_per_second': 25.484, 'train_loss': 2.6100546875, 'epoch': 25.0}
{'train_runtime': 10.0398, 'train_samples_per_second': 24.901, 'train_steps_per_second': 24.901, 'train_loss': 2.69565087890625, 'epoch': 25.0}
{'train_runtime': 10.0281, 'train_samples_per_second': 24.93, 'train_steps_per_second': 24.93, 'train_loss': 2.672468017578125, 'epoch': 25.0}
{'train_runtime': 10.0729, 'train_samples_per_second': 24.819, 'train_steps_per_second': 24.819, 'train_loss': 2.64080322265625, 'epoch': 25.0}
{'train_runtime': 9.8542, 'train_samples_per_second': 25.37, 'train_steps_per_second': 25.37, 'train_loss': 2.6476708984375, 'epoch': 25.0}
{'train_runtime': 10.0634, 'train_samples_per_second': 24.842, 'train_steps_per_second': 24.842, 'train_loss': 2.643592529296875, 'epoch': 25.0}
{'train_runtime': 10.0424, 'train_samples_per_second': 24.895, 'train_steps_per_second': 24.895, 'train_loss': 2.624063720703125, 'epoch': 25.0}
{'train_runtime': 10.1048, 'train_samples_per_second': 24.741, 'train_steps_per_second': 24.741, 'train_loss': 2.61028369140625, 'epoch': 25.0}
{'train_runtime': 10.0782, 'train_samples_per_second': 24.806, 'train_steps_per_second': 24.806, 'train_loss': 2.650130859375, 'epoch': 25.0}
{'train_runtime': 9.9045, 'train_samples_per_second': 25.241, 'train_steps_per_second': 25.241, 'train_loss': 2.62557666015625, 'epoch': 25.0}
{'train_runtime': 9.9906, 'train_samples_per_second': 25.024, 'train_steps_per_second': 25.024, 'train_loss': 2.6440625, 'epoch': 25.0}
{'train_runtime': 10.0487, 'train_samples_per_second': 24.879, 'train_steps_per_second': 24.879, 'train_loss': 2.685564697265625, 'epoch': 25.0}
{'train_runtime': 9.8635, 'train_samples_per_second': 25.346, 'train_steps_per_second': 25.346, 'train_loss': 2.67006005859375, 'epoch': 25.0}
{'train_runtime': 10.0212, 'train_samples_per_second': 24.947, 'train_steps_per_second': 24.947, 'train_loss': 2.638132568359375, 'epoch': 25.0}
{'train_runtime': 10.0125, 'train_samples_per_second': 24.969, 'train_steps_per_second': 24.969, 'train_loss': 2.676256591796875, 'epoch': 25.0}
{'train_runtime': 9.8269, 'train_samples_per_second': 25.44, 'train_steps_per_second': 25.44, 'train_loss': 2.64119384765625, 'epoch': 25.0}
{'train_runtime': 9.8181, 'train_samples_per_second': 25.463, 'train_steps_per_second': 25.463, 'train_loss': 2.622408935546875, 'epoch': 25.0}
{'train_runtime': 9.9622, 'train_samples_per_second': 25.095, 'train_steps_per_second': 25.095, 'train_loss': 2.66320166015625, 'epoch': 25.0}
{'train_runtime': 10.7454, 'train_samples_per_second': 23.266, 'train_steps_per_second': 23.266, 'train_loss': 3.049387451171875, 'epoch': 25.0}
{'train_runtime': 10.9987, 'train_samples_per_second': 22.73, 'train_steps_per_second': 22.73, 'train_loss': 3.030174072265625, 'epoch': 25.0}
{'train_runtime': 11.0154, 'train_samples_per_second': 22.695, 'train_steps_per_second': 22.695, 'train_loss': 3.08255810546875, 'epoch': 25.0}
{'train_runtime': 11.2426, 'train_samples_per_second': 22.237, 'train_steps_per_second': 22.237, 'train_loss': 3.06607470703125, 'epoch': 25.0}
{'train_runtime': 11.0486, 'train_samples_per_second': 22.627, 'train_steps_per_second': 22.627, 'train_loss': 3.04179150390625, 'epoch': 25.0}
{'train_runtime': 11.1115, 'train_samples_per_second': 22.499, 'train_steps_per_second': 22.499, 'train_loss': 3.079828857421875, 'epoch': 25.0}
{'train_runtime': 11.0713, 'train_samples_per_second': 22.581, 'train_steps_per_second': 22.581, 'train_loss': 3.087621826171875, 'epoch': 25.0}
{'train_runtime': 11.0362, 'train_samples_per_second': 22.653, 'train_steps_per_second': 22.653, 'train_loss': 3.05255126953125, 'epoch': 25.0}
{'train_runtime': 11.0543, 'train_samples_per_second': 22.616, 'train_steps_per_second': 22.616, 'train_loss': 3.055155029296875, 'epoch': 25.0}
{'train_runtime': 11.0261, 'train_samples_per_second': 22.673, 'train_steps_per_second': 22.673, 'train_loss': 3.031454833984375, 'epoch': 25.0}
{'train_runtime': 11.0896, 'train_samples_per_second': 22.544, 'train_steps_per_second': 22.544, 'train_loss': 3.06454345703125, 'epoch': 25.0}
{'train_runtime': 11.166, 'train_samples_per_second': 22.389, 'train_steps_per_second': 22.389, 'train_loss': 3.057032958984375, 'epoch': 25.0}
{'train_runtime': 11.0899, 'train_samples_per_second': 22.543, 'train_steps_per_second': 22.543, 'train_loss': 3.07639599609375, 'epoch': 25.0}
{'train_runtime': 10.8556, 'train_samples_per_second': 23.03, 'train_steps_per_second': 23.03, 'train_loss': 3.071984619140625, 'epoch': 25.0}
{'train_runtime': 10.9894, 'train_samples_per_second': 22.749, 'train_steps_per_second': 22.749, 'train_loss': 3.023869384765625, 'epoch': 25.0}
{'train_runtime': 11.0008, 'train_samples_per_second': 22.726, 'train_steps_per_second': 22.726, 'train_loss': 3.072044677734375, 'epoch': 25.0}
{'train_runtime': 11.0864, 'train_samples_per_second': 22.55, 'train_steps_per_second': 22.55, 'train_loss': 3.044675048828125, 'epoch': 25.0}
{'train_runtime': 11.0164, 'train_samples_per_second': 22.694, 'train_steps_per_second': 22.694, 'train_loss': 3.055595947265625, 'epoch': 25.0}
{'train_runtime': 11.1247, 'train_samples_per_second': 22.473, 'train_steps_per_second': 22.473, 'train_loss': 3.066748291015625, 'epoch': 25.0}
{'train_runtime': 11.1689, 'train_samples_per_second': 22.384, 'train_steps_per_second': 22.384, 'train_loss': 3.0373662109375, 'epoch': 25.0}

Explanations:  49%|████▊     | 681/1400 [38:15<35:05,  2.93s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▊     | 682/1400 [38:20<39:43,  3.32s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▉     | 683/1400 [38:25<45:09,  3.78s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▉     | 684/1400 [38:26<38:09,  3.20s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▉     | 685/1400 [38:29<34:56,  2.93s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 11.614, 'train_samples_per_second': 21.526, 'train_steps_per_second': 21.526, 'train_loss': 2.810153076171875, 'epoch': 25.0}
{'train_runtime': 11.7069, 'train_samples_per_second': 21.355, 'train_steps_per_second': 21.355, 'train_loss': 2.837221435546875, 'epoch': 25.0}
{'train_runtime': 11.7277, 'train_samples_per_second': 21.317, 'train_steps_per_second': 21.317, 'train_loss': 2.853242431640625, 'epoch': 25.0}
{'train_runtime': 11.682, 'train_samples_per_second': 21.4, 'train_steps_per_second': 21.4, 'train_loss': 2.881673095703125, 'epoch': 25.0}
{'train_runtime': 11.7084, 'train_samples_per_second': 21.352, 'train_steps_per_second': 21.352, 'train_loss': 2.861889404296875, 'epoch': 25.0}
{'train_runtime': 11.7388, 'train_samples_per_second': 21.297, 'train_steps_per_second': 21.297, 'train_loss': 2.877039794921875, 'epoch': 25.0}
{'train_runtime': 11.7565, 'train_samples_per_second': 21.265, 'train_steps_per_second': 21.265, 'train_loss': 2.869344482421875, 'epoch': 25.0}
{'train_runtime': 11.6499, 'train_samples_per_second': 21.459, 'train_steps_per_second': 21.459, 'train_loss': 2.849271728515625, 'epoch': 25.0}
{'train_runtime': 11.5882, 'train_samples_per_second': 21.574, 'train_steps_per_second': 21.574, 'train_loss': 2.84614404296875, 'epoch': 25.0}
{'train_runtime': 11.5451, 'train_samples_per_second': 21.654, 'train_steps_per_second': 21.654, 'train_loss': 2.87299462890625, 'epoch': 25.0}
{'train_runtime': 11.5477, 'train_samples_per_second': 21.649, 'train_steps_per_second': 21.649, 'train_loss': 2.86809814453125, 'epoch': 25.0}
{'train_runtime': 10.4365, 'train_samples_per_second': 23.954, 'train_steps_per_second': 23.954, 'train_loss': 2.6719208984375, 'epoch': 25.0}
{'train_runtime': 10.0875, 'train_samples_per_second': 24.783, 'train_steps_per_second': 24.783, 'train_loss': 2.63707080078125, 'epoch': 25.0}
{'train_runtime': 9.9628, 'train_samples_per_second': 25.093, 'train_steps_per_second': 25.093, 'train_loss': 2.639960205078125, 'epoch': 25.0}
{'train_runtime': 10.0378, 'train_samples_per_second': 24.906, 'train_steps_per_second': 24.906, 'train_loss': 2.648310791015625, 'epoch': 25.0}
{'train_runtime': 10.0741, 'train_samples_per_second': 24.816, 'train_steps_per_second': 24.816, 'train_loss': 2.66876708984375, 'epoch': 25.0}
{'train_runtime': 9.9531, 'train_samples_per_second': 25.118, 'train_steps_per_second': 25.118, 'train_loss': 2.6695478515625, 'epoch': 25.0}
{'train_runtime': 9.8193, 'train_samples_per_second': 25.46, 'train_steps_per_second': 25.46, 'train_loss': 2.643018310546875, 'epoch': 25.0}
{'train_runtime': 9.8607, 'train_samples_per_second': 25.353, 'train_steps_per_second': 25.353, 'train_loss': 2.628017578125, 'epoch': 25.0}
{'train_runtime': 10.0818, 'train_samples_per_second': 24.797, 'train_steps_per_second': 24.797, 'train_loss': 2.671451904296875, 'epoch': 25.0}
{'train_runtime': 9.9907, 'train_samples_per_second': 25.023, 'train_steps_per_second': 25.023, 'train_loss': 2.654412841796875, 'epoch': 25.0}
{'train_runtime': 9.9319, 'train_samples_per_second': 25.172, 'train_steps_per_second': 25.172, 'train_loss': 2.6404228515625, 'epoch': 25.0}
{'train_runtime': 9.9159, 'train_samples_per_second': 25.212, 'train_steps_per_second': 25.212, 'train_loss': 2.6600927734375, 'epoch': 25.0}
{'train_runtime': 9.9278, 'train_samples_per_second': 25.182, 'train_steps_per_second': 25.182, 'train_loss': 2.644730224609375, 'epoch': 25.0}
{'train_runtime': 9.9562, 'train_samples_per_second': 25.11, 'train_steps_per_second': 25.11, 'train_loss': 2.660220703125, 'epoch': 25.0}
{'train_runtime': 9.9332, 'train_samples_per_second': 25.168, 'train_steps_per_second': 25.168, 'train_loss': 2.61961279296875, 'epoch': 25.0}
{'train_runtime': 10.0942, 'train_samples_per_second': 24.767, 'train_steps_per_second': 24.767, 'train_loss': 2.6600205078125, 'epoch': 25.0}
{'train_runtime': 10.0868, 'train_samples_per_second': 24.785, 'train_steps_per_second': 24.785, 'train_loss': 2.64236279296875, 'epoch': 25.0}
{'train_runtime': 9.8893, 'train_samples_per_second': 25.28, 'train_steps_per_second': 25.28, 'train_loss': 2.657370361328125, 'epoch': 25.0}
{'train_runtime': 9.8729, 'train_samples_per_second': 25.322, 'train_steps_per_second': 25.322, 'train_loss': 2.674337890625, 'epoch': 25.0}
{'train_runtime': 10.1345, 'train_samples_per_second': 24.668, 'train_steps_per_second': 24.668, 'train_loss': 2.67620068359375, 'epoch': 25.0}
{'train_runtime': 9.9672, 'train_samples_per_second': 25.082, 'train_steps_per_second': 25.082, 'train_loss': 2.627772216796875, 'epoch': 25.0}
{'train_runtime': 10.132, 'train_samples_per_second': 24.674, 'train_steps_per_second': 24.674, 'train_loss': 2.67601220703125, 'epoch': 25.0}
{'train_runtime': 9.9392, 'train_samples_per_second': 25.153, 'train_steps_per_second': 25.153, 'train_loss': 2.62915234375, 'epoch': 25.0}
{'train_runtime': 9.9412, 'train_samples_per_second': 25.148, 'train_steps_per_second': 25.148, 'train_loss': 2.665898681640625, 'epoch': 25.0}
{'train_runtime': 10.2226, 'train_samples_per_second': 24.456, 'train_steps_per_second': 24.456, 'train_loss': 2.662473388671875, 'epoch': 25.0}
{'train_runtime': 11.0224, 'train_samples_per_second': 22.681, 'train_steps_per_second': 22.681, 'train_loss': 3.0918740234375, 'epoch': 25.0}
{'train_runtime': 10.9363, 'train_samples_per_second': 22.86, 'train_steps_per_second': 22.86, 'train_loss': 3.041489013671875, 'epoch': 25.0}
{'train_runtime': 11.0402, 'train_samples_per_second': 22.645, 'train_steps_per_second': 22.645, 'train_loss': 3.063002685546875, 'epoch': 25.0}
{'train_runtime': 10.9911, 'train_samples_per_second': 22.746, 'train_steps_per_second': 22.746, 'train_loss': 3.0680380859375, 'epoch': 25.0}
{'train_runtime': 11.2197, 'train_samples_per_second': 22.282, 'train_steps_per_second': 22.282, 'train_loss': 3.077425537109375, 'epoch': 25.0}
{'train_runtime': 11.0727, 'train_samples_per_second': 22.578, 'train_steps_per_second': 22.578, 'train_loss': 3.078000732421875, 'epoch': 25.0}
{'train_runtime': 11.2794, 'train_samples_per_second': 22.164, 'train_steps_per_second': 22.164, 'train_loss': 3.075024658203125, 'epoch': 25.0}
{'train_runtime': 11.2404, 'train_samples_per_second': 22.241, 'train_steps_per_second': 22.241, 'train_loss': 3.049701171875, 'epoch': 25.0}
{'train_runtime': 11.2038, 'train_samples_per_second': 22.314, 'train_steps_per_second': 22.314, 'train_loss': 3.08547265625, 'epoch': 25.0}
{'train_runtime': 10.9891, 'train_samples_per_second': 22.75, 'train_steps_per_second': 22.75, 'train_loss': 3.04486083984375, 'epoch': 25.0}
{'train_runtime': 11.0645, 'train_samples_per_second': 22.595, 'train_steps_per_second': 22.595, 'train_loss': 3.04524755859375, 'epoch': 25.0}
{'train_runtime': 11.2732, 'train_samples_per_second': 22.176, 'train_steps_per_second': 22.176, 'train_loss': 3.048501220703125, 'epoch': 25.0}
{'train_runtime': 11.1593, 'train_samples_per_second': 22.403, 'train_steps_per_second': 22.403, 'train_loss': 3.073681884765625, 'epoch': 25.0}
{'train_runtime': 11.1315, 'train_samples_per_second': 22.459, 'train_steps_per_second': 22.459, 'train_loss': 3.08869189453125, 'epoch': 25.0}
{'train_runtime': 11.1138, 'train_samples_per_second': 22.495, 'train_steps_per_second': 22.495, 'train_loss': 3.022800048828125, 'epoch': 25.0}
{'train_runtime': 11.066, 'train_samples_per_second': 22.592, 'train_steps_per_second': 22.592, 'train_loss': 3.085193603515625, 'epoch': 25.0}
{'train_runtime': 11.1148, 'train_samples_per_second': 22.493, 'train_steps_per_second': 22.493, 'train_loss': 3.04841552734375, 'epoch': 25.0}
{'train_runtime': 10.9372, 'train_samples_per_second': 22.858, 'train_steps_per_second': 22.858, 'train_loss': 3.057377197265625, 'epoch': 25.0}
{'train_runtime': 11.0635, 'train_samples_per_second': 22.597, 'train_steps_per_second': 22.597, 'train_loss': 3.084235107421875, 'epoch': 25.0}
{'train_runtime': 10.94, 'train_samples_per_second': 22.852, 'train_steps_per_second': 22.852, 'train_loss': 3.04738427734375, 'epoch': 25.0}
{'train_runtime': 11.2897, 'train_samples_per_second': 22.144, 'train_steps_per_second': 22.144, 'train_loss': 3.0875556640625, 'epoch': 25.0}

Explanations:  49%|████▉     | 686/1400 [38:33<40:03,  3.37s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

{'train_runtime': 11.256, 'train_samples_per_second': 22.21, 'train_steps_per_second': 22.21, 'train_loss': 2.83835888671875, 'epoch': 25.0}
{'train_runtime': 11.3482, 'train_samples_per_second': 22.03, 'train_steps_per_second': 22.03, 'train_loss': 2.86449462890625, 'epoch': 25.0}
{'train_runtime': 11.4115, 'train_samples_per_second': 21.908, 'train_steps_per_second': 21.908, 'train_loss': 2.872567138671875, 'epoch': 25.0}
{'train_runtime': 11.2597, 'train_samples_per_second': 22.203, 'train_steps_per_second': 22.203, 'train_loss': 2.861055908203125, 'epoch': 25.0}
{'train_runtime': 11.3216, 'train_samples_per_second': 22.082, 'train_steps_per_second': 22.082, 'train_loss': 2.838092041015625, 'epoch': 25.0}
{'train_runtime': 11.4273, 'train_samples_per_second': 21.877, 'train_steps_per_second': 21.877, 'train_loss': 2.85809765625, 'epoch': 25.0}
{'train_runtime': 11.1644, 'train_samples_per_second': 22.393, 'train_steps_per_second': 22.393, 'train_loss': 2.851984375, 'epoch': 25.0}
{'train_runtime': 11.5062, 'train_samples_per_second': 21.727, 'train_steps_per_second': 21.727, 'train_loss': 2.85721435546875, 'epoch': 25.0}
{'train_runtime': 11.6708, 'train_samples_per_second': 21.421, 'train_steps_per_second': 21.421, 'train_loss': 2.864476318359375, 'epoch': 25.0}
{'train_runtime': 11.5416, 'train_samples_per_second': 21.661, 'train_steps_per_second': 21.661, 'train_loss': 2.834435791015625, 'epoch': 25.0}
{'train_runtime': 10.9744, 'train_samples_per_second': 22.78, 'train_steps_per_second': 22.78, 'train_loss': 2.84591015625, 'epoch': 25.0}
{'train_runtime': 10.0188, 'train_samples_per_second': 24.953, 'train_steps_per_second': 24.953, 'train_loss': 2.68108447265625, 'epoch': 25.0}
{'train_runtime': 9.8679, 'train_samples_per_second': 25.335, 'train_steps_per_second': 25.335, 'train_loss': 2.622921875, 'epoch': 25.0}
{'train_runtime': 9.9326, 'train_samples_per_second': 25.17, 'train_steps_per_second': 25.17, 'train_loss': 2.6364677734375, 'epoch': 25.0}
{'train_runtime': 9.8589, 'train_samples_per_second': 25.358, 'train_steps_per_second': 25.358, 'train_loss': 2.662790771484375, 'epoch': 25.0}
{'train_runtime': 10.0313, 'train_samples_per_second': 24.922, 'train_steps_per_second': 24.922, 'train_loss': 2.643076416015625, 'epoch': 25.0}
{'train_runtime': 9.9111, 'train_samples_per_second': 25.224, 'train_steps_per_second': 25.224, 'train_loss': 2.630221435546875, 'epoch': 25.0}
{'train_runtime': 9.8347, 'train_samples_per_second': 25.42, 'train_steps_per_second': 25.42, 'train_loss': 2.61612109375, 'epoch': 25.0}
{'train_runtime': 9.763, 'train_samples_per_second': 25.607, 'train_steps_per_second': 25.607, 'train_loss': 2.650156494140625, 'epoch': 25.0}
{'train_runtime': 9.9452, 'train_samples_per_second': 25.138, 'train_steps_per_second': 25.138, 'train_loss': 2.636756103515625, 'epoch': 25.0}
{'train_runtime': 10.1489, 'train_samples_per_second': 24.633, 'train_steps_per_second': 24.633, 'train_loss': 2.6412119140625, 'epoch': 25.0}
{'train_runtime': 9.9757, 'train_samples_per_second': 25.061, 'train_steps_per_second': 25.061, 'train_loss': 2.6358251953125, 'epoch': 25.0}
{'train_runtime': 9.8793, 'train_samples_per_second': 25.305, 'train_steps_per_second': 25.305, 'train_loss': 2.698486328125, 'epoch': 25.0}
{'train_runtime': 9.9186, 'train_samples_per_second': 25.205, 'train_steps_per_second': 25.205, 'train_loss': 2.64002587890625, 'epoch': 25.0}
{'train_runtime': 9.8105, 'train_samples_per_second': 25.483, 'train_steps_per_second': 25.483, 'train_loss': 2.68479443359375, 'epoch': 25.0}
{'train_runtime': 9.9996, 'train_samples_per_second': 25.001, 'train_steps_per_second': 25.001, 'train_loss': 2.620487548828125, 'epoch': 25.0}
{'train_runtime': 9.9494, 'train_samples_per_second': 25.127, 'train_steps_per_second': 25.127, 'train_loss': 2.6224189453125, 'epoch': 25.0}
{'train_runtime': 9.9469, 'train_samples_per_second': 25.134, 'train_steps_per_second': 25.134, 'train_loss': 2.61956103515625, 'epoch': 25.0}
{'train_runtime': 9.996, 'train_samples_per_second': 25.01, 'train_steps_per_second': 25.01, 'train_loss': 2.64433544921875, 'epoch': 25.0}
{'train_runtime': 9.9717, 'train_samples_per_second': 25.071, 'train_steps_per_second': 25.071, 'train_loss': 2.665988037109375, 'epoch': 25.0}
{'train_runtime': 9.9018, 'train_samples_per_second': 25.248, 'train_steps_per_second': 25.248, 'train_loss': 2.65141357421875, 'epoch': 25.0}
{'train_runtime': 9.9354, 'train_samples_per_second': 25.163, 'train_steps_per_second': 25.163, 'train_loss': 2.65373583984375, 'epoch': 25.0}
{'train_runtime': 10.0402, 'train_samples_per_second': 24.9, 'train_steps_per_second': 24.9, 'train_loss': 2.626674072265625, 'epoch': 25.0}
{'train_runtime': 9.8883, 'train_samples_per_second': 25.282, 'train_steps_per_second': 25.282, 'train_loss': 2.673237060546875, 'epoch': 25.0}
{'train_runtime': 10.2002, 'train_samples_per_second': 24.509, 'train_steps_per_second': 24.509, 'train_loss': 2.6439306640625, 'epoch': 25.0}
{'train_runtime': 10.1476, 'train_samples_per_second': 24.636, 'train_steps_per_second': 24.636, 'train_loss': 2.658890625, 'epoch': 25.0}
{'train_runtime': 11.3117, 'train_samples_per_second': 22.101, 'train_steps_per_second': 22.101, 'train_loss': 3.04041796875, 'epoch': 25.0}
{'train_runtime': 11.3172, 'train_samples_per_second': 22.09, 'train_steps_per_second': 22.09, 'train_loss': 3.0937412109375, 'epoch': 25.0}
{'train_runtime': 11.1459, 'train_samples_per_second': 22.43, 'train_steps_per_second': 22.43, 'train_loss': 3.042121826171875, 'epoch': 25.0}
{'train_runtime': 11.1191, 'train_samples_per_second': 22.484, 'train_steps_per_second': 22.484, 'train_loss': 3.039666015625, 'epoch': 25.0}
{'train_runtime': 11.1453, 'train_samples_per_second': 22.431, 'train_steps_per_second': 22.431, 'train_loss': 3.03456689453125, 'epoch': 25.0}
{'train_runtime': 11.156, 'train_samples_per_second': 22.409, 'train_steps_per_second': 22.409, 'train_loss': 3.0700849609375, 'epoch': 25.0}
{'train_runtime': 11.2033, 'train_samples_per_second': 22.315, 'train_steps_per_second': 22.315, 'train_loss': 3.07279541015625, 'epoch': 25.0}
{'train_runtime': 11.2559, 'train_samples_per_second': 22.21, 'train_steps_per_second': 22.21, 'train_loss': 3.041809326171875, 'epoch': 25.0}
{'train_runtime': 11.2254, 'train_samples_per_second': 22.271, 'train_steps_per_second': 22.271, 'train_loss': 3.059027587890625, 'epoch': 25.0}
{'train_runtime': 11.2888, 'train_samples_per_second': 22.146, 'train_steps_per_second': 22.146, 'train_loss': 3.043422119140625, 'epoch': 25.0}
{'train_runtime': 11.1333, 'train_samples_per_second': 22.455, 'train_steps_per_second': 22.455, 'train_loss': 3.05671142578125, 'epoch': 25.0}
{'train_runtime': 11.1856, 'train_samples_per_second': 22.35, 'train_steps_per_second': 22.35, 'train_loss': 3.0782275390625, 'epoch': 25.0}
{'train_runtime': 10.9658, 'train_samples_per_second': 22.798, 'train_steps_per_second': 22.798, 'train_loss': 3.035507080078125, 'epoch': 25.0}
{'train_runtime': 11.1785, 'train_samples_per_second': 22.364, 'train_steps_per_second': 22.364, 'train_loss': 3.0425458984375, 'epoch': 25.0}
{'train_runtime': 11.1192, 'train_samples_per_second': 22.484, 'train_steps_per_second': 22.484, 'train_loss': 3.04457275390625, 'epoch': 25.0}
{'train_runtime': 11.0709, 'train_samples_per_second': 22.582, 'train_steps_per_second': 22.582, 'train_loss': 3.03720166015625, 'epoch': 25.0}
{'train_runtime': 11.1208, 'train_samples_per_second': 22.48, 'train_steps_per_second': 22.48, 'train_loss': 3.072324951171875, 'epoch': 25.0}
{'train_runtime': 11.181, 'train_samples_per_second': 22.359, 'train_steps_per_second': 22.359, 'train_loss': 3.046116455078125, 'epoch': 25.0}
{'train_runtime': 11.2959, 'train_samples_per_second': 22.132, 'train_steps_per_second': 22.132, 'train_loss': 3.044254150390625, 'epoch': 25.0}
{'train_runtime': 11.2114, 'train_samples_per_second': 22.299, 'train_steps_per_second': 22.299, 'train_loss': 3.0606494140625, 'epoch': 25.0}
{'train_runtime': 11.2656, 'train_samples_per_second': 22.191, 'train_steps_per_second': 22.191, 'train_loss': 3.09720654296875, 'epoch': 25.0}

Explanations:  49%|████▉     | 687/1400 [38:38<45:35,  3.84s/it]

{'train_runtime': 11.5258, 'train_samples_per_second': 21.69, 'train_steps_per_second': 21.69, 'train_loss': 2.848899169921875, 'epoch': 25.0}
{'train_runtime': 11.6918, 'train_samples_per_second': 21.382, 'train_steps_per_second': 21.382, 'train_loss': 2.849257568359375, 'epoch': 25.0}
{'train_runtime': 11.5796, 'train_samples_per_second': 21.59, 'train_steps_per_second': 21.59, 'train_loss': 2.870759521484375, 'epoch': 25.0}
{'train_runtime': 11.5103, 'train_samples_per_second': 21.72, 'train_steps_per_second': 21.72, 'train_loss': 2.865728515625, 'epoch': 25.0}
{'train_runtime': 11.4073, 'train_samples_per_second': 21.916, 'train_steps_per_second': 21.916, 'train_loss': 2.8734697265625, 'epoch': 25.0}
{'train_runtime': 11.1908, 'train_samples_per_second': 22.34, 'train_steps_per_second': 22.34, 'train_loss': 2.8558583984375, 'epoch': 25.0}
{'train_runtime': 11.4108, 'train_samples_per_second': 21.909, 'train_steps_per_second': 21.909, 'train_loss': 2.85898388671875, 'epoch': 25.0}
{'train_runtime': 11.2263, 'train_samples_per_second': 22.269, 'train_steps_per_second': 22.269, 'train_loss': 2.849049560546875, 'epoch': 25.0}
{'train_runtime': 11.4885, 'train_samples_per_second': 21.761, 'train_steps_per_second': 21.761, 'train_loss': 2.870362548828125, 'epoch': 25.0}
{'train_runtime': 11.5953, 'train_samples_per_second': 21.56, 'train_steps_per_second': 21.56, 'train_loss': 2.867382080078125, 'epoch': 25.0}
{'train_runtime': 10.7548, 'train_samples_per_second': 23.245, 'train_steps_per_second': 23.245, 'train_loss': 2.830802490234375, 'epoch': 25.0}
{'train_runtime': 10.0693, 'train_samples_per_second': 24.828, 'train_steps_per_second': 24.828, 'train_loss': 2.656587646484375, 'epoch': 25.0}
{'train_runtime': 10.0156, 'train_samples_per_second': 24.961, 'train_steps_per_second': 24.961, 'train_loss': 2.6501318359375, 'epoch': 25.0}
{'train_runtime': 9.9566, 'train_samples_per_second': 25.109, 'train_steps_per_second': 25.109, 'train_loss': 2.662618408203125, 'epoch': 25.0}
{'train_runtime': 9.8445, 'train_samples_per_second': 25.395, 'train_steps_per_second': 25.395, 'train_loss': 2.64197705078125, 'epoch': 25.0}
{'train_runtime': 9.8943, 'train_samples_per_second': 25.267, 'train_steps_per_second': 25.267, 'train_loss': 2.68467431640625, 'epoch': 25.0}
{'train_runtime': 9.8428, 'train_samples_per_second': 25.399, 'train_steps_per_second': 25.399, 'train_loss': 2.66105078125, 'epoch': 25.0}
{'train_runtime': 9.7434, 'train_samples_per_second': 25.658, 'train_steps_per_second': 25.658, 'train_loss': 2.662712158203125, 'epoch': 25.0}
{'train_runtime': 9.8905, 'train_samples_per_second': 25.277, 'train_steps_per_second': 25.277, 'train_loss': 2.6588193359375, 'epoch': 25.0}
{'train_runtime': 9.8134, 'train_samples_per_second': 25.475, 'train_steps_per_second': 25.475, 'train_loss': 2.636783935546875, 'epoch': 25.0}
{'train_runtime': 9.9665, 'train_samples_per_second': 25.084, 'train_steps_per_second': 25.084, 'train_loss': 2.6738271484375, 'epoch': 25.0}
{'train_runtime': 9.8497, 'train_samples_per_second': 25.382, 'train_steps_per_second': 25.382, 'train_loss': 2.63884130859375, 'epoch': 25.0}
{'train_runtime': 9.7582, 'train_samples_per_second': 25.619, 'train_steps_per_second': 25.619, 'train_loss': 2.607232666015625, 'epoch': 25.0}
{'train_runtime': 9.7921, 'train_samples_per_second': 25.531, 'train_steps_per_second': 25.531, 'train_loss': 2.670321044921875, 'epoch': 25.0}
{'train_runtime': 9.8876, 'train_samples_per_second': 25.284, 'train_steps_per_second': 25.284, 'train_loss': 2.628083251953125, 'epoch': 25.0}
{'train_runtime': 9.8608, 'train_samples_per_second': 25.353, 'train_steps_per_second': 25.353, 'train_loss': 2.654685302734375, 'epoch': 25.0}
{'train_runtime': 9.9826, 'train_samples_per_second': 25.043, 'train_steps_per_second': 25.043, 'train_loss': 2.678554443359375, 'epoch': 25.0}
{'train_runtime': 9.8713, 'train_samples_per_second': 25.326, 'train_steps_per_second': 25.326, 'train_loss': 2.686232177734375, 'epoch': 25.0}
{'train_runtime': 9.9697, 'train_samples_per_second': 25.076, 'train_steps_per_second': 25.076, 'train_loss': 2.654645263671875, 'epoch': 25.0}
{'train_runtime': 9.8904, 'train_samples_per_second': 25.277, 'train_steps_per_second': 25.277, 'train_loss': 2.656597900390625, 'epoch': 25.0}
{'train_runtime': 9.8158, 'train_samples_per_second': 25.469, 'train_steps_per_second': 25.469, 'train_loss': 2.68541015625, 'epoch': 25.0}
{'train_runtime': 9.9262, 'train_samples_per_second': 25.186, 'train_steps_per_second': 25.186, 'train_loss': 2.6663486328125, 'epoch': 25.0}
{'train_runtime': 10.1303, 'train_samples_per_second': 24.678, 'train_steps_per_second': 24.678, 'train_loss': 2.709376708984375, 'epoch': 25.0}
{'train_runtime': 9.9315, 'train_samples_per_second': 25.172, 'train_steps_per_second': 25.172, 'train_loss': 2.67873583984375, 'epoch': 25.0}
{'train_runtime': 10.039, 'train_samples_per_second': 24.903, 'train_steps_per_second': 24.903, 'train_loss': 2.64584375, 'epoch': 25.0}
{'train_runtime': 10.1053, 'train_samples_per_second': 24.74, 'train_steps_per_second': 24.74, 'train_loss': 2.663917236328125, 'epoch': 25.0}
{'train_runtime': 11.2192, 'train_samples_per_second': 22.283, 'train_steps_per_second': 22.283, 'train_loss': 3.082065673828125, 'epoch': 25.0}
{'train_runtime': 11.4307, 'train_samples_per_second': 21.871, 'train_steps_per_second': 21.871, 'train_loss': 3.053164794921875, 'epoch': 25.0}
{'train_runtime': 11.161, 'train_samples_per_second': 22.399, 'train_steps_per_second': 22.399, 'train_loss': 3.04439697265625, 'epoch': 25.0}
{'train_runtime': 11.0574, 'train_samples_per_second': 22.609, 'train_steps_per_second': 22.609, 'train_loss': 3.055195556640625, 'epoch': 25.0}
{'train_runtime': 11.1635, 'train_samples_per_second': 22.394, 'train_steps_per_second': 22.394, 'train_loss': 3.094892578125, 'epoch': 25.0}
{'train_runtime': 11.0572, 'train_samples_per_second': 22.61, 'train_steps_per_second': 22.61, 'train_loss': 3.053470458984375, 'epoch': 25.0}
{'train_runtime': 11.3752, 'train_samples_per_second': 21.978, 'train_steps_per_second': 21.978, 'train_loss': 3.0581552734375, 'epoch': 25.0}
{'train_runtime': 11.1035, 'train_samples_per_second': 22.515, 'train_steps_per_second': 22.515, 'train_loss': 3.06539208984375, 'epoch': 25.0}
{'train_runtime': 11.3312, 'train_samples_per_second': 22.063, 'train_steps_per_second': 22.063, 'train_loss': 3.06085595703125, 'epoch': 25.0}
{'train_runtime': 11.1714, 'train_samples_per_second': 22.379, 'train_steps_per_second': 22.379, 'train_loss': 3.0763564453125, 'epoch': 25.0}
{'train_runtime': 11.264, 'train_samples_per_second': 22.195, 'train_steps_per_second': 22.195, 'train_loss': 3.088277587890625, 'epoch': 25.0}
{'train_runtime': 11.1168, 'train_samples_per_second': 22.488, 'train_steps_per_second': 22.488, 'train_loss': 3.080866455078125, 'epoch': 25.0}
{'train_runtime': 11.0039, 'train_samples_per_second': 22.719, 'train_steps_per_second': 22.719, 'train_loss': 3.046329833984375, 'epoch': 25.0}
{'train_runtime': 11.1871, 'train_samples_per_second': 22.347, 'train_steps_per_second': 22.347, 'train_loss': 3.085802490234375, 'epoch': 25.0}
{'train_runtime': 11.2296, 'train_samples_per_second': 22.263, 'train_steps_per_second': 22.263, 'train_loss': 3.068262451171875, 'epoch': 25.0}
{'train_runtime': 11.0386, 'train_samples_per_second': 22.648, 'train_steps_per_second': 22.648, 'train_loss': 3.06309619140625, 'epoch': 25.0}
{'train_runtime': 11.1565, 'train_samples_per_second': 22.409, 'train_steps_per_second': 22.409, 'train_loss': 3.044759033203125, 'epoch': 25.0}
{'train_runtime': 11.047, 'train_samples_per_second': 22.631, 'train_steps_per_second': 22.631, 'train_loss': 3.071966796875, 'epoch': 25.0}
{'train_runtime': 11.1513, 'train_samples_per_second': 22.419, 'train_steps_per_second': 22.419, 'train_loss': 3.0374482421875, 'epoch': 25.0}
{'train_runtime': 11.1644, 'train_samples_per_second': 22.393, 'train_steps_per_second': 22.393, 'train_loss': 3.059701904296875, 'epoch': 25.0}
{'train_runtime': 11.1124, 'train_samples_per_second': 22.497, 'train_steps_per_second': 22.497, 'train_loss': 3.06654638671875, 'epoch': 25.0}

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▉     | 688/1400 [38:40<37:53,  3.19s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▉     | 689/1400 [38:42<34:28,  2.91s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▉     | 690/1400 [38:46<39:33,  3.34s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▉     | 691/1400 [38:52<46:01,  3.89s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  49%|████▉     | 692/1400 [38:53<37:10,  3.15s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|████▉     | 693/1400 [38:55<33:12,  2.82s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|████▉     | 694/1400 [38:59<38:39,  3.29s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|████▉     | 696/1400 [39:06<36:48,  3.14s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|████▉     | 697/1400 [39:08<32:50,  2.80s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|████▉     | 698/1400 [39:13<37:53,  3.24s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|█████     | 700/1400 [39:20<37:04,  3.18s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|█████     | 701/1400 [39:22<33:29,  2.87s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|█████     | 702/1400 [39:26<38:24,  3.30s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|█████     | 704/1400 [39:34<38:14,  3.30s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|█████     | 705/1400 [39:36<34:03,  2.94s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  50%|█████     | 706/1400 [39:40<38:13,  3.30s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 708/1400 [39:48<37:12,  3.23s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 709/1400 [39:50<33:12,  2.88s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 710/1400 [39:54<36:59,  3.22s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 711/1400 [40:02<52:58,  4.61s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 713/1400 [40:04<34:44,  3.03s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 714/1400 [40:08<36:06,  3.16s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 716/1400 [40:16<38:17,  3.36s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████     | 717/1400 [40:18<33:32,  2.95s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████▏    | 718/1400 [40:21<34:43,  3.06s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  51%|█████▏    | 720/1400 [40:30<38:58,  3.44s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 721/1400 [40:32<33:13,  2.94s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 722/1400 [40:35<33:34,  2.97s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 724/1400 [40:45<39:13,  3.48s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 725/1400 [40:46<32:29,  2.89s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 726/1400 [40:49<32:08,  2.86s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 728/1400 [40:59<39:28,  3.53s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 729/1400 [41:00<32:58,  2.95s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 730/1400 [41:03<31:14,  2.80s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 732/1400 [41:13<39:20,  3.53s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 733/1400 [41:14<32:37,  2.94s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  52%|█████▏    | 734/1400 [41:17<31:21,  2.83s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 736/1400 [41:27<40:02,  3.62s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 737/1400 [41:29<32:20,  2.93s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 738/1400 [41:31<30:34,  2.77s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 740/1400 [41:41<39:59,  3.64s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 741/1400 [41:43<32:37,  2.97s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 742/1400 [41:45<29:48,  2.72s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 744/1400 [41:56<41:12,  3.77s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 745/1400 [41:57<32:34,  2.98s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 746/1400 [41:59<29:36,  2.72s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  53%|█████▎    | 748/1400 [42:10<40:13,  3.70s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  54%|█████▎    | 749/1400 [42:12<32:00,  2.95s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  54%|█████▎    | 750/1400 [42:13<28:09,  2.60s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Explanations:  54%|█████▎    | 751/1400 [42:23<52:28,  4.85s/it]No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

In [ ]:
import pandas as pd

df_validation = pd.read_parquet("./cache/validation/partial/")

In [ ]:
[r for r in df_validation.explanation_type.unique() if "random examples with" in r]

['10 random examples with seed 42',
 '10 random examples with seed 0',
 '10 random examples with seed 1',
 '10 random examples with seed 2',
 '10 random examples with seed 3',
 '10 random examples with seed 4',
 '10 random examples with seed 5',
 '10 random examples with seed 6',
 '10 random examples with seed 7',
 '10 random examples with seed 8']

In [ ]:
import pandas as pd
all_rows = []
for rand_col in [r for r in df_validation.explanation_type.unique() if "random examples with" in r]:
    group_cols = ["document_idx", "train_dataset", "train_split", "test_dataset","test_split",
                "model", "estimator"]


    baseline_df = df_validation[df_validation["explanation_type"] == rand_col].copy()
    


    for expl_type in df_validation["explanation_type"].unique():
        expl_df = df_validation[df_validation["explanation_type"] == expl_type].copy()
        merged = expl_df.merge(
            baseline_df[group_cols + ["indices_target_document", "delta_target_document"]],
            on=group_cols + ["indices_target_document"],
            suffixes=("", "_random")
        )
        
        # 1(Δ_S > Δ_R)
        merged["xi"] = (merged["delta_target_document"] >= merged["delta_target_document_random"]).astype(int)
        merged["random_run"] = rand_col



        all_rows.append(merged[group_cols + ["explanation_type", "indices_target_document", 
                                            "delta_target_document", "delta_target_document_random", "xi", "random_run"]])


xi_df = pd.concat(all_rows, ignore_index=True)

In [ ]:
xi_df["explanation_type"] = xi_df.apply(
    lambda row: "rand" if "random " in row["explanation_type"] else row["explanation_type"], axis=1
)

In [ ]:
xi_df.groupby(["explanation_type","train_dataset", "train_split", "test_dataset","test_split",
              "model", "estimator"])["xi"].describe()

                                                                                                                                                                                                                 count  \
explanation_type                                   train_dataset              train_split test_dataset               test_split model                                estimator
Top-10 least influential (scores closest to zero)  loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True   50.0
                                                                                                                                                                     LESSEstimator: normalize=True                50.0
Top-10 most harmful (most positive scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True   50.0
                                                                                                                                                                     LESSEstimator: normalize=True                50.0
Top-10 most helpful (most negative scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True   50.0
                                                                                                                                                                     LESSEstimator: normalize=True                50.0
Top-10 most influential (scores with largest ab... loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True   50.0
                                                                                                                                                                     LESSEstimator: normalize=True                50.0
rand                                               loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  500.0
                                                                                                                                                                     LESSEstimator: normalize=True               500.0

                                                                                                                                                                                                                 mean  \
explanation_type                                   train_dataset              train_split test_dataset               test_split model                                estimator
Top-10 least influential (scores closest to zero)  loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.42
                                                                                                                                                                     LESSEstimator: normalize=True               0.70
Top-10 most harmful (most positive scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.30
                                                                                                                                                                     LESSEstimator: normalize=True               0.50
Top-10 most helpful (most negative scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.40
                                                                                                                                                                     LESSEstimator: normalize=True               0.66
Top-10 most influential (scores with largest ab... loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.32
                                                                                                                                                                     LESSEstimator: normalize=True               0.70
rand                                               loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.55
                                                                                                                                                                     LESSEstimator: normalize=True               0.55

                                                                                                                                                                                                                      std  \
explanation_type                                   train_dataset              train_split test_dataset               test_split model                                estimator
Top-10 least influential (scores closest to zero)  loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.498569
                                                                                                                                                                     LESSEstimator: normalize=True               0.462910
Top-10 most harmful (most positive scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.462910
                                                                                                                                                                     LESSEstimator: normalize=True               0.505076
Top-10 most helpful (most negative scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.494872
                                                                                                                                                                     LESSEstimator: normalize=True               0.478518
Top-10 most influential (scores with largest ab... loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.471212
                                                                                                                                                                     LESSEstimator: normalize=True               0.462910
rand                                               loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.497992
                                                                                                                                                                     LESSEstimator: normalize=True               0.497992

                                                                                                                                                                                                                 min  \
explanation_type                                   train_dataset              train_split test_dataset               test_split model                                estimator
Top-10 least influential (scores closest to zero)  loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               0.0
Top-10 most harmful (most positive scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               0.0
Top-10 most helpful (most negative scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               0.0
Top-10 most influential (scores with largest ab... loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               0.0
rand                                               loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               0.0

                                                                                                                                                                                                                 25%  \
explanation_type                                   train_dataset              train_split test_dataset               test_split model                                estimator
Top-10 least influential (scores closest to zero)  loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               0.0
Top-10 most harmful (most positive scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               0.0
Top-10 most helpful (most negative scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               0.0
Top-10 most influential (scores with largest ab... loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               0.0
rand                                               loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               0.0

                                                                                                                                                                                                                 50%  \
explanation_type                                   train_dataset              train_split test_dataset               test_split model                                estimator
Top-10 least influential (scores closest to zero)  loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0
Top-10 most harmful (most positive scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               0.5
Top-10 most helpful (most negative scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0
Top-10 most influential (scores with largest ab... loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  0.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0
rand                                               loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  1.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0

                                                                                                                                                                                                                 75%  \
explanation_type                                   train_dataset              train_split test_dataset               test_split model                                estimator
Top-10 least influential (scores closest to zero)  loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  1.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0
Top-10 most harmful (most positive scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  1.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0
Top-10 most helpful (most negative scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  1.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0
Top-10 most influential (scores with largest ab... loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  1.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0
rand                                               loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  1.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0

                                                                                                                                                                                                                 max
explanation_type                                   train_dataset              train_split test_dataset               test_split model                                estimator
Top-10 least influential (scores closest to zero)  loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  1.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0
Top-10 most harmful (most positive scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  1.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0
Top-10 most helpful (most negative scores)         loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  1.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0
Top-10 most influential (scores with largest ab... loris3/tulu-v2-sft-mixture test        loris3/tulu-v2-sft-mixture test       pythia-31m_tulu-v2-sft-mixture_train DataInfEstimator: fast_implementation=True  1.0
                                                                                                                                                                     LESSEstimator: normalize=True               1.0

In [ ]:
df_scoring = pd.read_parquet("./cache/scoring/partial/")

In [ ]:
df = df_scoring.merge(
    df_validation,
    on=["explanation_type", "model", "estimator", "document_idx", "train_dataset", "train_split", "test_dataset", "test_split"],
    how="left"
)[["explanation_type", "model", "linear_coder", "estimator", "document_idx", "pred_gain","mse", "delta_target_document"]]

In [ ]:
import statsmodels.api as sm
import pandas as pd

results = []

for keys, group in df.groupby(["explanation_type", "model", "estimator", "linear_coder"]):
    x = -pd.to_numeric(group["mse"], errors="coerce")  # negate MSE so lower is better
    y = pd.to_numeric(group["delta_target_document"], errors="coerce")
    
    mask = ~(x.isna() | y.isna())
    x_clean, y_clean = x[mask], y[mask]
    

    X = sm.add_constant(pd.DataFrame({"neg_mse": x_clean}))
    model = sm.OLS(y_clean, X).fit()
    
    results.append({
        "explanation_type": keys[0],
        "model": keys[1],
        "estimator": keys[2],
        "linear_coder": keys[3],
        "coef": model.params.get("neg_mse", None),       
        "p_value": model.pvalues.get("neg_mse", None),  
        "r_squared": model.rsquared
    })

results_df = pd.DataFrame(results)
results_df

,explanation_type,model,estimator,linear_coder,coef,p_value,r_squared
0,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,KLTCoder,-2.570608,0.510432,0.156053
1,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,MSECoder,-2.573869,0.509932,0.156391
2,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,MSECoderNNLSL2,-2.560777,0.505799,0.159201
3,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,MSECoderProjUSimp,-2.657760,0.486983,0.172374
4,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,MSECoderProjUSimpSparse,-2.713055,0.487209,0.172212
...,...,...,...,...,...,...,...
61,Top-10 most influential (scores with largest a...,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,MSECoderLemon,-0.319639,0.905681,0.005498
62,Top-10 most influential (scores with largest a...,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,MSECoderNNLSL2,-0.231939,0.911148,0.004878
63,Top-10 most influential (scores with largest a...,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,MSECoderProjUSimp,-0.301747,0.907474,0.005290
64,Top-10 most influential (scores with largest a...,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,MSECoderProjUSimpSparse,-0.314037,0.907163,0.005326
65,Top-10 most influential (scores with largest a...,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,MSECoderProjUSimpSparseSoftThresh,-0.336030,0.894445,0.006889

In [ ]:
import statsmodels.api as sm

results = []


for keys, group in df.groupby(["explanation_type", "model", "estimator", "linear_coder"]):
    x = pd.to_numeric(group["pred_gain"], errors="coerce")
    y = pd.to_numeric(group["delta_target_document"], errors="coerce")
    
    mask = ~(x.isna() | y.isna())
    x_clean, y_clean = x[mask], y[mask]
    

    X = sm.add_constant(x_clean)
    model = sm.OLS(y_clean, X).fit()
    
    results.append({
        "explanation_type": keys[0],
        "model": keys[1],
        "estimator": keys[2],
        "linear_coder": keys[3],
        "coef": model.params.get("pred_gain", None),
        "p_value": model.pvalues.get("pred_gain", None),
        "r_squared": model.rsquared
    })


results_df = pd.DataFrame(results)
results_df

,explanation_type,model,estimator,linear_coder,coef,p_value,r_squared
0,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,KLTCoder,-2.830133e+03,0.296353,0.346538
1,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,MSECoder,-3.191615e+02,0.232349,0.426176
2,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,MSECoderNNLSL2,-2.607489e+02,0.237516,0.419232
3,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,MSECoderProjUSimp,-2.715393e+03,0.007453,0.933358
4,10 random examples with seed 42,pythia-31m_tulu-v2-sft-mixture_train,DataInfEstimator: fast_implementation=True,MSECoderProjUSimpSparse,-1.393003e+03,0.212512,0.453792
...,...,...,...,...,...,...,...
61,Top-10 most influential (scores with largest a...,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,MSECoderLemon,3.072965e-02,0.053357,0.761921
62,Top-10 most influential (scores with largest a...,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,MSECoderNNLSL2,3.705363e-08,0.055823,0.755056
63,Top-10 most influential (scores with largest a...,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,MSECoderProjUSimp,3.705659e-08,0.055752,0.755253
64,Top-10 most influential (scores with largest a...,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,MSECoderProjUSimpSparse,3.706277e-08,0.055752,0.755252
65,Top-10 most influential (scores with largest a...,pythia-31m_tulu-v2-sft-mixture_train,LESSEstimator: normalize=True,MSECoderProjUSimpSparseSoftThresh,1.192901e+01,0.074813,0.705948